-- ============================================================================
-- Migration 656: Seed im_reference_data category = 'lookup_table'
-- (tool assembly num operators) — schema: migration 636
--
-- Generated by gen_656_seed_im_lookup_tool_assembly_num_operators.js.
-- Row count: 5 (memory/plastic modeling/lookup/cmToolAssemblyNumOperators.json).
--
-- NOT wired into any cost calculation — staging only. See the generator
-- script header for the shared open dependency (mold base area
-- methodology) with migration 654.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
('lookup_table', 'USA', '2026-03', $str$area_m2_1$str$, $str$1$str$, $str$count$str$, $str$Tool assembly operators required for mold base area <= 1 m^2$str$, $jsonb${"mold_base_area_m2":1,"num_operators_required":1}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$area_m2_2$str$, $str$2$str$, $str$count$str$, $str$Tool assembly operators required for mold base area <= 2 m^2$str$, $jsonb${"mold_base_area_m2":2,"num_operators_required":2}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$area_m2_3$str$, $str$3$str$, $str$count$str$, $str$Tool assembly operators required for mold base area <= 3 m^2$str$, $jsonb${"mold_base_area_m2":3,"num_operators_required":3}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$area_m2_4$str$, $str$4$str$, $str$count$str$, $str$Tool assembly operators required for mold base area <= 4 m^2$str$, $jsonb${"mold_base_area_m2":4,"num_operators_required":4}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$area_m2_100$str$, $str$5$str$, $str$count$str$, $str$Tool assembly operators required for mold base area <= 100 m^2$str$, $jsonb${"mold_base_area_m2":100,"num_operators_required":5}$jsonb$::jsonb)
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
