-- ============================================================================
-- Migration 661: Seed im_reference_data category = 'lookup_table'
-- (finishing hours per sq meter) — schema: migration 636
--
-- Generated by gen_661_seed_im_lookup_finishing_hrs_per_sqm.js.
-- Row count: 24 (memory/plastic modeling/lookup/finishingHrsPerSqMeter.json).
--
-- NOT wired into any cost calculation — staging only. See the generator
-- script header — unlike the mold-base-area-keyed tables, this one is
-- keyed by real part surface area, already computed for every part today.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
('lookup_table', 'USA', '2026-03', $str$0.06_Simple$str$, $str$232.5$str$, $str$hr/m^2$str$, $str$Finishing/polishing rate for surface area <= 0.06 m^2, Simple complexity$str$, $jsonb${"surface_area_m2":0.06,"hrs_per_sq_meter_hr_m2":232.5,"complexity":"Simple"}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$0.06_Average$str$, $str$279$str$, $str$hr/m^2$str$, $str$Finishing/polishing rate for surface area <= 0.06 m^2, Average complexity$str$, $jsonb${"surface_area_m2":0.06,"hrs_per_sq_meter_hr_m2":279,"complexity":"Average"}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$0.06_Complex$str$, $str$325.5$str$, $str$hr/m^2$str$, $str$Finishing/polishing rate for surface area <= 0.06 m^2, Complex complexity$str$, $jsonb${"surface_area_m2":0.06,"hrs_per_sq_meter_hr_m2":325.5,"complexity":"Complex"}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$0.16_Simple$str$, $str$195.3$str$, $str$hr/m^2$str$, $str$Finishing/polishing rate for surface area <= 0.16 m^2, Simple complexity$str$, $jsonb${"surface_area_m2":0.16,"hrs_per_sq_meter_hr_m2":195.3,"complexity":"Simple"}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$0.16_Average$str$, $str$241.8$str$, $str$hr/m^2$str$, $str$Finishing/polishing rate for surface area <= 0.16 m^2, Average complexity$str$, $jsonb${"surface_area_m2":0.16,"hrs_per_sq_meter_hr_m2":241.8,"complexity":"Average"}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$0.16_Complex$str$, $str$279$str$, $str$hr/m^2$str$, $str$Finishing/polishing rate for surface area <= 0.16 m^2, Complex complexity$str$, $jsonb${"surface_area_m2":0.16,"hrs_per_sq_meter_hr_m2":279,"complexity":"Complex"}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$0.32_Simple$str$, $str$158.1$str$, $str$hr/m^2$str$, $str$Finishing/polishing rate for surface area <= 0.32 m^2, Simple complexity$str$, $jsonb${"surface_area_m2":0.32,"hrs_per_sq_meter_hr_m2":158.1,"complexity":"Simple"}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$0.32_Average$str$, $str$195.3$str$, $str$hr/m^2$str$, $str$Finishing/polishing rate for surface area <= 0.32 m^2, Average complexity$str$, $jsonb${"surface_area_m2":0.32,"hrs_per_sq_meter_hr_m2":195.3,"complexity":"Average"}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$0.32_Complex$str$, $str$241.8$str$, $str$hr/m^2$str$, $str$Finishing/polishing rate for surface area <= 0.32 m^2, Complex complexity$str$, $jsonb${"surface_area_m2":0.32,"hrs_per_sq_meter_hr_m2":241.8,"complexity":"Complex"}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$0.65_Simple$str$, $str$120.9$str$, $str$hr/m^2$str$, $str$Finishing/polishing rate for surface area <= 0.65 m^2, Simple complexity$str$, $jsonb${"surface_area_m2":0.65,"hrs_per_sq_meter_hr_m2":120.9,"complexity":"Simple"}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$0.65_Average$str$, $str$158.1$str$, $str$hr/m^2$str$, $str$Finishing/polishing rate for surface area <= 0.65 m^2, Average complexity$str$, $jsonb${"surface_area_m2":0.65,"hrs_per_sq_meter_hr_m2":158.1,"complexity":"Average"}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$0.65_Complex$str$, $str$195.3$str$, $str$hr/m^2$str$, $str$Finishing/polishing rate for surface area <= 0.65 m^2, Complex complexity$str$, $jsonb${"surface_area_m2":0.65,"hrs_per_sq_meter_hr_m2":195.3,"complexity":"Complex"}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$0.97_Simple$str$, $str$102.3$str$, $str$hr/m^2$str$, $str$Finishing/polishing rate for surface area <= 0.97 m^2, Simple complexity$str$, $jsonb${"surface_area_m2":0.97,"hrs_per_sq_meter_hr_m2":102.3,"complexity":"Simple"}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$0.97_Average$str$, $str$139.5$str$, $str$hr/m^2$str$, $str$Finishing/polishing rate for surface area <= 0.97 m^2, Average complexity$str$, $jsonb${"surface_area_m2":0.97,"hrs_per_sq_meter_hr_m2":139.5,"complexity":"Average"}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$0.97_Complex$str$, $str$176.7$str$, $str$hr/m^2$str$, $str$Finishing/polishing rate for surface area <= 0.97 m^2, Complex complexity$str$, $jsonb${"surface_area_m2":0.97,"hrs_per_sq_meter_hr_m2":176.7,"complexity":"Complex"}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$1.61_Simple$str$, $str$93$str$, $str$hr/m^2$str$, $str$Finishing/polishing rate for surface area <= 1.61 m^2, Simple complexity$str$, $jsonb${"surface_area_m2":1.61,"hrs_per_sq_meter_hr_m2":93,"complexity":"Simple"}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$1.61_Average$str$, $str$120.9$str$, $str$hr/m^2$str$, $str$Finishing/polishing rate for surface area <= 1.61 m^2, Average complexity$str$, $jsonb${"surface_area_m2":1.61,"hrs_per_sq_meter_hr_m2":120.9,"complexity":"Average"}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$1.61_Complex$str$, $str$167.4$str$, $str$hr/m^2$str$, $str$Finishing/polishing rate for surface area <= 1.61 m^2, Complex complexity$str$, $jsonb${"surface_area_m2":1.61,"hrs_per_sq_meter_hr_m2":167.4,"complexity":"Complex"}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$1.94_Simple$str$, $str$83.7$str$, $str$hr/m^2$str$, $str$Finishing/polishing rate for surface area <= 1.94 m^2, Simple complexity$str$, $jsonb${"surface_area_m2":1.94,"hrs_per_sq_meter_hr_m2":83.7,"complexity":"Simple"}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$1.94_Average$str$, $str$111.6$str$, $str$hr/m^2$str$, $str$Finishing/polishing rate for surface area <= 1.94 m^2, Average complexity$str$, $jsonb${"surface_area_m2":1.94,"hrs_per_sq_meter_hr_m2":111.6,"complexity":"Average"}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$1.94_Complex$str$, $str$158.1$str$, $str$hr/m^2$str$, $str$Finishing/polishing rate for surface area <= 1.94 m^2, Complex complexity$str$, $jsonb${"surface_area_m2":1.94,"hrs_per_sq_meter_hr_m2":158.1,"complexity":"Complex"}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$2.26_Simple$str$, $str$74.4$str$, $str$hr/m^2$str$, $str$Finishing/polishing rate for surface area <= 2.26 m^2, Simple complexity$str$, $jsonb${"surface_area_m2":2.26,"hrs_per_sq_meter_hr_m2":74.4,"complexity":"Simple"}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$2.26_Average$str$, $str$102.3$str$, $str$hr/m^2$str$, $str$Finishing/polishing rate for surface area <= 2.26 m^2, Average complexity$str$, $jsonb${"surface_area_m2":2.26,"hrs_per_sq_meter_hr_m2":102.3,"complexity":"Average"}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$2.26_Complex$str$, $str$139.5$str$, $str$hr/m^2$str$, $str$Finishing/polishing rate for surface area <= 2.26 m^2, Complex complexity$str$, $jsonb${"surface_area_m2":2.26,"hrs_per_sq_meter_hr_m2":139.5,"complexity":"Complex"}$jsonb$::jsonb)
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
