-- ============================================================================
-- Migration 666: Seed im_reference_data category = 'lookup_table'
-- (material handling time) — schema: migration 636
--
-- Generated by gen_666_seed_im_lookup_material_handling.js.
-- Row count: 7 (memory/plastic modeling/lookup/materialHandling.json).
--
-- NOT wired into any cost calculation — staging only. See the generator
-- script header — a real, currently entirely-missing cycle-time component
-- (operator handling time), distinct from cycle-time.ts's IM_EJECT_SEC.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
('lookup_table', 'USA', '2026-03', $str$weight_kg_0.45$str$, $str$5$str$, $str$s$str$, $str$Operator handling time for part weight <= 0.45 kg$str$, $jsonb${"weight_kg":0.45,"handling_time_s":5}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$weight_kg_4.55$str$, $str$5$str$, $str$s$str$, $str$Operator handling time for part weight <= 4.55 kg$str$, $jsonb${"weight_kg":4.55,"handling_time_s":5}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$weight_kg_22.73$str$, $str$15$str$, $str$s$str$, $str$Operator handling time for part weight <= 22.73 kg$str$, $jsonb${"weight_kg":22.73,"handling_time_s":15}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$weight_kg_45.45$str$, $str$20$str$, $str$s$str$, $str$Operator handling time for part weight <= 45.45 kg$str$, $jsonb${"weight_kg":45.45,"handling_time_s":20}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$weight_kg_113.64$str$, $str$23$str$, $str$s$str$, $str$Operator handling time for part weight <= 113.64 kg$str$, $jsonb${"weight_kg":113.64,"handling_time_s":23}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$weight_kg_227.27$str$, $str$27$str$, $str$s$str$, $str$Operator handling time for part weight <= 227.27 kg$str$, $jsonb${"weight_kg":227.27,"handling_time_s":27}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$weight_kg_454.55$str$, $str$30$str$, $str$s$str$, $str$Operator handling time for part weight <= 454.55 kg$str$, $jsonb${"weight_kg":454.55,"handling_time_s":30}$jsonb$::jsonb)
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
