-- ============================================================================
-- Migration 674: Seed im_reference_data category = 'lookup_table'
-- (edge mold border Y) — schema: migration 636
--
-- Generated by gen_674_seed_im_lookup_edge_mold_border_y.js.
-- Row count: 4 (memory/plastic modeling/lookup/tblEdgeMoldBorderY.json).
--
-- NOT wired into any cost calculation — staging only. See the generator
-- script header — direct piece of the still-open mold-base-area formula,
-- Y-direction counterpart to migration 673.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
('lookup_table', 'USA', '2026-03', $str$press_kn_298.92$str$, $str$90$str$, $str$mm$str$, $str$Edge mold border (Y) for max press force <= 298.92 kN$str$, $jsonb${"edge_mold_border_y_mm":90,"max_press_force_kn":298.92}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$press_kn_1992.8$str$, $str$152$str$, $str$mm$str$, $str$Edge mold border (Y) for max press force <= 1992.8 kN$str$, $jsonb${"edge_mold_border_y_mm":152,"max_press_force_kn":1992.8}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$press_kn_9964$str$, $str$165$str$, $str$mm$str$, $str$Edge mold border (Y) for max press force <= 9964 kN$str$, $jsonb${"edge_mold_border_y_mm":165,"max_press_force_kn":9964}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$press_kn_99999999$str$, $str$165$str$, $str$mm$str$, $str$Edge mold border (Y) for max press force <= 99999999 kN$str$, $jsonb${"edge_mold_border_y_mm":165,"max_press_force_kn":99999999}$jsonb$::jsonb)
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
