-- ============================================================================
-- Migration 681: Seed im_reference_data category = 'lookup_table'
-- (slide sizes) — schema: migration 636
--
-- Generated by gen_681_seed_im_lookup_slide_sizes.js.
-- Row count: 13 (memory/plastic modeling/lookup/tblSlideSizes.json).
--
-- NOT wired into any cost calculation — staging only.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
('lookup_table', 'USA', '2026-03', $str$core_pin_dia_3.56$str$, $str$44.45$str$, $str$mm$str$, $str$Slide sizing for core pin dia <= 3.56 mm$str$, $jsonb${"Core Pin Dia (mm)":3.56,"Core Retainer Thickness (mm)":6.35,"Wear Plate Thickness (mm)":6.35,"Slide Body Length (mm)":44.45}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$core_pin_dia_3.96$str$, $str$44.45$str$, $str$mm$str$, $str$Slide sizing for core pin dia <= 3.96 mm$str$, $jsonb${"Core Pin Dia (mm)":3.96,"Core Retainer Thickness (mm)":7.92,"Wear Plate Thickness (mm)":6.35,"Slide Body Length (mm)":44.45}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$core_pin_dia_6.35$str$, $str$44.45$str$, $str$mm$str$, $str$Slide sizing for core pin dia <= 6.35 mm$str$, $jsonb${"Core Pin Dia (mm)":6.35,"Core Retainer Thickness (mm)":7.92,"Wear Plate Thickness (mm)":6.35,"Slide Body Length (mm)":44.45}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$core_pin_dia_11.1$str$, $str$50.8$str$, $str$mm$str$, $str$Slide sizing for core pin dia <= 11.1 mm$str$, $jsonb${"Core Pin Dia (mm)":11.1,"Core Retainer Thickness (mm)":12.7,"Wear Plate Thickness (mm)":6.35,"Slide Body Length (mm)":50.8}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$core_pin_dia_12.7$str$, $str$50.8$str$, $str$mm$str$, $str$Slide sizing for core pin dia <= 12.7 mm$str$, $jsonb${"Core Pin Dia (mm)":12.7,"Core Retainer Thickness (mm)":19.05,"Wear Plate Thickness (mm)":6.35,"Slide Body Length (mm)":50.8}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$core_pin_dia_15.88$str$, $str$63.5$str$, $str$mm$str$, $str$Slide sizing for core pin dia <= 15.88 mm$str$, $jsonb${"Core Pin Dia (mm)":15.88,"Core Retainer Thickness (mm)":22.23,"Wear Plate Thickness (mm)":6.35,"Slide Body Length (mm)":63.5}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$core_pin_dia_22.23$str$, $str$63.5$str$, $str$mm$str$, $str$Slide sizing for core pin dia <= 22.23 mm$str$, $jsonb${"Core Pin Dia (mm)":22.23,"Core Retainer Thickness (mm)":25.4,"Wear Plate Thickness (mm)":6.35,"Slide Body Length (mm)":63.5}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$core_pin_dia_25.4$str$, $str$63.5$str$, $str$mm$str$, $str$Slide sizing for core pin dia <= 25.4 mm$str$, $jsonb${"Core Pin Dia (mm)":25.4,"Core Retainer Thickness (mm)":31.75,"Wear Plate Thickness (mm)":12.7,"Slide Body Length (mm)":63.5}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$core_pin_dia_31.75$str$, $str$69.85$str$, $str$mm$str$, $str$Slide sizing for core pin dia <= 31.75 mm$str$, $jsonb${"Core Pin Dia (mm)":31.75,"Core Retainer Thickness (mm)":31.75,"Wear Plate Thickness (mm)":12.7,"Slide Body Length (mm)":69.85}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$core_pin_dia_38.1$str$, $str$69.85$str$, $str$mm$str$, $str$Slide sizing for core pin dia <= 38.1 mm$str$, $jsonb${"Core Pin Dia (mm)":38.1,"Core Retainer Thickness (mm)":38.1,"Wear Plate Thickness (mm)":12.7,"Slide Body Length (mm)":69.85}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$core_pin_dia_63.5$str$, $str$76.2$str$, $str$mm$str$, $str$Slide sizing for core pin dia <= 63.5 mm$str$, $jsonb${"Core Pin Dia (mm)":63.5,"Core Retainer Thickness (mm)":38.1,"Wear Plate Thickness (mm)":12.7,"Slide Body Length (mm)":76.2}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$core_pin_dia_76.2$str$, $str$82.55$str$, $str$mm$str$, $str$Slide sizing for core pin dia <= 76.2 mm$str$, $jsonb${"Core Pin Dia (mm)":76.2,"Core Retainer Thickness (mm)":38.1,"Wear Plate Thickness (mm)":12.7,"Slide Body Length (mm)":82.55}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$core_pin_dia_999999$str$, $str$82.55$str$, $str$mm$str$, $str$Slide sizing for core pin dia <= 999999 mm$str$, $jsonb${"Core Pin Dia (mm)":999999,"Core Retainer Thickness (mm)":50.8,"Wear Plate Thickness (mm)":12.7,"Slide Body Length (mm)":82.55}$jsonb$::jsonb)
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
