-- ============================================================================
-- Migration 682: Seed im_reference_data category = 'lookup_table'
-- (SPI mold type) — schema: migration 636
--
-- Generated by gen_682_seed_im_lookup_spi_type.js.
-- Row count: 5 (memory/plastic modeling/lookup/tblSpiType.json).
--
-- NOT wired into any cost calculation — staging only. See the generator
-- script header — CONFIRMED real source table for
-- cost-injection-molding-engine.ts's SPI_MOLD_CLASSES, which has real
-- discrepancies for Class101 and Class105 today.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
('lookup_table', 'USA', '2026-03', $str$SPI 101$str$, $str$9999999999$str$, $str$cycles$str$, $str$SPI Class 101 — life shot rating; use insert: true$str$, $jsonb${"Spi Type":101,"Num Annual Mold Cycles":9999999999,"Use Insert":"true"}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$SPI 102$str$, $str$1000000$str$, $str$cycles$str$, $str$SPI Class 102 — life shot rating; use insert: true$str$, $jsonb${"Spi Type":102,"Num Annual Mold Cycles":1000000,"Use Insert":"true"}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$SPI 103$str$, $str$500000$str$, $str$cycles$str$, $str$SPI Class 103 — life shot rating; use insert: false$str$, $jsonb${"Spi Type":103,"Num Annual Mold Cycles":500000,"Use Insert":"false"}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$SPI 104$str$, $str$100000$str$, $str$cycles$str$, $str$SPI Class 104 — life shot rating; use insert: false$str$, $jsonb${"Spi Type":104,"Num Annual Mold Cycles":100000,"Use Insert":"false"}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$SPI 105$str$, $str$5000$str$, $str$cycles$str$, $str$SPI Class 105 — life shot rating; use insert: false$str$, $jsonb${"Spi Type":105,"Num Annual Mold Cycles":5000,"Use Insert":"false"}$jsonb$::jsonb)
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
