-- ============================================================================
-- Migration 684: Seed im_reference_data category = 'lookup_table'
-- (tool coating) — schema: migration 636
--
-- Generated by gen_684_seed_im_lookup_tool_coating.js.
-- Row count: 10 (memory/plastic modeling/lookup/tblToolCoating.json).
--
-- NOT wired into any cost calculation — staging only. Genuine capability
-- gap: no tool-coating cost/life modeling exists anywhere in this app today.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
('lookup_table', 'USA', '2026-03', $str$None$str$, $str$1$str$, $str$life_factor$str$, $str$Tool coating: None — life improvement 1x, cost factor $0/kg$str$, $jsonb${"Coating Cost Factor (USD / kg)":0,"Coating Type":"None","Tool Life Improvement Factor":1}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$Tribo-coating$str$, $str$1.1$str$, $str$life_factor$str$, $str$Tool coating: Tribo-coating — life improvement 1.1x, cost factor $1.9/kg$str$, $jsonb${"Coating Cost Factor (USD / kg)":1.9,"Coating Type":"Tribo-coating","Tool Life Improvement Factor":1.1}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$Electroless Nickel$str$, $str$1.4$str$, $str$life_factor$str$, $str$Tool coating: Electroless Nickel — life improvement 1.4x, cost factor $2.8/kg$str$, $jsonb${"Coating Cost Factor (USD / kg)":2.8,"Coating Type":"Electroless Nickel","Tool Life Improvement Factor":1.4}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$Electroless Teflon$str$, $str$1.7$str$, $str$life_factor$str$, $str$Tool coating: Electroless Teflon — life improvement 1.7x, cost factor $3.5/kg$str$, $jsonb${"Coating Cost Factor (USD / kg)":3.5,"Coating Type":"Electroless Teflon","Tool Life Improvement Factor":1.7}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$Nitrided Steel$str$, $str$1.9$str$, $str$life_factor$str$, $str$Tool coating: Nitrided Steel — life improvement 1.9x, cost factor $4.1/kg$str$, $jsonb${"Coating Cost Factor (USD / kg)":4.1,"Coating Type":"Nitrided Steel","Tool Life Improvement Factor":1.9}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$Electroplated Chromium$str$, $str$2$str$, $str$life_factor$str$, $str$Tool coating: Electroplated Chromium — life improvement 2x, cost factor $4.4/kg$str$, $jsonb${"Coating Cost Factor (USD / kg)":4.4,"Coating Type":"Electroplated Chromium","Tool Life Improvement Factor":2}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$Plasma Sprayed$str$, $str$3$str$, $str$life_factor$str$, $str$Tool coating: Plasma Sprayed — life improvement 3x, cost factor $6.9/kg$str$, $jsonb${"Coating Cost Factor (USD / kg)":6.9,"Coating Type":"Plasma Sprayed","Tool Life Improvement Factor":3}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$PVD TiN$str$, $str$7.2$str$, $str$life_factor$str$, $str$Tool coating: PVD TiN — life improvement 7.2x, cost factor $18.2/kg$str$, $jsonb${"Coating Cost Factor (USD / kg)":18.2,"Coating Type":"PVD TiN","Tool Life Improvement Factor":7.2}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$CVD TiC$str$, $str$7.5$str$, $str$life_factor$str$, $str$Tool coating: CVD TiC — life improvement 7.5x, cost factor $19.1/kg$str$, $jsonb${"Coating Cost Factor (USD / kg)":19.1,"Coating Type":"CVD TiC","Tool Life Improvement Factor":7.5}$jsonb$::jsonb),
('lookup_table', 'USA', '2026-03', $str$DuplexVariantic$str$, $str$14.4$str$, $str$life_factor$str$, $str$Tool coating: DuplexVariantic — life improvement 14.4x, cost factor $26.6/kg$str$, $jsonb${"Coating Cost Factor (USD / kg)":26.6,"Coating Type":"DuplexVariantic","Tool Life Improvement Factor":14.4}$jsonb$::jsonb)
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
