-- ============================================================================
-- Migration 689: Seed machining_reference_data category = 'process'
-- (schema: migration 638)
--
-- Generated by gen_689_seed_machining_processes.js.
-- Row count: 43 (memory/machining/processes.json).
--
-- NOT wired into any cost calculation — staging only. Real machining
-- process-name catalog (mirrors Sheet Metal's process_operations.json
-- taxonomy for the Machining domain).
-- ============================================================================

INSERT INTO machining_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
('process', 'USA', '2026-03', $str$2 Axis Bar Feed Lathe with Sub Spindle$str$, $str$Haas DS-30 with BAR3010SS Feeder$str$, NULL, NULL, $jsonb${"processName":"2 Axis Bar Feed Lathe with Sub Spindle","defaultToolShopName":"","defaultMachine":"Haas DS-30 with BAR3010SS Feeder","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$2 Axis Lathe$str$, $str$Acra 2800 CET$str$, NULL, NULL, $jsonb${"processName":"2 Axis Lathe","defaultToolShopName":"","defaultMachine":"Acra 2800 CET","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$3 Axis Bar Feed Lathe with Sub Spindle$str$, $str$Haas DS-30SSY with BAR3010SS Feeder$str$, NULL, NULL, $jsonb${"processName":"3 Axis Bar Feed Lathe with Sub Spindle","defaultToolShopName":"","defaultMachine":"Haas DS-30SSY with BAR3010SS Feeder","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$3 Axis Lathe$str$, $str$Boehringer VDF 400$str$, NULL, NULL, $jsonb${"processName":"3 Axis Lathe","defaultToolShopName":"","defaultMachine":"Boehringer VDF 400","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$3 Axis Mill$str$, $str$Giddings & Lewis H60F$str$, NULL, NULL, $jsonb${"processName":"3 Axis Mill","defaultToolShopName":"","defaultMachine":"Giddings & Lewis H60F","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$3 Axis Router$str$, $str$Multicam 7000 Series CNC Router, Model 103$str$, NULL, NULL, $jsonb${"processName":"3 Axis Router","defaultToolShopName":"","defaultMachine":"Multicam 7000 Series CNC Router, Model 103","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$4 Axis Mill$str$, $str$Giddings & Lewis H60F w Rotary Table$str$, NULL, NULL, $jsonb${"processName":"4 Axis Mill","defaultToolShopName":"","defaultMachine":"Giddings & Lewis H60F w Rotary Table","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$5 Axis Mill$str$, $str$DMG MORI DMU 105 monoBLOCK$str$, NULL, NULL, $jsonb${"processName":"5 Axis Mill","defaultToolShopName":"","defaultMachine":"DMG MORI DMU 105 monoBLOCK","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$5 Axis Router$str$, $str$Thermwood Multipurpose 67, 5' x 10'$str$, NULL, NULL, $jsonb${"processName":"5 Axis Router","defaultToolShopName":"","defaultMachine":"Thermwood Multipurpose 67, 5' x 10'","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$Automated Deburr$str$, $str$Default Automated Deburr$str$, NULL, NULL, $jsonb${"processName":"Automated Deburr","defaultToolShopName":"","defaultMachine":"Default Automated Deburr","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$Bench Operation$str$, $str$Manual Bench Cell - 16m x 4m Footprint$str$, NULL, $str$Tool shop: Default$str$, $jsonb${"processName":"Bench Operation","defaultToolShopName":"Default","defaultMachine":"Manual Bench Cell - 16m x 4m Footprint","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$Bevel Gear Cutting Machine$str$, $str$Gleason Coniflex 104$str$, NULL, $str$Tool shop: Bevel Gear Cutting Machine$str$, $jsonb${"processName":"Bevel Gear Cutting Machine","defaultToolShopName":"Bevel Gear Cutting Machine","defaultMachine":"Gleason Coniflex 104","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$Broach$str$, $str$Cell-Mate$str$, NULL, $str$Tool shop: Broach$str$, $jsonb${"processName":"Broach","defaultToolShopName":"Broach","defaultMachine":"Cell-Mate","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$Cylindrical Grinder$str$, $str$Flex Grind Schaudt M$str$, NULL, NULL, $jsonb${"processName":"Cylindrical Grinder","defaultToolShopName":"","defaultMachine":"Flex Grind Schaudt M","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$Deep Bore Machine$str$, $str$Fortune 2225$str$, NULL, NULL, $jsonb${"processName":"Deep Bore Machine","defaultToolShopName":"","defaultMachine":"Fortune 2225","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$DeMask$str$, $str$DeMask Cell - 10m x 10m Footprint$str$, NULL, NULL, $jsonb${"processName":"DeMask","defaultToolShopName":"","defaultMachine":"DeMask Cell - 10m x 10m Footprint","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$Drill Press$str$, $str$Carlton 5 ft X 13 in$str$, NULL, NULL, $jsonb${"processName":"Drill Press","defaultToolShopName":"","defaultMachine":"Carlton 5 ft X 13 in","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$Etch Cell$str$, $str$Etch Cell - 1.8m x 1.0m x 1.2m Tank Size$str$, NULL, NULL, $jsonb${"processName":"Etch Cell","defaultToolShopName":"","defaultMachine":"Etch Cell - 1.8m x 1.0m x 1.2m Tank Size","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$Gun Drill$str$, $str$Honge XE 1200-CNC$str$, NULL, NULL, $jsonb${"processName":"Gun Drill","defaultToolShopName":"","defaultMachine":"Honge XE 1200-CNC","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$Hob Machine$str$, $str$Gleason Genesis 130H Vertical$str$, NULL, $str$Tool shop: Hob Machine$str$, $jsonb${"processName":"Hob Machine","defaultToolShopName":"Hob Machine","defaultMachine":"Gleason Genesis 130H Vertical","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$Inspection$str$, $str$Default$str$, NULL, NULL, $jsonb${"processName":"Inspection","defaultToolShopName":"","defaultMachine":"Default","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$Internal Grinder$str$, $str$Danobat Overbeck IC/iD$str$, NULL, NULL, $jsonb${"processName":"Internal Grinder","defaultToolShopName":"","defaultMachine":"Danobat Overbeck IC/iD","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$Jig Bore$str$, $str$SIP Hydroptic 6A$str$, NULL, NULL, $jsonb${"processName":"Jig Bore","defaultToolShopName":"","defaultMachine":"SIP Hydroptic 6A","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$Jig Grind$str$, $str$Hauser S3-DR$str$, NULL, NULL, $jsonb${"processName":"Jig Grind","defaultToolShopName":"","defaultMachine":"Hauser S3-DR","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$Manual Deburr$str$, $str$Default Manual Deburr$str$, NULL, NULL, $jsonb${"processName":"Manual Deburr","defaultToolShopName":"","defaultMachine":"Default Manual Deburr","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$Mask Cure$str$, $str$Curing Oven - 1.3m x 1.3m x 1.4m Useable Oven Size$str$, NULL, NULL, $jsonb${"processName":"Mask Cure","defaultToolShopName":"","defaultMachine":"Curing Oven - 1.3m x 1.3m x 1.4m Useable Oven Size","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$MillTurn$str$, $str$GILDEMEISTER GMX 400 LINEAR$str$, NULL, NULL, $jsonb${"processName":"MillTurn","defaultToolShopName":"","defaultMachine":"GILDEMEISTER GMX 400 LINEAR","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$No Cost Feature$str$, NULL, NULL, NULL, $jsonb${"processName":"No Cost Feature","defaultToolShopName":"","defaultMachine":"","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$Perimeter Cut$str$, NULL, NULL, NULL, $jsonb${"processName":"Perimeter Cut","defaultToolShopName":"","defaultMachine":"","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$Profile Gear Grinder$str$, $str$Gleason P 2400 G$str$, NULL, $str$Tool shop: Profile Gear Grinder$str$, $jsonb${"processName":"Profile Gear Grinder","defaultToolShopName":"Profile Gear Grinder","defaultMachine":"Gleason P 2400 G","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$Reciprocating Surface Grinder$str$, $str$Danobat RTU$str$, NULL, NULL, $jsonb${"processName":"Reciprocating Surface Grinder","defaultToolShopName":"","defaultMachine":"Danobat RTU","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$Rotary Surface Grinder$str$, $str$ABA Z&B MR$str$, NULL, NULL, $jsonb${"processName":"Rotary Surface Grinder","defaultToolShopName":"","defaultMachine":"ABA Z&B MR","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$Scribe$str$, $str$Gantry Laser Scribe - 15m x 4m x 1.5m Bed Size$str$, NULL, NULL, $jsonb${"processName":"Scribe","defaultToolShopName":"","defaultMachine":"Gantry Laser Scribe - 15m x 4m x 1.5m Bed Size","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$Shaper$str$, $str$Gleason 800ES Shaper$str$, NULL, $str$Tool shop: Shaper$str$, $jsonb${"processName":"Shaper","defaultToolShopName":"Shaper","defaultMachine":"Gleason 800ES Shaper","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$Shaver$str$, $str$Gleason Genesis 130 SV$str$, NULL, $str$Tool shop: Shaver$str$, $jsonb${"processName":"Shaver","defaultToolShopName":"Shaver","defaultMachine":"Gleason Genesis 130 SV","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$Simultaneous Turning$str$, $str$Virtual CNC Multi-Spindle, 6 Spindles, Large$str$, NULL, NULL, $jsonb${"processName":"Simultaneous Turning","defaultToolShopName":"","defaultMachine":"Virtual CNC Multi-Spindle, 6 Spindles, Large","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$Special Inspection$str$, $str$Default$str$, NULL, NULL, $jsonb${"processName":"Special Inspection","defaultToolShopName":"","defaultMachine":"Default","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$Spline Roller$str$, $str$Yieh Chen YC-800$str$, NULL, $str$Tool shop: Spline Roller$str$, $jsonb${"processName":"Spline Roller","defaultToolShopName":"Spline Roller","defaultMachine":"Yieh Chen YC-800","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$Stock Prep Lathe$str$, $str$Acra 2800 CET$str$, NULL, NULL, $jsonb${"processName":"Stock Prep Lathe","defaultToolShopName":"","defaultMachine":"Acra 2800 CET","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$Stock Prep Mill$str$, $str$Giddings & Lewis H60F$str$, NULL, NULL, $jsonb${"processName":"Stock Prep Mill","defaultToolShopName":"","defaultMachine":"Giddings & Lewis H60F","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$Threaded Wheel Gear Grinder$str$, $str$Gleason 300 TWG$str$, NULL, $str$Tool shop: Threaded Wheel Gear Grinder$str$, $jsonb${"processName":"Threaded Wheel Gear Grinder","defaultToolShopName":"Threaded Wheel Gear Grinder","defaultMachine":"Gleason 300 TWG","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$Use Stock Machining$str$, NULL, NULL, NULL, $jsonb${"processName":"Use Stock Machining","defaultToolShopName":"","defaultMachine":"","notes":""}$jsonb$::jsonb),
('process', 'USA', '2026-03', $str$Wire EDM$str$, $str$Fanuc 0id$str$, NULL, NULL, $jsonb${"processName":"Wire EDM","defaultToolShopName":"","defaultMachine":"Fanuc 0id","notes":""}$jsonb$::jsonb)
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
