-- ============================================================================
-- Migration 790: Seed every remaining memory/ process + operation source into
-- the Process Calculator Mappings catalog, and retire the Post Processing group
-- ============================================================================
-- Generated by scripts/gen_790_seed_remaining_process_groups.js -- do not
-- hand-edit, re-run the generator and diff instead.
--
-- WHY
--
-- The catalog is scoped to named source folders (migrations 731 and 736).
-- Nine source folders under memory/ were never seeded, so their processes and
-- operations were absent from the Process page. Each is added under the group
-- name the catalog already uses (migration 302):
--
--   Additive Manufacturing     <- memory/Additive Manufacturing  (12 processes, 55 operations)
--   Assembly                   <- memory/Assembly  (21 processes, 34 operations)
--   Part Assembly              <- memory/Part Assembly  (9 processes, 44 operations)
--   Composites                 <- memory/Composites  (11 processes, 29 operations)
--   PCB                        <- memory/PCBA  (33 processes, 26 operations)
--   Surface Treatment          <- memory/SurfaceTreatment  (33 processes, 39 operations)
--   Forging                    <- memory/Forging  (12 processes, 0 operations)
--   Other Secondary Processes  <- memory/secondary process  (12 processes, 0 operations)
--   Stock Machining            <- memory/Stock Maching  (2 processes, 3 operations)
--
-- 145 processes and 230 operation rows in total. Machines are NOT seeded here;
-- that is separate work against mhr_records.
--
-- NEW ROWS ARE NOT WIRED TO A COST ENGINE, SO THEY ARE SEEDED INACTIVE
--
-- None of these groups has a registered costing engine, so every process is
-- seeded roadmap_status not_modeled with machine_class NULL. No machine class or
-- calculator is guessed. No Cost Feature and Material Stock are non_mfg markers,
-- as in migration 609. User-Defined Process is a placeholder with no data behind
-- it and is not present in any already-seeded group, so it is skipped.
--
-- The mapping rows are inserted with is_active = false. The table CHECK
-- chk_machine_class_required (migrations 369, 617, 756) rejects any ACTIVE row
-- with a NULL machine_class unless it is a named non-machine exemption. A first
-- draft of this migration inserted them active, the check rejected the insert,
-- and the whole transaction rolled back, leaving the page unchanged. Inactive is
-- also the established convention (migration 756): a real process with no
-- machine class yet stays visible on the Process page as inactive, an honest
-- view of what is built versus not. The two re-homed rows below stay active
-- because they carry a real machine_class. Activating a marker such as No Cost
-- Feature would need its own named exemption in that check, as 617 and 756 did,
-- and is deliberately not done here.
--
-- THE TWO POST PROCESSING ROWS WERE NOT DISPOSABLE
--
-- Post Processing held exactly two rows, and migration 731 established both are
-- wired to real registered engines:
--   Surface Treatment  -> surface_treatment  (real surface-treatment calculator)
--   CMM Inspection     -> cmm
-- Deleting them would break the Add Operation picker and workflow validation.
-- Their real homes are the groups seeded below (Surface Treatment, and Other
-- Secondary Processes where memory/secondary process lists CMM Inspection), so
-- they are MOVED, keeping id, machine_class and calculator link, and only then
-- is the empty Post Processing group removed. A guard aborts the migration if
-- anything wired or referenced by mhr_records would be lost.
--
-- NOT SEEDED (see scripts/790_unresolved.json)
--   2 Mold Molding        operation rows only, no process list, no confirmed group.
--   Multi-Spindle Maching source files hold only a header row; nothing real.
-- ============================================================================

BEGIN;

-- ── Step 1: re-home the two wired Post Processing rows ─────────────────────
-- Taxonomy first (its id is what mappings and mhr_records point at, so moving
-- the row keeps every link intact). The NOT EXISTS guard keeps a re-run safe.
--
-- LABOUR TIER IS PINNED. Applied-route costing bills labour against
-- lhr_process_group, falling back to the mapping own process_group when it is
-- NULL (migration 424). CMM Inspection is already Quality via 424, but Surface
-- Treatment has NULL, so it currently bills at the Post Processing tier. Moving
-- it to a group with no labour rate would silently change that cost, so the old
-- tier is written into lhr_process_group first (COALESCE never overrides an
-- existing value).
UPDATE process_taxonomy pt
SET process_group = 'Surface Treatment'
WHERE pt.process_group = 'Post Processing' AND pt.process_name = 'Surface Treatment'
  AND NOT EXISTS (SELECT 1 FROM process_taxonomy x WHERE x.process_group = 'Surface Treatment' AND x.process_name = 'Surface Treatment');

UPDATE process_taxonomy pt
SET process_group = 'Other Secondary Processes'
WHERE pt.process_group = 'Post Processing' AND pt.process_name = 'CMM Inspection'
  AND NOT EXISTS (SELECT 1 FROM process_taxonomy x WHERE x.process_group = 'Other Secondary Processes' AND x.process_name = 'CMM Inspection');

UPDATE process_calculator_mappings m
SET process_group = 'Surface Treatment',
    lhr_process_group = COALESCE(m.lhr_process_group, 'Post Processing')
WHERE m.process_group = 'Post Processing' AND m.operation = 'Surface Treatment'
  AND NOT EXISTS (SELECT 1 FROM process_calculator_mappings x
                  WHERE x.process_group = 'Surface Treatment' AND x.process_route = m.process_route AND x.operation = m.operation);

UPDATE process_calculator_mappings m
SET process_group = 'Other Secondary Processes',
    lhr_process_group = COALESCE(m.lhr_process_group, 'Post Processing')
WHERE m.process_group = 'Post Processing' AND m.operation = 'CMM Inspection'
  AND NOT EXISTS (SELECT 1 FROM process_calculator_mappings x
                  WHERE x.process_group = 'Other Secondary Processes' AND x.process_route = m.process_route AND x.operation = m.operation);

-- ── Step 2: process_taxonomy ───────────────────────────────────────────────
-- ON CONFLICT only fills MISSING defaults. It never touches machine_class or
-- roadmap_status, so a row that is already wired (the two re-homed above)
-- keeps its live wiring.
INSERT INTO process_taxonomy (process_group, process_name, machine_class, roadmap_status, default_machine_name, default_tool_shop_name, display_order)
VALUES
($str$Additive Manufacturing$str$, $str$Breakoff$str$, NULL, 'not_modeled', $str$Manual Breakoff with Hand Tools$str$, NULL, 700),
($str$Additive Manufacturing$str$, $str$Cleaning$str$, NULL, 'not_modeled', $str$Compressed Air Blasting$str$, NULL, 701),
($str$Additive Manufacturing$str$, $str$Laser Sintering$str$, NULL, 'not_modeled', $str$3D Systems ProX SLS 500$str$, NULL, 702),
($str$Additive Manufacturing$str$, $str$Manual Tool Base Removal$str$, NULL, 'not_modeled', $str$Manual Hand Tools$str$, NULL, 703),
($str$Additive Manufacturing$str$, $str$Metal Sintering$str$, NULL, 'not_modeled', $str$Concept Laser M Line Factory$str$, NULL, 704),
($str$Additive Manufacturing$str$, $str$No Cost Feature$str$, NULL, 'non_mfg', NULL, NULL, 705),
($str$Additive Manufacturing$str$, $str$Part Curing$str$, NULL, 'not_modeled', $str$AaroCure Oven$str$, NULL, 706),
($str$Additive Manufacturing$str$, $str$Powder Loading$str$, NULL, 'not_modeled', $str$Electric Trolley Loader - 2m Lift Height$str$, NULL, 707),
($str$Additive Manufacturing$str$, $str$Power Tool Base Removal$str$, NULL, 'not_modeled', $str$Oscillating Power Tool 300W$str$, NULL, 708),
($str$Additive Manufacturing$str$, $str$Printing$str$, NULL, 'not_modeled', $str$Connex 1 Objet260$str$, NULL, 709),
($str$Additive Manufacturing$str$, $str$Resin Curing$str$, NULL, 'not_modeled', $str$ProJet 7000HD$str$, NULL, 710),
($str$Additive Manufacturing$str$, $str$Sieving$str$, NULL, 'not_modeled', $str$Vibratory Compact Sieve - 500mm Diameter$str$, NULL, 711),
($str$Assembly$str$, $str$Adhesive Bonding$str$, NULL, 'not_modeled', $str$Manual Adhesive Bonding$str$, $str$Default$str$, 800),
($str$Assembly$str$, $str$Cap Sealing$str$, NULL, 'not_modeled', $str$Manual Cap Sealing$str$, $str$Default$str$, 801),
($str$Assembly$str$, $str$Electron Beam Welding$str$, NULL, 'not_modeled', $str$Electron Beam Welder - 15000 Watts - 0.8m x 0.7m$str$, NULL, 802),
($str$Assembly$str$, $str$Fay Sealing$str$, NULL, 'not_modeled', $str$Manual Fay Sealing$str$, $str$Default$str$, 803),
($str$Assembly$str$, $str$Fillet Sealing$str$, NULL, 'not_modeled', $str$Manual Fillet Sealing$str$, $str$Default$str$, 804),
($str$Assembly$str$, $str$Laser Welding$str$, NULL, 'not_modeled', $str$Laser Welder - 1000 Watts - 0.5m x 0.3m$str$, NULL, 805),
($str$Assembly$str$, $str$Lock Bolt$str$, NULL, 'not_modeled', $str$Huck 3585$str$, NULL, 806),
($str$Assembly$str$, $str$Manual MIG Welding$str$, NULL, 'not_modeled', $str$Default Mig Weld$str$, NULL, 807),
($str$Assembly$str$, $str$Manual Spot Welding$str$, NULL, 'not_modeled', $str$Default Spot Weld$str$, NULL, 808),
($str$Assembly$str$, $str$Manual TIG Welding$str$, NULL, 'not_modeled', $str$Default TIG Welding$str$, NULL, 809),
($str$Assembly$str$, $str$Mechanical Assembly$str$, NULL, 'not_modeled', $str$Default Mechanical Assembly$str$, NULL, 810),
($str$Assembly$str$, $str$No Cost Feature$str$, NULL, 'non_mfg', NULL, NULL, 811),
($str$Assembly$str$, $str$Pick and Place$str$, NULL, 'not_modeled', $str$Default Pick and Place$str$, NULL, 812),
($str$Assembly$str$, $str$Rivet$str$, NULL, 'not_modeled', $str$Default$str$, NULL, 813),
($str$Assembly$str$, $str$Robotic MIG Welding$str$, NULL, 'not_modeled', $str$Default Robotic Mig$str$, NULL, 814),
($str$Assembly$str$, $str$Robotic Spot Welding$str$, NULL, 'not_modeled', $str$Default Robotic Spot$str$, NULL, 815),
($str$Assembly$str$, $str$Robotic TIG Welding$str$, NULL, 'not_modeled', $str$Default Robotic TIG Weld$str$, NULL, 816),
($str$Assembly$str$, $str$Threaded Insert$str$, NULL, 'not_modeled', $str$Default Threaded Insert$str$, NULL, 817),
($str$Assembly$str$, $str$Ultrasonic Welding$str$, NULL, 'not_modeled', $str$15kHz Ultrasonic Bench Welder 3500W$str$, $str$Default$str$, 818),
($str$Assembly$str$, $str$Weld Clean Up$str$, NULL, 'not_modeled', $str$Default$str$, NULL, 819),
($str$Assembly$str$, $str$Weld Prep$str$, NULL, 'not_modeled', $str$Default$str$, NULL, 820),
($str$Part Assembly$str$, $str$Bevel Cutting$str$, NULL, 'not_modeled', $str$default$str$, NULL, 900),
($str$Part Assembly$str$, $str$Finish Grinding$str$, NULL, 'not_modeled', $str$default$str$, NULL, 901),
($str$Part Assembly$str$, $str$Grinding$str$, NULL, 'not_modeled', $str$default$str$, NULL, 902),
($str$Part Assembly$str$, $str$Laser Seam Welding$str$, NULL, 'not_modeled', $str$Default$str$, NULL, 903),
($str$Part Assembly$str$, $str$Manual MIG Welding$str$, NULL, 'not_modeled', $str$Default Mig Weld$str$, NULL, 904),
($str$Part Assembly$str$, $str$Manual Spot Welding$str$, NULL, 'not_modeled', $str$Default Spot Weld$str$, NULL, 905),
($str$Part Assembly$str$, $str$Robotic MIG Welding$str$, NULL, 'not_modeled', $str$Default Robotic Mig$str$, NULL, 906),
($str$Part Assembly$str$, $str$Robotic Spot Welding$str$, NULL, 'not_modeled', $str$Default Robotic Spot$str$, NULL, 907),
($str$Part Assembly$str$, $str$Wire Brushing$str$, NULL, 'not_modeled', $str$default$str$, NULL, 908),
($str$Composites$str$, $str$Autoclave Cure$str$, NULL, 'not_modeled', $str$ASC Process Systems EC 0.9m x 1.5m$str$, NULL, 1000),
($str$Composites$str$, $str$Automated Fiber Placement$str$, NULL, 'not_modeled', $str$Automated Fiber Placement Machine - 11.4m x 4.2m x 4.2m$str$, $str$default$str$, 1001),
($str$Composites$str$, $str$Automated Tape Layup$str$, NULL, 'not_modeled', $str$Automated Tape Layup Machine - 16m x 5.3m x 1.6m$str$, $str$default$str$, 1002),
($str$Composites$str$, $str$Bench Operation$str$, NULL, 'not_modeled', $str$Manual Bench Cell - 16m x 4m$str$, NULL, 1003),
($str$Composites$str$, $str$Final Vacuum Bag$str$, NULL, 'not_modeled', NULL, $str$default$str$, 1004),
($str$Composites$str$, $str$Hand Layup$str$, NULL, 'not_modeled', $str$Clean Room Area - 16m x 4m$str$, $str$default$str$, 1005),
($str$Composites$str$, $str$Mold Preparation$str$, NULL, 'not_modeled', $str$Mold Preparation Area 16m x 4m$str$, $str$default$str$, 1006),
($str$Composites$str$, $str$No Cost Feature$str$, NULL, 'non_mfg', NULL, NULL, 1007),
($str$Composites$str$, $str$Tool Clean$str$, NULL, 'not_modeled', $str$Tool Clean Area: Adapt 1000W Laser - 16m x 4m$str$, $str$default$str$, 1008),
($str$Composites$str$, $str$Ultrasonic Cut$str$, NULL, 'not_modeled', $str$American GFM CM10 - 1.8m x 1.8m$str$, NULL, 1009),
($str$Composites$str$, $str$Vacuum Bag$str$, NULL, 'not_modeled', NULL, $str$default$str$, 1010),
($str$PCB$str$, $str$Apply Photo Resist$str$, NULL, 'not_modeled', $str$Hakuto Mach 630up$str$, NULL, 1100),
($str$PCB$str$, $str$Automated Optical Inspection$str$, NULL, 'not_modeled', $str$CISM Phoenix HDI$str$, NULL, 1101),
($str$PCB$str$, $str$Automated Vision Inspection$str$, NULL, 'not_modeled', $str$CISM Phoenix FI$str$, NULL, 1102),
($str$PCB$str$, $str$Bed of Nails$str$, NULL, 'not_modeled', $str$Kyoritsu Focus -2000Plus$str$, $str$Default$str$, 1103),
($str$PCB$str$, $str$Bench Operation$str$, NULL, 'not_modeled', $str$Default$str$, NULL, 1104),
($str$PCB$str$, $str$Copper Plate and Tin Coat$str$, NULL, 'not_modeled', $str$Plating Line - 10 Gating Cells - 4900mm x 640mm$str$, NULL, 1105),
($str$PCB$str$, $str$Cure Plugged Vias$str$, NULL, 'not_modeled', $str$Aeolus Forced Air Conveyor Dryer BBC-Air 366C-4-2$str$, NULL, 1106),
($str$PCB$str$, $str$Cure Solder Mask$str$, NULL, 'not_modeled', $str$Rack 1.2m x 1.2m x 1.2m - BedSize$str$, NULL, 1107),
($str$PCB$str$, $str$DES$str$, NULL, 'not_modeled', $str$DES Line (25m x 1.7m)$str$, NULL, 1108),
($str$PCB$str$, $str$Desmear and Plate Through Holes$str$, NULL, 'not_modeled', $str$Plating Line - 10 Gating Tanks - 4900mm x 640mm$str$, NULL, 1109),
($str$PCB$str$, $str$Develop Solder Mask$str$, NULL, 'not_modeled', $str$Solder Mask Developer (8m x 1.7m)$str$, NULL, 1110),
($str$PCB$str$, $str$Dissolve Unexposed Photo Resist$str$, NULL, 'not_modeled', $str$Photo Resist Developer (8m x 1.7m)$str$, NULL, 1111),
($str$PCB$str$, $str$Drill Circuit Holes$str$, NULL, 'not_modeled', $str$Excellon HS 1L 2 heads 1 station$str$, $str$Default$str$, 1112),
($str$PCB$str$, $str$Drill Registration Holes$str$, NULL, 'not_modeled', $str$Excellon HS 1L 2 heads 1 station$str$, NULL, 1113),
($str$PCB$str$, $str$Electroless Nickel Immersion Gold$str$, NULL, 'not_modeled', $str$High Capacity Plating Line$str$, NULL, 1114),
($str$PCB$str$, $str$Film Imaging$str$, NULL, 'not_modeled', $str$Altix Afosa ies$str$, NULL, 1115),
($str$PCB$str$, $str$Flying Probe$str$, NULL, 'not_modeled', $str$ATG- A5Neo Flying Probe Tester$str$, NULL, 1116),
($str$PCB$str$, $str$Hot Air Solder Leveling$str$, NULL, 'not_modeled', $str$HASL Large$str$, NULL, 1117),
($str$PCB$str$, $str$Laser Drill Vias$str$, NULL, 'not_modeled', $str$ESI 5335$str$, NULL, 1118),
($str$PCB$str$, $str$Material Stock$str$, NULL, 'non_mfg', $str$Default$str$, $str$Default$str$, 1119),
($str$PCB$str$, $str$No Cost Feature$str$, NULL, 'non_mfg', NULL, NULL, 1120),
($str$PCB$str$, $str$Organic Solderability Preservative$str$, NULL, 'not_modeled', $str$OSP Line$str$, NULL, 1121),
($str$PCB$str$, $str$Oven Cure Layers$str$, NULL, 'not_modeled', $str$Lauffer RMV 125$str$, NULL, 1122),
($str$PCB$str$, $str$Photolithography$str$, NULL, 'not_modeled', $str$Altix Afosa ies$str$, NULL, 1123),
($str$PCB$str$, $str$Plug Vias$str$, NULL, 'not_modeled', $str$ATMA PC 68$str$, $str$Default$str$, 1124),
($str$PCB$str$, $str$Router$str$, NULL, 'not_modeled', $str$GETECH ESR1000$str$, NULL, 1125),
($str$PCB$str$, $str$Screen Printing$str$, NULL, 'not_modeled', $str$ATMA PC 68$str$, $str$Default$str$, 1126),
($str$PCB$str$, $str$SES$str$, NULL, 'not_modeled', $str$SES Line (22.5m x 2m)$str$, NULL, 1127),
($str$PCB$str$, $str$Silkscreen Cure$str$, NULL, 'not_modeled', $str$Aeolus Forced Air Conveyor Dryer BBC-Air 366C-4-2$str$, NULL, 1128),
($str$PCB$str$, $str$Stamp$str$, NULL, 'not_modeled', $str$Ascen ASPM-10T$str$, $str$Default$str$, 1129),
($str$PCB$str$, $str$Surface Preparation$str$, NULL, 'not_modeled', $str$Chemcut Model 604$str$, NULL, 1130),
($str$PCB$str$, $str$Tack Dry Solder Mask$str$, NULL, 'not_modeled', $str$Rack 1.2m x 1.2m x 1.2m - BedSize$str$, NULL, 1131),
($str$PCB$str$, $str$Wet Film Solder Mask$str$, NULL, 'not_modeled', $str$ATMA PC 68$str$, NULL, 1132),
($str$Surface Treatment$str$, $str$Anodize$str$, NULL, 'not_modeled', $str$Type I Line - Large$str$, NULL, 1200),
($str$Surface Treatment$str$, $str$Bead Blast$str$, NULL, 'not_modeled', $str$Default Bead Blast$str$, NULL, 1201),
($str$Surface Treatment$str$, $str$Black Oxide$str$, NULL, 'not_modeled', $str$Hot Temp Black Oxide Machine - 1200mm x 900mm$str$, $str$Default$str$, 1202),
($str$Surface Treatment$str$, $str$Cadmium Plating$str$, NULL, 'not_modeled', $str$Default Cadmium Plating$str$, NULL, 1203),
($str$Surface Treatment$str$, $str$Conveyor Abrasive Finishing$str$, NULL, 'not_modeled', $str$AMADA BR-610W$str$, NULL, 1204),
($str$Surface Treatment$str$, $str$Conveyor Conversion Coating$str$, NULL, 'not_modeled', $str$10 Stage Conveyor Pretreatment Washer - 2.1m x 1.5m$str$, $str$Default$str$, 1205),
($str$Surface Treatment$str$, $str$Conveyor Dry$str$, NULL, 'not_modeled', $str$RDM Mars 1$str$, NULL, 1206),
($str$Surface Treatment$str$, $str$Conveyor Oven Cure$str$, NULL, 'not_modeled', $str$Conveyor Cure Oven - 1500mm x 900mm$str$, NULL, 1207),
($str$Surface Treatment$str$, $str$Conveyor Part Loading$str$, NULL, 'not_modeled', $str$Default Loading Area$str$, NULL, 1208),
($str$Surface Treatment$str$, $str$Conveyor Part Unloading$str$, NULL, 'not_modeled', $str$Default Unloading Area$str$, NULL, 1209),
($str$Surface Treatment$str$, $str$Conveyor Powder Coating$str$, NULL, 'not_modeled', $str$Automated Conveyor Powder Booth System - 1800mm x 1200mm$str$, $str$Default$str$, 1210),
($str$Surface Treatment$str$, $str$Conveyor Shot Blast$str$, NULL, 'not_modeled', $str$Binhai Abrator Q383$str$, $str$Default$str$, 1211),
($str$Surface Treatment$str$, $str$Decorative Chrome Plating$str$, NULL, 'not_modeled', $str$Default Decorative Chrome$str$, NULL, 1212),
($str$Surface Treatment$str$, $str$Degrease$str$, NULL, 'not_modeled', $str$16 in Conveyor Power Parts Washer$str$, NULL, 1213),
($str$Surface Treatment$str$, $str$Dot Peen$str$, NULL, 'not_modeled', $str$Benchtop Dot Peen$str$, NULL, 1214),
($str$Surface Treatment$str$, $str$Hard Chrome Plating$str$, NULL, 'not_modeled', $str$Default-Hard Chrome$str$, NULL, 1215),
($str$Surface Treatment$str$, $str$Laser Engraving$str$, NULL, 'not_modeled', $str$Gravograph LS100$str$, NULL, 1216),
($str$Surface Treatment$str$, $str$Manual Paint$str$, NULL, 'not_modeled', $str$Paint Booth - 11.0m x 5.0m x 3.6m$str$, $str$Default$str$, 1217),
($str$Surface Treatment$str$, $str$Mask-Bench$str$, NULL, 'not_modeled', $str$Default Mask Bench$str$, NULL, 1218),
($str$Surface Treatment$str$, $str$Mask-Spray$str$, NULL, 'not_modeled', $str$Pretec Spray Booth$str$, $str$Default$str$, 1219),
($str$Surface Treatment$str$, $str$Nickel Plating$str$, NULL, 'not_modeled', $str$Default Nickel Plating$str$, NULL, 1220),
($str$Surface Treatment$str$, $str$Oven Cure$str$, NULL, 'not_modeled', $str$Cure Oven - 1m x 1m x 2m$str$, NULL, 1221),
($str$Surface Treatment$str$, $str$Painting$str$, NULL, 'not_modeled', $str$Default ElectroCoat$str$, NULL, 1222),
($str$Surface Treatment$str$, $str$Passivation$str$, NULL, 'not_modeled', $str$Best Technology 188P$str$, NULL, 1223),
($str$Surface Treatment$str$, $str$Powder Coat Cart$str$, NULL, 'not_modeled', NULL, $str$Default$str$, 1224),
($str$Surface Treatment$str$, $str$Sand Blast$str$, NULL, 'not_modeled', $str$Default Sand Blast$str$, NULL, 1225),
($str$Surface Treatment$str$, $str$Screen Printing$str$, NULL, 'not_modeled', $str$Manual Screen Printing$str$, NULL, 1226),
($str$Surface Treatment$str$, $str$Shot Blast$str$, NULL, 'not_modeled', $str$Shot Blast - 1500mm x 2100mm$str$, $str$Default$str$, 1227),
($str$Surface Treatment$str$, $str$Shot Peen$str$, NULL, 'not_modeled', $str$Manual Shot Peen$str$, $str$shotPeenMedia$str$, 1228),
($str$Surface Treatment$str$, $str$Vibratory Finishing$str$, NULL, 'not_modeled', $str$Burr King M25 (2.8 Cu. Ft.)$str$, $str$Media$str$, 1229),
($str$Surface Treatment$str$, $str$Wet Coat Line$str$, NULL, 'not_modeled', $str$WetCoatLine01$str$, NULL, 1230),
($str$Surface Treatment$str$, $str$Zinc Nickel Plating$str$, NULL, 'not_modeled', $str$Default Zinc Nickel Plating$str$, NULL, 1231),
($str$Surface Treatment$str$, $str$Zinc Plating$str$, NULL, 'not_modeled', $str$Default Zinc Plating$str$, NULL, 1232),
($str$Forging$str$, $str$Band Saw$str$, NULL, 'not_modeled', $str$BLIN HDS-J150$str$, NULL, 1300),
($str$Forging$str$, $str$Conveyor Induction Heat$str$, NULL, 'not_modeled', $str$Conveyor Induction Heater - 1 Module$str$, NULL, 1301),
($str$Forging$str$, $str$Hammer$str$, NULL, 'not_modeled', $str$Chambersburg - 20,000 lb$str$, $str$Default$str$, 1302),
($str$Forging$str$, $str$Material Stock$str$, NULL, 'non_mfg', $str$Default Material Stock$str$, NULL, 1303),
($str$Forging$str$, $str$Mechanical Press$str$, NULL, 'not_modeled', $str$Schuler PK1250$str$, $str$Default$str$, 1304),
($str$Forging$str$, $str$No Cost Feature$str$, NULL, 'non_mfg', NULL, NULL, 1305),
($str$Forging$str$, $str$Open Die Press$str$, NULL, 'not_modeled', $str$ERIE Press Systems 3500 Ton Press$str$, NULL, 1306),
($str$Forging$str$, $str$Preheat$str$, NULL, 'not_modeled', $str$H.K. Furnace RT4-105-12$str$, NULL, 1307),
($str$Forging$str$, $str$Press$str$, NULL, 'not_modeled', $str$Lasco KFP 1000$str$, $str$Default$str$, 1308),
($str$Forging$str$, $str$Reheat$str$, NULL, 'not_modeled', $str$H.K. Furnace RT4-105-12$str$, NULL, 1309),
($str$Forging$str$, $str$Ring Rolling$str$, NULL, 'not_modeled', $str$D51-1000E$str$, NULL, 1310),
($str$Forging$str$, $str$Trim$str$, NULL, 'not_modeled', $str$Lasco KFP 1000$str$, $str$Default$str$, 1311),
($str$Other Secondary Processes$str$, $str$Carton Forming$str$, NULL, 'not_modeled', $str$COMBI 2-EZ$str$, NULL, 1400),
($str$Other Secondary Processes$str$, $str$Carton Sealing$str$, NULL, 'not_modeled', $str$3M 800r$str$, NULL, 1401),
($str$Other Secondary Processes$str$, $str$CMM Inspection$str$, NULL, 'not_modeled', $str$Axiom Too 1200$str$, NULL, 1402),
($str$Other Secondary Processes$str$, $str$CT Scan$str$, NULL, 'not_modeled', $str$Default$str$, NULL, 1403),
($str$Other Secondary Processes$str$, $str$Fluorescent Penetrant Testing$str$, NULL, 'not_modeled', $str$AIM 1836W$str$, NULL, 1404),
($str$Other Secondary Processes$str$, $str$Hydrostatic Leak Testing$str$, NULL, 'not_modeled', $str$Default$str$, NULL, 1405),
($str$Other Secondary Processes$str$, $str$Magnetic Particle Testing$str$, NULL, 'not_modeled', $str$WHM-4102$str$, NULL, 1406),
($str$Other Secondary Processes$str$, $str$Pack & Load$str$, NULL, 'not_modeled', $str$Accu-Seal HDMP3-332$str$, NULL, 1407),
($str$Other Secondary Processes$str$, $str$Ultrasonic A-Scan$str$, NULL, 'not_modeled', $str$Ultrasonic A-Scan - 12.19m x 3.66m x 1.21m$str$, NULL, 1408),
($str$Other Secondary Processes$str$, $str$Ultrasonic C-Scan$str$, NULL, 'not_modeled', $str$Ultrasonic C-Scan - 12.19m x 7.31m x 3.65m$str$, NULL, 1409),
($str$Other Secondary Processes$str$, $str$Ultrasonic Cleaning$str$, NULL, 'not_modeled', $str$Allendale-Ultrasonics 112 Litre$str$, NULL, 1410),
($str$Other Secondary Processes$str$, $str$Xray Inspection$str$, NULL, 'not_modeled', $str$Default$str$, NULL, 1411),
($str$Stock Machining$str$, $str$Band Saw$str$, NULL, 'not_modeled', $str$BLIN HDS-J150$str$, NULL, 1500),
($str$Stock Machining$str$, $str$Material Stock$str$, NULL, 'non_mfg', $str$Default Material Stock$str$, NULL, 1501)
ON CONFLICT (process_group, process_name) DO UPDATE
SET default_machine_name = COALESCE(process_taxonomy.default_machine_name, EXCLUDED.default_machine_name),
    default_tool_shop_name = COALESCE(process_taxonomy.default_tool_shop_name, EXCLUDED.default_tool_shop_name);

-- ── Step 3: process_taxonomy_operations ────────────────────────────────────
INSERT INTO process_taxonomy_operations (canonical_process_id, operation_category, feature_type, raw_compound_string)
SELECT pt.id, v.operation_category, v.feature_type, v.raw
FROM process_taxonomy pt
JOIN (VALUES
($str$Additive Manufacturing$str$, $str$Breakoff$str$, $str$Breakoff$str$, $str$SupportStructure$str$, $str$Breakoff:Breakoff//SupportStructure$str$),
($str$Additive Manufacturing$str$, $str$Laser Sintering$str$, $str$As Sintered$str$, $str$AxiGroove$str$, $str$Laser Sintering:As Sintered//AxiGroove$str$),
($str$Additive Manufacturing$str$, $str$Laser Sintering$str$, $str$As Sintered$str$, $str$BuildDirection$str$, $str$Laser Sintering:As Sintered//BuildDirection$str$),
($str$Additive Manufacturing$str$, $str$Laser Sintering$str$, $str$As Sintered$str$, $str$CurvedSurface$str$, $str$Laser Sintering:As Sintered//CurvedSurface$str$),
($str$Additive Manufacturing$str$, $str$Laser Sintering$str$, $str$As Sintered$str$, $str$CurvedWall$str$, $str$Laser Sintering:As Sintered//CurvedWall$str$),
($str$Additive Manufacturing$str$, $str$Laser Sintering$str$, $str$As Sintered$str$, $str$Keyway$str$, $str$Laser Sintering:As Sintered//Keyway$str$),
($str$Additive Manufacturing$str$, $str$Laser Sintering$str$, $str$As Sintered$str$, $str$MultiStepHole$str$, $str$Laser Sintering:As Sintered//MultiStepHole$str$),
($str$Additive Manufacturing$str$, $str$Laser Sintering$str$, $str$As Sintered$str$, $str$Perimeter$str$, $str$Laser Sintering:As Sintered//Perimeter$str$),
($str$Additive Manufacturing$str$, $str$Laser Sintering$str$, $str$As Sintered$str$, $str$PlanarFace$str$, $str$Laser Sintering:As Sintered//PlanarFace$str$),
($str$Additive Manufacturing$str$, $str$Laser Sintering$str$, $str$As Sintered$str$, $str$Ring$str$, $str$Laser Sintering:As Sintered//Ring$str$),
($str$Additive Manufacturing$str$, $str$Laser Sintering$str$, $str$As Sintered$str$, $str$RingedHole$str$, $str$Laser Sintering:As Sintered//RingedHole$str$),
($str$Additive Manufacturing$str$, $str$Laser Sintering$str$, $str$As Sintered$str$, $str$SimpleHole$str$, $str$Laser Sintering:As Sintered//SimpleHole$str$),
($str$Additive Manufacturing$str$, $str$Laser Sintering$str$, $str$As Sintered$str$, $str$Void$str$, $str$Laser Sintering:As Sintered//Void$str$),
($str$Additive Manufacturing$str$, $str$Manual Tool Base Removal$str$, $str$Base Removal Manual$str$, $str$SupportStructure$str$, $str$Manual Tool Base Removal:Base Removal Manual//SupportStructure$str$),
($str$Additive Manufacturing$str$, $str$Metal Sintering$str$, $str$As Sintered$str$, $str$AxiGroove$str$, $str$Metal Sintering:As Sintered//AxiGroove$str$),
($str$Additive Manufacturing$str$, $str$Metal Sintering$str$, $str$As Sintered$str$, $str$BuildDirection$str$, $str$Metal Sintering:As Sintered//BuildDirection$str$),
($str$Additive Manufacturing$str$, $str$Metal Sintering$str$, $str$As Sintered$str$, $str$CurvedSurface$str$, $str$Metal Sintering:As Sintered//CurvedSurface$str$),
($str$Additive Manufacturing$str$, $str$Metal Sintering$str$, $str$As Sintered$str$, $str$CurvedWall$str$, $str$Metal Sintering:As Sintered//CurvedWall$str$),
($str$Additive Manufacturing$str$, $str$Metal Sintering$str$, $str$As Sintered$str$, $str$Keyway$str$, $str$Metal Sintering:As Sintered//Keyway$str$),
($str$Additive Manufacturing$str$, $str$Metal Sintering$str$, $str$As Sintered$str$, $str$MultiStepHole$str$, $str$Metal Sintering:As Sintered//MultiStepHole$str$),
($str$Additive Manufacturing$str$, $str$Metal Sintering$str$, $str$As Sintered$str$, $str$Perimeter$str$, $str$Metal Sintering:As Sintered//Perimeter$str$),
($str$Additive Manufacturing$str$, $str$Metal Sintering$str$, $str$As Sintered$str$, $str$PlanarFace$str$, $str$Metal Sintering:As Sintered//PlanarFace$str$),
($str$Additive Manufacturing$str$, $str$Metal Sintering$str$, $str$As Sintered$str$, $str$Ring$str$, $str$Metal Sintering:As Sintered//Ring$str$),
($str$Additive Manufacturing$str$, $str$Metal Sintering$str$, $str$As Sintered$str$, $str$RingedHole$str$, $str$Metal Sintering:As Sintered//RingedHole$str$),
($str$Additive Manufacturing$str$, $str$Metal Sintering$str$, $str$As Sintered$str$, $str$SimpleHole$str$, $str$Metal Sintering:As Sintered//SimpleHole$str$),
($str$Additive Manufacturing$str$, $str$Metal Sintering$str$, $str$As Sintered$str$, $str$SupportStructure$str$, $str$Metal Sintering:As Sintered//SupportStructure$str$),
($str$Additive Manufacturing$str$, $str$Metal Sintering$str$, $str$As Sintered$str$, $str$Void$str$, $str$Metal Sintering:As Sintered//Void$str$),
($str$Additive Manufacturing$str$, $str$No Cost Feature$str$, $str$No Cost Feature$str$, $str$SupportStructure$str$, $str$No Cost Feature:No Cost Feature//SupportStructure$str$),
($str$Additive Manufacturing$str$, $str$Power Tool Base Removal$str$, $str$Base Removal Powered$str$, $str$SupportStructure$str$, $str$Power Tool Base Removal:Base Removal Powered//SupportStructure$str$),
($str$Additive Manufacturing$str$, $str$Printing$str$, $str$As Printed$str$, $str$AxiGroove$str$, $str$Printing:As Printed//AxiGroove$str$),
($str$Additive Manufacturing$str$, $str$Printing$str$, $str$As Printed$str$, $str$BuildDirection$str$, $str$Printing:As Printed//BuildDirection$str$),
($str$Additive Manufacturing$str$, $str$Printing$str$, $str$As Printed$str$, $str$CurvedSurface$str$, $str$Printing:As Printed//CurvedSurface$str$),
($str$Additive Manufacturing$str$, $str$Printing$str$, $str$As Printed$str$, $str$CurvedWall$str$, $str$Printing:As Printed//CurvedWall$str$),
($str$Additive Manufacturing$str$, $str$Printing$str$, $str$As Printed$str$, $str$Keyway$str$, $str$Printing:As Printed//Keyway$str$),
($str$Additive Manufacturing$str$, $str$Printing$str$, $str$As Printed$str$, $str$MultiStepHole$str$, $str$Printing:As Printed//MultiStepHole$str$),
($str$Additive Manufacturing$str$, $str$Printing$str$, $str$As Printed$str$, $str$Perimeter$str$, $str$Printing:As Printed//Perimeter$str$),
($str$Additive Manufacturing$str$, $str$Printing$str$, $str$As Printed$str$, $str$PlanarFace$str$, $str$Printing:As Printed//PlanarFace$str$),
($str$Additive Manufacturing$str$, $str$Printing$str$, $str$As Printed$str$, $str$Ring$str$, $str$Printing:As Printed//Ring$str$),
($str$Additive Manufacturing$str$, $str$Printing$str$, $str$As Printed$str$, $str$RingedHole$str$, $str$Printing:As Printed//RingedHole$str$),
($str$Additive Manufacturing$str$, $str$Printing$str$, $str$As Printed$str$, $str$SimpleHole$str$, $str$Printing:As Printed//SimpleHole$str$),
($str$Additive Manufacturing$str$, $str$Printing$str$, $str$As Printed$str$, $str$SupportStructure$str$, $str$Printing:As Printed//SupportStructure$str$),
($str$Additive Manufacturing$str$, $str$Printing$str$, $str$As Printed$str$, $str$Void$str$, $str$Printing:As Printed//Void$str$),
($str$Additive Manufacturing$str$, $str$Resin Curing$str$, $str$As Cured$str$, $str$AxiGroove$str$, $str$Resin Curing:As Cured//AxiGroove$str$),
($str$Additive Manufacturing$str$, $str$Resin Curing$str$, $str$As Cured$str$, $str$BuildDirection$str$, $str$Resin Curing:As Cured//BuildDirection$str$),
($str$Additive Manufacturing$str$, $str$Resin Curing$str$, $str$As Cured$str$, $str$CurvedSurface$str$, $str$Resin Curing:As Cured//CurvedSurface$str$),
($str$Additive Manufacturing$str$, $str$Resin Curing$str$, $str$As Cured$str$, $str$CurvedWall$str$, $str$Resin Curing:As Cured//CurvedWall$str$),
($str$Additive Manufacturing$str$, $str$Resin Curing$str$, $str$As Cured$str$, $str$Keyway$str$, $str$Resin Curing:As Cured//Keyway$str$),
($str$Additive Manufacturing$str$, $str$Resin Curing$str$, $str$As Cured$str$, $str$MultiStepHole$str$, $str$Resin Curing:As Cured//MultiStepHole$str$),
($str$Additive Manufacturing$str$, $str$Resin Curing$str$, $str$As Cured$str$, $str$Perimeter$str$, $str$Resin Curing:As Cured//Perimeter$str$),
($str$Additive Manufacturing$str$, $str$Resin Curing$str$, $str$As Cured$str$, $str$PlanarFace$str$, $str$Resin Curing:As Cured//PlanarFace$str$),
($str$Additive Manufacturing$str$, $str$Resin Curing$str$, $str$As Cured$str$, $str$Ring$str$, $str$Resin Curing:As Cured//Ring$str$),
($str$Additive Manufacturing$str$, $str$Resin Curing$str$, $str$As Cured$str$, $str$RingedHole$str$, $str$Resin Curing:As Cured//RingedHole$str$),
($str$Additive Manufacturing$str$, $str$Resin Curing$str$, $str$As Cured$str$, $str$SimpleHole$str$, $str$Resin Curing:As Cured//SimpleHole$str$),
($str$Additive Manufacturing$str$, $str$Resin Curing$str$, $str$As Cured$str$, $str$SupportStructure$str$, $str$Resin Curing:As Cured//SupportStructure$str$),
($str$Additive Manufacturing$str$, $str$Resin Curing$str$, $str$As Cured$str$, $str$Void$str$, $str$Resin Curing:As Cured//Void$str$),
($str$Assembly$str$, $str$Adhesive Bonding$str$, $str$Adhesive Bonding$str$, $str$ContactRegion$str$, $str$Adhesive Bonding:Adhesive Bonding//ContactRegion$str$),
($str$Assembly$str$, $str$Adhesive Bonding$str$, $str$Clamping$str$, $str$ContactRegion$str$, $str$Adhesive Bonding:Clamping//ContactRegion$str$),
($str$Assembly$str$, $str$Electron Beam Welding$str$, $str$Electron Beam Welding$str$, $str$Weld$str$, $str$Electron Beam Welding:Electron Beam Welding//Weld$str$),
($str$Assembly$str$, $str$Fay Sealing$str$, $str$Fay Sealing$str$, $str$ContactRegion$str$, $str$Fay Sealing:Fay Sealing//ContactRegion$str$),
($str$Assembly$str$, $str$Laser Welding$str$, $str$Laser Welding$str$, $str$Weld$str$, $str$Laser Welding:Laser Welding//Weld$str$),
($str$Assembly$str$, $str$Lock Bolt$str$, $str$Lock Bolt Install$str$, $str$AssemblyComponentGcd$str$, $str$Lock Bolt:Lock Bolt Install//AssemblyComponentGcd$str$),
($str$Assembly$str$, $str$Manual MIG Welding$str$, $str$Manual MIG Welding$str$, $str$Weld$str$, $str$Manual MIG Welding:Manual MIG Welding//Weld$str$),
($str$Assembly$str$, $str$Manual Spot Welding$str$, $str$Manual Spot Welding$str$, $str$Weld$str$, $str$Manual Spot Welding:Manual Spot Welding//Weld$str$),
($str$Assembly$str$, $str$Manual TIG Welding$str$, $str$Manual TIG Welding$str$, $str$Weld$str$, $str$Manual TIG Welding:Manual TIG Welding//Weld$str$),
($str$Assembly$str$, $str$Mechanical Assembly$str$, $str$Mechanical Assembly$str$, $str$Stage$str$, $str$Mechanical Assembly:Mechanical Assembly//Stage$str$),
($str$Assembly$str$, $str$Mechanical Assembly$str$, $str$Nut Insert$str$, $str$AssemblyComponentGcd$str$, $str$Mechanical Assembly:Nut Insert//AssemblyComponentGcd$str$),
($str$Assembly$str$, $str$Mechanical Assembly$str$, $str$Press Fit$str$, $str$AssemblyComponentGcd$str$, $str$Mechanical Assembly:Press Fit//AssemblyComponentGcd$str$),
($str$Assembly$str$, $str$Mechanical Assembly$str$, $str$Rivet$str$, $str$AssemblyComponentGcd$str$, $str$Mechanical Assembly:Rivet//AssemblyComponentGcd$str$),
($str$Assembly$str$, $str$Mechanical Assembly$str$, $str$Screw Tighten - Manual$str$, $str$AssemblyComponentGcd$str$, $str$Mechanical Assembly:Screw Tighten - Manual//AssemblyComponentGcd$str$),
($str$Assembly$str$, $str$Mechanical Assembly$str$, $str$Screw Tighten - Power$str$, $str$AssemblyComponentGcd$str$, $str$Mechanical Assembly:Screw Tighten - Power//AssemblyComponentGcd$str$),
($str$Assembly$str$, $str$Mechanical Assembly$str$, $str$Snap Fit$str$, $str$AssemblyComponentGcd$str$, $str$Mechanical Assembly:Snap Fit//AssemblyComponentGcd$str$),
($str$Assembly$str$, $str$Mechanical Assembly$str$, $str$Tab Bend$str$, $str$AssemblyComponentGcd$str$, $str$Mechanical Assembly:Tab Bend//AssemblyComponentGcd$str$),
($str$Assembly$str$, $str$Mechanical Assembly$str$, $str$User-Defined Operation$str$, $str$AssemblyComponentGcd$str$, $str$Mechanical Assembly:User-Defined Operation//AssemblyComponentGcd$str$),
($str$Assembly$str$, $str$No Cost Feature$str$, $str$No Cost Feature$str$, $str$Weld$str$, $str$No Cost Feature:No Cost Feature//Weld$str$),
($str$Assembly$str$, $str$Pick and Place$str$, $str$Clamping$str$, $str$ContactGroup$str$, $str$Pick and Place:Clamping//ContactGroup$str$),
($str$Assembly$str$, $str$Pick and Place$str$, $str$Load$str$, $str$AssemblyComponentGcd$str$, $str$Pick and Place:Load//AssemblyComponentGcd$str$),
($str$Assembly$str$, $str$Pick and Place$str$, $str$Pick and Place$str$, $str$Stage$str$, $str$Pick and Place:Pick and Place//Stage$str$),
($str$Assembly$str$, $str$Pick and Place$str$, $str$Clamp$str$, $str$AssemblyComponentGcd$str$, $str$Pick and Place:Pick and Place//Stage:Clamp//AssemblyComponentGcd$str$),
($str$Assembly$str$, $str$Robotic MIG Welding$str$, $str$Robotic MIG Welding$str$, $str$Weld$str$, $str$Robotic MIG Welding:Robotic MIG Welding//Weld$str$),
($str$Assembly$str$, $str$Robotic Spot Welding$str$, $str$Robotic Spot Welding$str$, $str$Weld$str$, $str$Robotic Spot Welding:Robotic Spot Welding//Weld$str$),
($str$Assembly$str$, $str$Robotic TIG Welding$str$, $str$Robotic TIG Welding$str$, $str$Weld$str$, $str$Robotic TIG Welding:Robotic TIG Welding//Weld$str$),
($str$Assembly$str$, $str$Threaded Insert$str$, $str$Threaded Insert$str$, $str$AssemblyComponentGcd$str$, $str$Threaded Insert:Threaded Insert//AssemblyComponentGcd$str$),
($str$Assembly$str$, $str$Threaded Insert$str$, $str$Threaded Insert$str$, $str$Stage$str$, $str$Threaded Insert:Threaded Insert//Stage$str$),
($str$Assembly$str$, $str$Ultrasonic Welding$str$, $str$Ultrasonic Welding$str$, $str$AssemblyComponentGcd$str$, $str$Ultrasonic Welding:Ultrasonic Welding//AssemblyComponentGcd$str$),
($str$Assembly$str$, $str$Ultrasonic Welding$str$, $str$Ultrasonic Welding$str$, $str$Stage$str$, $str$Ultrasonic Welding:Ultrasonic Welding//Stage$str$),
($str$Assembly$str$, $str$Weld Clean Up$str$, $str$Grinding$str$, $str$Weld$str$, $str$Weld Clean Up:Grinding//Weld$str$),
($str$Assembly$str$, $str$Weld Prep$str$, $str$Bevel Cutting$str$, $str$Weld$str$, $str$Weld Prep:Bevel Cutting//Weld$str$),
($str$Assembly$str$, $str$Weld Prep$str$, $str$Grinding$str$, $str$Weld$str$, $str$Weld Prep:Grinding//Weld$str$),
($str$Assembly$str$, $str$Weld Prep$str$, $str$Wire Brushing$str$, $str$Weld$str$, $str$Weld Prep:Wire Brushing//Weld$str$),
($str$Part Assembly$str$, $str$Bevel Cutting$str$, $str$Bevel Cutting$str$, $str$Blank$str$, $str$Bevel Cutting:Bevel Cutting//Blank$str$),
($str$Part Assembly$str$, $str$Bevel Cutting$str$, $str$Bevel Cutting$str$, $str$Edge$str$, $str$Bevel Cutting:Bevel Cutting//Edge$str$),
($str$Part Assembly$str$, $str$Bevel Cutting$str$, $str$Bevel Cutting$str$, $str$SimpleHole$str$, $str$Bevel Cutting:Bevel Cutting//SimpleHole$str$),
($str$Part Assembly$str$, $str$Finish Grinding$str$, $str$Finish Grinding$str$, $str$Blank$str$, $str$Finish Grinding:Finish Grinding//Blank$str$),
($str$Part Assembly$str$, $str$Finish Grinding$str$, $str$Finish Grinding$str$, $str$Edge$str$, $str$Finish Grinding:Finish Grinding//Edge$str$),
($str$Part Assembly$str$, $str$Finish Grinding$str$, $str$Finish Grinding$str$, $str$SimpleHole$str$, $str$Finish Grinding:Finish Grinding//SimpleHole$str$),
($str$Part Assembly$str$, $str$Grinding$str$, $str$Grinding$str$, $str$Blank$str$, $str$Grinding:Grinding//Blank$str$),
($str$Part Assembly$str$, $str$Grinding$str$, $str$Grinding$str$, $str$Edge$str$, $str$Grinding:Grinding//Edge$str$),
($str$Part Assembly$str$, $str$Grinding$str$, $str$Grinding$str$, $str$SimpleHole$str$, $str$Grinding:Grinding//SimpleHole$str$),
($str$Part Assembly$str$, $str$Laser Seam Welding$str$, $str$Laser Seam Welding$str$, $str$Blank$str$, $str$Laser Seam Welding:Laser Seam Welding//Blank$str$),
($str$Part Assembly$str$, $str$Laser Seam Welding$str$, $str$Laser Seam Welding$str$, $str$Edge$str$, $str$Laser Seam Welding:Laser Seam Welding//Edge$str$),
($str$Part Assembly$str$, $str$Manual MIG Welding$str$, $str$Bevel Groove Welding$str$, $str$Edge$str$, $str$Manual MIG Welding:Bevel Groove Welding//Edge$str$),
($str$Part Assembly$str$, $str$Manual MIG Welding$str$, $str$Fillet Welding$str$, $str$Edge$str$, $str$Manual MIG Welding:Fillet Welding//Edge$str$),
($str$Part Assembly$str$, $str$Manual MIG Welding$str$, $str$Flared Bevel Groove Welding$str$, $str$Edge$str$, $str$Manual MIG Welding:Flared Bevel Groove Welding//Edge$str$),
($str$Part Assembly$str$, $str$Manual MIG Welding$str$, $str$Flared V-Groove Welding$str$, $str$Edge$str$, $str$Manual MIG Welding:Flared V-Groove Welding//Edge$str$),
($str$Part Assembly$str$, $str$Manual MIG Welding$str$, $str$Groove Welding$str$, $str$Blank$str$, $str$Manual MIG Welding:Groove Welding//Blank$str$),
($str$Part Assembly$str$, $str$Manual MIG Welding$str$, $str$J-Groove Welding$str$, $str$Edge$str$, $str$Manual MIG Welding:J-Groove Welding//Edge$str$),
($str$Part Assembly$str$, $str$Manual MIG Welding$str$, $str$Other Welding$str$, $str$Blank$str$, $str$Manual MIG Welding:Other Welding//Blank$str$),
($str$Part Assembly$str$, $str$Manual MIG Welding$str$, $str$Plug Welding$str$, $str$SimpleHole$str$, $str$Manual MIG Welding:Plug Welding//SimpleHole$str$),
($str$Part Assembly$str$, $str$Manual MIG Welding$str$, $str$Square Groove Welding$str$, $str$Edge$str$, $str$Manual MIG Welding:Square Groove Welding//Edge$str$),
($str$Part Assembly$str$, $str$Manual MIG Welding$str$, $str$Tack Welding$str$, $str$Edge$str$, $str$Manual MIG Welding:Tack Welding//Edge$str$),
($str$Part Assembly$str$, $str$Manual MIG Welding$str$, $str$U-Groove Welding$str$, $str$Edge$str$, $str$Manual MIG Welding:U-Groove Welding//Edge$str$),
($str$Part Assembly$str$, $str$Manual MIG Welding$str$, $str$V-Groove Welding$str$, $str$Edge$str$, $str$Manual MIG Welding:V-Groove Welding//Edge$str$),
($str$Part Assembly$str$, $str$Manual MIG Welding$str$, $str$Wrap Tie Welding$str$, $str$Edge$str$, $str$Manual MIG Welding:Wrap Tie Welding//Edge$str$),
($str$Part Assembly$str$, $str$Manual Spot Welding$str$, $str$Spot Welding$str$, $str$Blank$str$, $str$Manual Spot Welding:Spot Welding//Blank$str$),
($str$Part Assembly$str$, $str$Manual Spot Welding$str$, $str$Spot Welding$str$, $str$Edge$str$, $str$Manual Spot Welding:Spot Welding//Edge$str$),
($str$Part Assembly$str$, $str$Robotic MIG Welding$str$, $str$Bevel Groove Welding$str$, $str$Edge$str$, $str$Robotic MIG Welding:Bevel Groove Welding//Edge$str$),
($str$Part Assembly$str$, $str$Robotic MIG Welding$str$, $str$Fillet Welding$str$, $str$Edge$str$, $str$Robotic MIG Welding:Fillet Welding//Edge$str$),
($str$Part Assembly$str$, $str$Robotic MIG Welding$str$, $str$Flared Bevel Groove Welding$str$, $str$Edge$str$, $str$Robotic MIG Welding:Flared Bevel Groove Welding//Edge$str$),
($str$Part Assembly$str$, $str$Robotic MIG Welding$str$, $str$Flared V-Groove Welding$str$, $str$Edge$str$, $str$Robotic MIG Welding:Flared V-Groove Welding//Edge$str$),
($str$Part Assembly$str$, $str$Robotic MIG Welding$str$, $str$Groove Welding$str$, $str$Blank$str$, $str$Robotic MIG Welding:Groove Welding//Blank$str$),
($str$Part Assembly$str$, $str$Robotic MIG Welding$str$, $str$J-Groove Welding$str$, $str$Edge$str$, $str$Robotic MIG Welding:J-Groove Welding//Edge$str$),
($str$Part Assembly$str$, $str$Robotic MIG Welding$str$, $str$Other Welding$str$, $str$Blank$str$, $str$Robotic MIG Welding:Other Welding//Blank$str$),
($str$Part Assembly$str$, $str$Robotic MIG Welding$str$, $str$Plug Welding$str$, $str$SimpleHole$str$, $str$Robotic MIG Welding:Plug Welding//SimpleHole$str$),
($str$Part Assembly$str$, $str$Robotic MIG Welding$str$, $str$Square Groove Welding$str$, $str$Edge$str$, $str$Robotic MIG Welding:Square Groove Welding//Edge$str$),
($str$Part Assembly$str$, $str$Robotic MIG Welding$str$, $str$Tack Welding$str$, $str$Edge$str$, $str$Robotic MIG Welding:Tack Welding//Edge$str$),
($str$Part Assembly$str$, $str$Robotic MIG Welding$str$, $str$U-Groove Welding$str$, $str$Edge$str$, $str$Robotic MIG Welding:U-Groove Welding//Edge$str$),
($str$Part Assembly$str$, $str$Robotic MIG Welding$str$, $str$V-Groove Welding$str$, $str$Edge$str$, $str$Robotic MIG Welding:V-Groove Welding//Edge$str$),
($str$Part Assembly$str$, $str$Robotic MIG Welding$str$, $str$Wrap Tie Welding$str$, $str$Edge$str$, $str$Robotic MIG Welding:Wrap Tie Welding//Edge$str$),
($str$Part Assembly$str$, $str$Robotic Spot Welding$str$, $str$Spot Welding$str$, $str$Blank$str$, $str$Robotic Spot Welding:Spot Welding//Blank$str$),
($str$Part Assembly$str$, $str$Robotic Spot Welding$str$, $str$Spot Welding$str$, $str$Edge$str$, $str$Robotic Spot Welding:Spot Welding//Edge$str$),
($str$Part Assembly$str$, $str$Wire Brushing$str$, $str$Wire Brushing$str$, $str$Blank$str$, $str$Wire Brushing:Wire Brushing//Blank$str$),
($str$Part Assembly$str$, $str$Wire Brushing$str$, $str$Wire Brushing$str$, $str$Edge$str$, $str$Wire Brushing:Wire Brushing//Edge$str$),
($str$Part Assembly$str$, $str$Wire Brushing$str$, $str$Wire Brushing$str$, $str$SimpleHole$str$, $str$Wire Brushing:Wire Brushing//SimpleHole$str$),
($str$Composites$str$, $str$Automated Fiber Placement$str$, $str$AFP Ply Placement$str$, NULL, $str$Automated Fiber Placement:AFP Ply Placement$str$),
($str$Composites$str$, $str$Automated Fiber Placement$str$, $str$Ply Placing$str$, $str$Ply$str$, $str$Automated Fiber Placement:AFP Ply Placement:Ply Placing//Ply$str$),
($str$Composites$str$, $str$Automated Fiber Placement$str$, $str$Attach Thermocouples$str$, NULL, $str$Automated Fiber Placement:Attach Thermocouples$str$),
($str$Composites$str$, $str$Automated Fiber Placement$str$, $str$Vacuum Drop Test$str$, NULL, $str$Automated Fiber Placement:Vacuum Drop Test$str$),
($str$Composites$str$, $str$Automated Tape Layup$str$, $str$ATL Ply Placement$str$, NULL, $str$Automated Tape Layup:ATL Ply Placement$str$),
($str$Composites$str$, $str$Automated Tape Layup$str$, $str$Ply Placing$str$, $str$Ply$str$, $str$Automated Tape Layup:ATL Ply Placement:Ply Placing//Ply$str$),
($str$Composites$str$, $str$Automated Tape Layup$str$, $str$Attach Thermocouples$str$, NULL, $str$Automated Tape Layup:Attach Thermocouples$str$),
($str$Composites$str$, $str$Automated Tape Layup$str$, $str$Vacuum Drop Test$str$, NULL, $str$Automated Tape Layup:Vacuum Drop Test$str$),
($str$Composites$str$, $str$Bench Operation$str$, $str$Inspecting$str$, NULL, $str$Bench Operation:Inspecting$str$),
($str$Composites$str$, $str$Bench Operation$str$, $str$Tool Breakdown$str$, NULL, $str$Bench Operation:Tool Breakdown$str$),
($str$Composites$str$, $str$Hand Layup$str$, $str$Attach Thermocouples$str$, NULL, $str$Hand Layup:Attach Thermocouples$str$),
($str$Composites$str$, $str$Hand Layup$str$, $str$Debulk$str$, NULL, $str$Hand Layup:Debulk$str$),
($str$Composites$str$, $str$Hand Layup$str$, $str$Hand Ply Placement$str$, NULL, $str$Hand Layup:Hand Ply Placement$str$),
($str$Composites$str$, $str$Hand Layup$str$, $str$Core Placing$str$, $str$Core$str$, $str$Hand Layup:Hand Ply Placement:Core Placing//Core$str$),
($str$Composites$str$, $str$Hand Layup$str$, $str$Core Potting$str$, $str$Core$str$, $str$Hand Layup:Hand Ply Placement:Core Potting//Core$str$),
($str$Composites$str$, $str$Hand Layup$str$, $str$Core Splicing$str$, $str$Core$str$, $str$Hand Layup:Hand Ply Placement:Core Splicing//Core$str$),
($str$Composites$str$, $str$Hand Layup$str$, $str$Ply Placing$str$, $str$Ply$str$, $str$Hand Layup:Hand Ply Placement:Ply Placing//Ply$str$),
($str$Composites$str$, $str$Hand Layup$str$, $str$Remove Vacuum Bag$str$, NULL, $str$Hand Layup:Remove Vacuum Bag$str$),
($str$Composites$str$, $str$Hand Layup$str$, $str$Vacuum Drop Test$str$, NULL, $str$Hand Layup:Vacuum Drop Test$str$),
($str$Composites$str$, $str$Mold Preparation$str$, $str$Applying Mold Release$str$, NULL, $str$Mold Preparation:Applying Mold Release$str$),
($str$Composites$str$, $str$Mold Preparation$str$, $str$Applying Tool Tack$str$, NULL, $str$Mold Preparation:Applying Tool Tack$str$),
($str$Composites$str$, $str$Mold Preparation$str$, $str$Curing Mold Release$str$, NULL, $str$Mold Preparation:Curing Mold Release$str$),
($str$Composites$str$, $str$Mold Preparation$str$, $str$Curing Tool Tack$str$, NULL, $str$Mold Preparation:Curing Tool Tack$str$),
($str$Composites$str$, $str$No Cost Feature$str$, $str$No Cost Feature$str$, $str$Core$str$, $str$No Cost Feature:No Cost Feature//Core$str$),
($str$Composites$str$, $str$No Cost Feature$str$, $str$No Cost Feature$str$, $str$Ply$str$, $str$No Cost Feature:No Cost Feature//Ply$str$),
($str$Composites$str$, $str$Tool Clean$str$, $str$Cryogenic Tool Cleaning$str$, NULL, $str$Tool Clean:Cryogenic Tool Cleaning$str$),
($str$Composites$str$, $str$Tool Clean$str$, $str$Laser Tool Cleaning$str$, NULL, $str$Tool Clean:Laser Tool Cleaning$str$),
($str$Composites$str$, $str$Tool Clean$str$, $str$Manual Tool Cleaning$str$, NULL, $str$Tool Clean:Manual Tool Cleaning$str$),
($str$Composites$str$, $str$Ultrasonic Cut$str$, $str$Ultrasonic Cutting$str$, $str$Ply$str$, $str$Ultrasonic Cut:Ultrasonic Cutting//Ply$str$),
($str$PCB$str$, $str$Apply Photo Resist$str$, $str$Photo Resist Applying$str$, $str$Layer$str$, $str$Apply Photo Resist:Photo Resist Applying//Layer$str$),
($str$PCB$str$, $str$Automated Optical Inspection$str$, $str$AOI$str$, $str$Layer$str$, $str$Automated Optical Inspection:AOI//Layer$str$),
($str$PCB$str$, $str$Bench Operation$str$, $str$Assemble And Press Layers$str$, NULL, $str$Bench Operation:Assemble And Press Layers$str$),
($str$PCB$str$, $str$Bench Operation$str$, $str$Layer Assembly-Pressing$str$, $str$Layer$str$, $str$Bench Operation:Layer Assembly-Pressing//Layer$str$),
($str$PCB$str$, $str$Copper Plate and Tin Coat$str$, $str$Copper Plating and Tin Coating$str$, $str$CommonHoleGroup$str$, $str$Copper Plate and Tin Coat:Copper Plating and Tin Coating//CommonHoleGroup$str$),
($str$PCB$str$, $str$Copper Plate and Tin Coat$str$, $str$Copper Plating and Tin Coating$str$, $str$Contour$str$, $str$Copper Plate and Tin Coat:Copper Plating and Tin Coating//Contour$str$),
($str$PCB$str$, $str$Cure Plugged Vias$str$, $str$Via Plugging Curing$str$, $str$CommonHoleGroup$str$, $str$Cure Plugged Vias:Via Plugging Curing//CommonHoleGroup$str$),
($str$PCB$str$, $str$DES$str$, $str$Develop Etch Strip$str$, $str$Layer$str$, $str$DES:Develop Etch Strip//Layer$str$),
($str$PCB$str$, $str$Desmear and Plate Through Holes$str$, $str$Desmearing and Electroless Through Hole Plating$str$, $str$CommonHoleGroup$str$, $str$Desmear and Plate Through Holes:Desmearing and Electroless Through Hole Plating//CommonHoleGroup$str$),
($str$PCB$str$, $str$Desmear and Plate Through Holes$str$, $str$Desmearing and Electroless Through Hole Plating$str$, $str$Contour$str$, $str$Desmear and Plate Through Holes:Desmearing and Electroless Through Hole Plating//Contour$str$),
($str$PCB$str$, $str$Dissolve Unexposed Photo Resist$str$, $str$Unexposed Photo Resist Dissolving$str$, $str$Layer$str$, $str$Dissolve Unexposed Photo Resist:Unexposed Photo Resist Dissolving//Layer$str$),
($str$PCB$str$, $str$Drill Circuit Holes$str$, $str$Circuit Hole Drilling$str$, $str$CommonHoleGroup$str$, $str$Drill Circuit Holes:Circuit Hole Drilling//CommonHoleGroup$str$),
($str$PCB$str$, $str$Drill Circuit Holes$str$, $str$Circuit Hole Drilling$str$, $str$Contour$str$, $str$Drill Circuit Holes:Circuit Hole Drilling//Contour$str$),
($str$PCB$str$, $str$Laser Drill Vias$str$, $str$Via Laser Drilling$str$, $str$CommonHoleGroup$str$, $str$Laser Drill Vias:Via Laser Drilling//CommonHoleGroup$str$),
($str$PCB$str$, $str$Material Stock$str$, $str$Layer Material$str$, $str$Layer$str$, $str$Material Stock:Layer Material//Layer$str$),
($str$PCB$str$, $str$No Cost Feature$str$, $str$No Cost Feature$str$, $str$CommonHoleGroup$str$, $str$No Cost Feature:No Cost Feature//CommonHoleGroup$str$),
($str$PCB$str$, $str$No Cost Feature$str$, $str$No Cost Feature$str$, $str$Contour$str$, $str$No Cost Feature:No Cost Feature//Contour$str$),
($str$PCB$str$, $str$Oven Cure Layers$str$, $str$Layer Curing$str$, $str$Layer$str$, $str$Oven Cure Layers:Layer Curing//Layer$str$),
($str$PCB$str$, $str$Photolithography$str$, $str$UV Exposure$str$, $str$Layer$str$, $str$Photolithography:UV Exposure//Layer$str$),
($str$PCB$str$, $str$Plug Vias$str$, $str$Via Plugging Screen Printing$str$, $str$CommonHoleGroup$str$, $str$Plug Vias:Via Plugging Screen Printing//CommonHoleGroup$str$),
($str$PCB$str$, $str$Router$str$, $str$Routering$str$, $str$CommonHoleGroup$str$, $str$Router:Routering//CommonHoleGroup$str$),
($str$PCB$str$, $str$Router$str$, $str$Routering$str$, $str$Contour$str$, $str$Router:Routering//Contour$str$),
($str$PCB$str$, $str$SES$str$, $str$Strip Etch Strip$str$, $str$Layer$str$, $str$SES:Strip Etch Strip//Layer$str$),
($str$PCB$str$, $str$Stamp$str$, $str$As Stamped$str$, $str$CommonHoleGroup$str$, $str$Stamp:As Stamped//CommonHoleGroup$str$),
($str$PCB$str$, $str$Stamp$str$, $str$As Stamped$str$, $str$Contour$str$, $str$Stamp:As Stamped//Contour$str$),
($str$PCB$str$, $str$Surface Preparation$str$, $str$Prep Surface$str$, $str$Layer$str$, $str$Surface Preparation:Prep Surface//Layer$str$),
($str$Surface Treatment$str$, $str$Anodize$str$, $str$Anodize Type I$str$, NULL, $str$Anodize:Anodize Type I$str$),
($str$Surface Treatment$str$, $str$Anodize$str$, $str$Anodize Type IB$str$, NULL, $str$Anodize:Anodize Type IB$str$),
($str$Surface Treatment$str$, $str$Anodize$str$, $str$Anodize Type IC$str$, NULL, $str$Anodize:Anodize Type IC$str$),
($str$Surface Treatment$str$, $str$Anodize$str$, $str$Anodize Type II$str$, NULL, $str$Anodize:Anodize Type II$str$),
($str$Surface Treatment$str$, $str$Anodize$str$, $str$Anodize Type III$str$, NULL, $str$Anodize:Anodize Type III$str$),
($str$Surface Treatment$str$, $str$Anodize$str$, $str$Clean$str$, NULL, $str$Anodize:Clean$str$),
($str$Surface Treatment$str$, $str$Anodize$str$, $str$Deoxidize$str$, NULL, $str$Anodize:Deoxidize$str$),
($str$Surface Treatment$str$, $str$Anodize$str$, $str$Dry$str$, NULL, $str$Anodize:Dry$str$),
($str$Surface Treatment$str$, $str$Anodize$str$, $str$Etch$str$, NULL, $str$Anodize:Etch$str$),
($str$Surface Treatment$str$, $str$Anodize$str$, $str$Rinse$str$, NULL, $str$Anodize:Rinse$str$),
($str$Surface Treatment$str$, $str$Anodize$str$, $str$Seal$str$, NULL, $str$Anodize:Seal$str$),
($str$Surface Treatment$str$, $str$Anodize$str$, $str$Spray Rinse$str$, NULL, $str$Anodize:Spray Rinse$str$),
($str$Surface Treatment$str$, $str$Manual Paint$str$, $str$Curing Finish Coat$str$, NULL, $str$Manual Paint:Curing Finish Coat$str$),
($str$Surface Treatment$str$, $str$Manual Paint$str$, $str$Curing Primer$str$, NULL, $str$Manual Paint:Curing Primer$str$),
($str$Surface Treatment$str$, $str$Manual Paint$str$, $str$Hand Cleaning$str$, NULL, $str$Manual Paint:Hand Cleaning$str$),
($str$Surface Treatment$str$, $str$Manual Paint$str$, $str$Hand Sanding$str$, NULL, $str$Manual Paint:Hand Sanding$str$),
($str$Surface Treatment$str$, $str$Manual Paint$str$, $str$Spraying Finish Coat$str$, NULL, $str$Manual Paint:Spraying Finish Coat$str$),
($str$Surface Treatment$str$, $str$Manual Paint$str$, $str$Spraying Primer$str$, NULL, $str$Manual Paint:Spraying Primer$str$),
($str$Surface Treatment$str$, $str$Mask-Bench$str$, $str$Mask-Bench$str$, $str$ComboVoid$str$, $str$Mask-Bench:Mask-Bench//ComboVoid$str$),
($str$Surface Treatment$str$, $str$Mask-Bench$str$, $str$Mask-Bench$str$, $str$End$str$, $str$Mask-Bench:Mask-Bench//End$str$),
($str$Surface Treatment$str$, $str$Mask-Bench$str$, $str$Mask-Bench$str$, $str$Flat$str$, $str$Mask-Bench:Mask-Bench//Flat$str$),
($str$Surface Treatment$str$, $str$Mask-Bench$str$, $str$Mask-Bench$str$, $str$Form$str$, $str$Mask-Bench:Mask-Bench//Form$str$),
($str$Surface Treatment$str$, $str$Mask-Bench$str$, $str$Mask-Bench$str$, $str$Keyway$str$, $str$Mask-Bench:Mask-Bench//Keyway$str$),
($str$Surface Treatment$str$, $str$Mask-Bench$str$, $str$Mask-Bench$str$, $str$MultiStepHole$str$, $str$Mask-Bench:Mask-Bench//MultiStepHole$str$),
($str$Surface Treatment$str$, $str$Mask-Bench$str$, $str$Mask-Bench$str$, $str$Ring$str$, $str$Mask-Bench:Mask-Bench//Ring$str$),
($str$Surface Treatment$str$, $str$Mask-Bench$str$, $str$Mask-Bench$str$, $str$RingedHole$str$, $str$Mask-Bench:Mask-Bench//RingedHole$str$),
($str$Surface Treatment$str$, $str$Mask-Bench$str$, $str$Mask-Bench$str$, $str$SlideBundle$str$, $str$Mask-Bench:Mask-Bench//SlideBundle$str$),
($str$Surface Treatment$str$, $str$Mask-Bench$str$, $str$Mask-Bench$str$, $str$StraightBend$str$, $str$Mask-Bench:Mask-Bench//StraightBend$str$),
($str$Surface Treatment$str$, $str$Mask-Bench$str$, $str$Masking-Bench$str$, $str$AxiGroove$str$, $str$Mask-Bench:Masking-Bench//AxiGroove$str$),
($str$Surface Treatment$str$, $str$Mask-Bench$str$, $str$Masking-Bench$str$, $str$ComplexHole$str$, $str$Mask-Bench:Masking-Bench//ComplexHole$str$),
($str$Surface Treatment$str$, $str$Mask-Bench$str$, $str$Masking-Bench$str$, $str$CurvedSurface$str$, $str$Mask-Bench:Masking-Bench//CurvedSurface$str$),
($str$Surface Treatment$str$, $str$Mask-Bench$str$, $str$Masking-Bench$str$, $str$CurvedWall$str$, $str$Mask-Bench:Masking-Bench//CurvedWall$str$),
($str$Surface Treatment$str$, $str$Mask-Bench$str$, $str$Masking-Bench$str$, $str$PlanarFace$str$, $str$Mask-Bench:Masking-Bench//PlanarFace$str$),
($str$Surface Treatment$str$, $str$Mask-Bench$str$, $str$Masking-Bench$str$, $str$SharpEdge$str$, $str$Mask-Bench:Masking-Bench//SharpEdge$str$),
($str$Surface Treatment$str$, $str$Mask-Bench$str$, $str$Masking-Bench$str$, $str$SimpleHole$str$, $str$Mask-Bench:Masking-Bench//SimpleHole$str$),
($str$Surface Treatment$str$, $str$Mask-Bench$str$, $str$Plugging$str$, $str$ComplexHole$str$, $str$Mask-Bench:Plugging//ComplexHole$str$),
($str$Surface Treatment$str$, $str$Mask-Bench$str$, $str$Plugging$str$, $str$SimpleHole$str$, $str$Mask-Bench:Plugging//SimpleHole$str$),
($str$Surface Treatment$str$, $str$Mask-Spray$str$, $str$Masking-Spray$str$, $str$Blank$str$, $str$Mask-Spray:Masking-Spray//Blank$str$),
($str$Surface Treatment$str$, $str$Vibratory Finishing$str$, $str$Tumble Deburr$str$, NULL, $str$Vibratory Finishing:Tumble Deburr$str$),
($str$Stock Machining$str$, $str$Band Saw$str$, $str$Band Saw$str$, $str$StockTrim$str$, $str$Band Saw:Band Saw//StockTrim$str$),
($str$Stock Machining$str$, $str$Material Stock$str$, $str$As Supplied$str$, $str$CurvedWall$str$, $str$Material Stock:As Supplied//CurvedWall$str$),
($str$Stock Machining$str$, $str$Material Stock$str$, $str$As Supplied$str$, $str$PlanarFace$str$, $str$Material Stock:As Supplied//PlanarFace$str$)
) AS v(grp, proc, operation_category, feature_type, raw)
  ON pt.process_group = v.grp AND pt.process_name = v.proc
ON CONFLICT (canonical_process_id, raw_compound_string) DO NOTHING;

-- ── Step 4: process_calculator_mappings (what the Process page lists) ──────
-- Inserted inactive so they satisfy chk_machine_class_required (see header).
-- The WHERE NOT EXISTS skips any operation that already has a mapping in its
-- group, so the re-homed CMM Inspection row (route Inspection) is not
-- duplicated under a second route.
INSERT INTO process_calculator_mappings (process_group, process_route, operation, calculator_id, calculator_name, is_active, display_order, machine_class, canonical_process_id)
SELECT v.grp, v.name, v.name, NULL, NULL, false, v.display_order, NULL, pt.id
FROM process_taxonomy pt
JOIN (VALUES
($str$Additive Manufacturing$str$, $str$Breakoff$str$, 700),
($str$Additive Manufacturing$str$, $str$Cleaning$str$, 701),
($str$Additive Manufacturing$str$, $str$Laser Sintering$str$, 702),
($str$Additive Manufacturing$str$, $str$Manual Tool Base Removal$str$, 703),
($str$Additive Manufacturing$str$, $str$Metal Sintering$str$, 704),
($str$Additive Manufacturing$str$, $str$No Cost Feature$str$, 705),
($str$Additive Manufacturing$str$, $str$Part Curing$str$, 706),
($str$Additive Manufacturing$str$, $str$Powder Loading$str$, 707),
($str$Additive Manufacturing$str$, $str$Power Tool Base Removal$str$, 708),
($str$Additive Manufacturing$str$, $str$Printing$str$, 709),
($str$Additive Manufacturing$str$, $str$Resin Curing$str$, 710),
($str$Additive Manufacturing$str$, $str$Sieving$str$, 711),
($str$Assembly$str$, $str$Adhesive Bonding$str$, 800),
($str$Assembly$str$, $str$Cap Sealing$str$, 801),
($str$Assembly$str$, $str$Electron Beam Welding$str$, 802),
($str$Assembly$str$, $str$Fay Sealing$str$, 803),
($str$Assembly$str$, $str$Fillet Sealing$str$, 804),
($str$Assembly$str$, $str$Laser Welding$str$, 805),
($str$Assembly$str$, $str$Lock Bolt$str$, 806),
($str$Assembly$str$, $str$Manual MIG Welding$str$, 807),
($str$Assembly$str$, $str$Manual Spot Welding$str$, 808),
($str$Assembly$str$, $str$Manual TIG Welding$str$, 809),
($str$Assembly$str$, $str$Mechanical Assembly$str$, 810),
($str$Assembly$str$, $str$No Cost Feature$str$, 811),
($str$Assembly$str$, $str$Pick and Place$str$, 812),
($str$Assembly$str$, $str$Rivet$str$, 813),
($str$Assembly$str$, $str$Robotic MIG Welding$str$, 814),
($str$Assembly$str$, $str$Robotic Spot Welding$str$, 815),
($str$Assembly$str$, $str$Robotic TIG Welding$str$, 816),
($str$Assembly$str$, $str$Threaded Insert$str$, 817),
($str$Assembly$str$, $str$Ultrasonic Welding$str$, 818),
($str$Assembly$str$, $str$Weld Clean Up$str$, 819),
($str$Assembly$str$, $str$Weld Prep$str$, 820),
($str$Part Assembly$str$, $str$Bevel Cutting$str$, 900),
($str$Part Assembly$str$, $str$Finish Grinding$str$, 901),
($str$Part Assembly$str$, $str$Grinding$str$, 902),
($str$Part Assembly$str$, $str$Laser Seam Welding$str$, 903),
($str$Part Assembly$str$, $str$Manual MIG Welding$str$, 904),
($str$Part Assembly$str$, $str$Manual Spot Welding$str$, 905),
($str$Part Assembly$str$, $str$Robotic MIG Welding$str$, 906),
($str$Part Assembly$str$, $str$Robotic Spot Welding$str$, 907),
($str$Part Assembly$str$, $str$Wire Brushing$str$, 908),
($str$Composites$str$, $str$Autoclave Cure$str$, 1000),
($str$Composites$str$, $str$Automated Fiber Placement$str$, 1001),
($str$Composites$str$, $str$Automated Tape Layup$str$, 1002),
($str$Composites$str$, $str$Bench Operation$str$, 1003),
($str$Composites$str$, $str$Final Vacuum Bag$str$, 1004),
($str$Composites$str$, $str$Hand Layup$str$, 1005),
($str$Composites$str$, $str$Mold Preparation$str$, 1006),
($str$Composites$str$, $str$No Cost Feature$str$, 1007),
($str$Composites$str$, $str$Tool Clean$str$, 1008),
($str$Composites$str$, $str$Ultrasonic Cut$str$, 1009),
($str$Composites$str$, $str$Vacuum Bag$str$, 1010),
($str$PCB$str$, $str$Apply Photo Resist$str$, 1100),
($str$PCB$str$, $str$Automated Optical Inspection$str$, 1101),
($str$PCB$str$, $str$Automated Vision Inspection$str$, 1102),
($str$PCB$str$, $str$Bed of Nails$str$, 1103),
($str$PCB$str$, $str$Bench Operation$str$, 1104),
($str$PCB$str$, $str$Copper Plate and Tin Coat$str$, 1105),
($str$PCB$str$, $str$Cure Plugged Vias$str$, 1106),
($str$PCB$str$, $str$Cure Solder Mask$str$, 1107),
($str$PCB$str$, $str$DES$str$, 1108),
($str$PCB$str$, $str$Desmear and Plate Through Holes$str$, 1109),
($str$PCB$str$, $str$Develop Solder Mask$str$, 1110),
($str$PCB$str$, $str$Dissolve Unexposed Photo Resist$str$, 1111),
($str$PCB$str$, $str$Drill Circuit Holes$str$, 1112),
($str$PCB$str$, $str$Drill Registration Holes$str$, 1113),
($str$PCB$str$, $str$Electroless Nickel Immersion Gold$str$, 1114),
($str$PCB$str$, $str$Film Imaging$str$, 1115),
($str$PCB$str$, $str$Flying Probe$str$, 1116),
($str$PCB$str$, $str$Hot Air Solder Leveling$str$, 1117),
($str$PCB$str$, $str$Laser Drill Vias$str$, 1118),
($str$PCB$str$, $str$Material Stock$str$, 1119),
($str$PCB$str$, $str$No Cost Feature$str$, 1120),
($str$PCB$str$, $str$Organic Solderability Preservative$str$, 1121),
($str$PCB$str$, $str$Oven Cure Layers$str$, 1122),
($str$PCB$str$, $str$Photolithography$str$, 1123),
($str$PCB$str$, $str$Plug Vias$str$, 1124),
($str$PCB$str$, $str$Router$str$, 1125),
($str$PCB$str$, $str$Screen Printing$str$, 1126),
($str$PCB$str$, $str$SES$str$, 1127),
($str$PCB$str$, $str$Silkscreen Cure$str$, 1128),
($str$PCB$str$, $str$Stamp$str$, 1129),
($str$PCB$str$, $str$Surface Preparation$str$, 1130),
($str$PCB$str$, $str$Tack Dry Solder Mask$str$, 1131),
($str$PCB$str$, $str$Wet Film Solder Mask$str$, 1132),
($str$Surface Treatment$str$, $str$Anodize$str$, 1200),
($str$Surface Treatment$str$, $str$Bead Blast$str$, 1201),
($str$Surface Treatment$str$, $str$Black Oxide$str$, 1202),
($str$Surface Treatment$str$, $str$Cadmium Plating$str$, 1203),
($str$Surface Treatment$str$, $str$Conveyor Abrasive Finishing$str$, 1204),
($str$Surface Treatment$str$, $str$Conveyor Conversion Coating$str$, 1205),
($str$Surface Treatment$str$, $str$Conveyor Dry$str$, 1206),
($str$Surface Treatment$str$, $str$Conveyor Oven Cure$str$, 1207),
($str$Surface Treatment$str$, $str$Conveyor Part Loading$str$, 1208),
($str$Surface Treatment$str$, $str$Conveyor Part Unloading$str$, 1209),
($str$Surface Treatment$str$, $str$Conveyor Powder Coating$str$, 1210),
($str$Surface Treatment$str$, $str$Conveyor Shot Blast$str$, 1211),
($str$Surface Treatment$str$, $str$Decorative Chrome Plating$str$, 1212),
($str$Surface Treatment$str$, $str$Degrease$str$, 1213),
($str$Surface Treatment$str$, $str$Dot Peen$str$, 1214),
($str$Surface Treatment$str$, $str$Hard Chrome Plating$str$, 1215),
($str$Surface Treatment$str$, $str$Laser Engraving$str$, 1216),
($str$Surface Treatment$str$, $str$Manual Paint$str$, 1217),
($str$Surface Treatment$str$, $str$Mask-Bench$str$, 1218),
($str$Surface Treatment$str$, $str$Mask-Spray$str$, 1219),
($str$Surface Treatment$str$, $str$Nickel Plating$str$, 1220),
($str$Surface Treatment$str$, $str$Oven Cure$str$, 1221),
($str$Surface Treatment$str$, $str$Painting$str$, 1222),
($str$Surface Treatment$str$, $str$Passivation$str$, 1223),
($str$Surface Treatment$str$, $str$Powder Coat Cart$str$, 1224),
($str$Surface Treatment$str$, $str$Sand Blast$str$, 1225),
($str$Surface Treatment$str$, $str$Screen Printing$str$, 1226),
($str$Surface Treatment$str$, $str$Shot Blast$str$, 1227),
($str$Surface Treatment$str$, $str$Shot Peen$str$, 1228),
($str$Surface Treatment$str$, $str$Vibratory Finishing$str$, 1229),
($str$Surface Treatment$str$, $str$Wet Coat Line$str$, 1230),
($str$Surface Treatment$str$, $str$Zinc Nickel Plating$str$, 1231),
($str$Surface Treatment$str$, $str$Zinc Plating$str$, 1232),
($str$Forging$str$, $str$Band Saw$str$, 1300),
($str$Forging$str$, $str$Conveyor Induction Heat$str$, 1301),
($str$Forging$str$, $str$Hammer$str$, 1302),
($str$Forging$str$, $str$Material Stock$str$, 1303),
($str$Forging$str$, $str$Mechanical Press$str$, 1304),
($str$Forging$str$, $str$No Cost Feature$str$, 1305),
($str$Forging$str$, $str$Open Die Press$str$, 1306),
($str$Forging$str$, $str$Preheat$str$, 1307),
($str$Forging$str$, $str$Press$str$, 1308),
($str$Forging$str$, $str$Reheat$str$, 1309),
($str$Forging$str$, $str$Ring Rolling$str$, 1310),
($str$Forging$str$, $str$Trim$str$, 1311),
($str$Other Secondary Processes$str$, $str$Carton Forming$str$, 1400),
($str$Other Secondary Processes$str$, $str$Carton Sealing$str$, 1401),
($str$Other Secondary Processes$str$, $str$CMM Inspection$str$, 1402),
($str$Other Secondary Processes$str$, $str$CT Scan$str$, 1403),
($str$Other Secondary Processes$str$, $str$Fluorescent Penetrant Testing$str$, 1404),
($str$Other Secondary Processes$str$, $str$Hydrostatic Leak Testing$str$, 1405),
($str$Other Secondary Processes$str$, $str$Magnetic Particle Testing$str$, 1406),
($str$Other Secondary Processes$str$, $str$Pack & Load$str$, 1407),
($str$Other Secondary Processes$str$, $str$Ultrasonic A-Scan$str$, 1408),
($str$Other Secondary Processes$str$, $str$Ultrasonic C-Scan$str$, 1409),
($str$Other Secondary Processes$str$, $str$Ultrasonic Cleaning$str$, 1410),
($str$Other Secondary Processes$str$, $str$Xray Inspection$str$, 1411),
($str$Stock Machining$str$, $str$Band Saw$str$, 1500),
($str$Stock Machining$str$, $str$Material Stock$str$, 1501)
) AS v(grp, name, display_order)
  ON pt.process_group = v.grp AND pt.process_name = v.name
WHERE NOT EXISTS (
  SELECT 1 FROM process_calculator_mappings m WHERE m.process_group = v.grp AND m.operation = v.name
)
ON CONFLICT (process_group, process_route, operation) DO NOTHING;

-- ── Step 5: guard, then retire the empty Post Processing group ─────────────
DO $guard$
DECLARE
  wired integer;
  referenced integer;
BEGIN
  SELECT count(*) INTO wired
  FROM process_calculator_mappings
  WHERE process_group = 'Post Processing' AND machine_class IS NOT NULL;

  SELECT count(*) INTO referenced
  FROM mhr_records mr
  JOIN process_taxonomy pt ON pt.id = mr.canonical_process_id
  WHERE pt.process_group = 'Post Processing';

  IF wired > 0 OR referenced > 0 THEN
    RAISE EXCEPTION 'Post Processing still has % wired mapping row(s) and % mhr_records reference(s) after the re-home; refusing to delete. Inspect and re-home them first.', wired, referenced;
  END IF;
END
$guard$;

DELETE FROM process_calculator_mappings WHERE process_group = 'Post Processing';
DELETE FROM process_taxonomy WHERE process_group = 'Post Processing';

COMMIT;

-- Verification (run manually after):
-- SELECT process_group, count(*) FROM process_calculator_mappings GROUP BY 1 ORDER BY 1;
-- SELECT count(*) FROM process_calculator_mappings WHERE process_group = $pp$Post Processing$pp$;  -- expect 0
-- SELECT process_group, operation, machine_class, lhr_process_group FROM process_calculator_mappings
--   WHERE operation IN ($pp$Surface Treatment$pp$, $pp$CMM Inspection$pp$);  -- machine_class must still be set
