-- ============================================================================
-- Migration 795: Seed mhr_records with the real Part Assembly (welding
-- group) machines (Phase 3 of the multi-group MHR/LHR seeding program)
-- ============================================================================
-- Generated by scripts/gen_795_seed_part_assembly_mhr_records.js -- do not
-- hand-edit, re-run the generator and diff instead.
--
-- Source: memory/Part Assembly/Machine/*.csv (9 real per-category files,
-- three real source shapes -- see this generator script own header).
--
--   Laser Seam Welding       1 machines
--   Bevel Cutting            1 machines
--   Finish Grinding          1 machines
--   Grinding                 1 machines
--   Wire Brushing            1 machines
--   Manual MIG Welding       5 machines
--   Manual Spot Welding      5 machines
--   Robotic MIG Welding      5 machines
--   Robotic Spot Welding     5 machines
--
-- 25 real machine rows total. All 9 real Part Assembly processes have
-- machine data -- no disclosed gap this phase.
--
-- Same 38-column shape/value-mapping discipline as migration 738/793/794.
-- process_family: 'weldment' for the 5 genuine welding processes, the same
-- disclosed 'assembly' value migration 794 introduced for the 4 mechanical-
-- prep processes (Bevel Cutting, Finish Grinding, Grinding, Wire Brushing).
-- wage_grade is the REAL per-process value from
-- memory/Part Assembly/wage_grade_associations_welding_group.csv, verified
-- directly. machine_class: no collision found against MACHINE_REGISTRY for
-- any of the 9 natural snake_case slugs -- no exception needed this phase.
--
-- REMINDER (see migration 794 own header): mhr_records has no unique
-- constraint on (machine_class, machine_name) -- do not run this migration
-- more than once.
-- ============================================================================

INSERT INTO mhr_records (
  machine_class, location, machine_name, currency_code, country_code, source_type, process_family, process_group, operators, setup_time_hr, press_cycle_time_s, landed_machine_cost, direct_overhead_rate, indirect_overhead_rate, benchmark_direct_overhead_rate_usd_hr, benchmark_indirect_overhead_rate_usd_hr, total_machine_hour_rate, mhr_usd_per_hour, usd_labor_rate_per_hr, benchmark_labor_rate_usd_hr, usd_lhr_total, work_center_labor_rate_factor, labor_time_standard, wage_grade, machine_price_usd, machine_length_mm, machine_width_mm, footprint_allowance_factor, machine_power_kw, machine_life_yr, installation_factor_pct, machine_uptime_pct, annual_maintenance_factor_pct, salvage_value_factor_pct, supplies_cost_per_year, avg_utilization, good_part_yield, manufacturer_country, benchmark_source_key
) VALUES
  ($str$laser_seam_welding$str$, $str$USA$str$, $str$Default$str$, $str$USD$str$, $str$US$str$, $str$BENCHMARK$str$, $str$weldment$str$, $str$Part Assembly$str$, 1, 0.5, NULL, 300000, 21.18, 25.76, 21.18, 25.76, 46.94, 46.94, 52.71, 52.71, 52.71, 1, 1, $str$6 - Metal$str$, 300000, 9140, 6100, 2.5, 20, 10, 20, 80, 5, 0, 0, NULL, 1, $str$USA$str$, $str$Laser Seam Welding:Default$str$),
  ($str$bevel_cutting$str$, $str$USA$str$, $str$default$str$, $str$USD$str$, $str$US$str$, $str$BENCHMARK$str$, $str$assembly$str$, $str$Part Assembly$str$, 1, 0, NULL, 1000, 0.36, 15.03, 0.36, 15.03, 15.39, 15.39, 29.85, 29.85, 29.85, 1, 1, $str$2 - Metal$str$, 1000, 3050, 3050, 1.5, 2, 10, 20, 80, 5, 0, 0, NULL, 1, $str$USA$str$, $str$Bevel Cutting:default$str$),
  ($str$finish_grinding$str$, $str$USA$str$, $str$default$str$, $str$USD$str$, $str$US$str$, $str$BENCHMARK$str$, $str$assembly$str$, $str$Part Assembly$str$, 1, 0, NULL, 1000, 0.36, 15.03, 0.36, 15.03, 15.39, 15.39, 29.85, 29.85, 29.85, 1, 1, $str$2 - Metal$str$, 1000, 3050, 3050, 1.5, 2, 10, 20, 80, 5, 0, 0, NULL, 1, $str$USA$str$, $str$Finish Grinding:default$str$),
  ($str$grinding$str$, $str$USA$str$, $str$default$str$, $str$USD$str$, $str$US$str$, $str$BENCHMARK$str$, $str$assembly$str$, $str$Part Assembly$str$, 1, 0, NULL, 1000, 0.36, 15.03, 0.36, 15.03, 15.39, 15.39, 29.85, 29.85, 29.85, 1, 1, $str$2 - Metal$str$, 1000, 3050, 3050, 1.5, 2, 10, 20, 80, 5, 0, 0, NULL, 1, $str$USA$str$, $str$Grinding:default$str$),
  ($str$wire_brushing$str$, $str$USA$str$, $str$default$str$, $str$USD$str$, $str$US$str$, $str$BENCHMARK$str$, $str$assembly$str$, $str$Part Assembly$str$, 1, 0, NULL, 1000, 0.36, 15.03, 0.36, 15.03, 15.39, 15.39, 29.95, 29.95, 29.95, 1, 1, $str$2 - Metal$str$, 1000, 3050, 3050, 1.5, 2, 10, 20, 80, 5, 0, 0, NULL, 1, $str$USA$str$, $str$Wire Brushing:default$str$),
  ($str$manual_mig_welding$str$, $str$USA$str$, $str$C240 (ESAB- 20A to 220A)$str$, $str$USD$str$, $str$US$str$, $str$BENCHMARK$str$, $str$weldment$str$, $str$Part Assembly$str$, 1, 1, NULL, 3400, 1.72, 15.2, 1.72, 15.2, 16.92, 16.92, 52.71, 52.71, 52.71, 1, 1, $str$6 - Metal$str$, 3400, 970, 660, 25, 10, 10, 20, 80, 5, 0, 0, NULL, 1, $str$USA$str$, $str$Manual MIG Welding:C240 (ESAB- 20A to 220A)$str$),
  ($str$manual_mig_welding$str$, $str$USA$str$, $str$C280 (ESAB- 30A to 280A)$str$, $str$USD$str$, $str$US$str$, $str$BENCHMARK$str$, $str$weldment$str$, $str$Part Assembly$str$, 1, 1, NULL, 3400, 1.72, 14.73, 1.72, 14.73, 16.45, 16.45, 52.71, 52.71, 52.71, 1, 1, $str$6 - Metal$str$, 3400, 910, 460, 25, 10, 10, 20, 80, 5, 0, 0, NULL, 1, $str$USA$str$, $str$Manual MIG Welding:C280 (ESAB- 30A to 280A)$str$),
  ($str$manual_mig_welding$str$, $str$USA$str$, $str$C420 (ESAB- 50A to 420A)$str$, $str$USD$str$, $str$US$str$, $str$BENCHMARK$str$, $str$weldment$str$, $str$Part Assembly$str$, 1, 1, NULL, 3444, 1.72, 14.86, 1.72, 14.86, 16.58, 16.58, 52.71, 52.71, 52.71, 1, 1, $str$6 - Metal$str$, 3444, 910, 530, 25, 10, 10, 20, 80, 5, 0, 0, NULL, 1, $str$USA$str$, $str$Manual MIG Welding:C420 (ESAB- 50A to 420A)$str$),
  ($str$manual_mig_welding$str$, $str$USA$str$, $str$Default Mig Weld$str$, $str$USD$str$, $str$US$str$, $str$BENCHMARK$str$, $str$weldment$str$, $str$Part Assembly$str$, 1, 1, NULL, 3400, 1.72, 14.86, 1.72, 14.86, 16.58, 16.58, 52.71, 52.71, 52.71, 1, 1, $str$6 - Metal$str$, 3400, 910, 530, 25, 10, 10, 20, 80, 5, 0, 0, NULL, 1, $str$USA$str$, $str$Manual MIG Welding:Default Mig Weld$str$),
  ($str$manual_mig_welding$str$, $str$USA$str$, $str$Deltaweld 653 (Miller)$str$, $str$USD$str$, $str$US$str$, $str$BENCHMARK$str$, $str$weldment$str$, $str$Part Assembly$str$, 1, 1, NULL, 3715, 1.74, 15.1, 1.74, 15.1, 16.84, 16.84, 52.71, 52.71, 52.71, 1, 1, $str$6 - Metal$str$, 3715, 970, 610, 25, 10, 10, 20, 80, 5, 0, 0, NULL, 1, $str$USA$str$, $str$Manual MIG Welding:Deltaweld 653 (Miller)$str$),
  ($str$manual_spot_welding$str$, $str$USA$str$, $str$Default Spot Weld$str$, $str$USD$str$, $str$US$str$, $str$BENCHMARK$str$, $str$weldment$str$, $str$Part Assembly$str$, 1, 1, NULL, 3700, 1.74, 15.1, 1.74, 15.1, 16.84, 16.84, 52.71, 52.71, 52.71, 1, 1, $str$6 - Metal$str$, 3700, 970, 610, 25, 10, 10, 20, 80, 5, 0, 0, NULL, 1, $str$USA$str$, $str$Manual Spot Welding:Default Spot Weld$str$),
  ($str$manual_spot_welding$str$, $str$USA$str$, $str$LMSW (Miller- 152mm tongs)$str$, $str$USD$str$, $str$US$str$, $str$BENCHMARK$str$, $str$weldment$str$, $str$Part Assembly$str$, 1, 1, NULL, 696, 1.55, 15.02, 1.55, 15.02, 16.57, 16.57, 52.71, 52.71, 52.71, 1, 1, $str$6 - Metal$str$, 696, 910, 610, 25, 10, 10, 20, 80, 5, 0, 0, NULL, 1, $str$USA$str$, $str$Manual Spot Welding:LMSW (Miller- 152mm tongs)$str$),
  ($str$manual_spot_welding$str$, $str$USA$str$, $str$MSW (Miller- 152 mm tongs)$str$, $str$USD$str$, $str$US$str$, $str$BENCHMARK$str$, $str$weldment$str$, $str$Part Assembly$str$, 1, 1, NULL, 605, 1.55, 15.02, 1.55, 15.02, 16.57, 16.57, 52.71, 52.71, 52.71, 1, 1, $str$6 - Metal$str$, 605, 910, 610, 25, 10, 10, 20, 80, 5, 0, 0, NULL, 1, $str$USA$str$, $str$Manual Spot Welding:MSW (Miller- 152 mm tongs)$str$),
  ($str$manual_spot_welding$str$, $str$USA$str$, $str$SSW (Miller- 152 mm tongs)$str$, $str$USD$str$, $str$US$str$, $str$BENCHMARK$str$, $str$weldment$str$, $str$Part Assembly$str$, 1, 1, NULL, 5340, 5.46, 15.02, 5.46, 15.02, 20.48, 20.48, 52.71, 52.71, 52.71, 1, 1, $str$6 - Metal$str$, 5340, 910, 610, 25, 34, 10, 20, 80, 5, 0, 0, NULL, 1, $str$USA$str$, $str$Manual Spot Welding:SSW (Miller- 152 mm tongs)$str$),
  ($str$manual_spot_welding$str$, $str$USA$str$, $str$SSW (Miller- 305 mm tongs)$str$, $str$USD$str$, $str$US$str$, $str$BENCHMARK$str$, $str$weldment$str$, $str$Part Assembly$str$, 1, 1, NULL, 5340, 1.83, 15.02, 1.83, 15.02, 16.85, 16.85, 52.71, 52.71, 52.71, 1, 1, $str$6 - Metal$str$, 5340, 910, 610, 25, 10, 10, 20, 80, 5, 0, 0, NULL, 1, $str$USA$str$, $str$Manual Spot Welding:SSW (Miller- 305 mm tongs)$str$),
  ($str$robotic_mig_welding$str$, $str$USA$str$, $str$Default Robotic Mig$str$, $str$USD$str$, $str$US$str$, $str$BENCHMARK$str$, $str$weldment$str$, $str$Part Assembly$str$, 1, 1, NULL, 100000, 7.56, 17.81, 7.56, 17.81, 25.37, 25.37, 47.36, 47.36, 47.36, 1, 1, $str$5 - Metal$str$, 100000, 6100, 3050, 2.5, 10, 10, 20, 80, 5, 0, 0, NULL, 1, $str$USA$str$, $str$Robotic MIG Welding:Default Robotic Mig$str$),
  ($str$robotic_mig_welding$str$, $str$USA$str$, $str$Pro System 2000 (Pro-Robots)$str$, $str$USD$str$, $str$US$str$, $str$BENCHMARK$str$, $str$weldment$str$, $str$Part Assembly$str$, 1, 1, NULL, 100000, 7.56, 17.81, 7.56, 17.81, 25.37, 25.37, 47.36, 47.36, 47.36, 1, 1, $str$5 - Metal$str$, 100000, 6100, 3050, 2.5, 10, 10, 20, 80, 5, 0, 0, NULL, 1, $str$USA$str$, $str$Robotic MIG Welding:Pro System 2000 (Pro-Robots)$str$),
  ($str$robotic_mig_welding$str$, $str$USA$str$, $str$Pro System 3000 (Pro-Robots)$str$, $str$USD$str$, $str$US$str$, $str$BENCHMARK$str$, $str$weldment$str$, $str$Part Assembly$str$, 1, 1, NULL, 100000, 7.56, 17.81, 7.56, 17.81, 25.37, 25.37, 47.36, 47.36, 47.36, 1, 1, $str$5 - Metal$str$, 100000, 6100, 3050, 2.5, 10, 10, 20, 80, 5, 0, 0, NULL, 1, $str$USA$str$, $str$Robotic MIG Welding:Pro System 3000 (Pro-Robots)$str$),
  ($str$robotic_mig_welding$str$, $str$USA$str$, $str$Pro Systen 1200$str$, $str$USD$str$, $str$US$str$, $str$BENCHMARK$str$, $str$weldment$str$, $str$Part Assembly$str$, 1, 1, NULL, 100000, 7.56, 17.81, 7.56, 17.81, 25.37, 25.37, 47.36, 47.36, 47.36, 1, 1, $str$5 - Metal$str$, 100000, 6100, 3050, 2.5, 10, 10, 20, 80, 5, 0, 0, NULL, 1, $str$USA$str$, $str$Robotic MIG Welding:Pro Systen 1200$str$),
  ($str$robotic_mig_welding$str$, $str$USA$str$, $str$Twin Station (ICS Robotics)$str$, $str$USD$str$, $str$US$str$, $str$BENCHMARK$str$, $str$weldment$str$, $str$Part Assembly$str$, 1, 1, NULL, 100000, 7.56, 17.81, 7.56, 17.81, 25.37, 25.37, 47.36, 47.36, 47.36, 1, 1, $str$5 - Metal$str$, 100000, 6100, 3050, 2.5, 10, 10, 20, 80, 5, 0, 0, NULL, 1, NULL, $str$Robotic MIG Welding:Twin Station (ICS Robotics)$str$),
  ($str$robotic_spot_welding$str$, $str$USA$str$, $str$Default Robotic Spot$str$, $str$USD$str$, $str$US$str$, $str$BENCHMARK$str$, $str$weldment$str$, $str$Part Assembly$str$, 0.1, 1, NULL, 100000, 7.56, 17.81, 7.56, 17.81, 25.37, 25.37, 47.36, 47.36, 47.36, 1, 1, $str$5 - Metal$str$, 100000, 6100, 3050, 2.5, 10, 10, 20, 80, 5, 0, 0, NULL, 1, $str$USA$str$, $str$Robotic Spot Welding:Default Robotic Spot$str$),
  ($str$robotic_spot_welding$str$, $str$USA$str$, $str$PerformArc 100 (Pansonic- 60'' Turntable)$str$, $str$USD$str$, $str$US$str$, $str$BENCHMARK$str$, $str$weldment$str$, $str$Part Assembly$str$, 0.1, 1, NULL, 100000, 7.56, 17.81, 7.56, 17.81, 25.37, 25.37, 47.36, 47.36, 47.36, 1, 1, $str$5 - Metal$str$, 100000, 6096, 3048, 2.5, 10, 10, 20, 80, 5, 0, 0, NULL, 1, $str$USA$str$, $str$Robotic Spot Welding:PerformArc 100 (Pansonic- 60'' Turntable)$str$),
  ($str$robotic_spot_welding$str$, $str$USA$str$, $str$PerformArc 125 (Panasonic- 60'' Turntable)$str$, $str$USD$str$, $str$US$str$, $str$BENCHMARK$str$, $str$weldment$str$, $str$Part Assembly$str$, 0.1, 1, NULL, 100000, 7.56, 17.81, 7.56, 17.81, 25.37, 25.37, 47.36, 47.36, 47.36, 1, 1, $str$5 - Metal$str$, 100000, 6096, 3048, 2.5, 10, 10, 20, 80, 5, 0, 0, NULL, 1, $str$USA$str$, $str$Robotic Spot Welding:PerformArc 125 (Panasonic- 60'' Turntable)$str$),
  ($str$robotic_spot_welding$str$, $str$USA$str$, $str$PerformArc 150 (Panasonic- Servo Turntable)$str$, $str$USD$str$, $str$US$str$, $str$BENCHMARK$str$, $str$weldment$str$, $str$Part Assembly$str$, 0.1, 1, NULL, 100000, 7.56, 17.81, 7.56, 17.81, 25.37, 25.37, 47.36, 47.36, 47.36, 1, 1, $str$5 - Metal$str$, 100000, 6100, 3050, 2.5, 10, 10, 20, 80, 5, 0, 0, NULL, 1, $str$USA$str$, $str$Robotic Spot Welding:PerformArc 150 (Panasonic- Servo Turntable)$str$),
  ($str$robotic_spot_welding$str$, $str$USA$str$, $str$PerformArc 52 (Panasonic)$str$, $str$USD$str$, $str$US$str$, $str$BENCHMARK$str$, $str$weldment$str$, $str$Part Assembly$str$, 0.1, 1, NULL, 100000, 7.56, 17.81, 7.56, 17.81, 25.37, 25.37, 47.36, 47.36, 47.36, 1, 1, $str$5 - Metal$str$, 100000, 6100, 3050, 2.5, 10, 10, 20, 80, 5, 0, 0, NULL, 1, $str$USA$str$, $str$Robotic Spot Welding:PerformArc 52 (Panasonic)$str$)
;

NOTIFY pgrst, 'reload schema';
