-- 804: Machining calculators -- every machining cycle-time formula as a real
-- database calculator, wired per operation, replacing the hand-typed templates.
--
-- GENERATED by scripts/generate-machining-calculators-migration.ts from
-- src/modules/bom-items/costing/machining/calculators/machining-calculators.json.
-- Do not edit by hand: change the spec and regenerate.
--
-- ROOT CAUSE
--
-- Machining cycle times were computed by formulas held in TypeScript, while the
-- database carried a second, unrelated set of hand-typed "Machining - ..."
-- calculators (fixed +10 mm approach, CEIL, OLE 80 percent, setup 30 percent,
-- 91.6/hr defaults, no lookup links) that no catalog row pointed at. Every
-- Machining row in process_calculator_mappings had calculator_id NULL, so the
-- Edit Process Cost dialog offered other domains calculators, and the dialog and
-- the quote could not agree.
--
-- This migration:
--   1. retires the unused hand-typed machining templates (renamed with
--      " (retired template)" and stamped retired_at; nothing references them);
--   2. creates one global calculator per machining operation whose inputs are
--      CAD measurements and real machining_reference_data lookup values
--      (data_source machining_lookup, source_table/source_field naming the
--      table and column) and whose calculated fields are the formulas the cost
--      engine evaluates -- the engine holds none of its own;
--   3. maps each operation to its calculator for every machine class that
--      performs it (process_calculator_mappings), after the station rows so
--      the station stays each class first catalog row.
--
-- Requires migration 802 (station rows on the engine machine classes).
-- Self-contained, idempotent, post-checked.

BEGIN;

DO $pre$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.process_calculator_mappings
    WHERE process_group = 'Machining' AND operation = '3 Axis Mill' AND machine_class = '3_axis_mill'
  ) THEN
    RAISE EXCEPTION 'migration 804 needs migration 802 applied first (Machining stations still on retired cnc_* classes)';
  END IF;
END
$pre$;

ALTER TABLE public.calculator_fields DROP CONSTRAINT IF EXISTS valid_data_source;
ALTER TABLE public.calculator_fields ADD CONSTRAINT valid_data_source CHECK (
  data_source IS NULL OR data_source IN ('lhr', 'mhr', 'raw_materials', 'processes', 'manual', 'sheet_metal_lookup', 'machining_lookup')
);

ALTER TABLE public.calculators ADD COLUMN IF NOT EXISTS retired_at TIMESTAMPTZ;
ALTER TABLE public.calculators ADD COLUMN IF NOT EXISTS retired_reason TEXT;
COMMENT ON COLUMN public.calculators.retired_at IS
  'Set when a calculator is withdrawn; retired calculators are hidden from calculator pickers but kept so any saved reference still opens.';

UPDATE public.calculators
SET retired_at = now(),
    retired_reason = $q$Hand-typed template with fixed constants and no lookup-table inputs; superseded by the generated machining calculators (migration 804).$q$,
    name = name || ' (retired template)'
WHERE user_id IS NOT NULL
  AND retired_at IS NULL
  AND name IN ($q$CNC Drilling Calculator$q$, $q$Machining - Boring$q$, $q$Machining - Cost Drivers$q$, $q$Machining - Cutoff$q$, $q$Machining - Drilling$q$, $q$Machining - End Milling and Sawing$q$, $q$Machining - Face Milling$q$, $q$Machining - Facing$q$, $q$Machining - Inspection$q$, $q$Machining - Internal Boring$q$, $q$Machining - Knurling$q$, $q$Machining - Laser Cutting$q$, $q$Machining - Manufacturing$q$, $q$Machining - Plasma Cutting$q$, $q$Machining - Plunge Milling$q$, $q$Machining - Reaming$q$, $q$Machining - Slot Milling$q$, $q$Machining - Step Drilling$q$, $q$Machining - Threading$q$, $q$Machining - Turning$q$, $q$Thread Milling Calculator$q$, $q$Thread Tapping Calculator$q$, $q$Turning Cycle time Calculation$q$);

-- Machining - Drilling
DO $calc$
DECLARE v_id UUID;
BEGIN
  SELECT id INTO v_id FROM public.calculators WHERE name = $q$Machining - Drilling$q$ AND user_id IS NULL AND retired_at IS NULL;
  IF v_id IS NULL THEN
    INSERT INTO public.calculators (user_id, name, calc_category, calculator_type, is_template, is_public, is_global, description)
    VALUES (NULL, $q$Machining - Drilling$q$, 'process', 'single', false, true, true, $q$Drilled-hole cycle time: CAD hole diameter and depth, cutting speed and feed from tblDrilling for the material and drill construction.$q$)
    RETURNING id INTO v_id;
  ELSE
    UPDATE public.calculators SET description = $q$Drilled-hole cycle time: CAD hole diameter and depth, cutting speed and feed from tblDrilling for the material and drill construction.$q$, updated_at = now() WHERE id = v_id;
  END IF;

  DELETE FROM public.calculator_fields WHERE calculator_id = v_id;
  INSERT INTO public.calculator_fields
    (calculator_id, field_name, display_label, field_type, unit, data_source, source_table, source_field, default_value, display_order, is_required)
  VALUES
    (v_id, $q$Hole Diameter$q$, $q$Hole Diameter (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 1, true),
    (v_id, $q$Hole Depth$q$, $q$Hole Depth (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 2, true),
    (v_id, $q$Holes$q$, $q$Holes$q$, $q$number$q$, NULL, NULL, NULL, NULL, NULL, 3, true),
    (v_id, $q$Cutting Speed$q$, $q$Cutting Speed (m/min)$q$, $q$number$q$, $q$m/min$q$, $q$machining_lookup$q$, $q$tblDrilling$q$, $q$cutting_speed_m_min$q$, NULL, 4, true),
    (v_id, $q$Feed$q$, $q$Feed (mm/rev)$q$, $q$number$q$, $q$mm/rev$q$, $q$machining_lookup$q$, $q$tblDrilling$q$, $q$feed_mm_rev$q$, NULL, 5, true),
    (v_id, $q$Spindle Speed$q$, $q$Spindle Speed (rpm)$q$, $q$calculated$q$, $q$rpm$q$, NULL, NULL, NULL, $q${Cutting Speed} * 1000 / (pi * {Hole Diameter})$q$, 6, false),
    (v_id, $q$Feed Rate$q$, $q$Feed Rate (mm/min)$q$, $q$calculated$q$, $q$mm/min$q$, NULL, NULL, NULL, $q${Spindle Speed} * {Feed}$q$, 7, false),
    (v_id, $q$Time per Hole$q$, $q$Time per Hole (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Hole Depth} / {Feed Rate} * 60$q$, 8, false),
    (v_id, $q$Cycle Time$q$, $q$Cycle Time (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Time per Hole} * {Holes}$q$, 9, false);

  INSERT INTO public.process_calculator_mappings
    (process_group, process_route, operation, calculator_id, calculator_name, is_active, display_order, machine_class, canonical_process_id)
  SELECT 'Machining', s.station, $q$Drilling$q$, v_id, $q$Machining - Drilling$q$, true, 700, s.cls,
         (SELECT pt.id FROM public.process_taxonomy pt WHERE pt.process_group = 'Machining' AND pt.process_name = s.station LIMIT 1)
  FROM (VALUES ($q$2_axis_lathe$q$, $q$2 Axis Lathe$q$), ($q$3_axis_lathe$q$, $q$3 Axis Lathe$q$), ($q$2_axis_bar_feed_lathe_with_sub_spindle$q$, $q$2 Axis Bar Feed Lathe with Sub Spindle$q$), ($q$3_axis_bar_feed_lathe_with_sub_spindle$q$, $q$3 Axis Bar Feed Lathe with Sub Spindle$q$), ($q$simultaneous_turning$q$, $q$Simultaneous Turning$q$), ($q$machining_millturn$q$, $q$MillTurn$q$), ($q$3_axis_mill$q$, $q$3 Axis Mill$q$), ($q$4_axis_mill$q$, $q$4 Axis Mill$q$), ($q$5_axis_mill$q$, $q$5 Axis Mill$q$)) AS s(cls, station)
  ON CONFLICT (process_group, process_route, operation) DO UPDATE
  SET calculator_id = EXCLUDED.calculator_id,
      calculator_name = EXCLUDED.calculator_name,
      machine_class = EXCLUDED.machine_class,
      is_active = true,
      canonical_process_id = EXCLUDED.canonical_process_id;
END
$calc$;

-- Machining - Rough Turning
DO $calc$
DECLARE v_id UUID;
BEGIN
  SELECT id INTO v_id FROM public.calculators WHERE name = $q$Machining - Rough Turning$q$ AND user_id IS NULL AND retired_at IS NULL;
  IF v_id IS NULL THEN
    INSERT INTO public.calculators (user_id, name, calc_category, calculator_type, is_template, is_public, is_global, description)
    VALUES (NULL, $q$Machining - Rough Turning$q$, 'process', 'single', false, true, true, $q$Rough turning passes over the turned length: CAD turned diameter/length, stock bar diameter, depth of cut / speed / feed from tblGeneralTurning.$q$)
    RETURNING id INTO v_id;
  ELSE
    UPDATE public.calculators SET description = $q$Rough turning passes over the turned length: CAD turned diameter/length, stock bar diameter, depth of cut / speed / feed from tblGeneralTurning.$q$, updated_at = now() WHERE id = v_id;
  END IF;

  DELETE FROM public.calculator_fields WHERE calculator_id = v_id;
  INSERT INTO public.calculator_fields
    (calculator_id, field_name, display_label, field_type, unit, data_source, source_table, source_field, default_value, display_order, is_required)
  VALUES
    (v_id, $q$Turned Diameter$q$, $q$Turned Diameter (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 1, true),
    (v_id, $q$Turned Length$q$, $q$Turned Length (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 2, true),
    (v_id, $q$Bar Diameter$q$, $q$Bar Diameter (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 3, true),
    (v_id, $q$Finish Depth of Cut$q$, $q$Finish Depth of Cut (mm)$q$, $q$number$q$, $q$mm$q$, $q$machining_lookup$q$, $q$tblGeneralTurning$q$, $q$cut_depth_mm$q$, NULL, 4, true),
    (v_id, $q$Rough Depth of Cut$q$, $q$Rough Depth of Cut (mm)$q$, $q$number$q$, $q$mm$q$, $q$machining_lookup$q$, $q$tblGeneralTurning$q$, $q$cut_depth_mm$q$, NULL, 5, true),
    (v_id, $q$Rough Cutting Speed$q$, $q$Rough Cutting Speed (m/min)$q$, $q$number$q$, $q$m/min$q$, $q$machining_lookup$q$, $q$tblGeneralTurning$q$, $q$cutting_speed_m_min$q$, NULL, 6, true),
    (v_id, $q$Rough Feed$q$, $q$Rough Feed (mm/rev)$q$, $q$number$q$, $q$mm/rev$q$, $q$machining_lookup$q$, $q$tblGeneralTurning$q$, $q$feed_rate_mm_rev$q$, NULL, 7, true),
    (v_id, $q$Radial Stock$q$, $q$Radial Stock (mm)$q$, $q$calculated$q$, $q$mm$q$, NULL, NULL, NULL, $q$({Bar Diameter} - {Turned Diameter}) / 2$q$, 8, false),
    (v_id, $q$Rough Stock$q$, $q$Rough Stock (mm)$q$, $q$calculated$q$, $q$mm$q$, NULL, NULL, NULL, $q$max({Radial Stock} - min({Finish Depth of Cut}, {Radial Stock}), 0)$q$, 9, false),
    (v_id, $q$Rough Passes$q$, $q$Rough Passes$q$, $q$calculated$q$, NULL, NULL, NULL, NULL, $q$round({Rough Stock} / {Rough Depth of Cut})$q$, 10, false),
    (v_id, $q$Spindle Speed$q$, $q$Spindle Speed (rpm)$q$, $q$calculated$q$, $q$rpm$q$, NULL, NULL, NULL, $q${Rough Cutting Speed} * 1000 / (pi * {Turned Diameter})$q$, 11, false),
    (v_id, $q$Feed Rate$q$, $q$Feed Rate (mm/min)$q$, $q$calculated$q$, $q$mm/min$q$, NULL, NULL, NULL, $q${Spindle Speed} * {Rough Feed}$q$, 12, false),
    (v_id, $q$Time per Pass$q$, $q$Time per Pass (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Turned Length} / {Feed Rate} * 60$q$, 13, false),
    (v_id, $q$Cycle Time$q$, $q$Cycle Time (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Rough Passes} * {Time per Pass}$q$, 14, false);

  INSERT INTO public.process_calculator_mappings
    (process_group, process_route, operation, calculator_id, calculator_name, is_active, display_order, machine_class, canonical_process_id)
  SELECT 'Machining', s.station, $q$Rough Turning$q$, v_id, $q$Machining - Rough Turning$q$, true, 701, s.cls,
         (SELECT pt.id FROM public.process_taxonomy pt WHERE pt.process_group = 'Machining' AND pt.process_name = s.station LIMIT 1)
  FROM (VALUES ($q$2_axis_lathe$q$, $q$2 Axis Lathe$q$), ($q$3_axis_lathe$q$, $q$3 Axis Lathe$q$), ($q$2_axis_bar_feed_lathe_with_sub_spindle$q$, $q$2 Axis Bar Feed Lathe with Sub Spindle$q$), ($q$3_axis_bar_feed_lathe_with_sub_spindle$q$, $q$3 Axis Bar Feed Lathe with Sub Spindle$q$), ($q$simultaneous_turning$q$, $q$Simultaneous Turning$q$), ($q$machining_millturn$q$, $q$MillTurn$q$)) AS s(cls, station)
  ON CONFLICT (process_group, process_route, operation) DO UPDATE
  SET calculator_id = EXCLUDED.calculator_id,
      calculator_name = EXCLUDED.calculator_name,
      machine_class = EXCLUDED.machine_class,
      is_active = true,
      canonical_process_id = EXCLUDED.canonical_process_id;
END
$calc$;

-- Machining - Finish Turning
DO $calc$
DECLARE v_id UUID;
BEGIN
  SELECT id INTO v_id FROM public.calculators WHERE name = $q$Machining - Finish Turning$q$ AND user_id IS NULL AND retired_at IS NULL;
  IF v_id IS NULL THEN
    INSERT INTO public.calculators (user_id, name, calc_category, calculator_type, is_template, is_public, is_global, description)
    VALUES (NULL, $q$Machining - Finish Turning$q$, 'process', 'single', false, true, true, $q$One finish turning pass over the turned length: CAD turned diameter/length, finish speed and feed from tblGeneralTurning.$q$)
    RETURNING id INTO v_id;
  ELSE
    UPDATE public.calculators SET description = $q$One finish turning pass over the turned length: CAD turned diameter/length, finish speed and feed from tblGeneralTurning.$q$, updated_at = now() WHERE id = v_id;
  END IF;

  DELETE FROM public.calculator_fields WHERE calculator_id = v_id;
  INSERT INTO public.calculator_fields
    (calculator_id, field_name, display_label, field_type, unit, data_source, source_table, source_field, default_value, display_order, is_required)
  VALUES
    (v_id, $q$Turned Diameter$q$, $q$Turned Diameter (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 1, true),
    (v_id, $q$Turned Length$q$, $q$Turned Length (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 2, true),
    (v_id, $q$Finish Cutting Speed$q$, $q$Finish Cutting Speed (m/min)$q$, $q$number$q$, $q$m/min$q$, $q$machining_lookup$q$, $q$tblGeneralTurning$q$, $q$cutting_speed_m_min$q$, NULL, 3, true),
    (v_id, $q$Finish Feed$q$, $q$Finish Feed (mm/rev)$q$, $q$number$q$, $q$mm/rev$q$, $q$machining_lookup$q$, $q$tblGeneralTurning$q$, $q$feed_rate_mm_rev$q$, NULL, 4, true),
    (v_id, $q$Spindle Speed$q$, $q$Spindle Speed (rpm)$q$, $q$calculated$q$, $q$rpm$q$, NULL, NULL, NULL, $q${Finish Cutting Speed} * 1000 / (pi * {Turned Diameter})$q$, 5, false),
    (v_id, $q$Feed Rate$q$, $q$Feed Rate (mm/min)$q$, $q$calculated$q$, $q$mm/min$q$, NULL, NULL, NULL, $q${Spindle Speed} * {Finish Feed}$q$, 6, false),
    (v_id, $q$Cycle Time$q$, $q$Cycle Time (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Turned Length} / {Feed Rate} * 60$q$, 7, false);

  INSERT INTO public.process_calculator_mappings
    (process_group, process_route, operation, calculator_id, calculator_name, is_active, display_order, machine_class, canonical_process_id)
  SELECT 'Machining', s.station, $q$Finish Turning$q$, v_id, $q$Machining - Finish Turning$q$, true, 702, s.cls,
         (SELECT pt.id FROM public.process_taxonomy pt WHERE pt.process_group = 'Machining' AND pt.process_name = s.station LIMIT 1)
  FROM (VALUES ($q$2_axis_lathe$q$, $q$2 Axis Lathe$q$), ($q$3_axis_lathe$q$, $q$3 Axis Lathe$q$), ($q$2_axis_bar_feed_lathe_with_sub_spindle$q$, $q$2 Axis Bar Feed Lathe with Sub Spindle$q$), ($q$3_axis_bar_feed_lathe_with_sub_spindle$q$, $q$3 Axis Bar Feed Lathe with Sub Spindle$q$), ($q$simultaneous_turning$q$, $q$Simultaneous Turning$q$), ($q$machining_millturn$q$, $q$MillTurn$q$)) AS s(cls, station)
  ON CONFLICT (process_group, process_route, operation) DO UPDATE
  SET calculator_id = EXCLUDED.calculator_id,
      calculator_name = EXCLUDED.calculator_name,
      machine_class = EXCLUDED.machine_class,
      is_active = true,
      canonical_process_id = EXCLUDED.canonical_process_id;
END
$calc$;

-- Machining - Parting
DO $calc$
DECLARE v_id UUID;
BEGIN
  SELECT id INTO v_id FROM public.calculators WHERE name = $q$Machining - Parting$q$ AND user_id IS NULL AND retired_at IS NULL;
  IF v_id IS NULL THEN
    INSERT INTO public.calculators (user_id, name, calc_category, calculator_type, is_template, is_public, is_global, description)
    VALUES (NULL, $q$Machining - Parting$q$, 'process', 'single', false, true, true, $q$Part-off plunge from the bar surface to its centre: stock bar diameter, insert speed and feed from tblVirtualPartoffInsertCutData.$q$)
    RETURNING id INTO v_id;
  ELSE
    UPDATE public.calculators SET description = $q$Part-off plunge from the bar surface to its centre: stock bar diameter, insert speed and feed from tblVirtualPartoffInsertCutData.$q$, updated_at = now() WHERE id = v_id;
  END IF;

  DELETE FROM public.calculator_fields WHERE calculator_id = v_id;
  INSERT INTO public.calculator_fields
    (calculator_id, field_name, display_label, field_type, unit, data_source, source_table, source_field, default_value, display_order, is_required)
  VALUES
    (v_id, $q$Bar Diameter$q$, $q$Bar Diameter (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 1, true),
    (v_id, $q$Cutting Speed$q$, $q$Cutting Speed (m/min)$q$, $q$number$q$, $q$m/min$q$, $q$machining_lookup$q$, $q$tblVirtualPartoffInsertCutData$q$, $q$CuttingSpeedMPerMin$q$, NULL, 2, true),
    (v_id, $q$Feed$q$, $q$Feed (mm/rev)$q$, $q$number$q$, $q$mm/rev$q$, $q$machining_lookup$q$, $q$tblVirtualPartoffInsertCutData$q$, $q$FeedMm$q$, NULL, 3, true),
    (v_id, $q$Cut Depth$q$, $q$Cut Depth (mm)$q$, $q$calculated$q$, $q$mm$q$, NULL, NULL, NULL, $q${Bar Diameter} / 2$q$, 4, false),
    (v_id, $q$Spindle Speed$q$, $q$Spindle Speed (rpm)$q$, $q$calculated$q$, $q$rpm$q$, NULL, NULL, NULL, $q${Cutting Speed} * 1000 / (pi * {Bar Diameter})$q$, 5, false),
    (v_id, $q$Feed Rate$q$, $q$Feed Rate (mm/min)$q$, $q$calculated$q$, $q$mm/min$q$, NULL, NULL, NULL, $q${Spindle Speed} * {Feed}$q$, 6, false),
    (v_id, $q$Cycle Time$q$, $q$Cycle Time (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Cut Depth} / {Feed Rate} * 60$q$, 7, false);

  INSERT INTO public.process_calculator_mappings
    (process_group, process_route, operation, calculator_id, calculator_name, is_active, display_order, machine_class, canonical_process_id)
  SELECT 'Machining', s.station, $q$Parting$q$, v_id, $q$Machining - Parting$q$, true, 703, s.cls,
         (SELECT pt.id FROM public.process_taxonomy pt WHERE pt.process_group = 'Machining' AND pt.process_name = s.station LIMIT 1)
  FROM (VALUES ($q$2_axis_lathe$q$, $q$2 Axis Lathe$q$), ($q$3_axis_lathe$q$, $q$3 Axis Lathe$q$), ($q$2_axis_bar_feed_lathe_with_sub_spindle$q$, $q$2 Axis Bar Feed Lathe with Sub Spindle$q$), ($q$3_axis_bar_feed_lathe_with_sub_spindle$q$, $q$3 Axis Bar Feed Lathe with Sub Spindle$q$), ($q$simultaneous_turning$q$, $q$Simultaneous Turning$q$), ($q$machining_millturn$q$, $q$MillTurn$q$)) AS s(cls, station)
  ON CONFLICT (process_group, process_route, operation) DO UPDATE
  SET calculator_id = EXCLUDED.calculator_id,
      calculator_name = EXCLUDED.calculator_name,
      machine_class = EXCLUDED.machine_class,
      is_active = true,
      canonical_process_id = EXCLUDED.canonical_process_id;
END
$calc$;

-- Machining - Reaming
DO $calc$
DECLARE v_id UUID;
BEGIN
  SELECT id INTO v_id FROM public.calculators WHERE name = $q$Machining - Reaming$q$ AND user_id IS NULL AND retired_at IS NULL;
  IF v_id IS NULL THEN
    INSERT INTO public.calculators (user_id, name, calc_category, calculator_type, is_template, is_public, is_global, description)
    VALUES (NULL, $q$Machining - Reaming$q$, 'process', 'single', false, true, true, $q$Reaming pass through the drilled hole: CAD hole diameter and depth, speed and feed from tblReaming.$q$)
    RETURNING id INTO v_id;
  ELSE
    UPDATE public.calculators SET description = $q$Reaming pass through the drilled hole: CAD hole diameter and depth, speed and feed from tblReaming.$q$, updated_at = now() WHERE id = v_id;
  END IF;

  DELETE FROM public.calculator_fields WHERE calculator_id = v_id;
  INSERT INTO public.calculator_fields
    (calculator_id, field_name, display_label, field_type, unit, data_source, source_table, source_field, default_value, display_order, is_required)
  VALUES
    (v_id, $q$Hole Diameter$q$, $q$Hole Diameter (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 1, true),
    (v_id, $q$Hole Depth$q$, $q$Hole Depth (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 2, true),
    (v_id, $q$Holes$q$, $q$Holes$q$, $q$number$q$, NULL, NULL, NULL, NULL, NULL, 3, true),
    (v_id, $q$Cutting Speed$q$, $q$Cutting Speed (m/min)$q$, $q$number$q$, $q$m/min$q$, $q$machining_lookup$q$, $q$tblReaming$q$, $q$CuttingSpeedMPerMin$q$, NULL, 4, true),
    (v_id, $q$Feed$q$, $q$Feed (mm/rev)$q$, $q$number$q$, $q$mm/rev$q$, $q$machining_lookup$q$, $q$tblReaming$q$, $q$FeedMm$q$, NULL, 5, true),
    (v_id, $q$Spindle Speed$q$, $q$Spindle Speed (rpm)$q$, $q$calculated$q$, $q$rpm$q$, NULL, NULL, NULL, $q${Cutting Speed} * 1000 / (pi * {Hole Diameter})$q$, 6, false),
    (v_id, $q$Feed Rate$q$, $q$Feed Rate (mm/min)$q$, $q$calculated$q$, $q$mm/min$q$, NULL, NULL, NULL, $q${Spindle Speed} * {Feed}$q$, 7, false),
    (v_id, $q$Time per Hole$q$, $q$Time per Hole (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Hole Depth} / {Feed Rate} * 60$q$, 8, false),
    (v_id, $q$Cycle Time$q$, $q$Cycle Time (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Time per Hole} * {Holes}$q$, 9, false);

  INSERT INTO public.process_calculator_mappings
    (process_group, process_route, operation, calculator_id, calculator_name, is_active, display_order, machine_class, canonical_process_id)
  SELECT 'Machining', s.station, $q$Reaming$q$, v_id, $q$Machining - Reaming$q$, true, 704, s.cls,
         (SELECT pt.id FROM public.process_taxonomy pt WHERE pt.process_group = 'Machining' AND pt.process_name = s.station LIMIT 1)
  FROM (VALUES ($q$2_axis_lathe$q$, $q$2 Axis Lathe$q$), ($q$3_axis_lathe$q$, $q$3 Axis Lathe$q$), ($q$2_axis_bar_feed_lathe_with_sub_spindle$q$, $q$2 Axis Bar Feed Lathe with Sub Spindle$q$), ($q$3_axis_bar_feed_lathe_with_sub_spindle$q$, $q$3 Axis Bar Feed Lathe with Sub Spindle$q$), ($q$simultaneous_turning$q$, $q$Simultaneous Turning$q$), ($q$machining_millturn$q$, $q$MillTurn$q$), ($q$3_axis_mill$q$, $q$3 Axis Mill$q$), ($q$4_axis_mill$q$, $q$4 Axis Mill$q$), ($q$5_axis_mill$q$, $q$5 Axis Mill$q$)) AS s(cls, station)
  ON CONFLICT (process_group, process_route, operation) DO UPDATE
  SET calculator_id = EXCLUDED.calculator_id,
      calculator_name = EXCLUDED.calculator_name,
      machine_class = EXCLUDED.machine_class,
      is_active = true,
      canonical_process_id = EXCLUDED.canonical_process_id;
END
$calc$;

-- Machining - Rigid Tapping
DO $calc$
DECLARE v_id UUID;
BEGIN
  SELECT id INTO v_id FROM public.calculators WHERE name = $q$Machining - Rigid Tapping$q$ AND user_id IS NULL AND retired_at IS NULL;
  IF v_id IS NULL THEN
    INSERT INTO public.calculators (user_id, name, calc_category, calculator_type, is_template, is_public, is_global, description)
    VALUES (NULL, $q$Machining - Rigid Tapping$q$, 'process', 'single', false, true, true, $q$Rigid tapping of a threaded hole: CAD thread diameter, depth and pitch (the part, else the ISO 261 coarse pitch of its nominal size), cutting speed from tblTapping for the material and pitch. The tap feeds one pitch per revolution in and reverses out at the same feed.$q$)
    RETURNING id INTO v_id;
  ELSE
    UPDATE public.calculators SET description = $q$Rigid tapping of a threaded hole: CAD thread diameter, depth and pitch (the part, else the ISO 261 coarse pitch of its nominal size), cutting speed from tblTapping for the material and pitch. The tap feeds one pitch per revolution in and reverses out at the same feed.$q$, updated_at = now() WHERE id = v_id;
  END IF;

  DELETE FROM public.calculator_fields WHERE calculator_id = v_id;
  INSERT INTO public.calculator_fields
    (calculator_id, field_name, display_label, field_type, unit, data_source, source_table, source_field, default_value, display_order, is_required)
  VALUES
    (v_id, $q$Thread Diameter$q$, $q$Thread Diameter (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 1, true),
    (v_id, $q$Thread Depth$q$, $q$Thread Depth (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 2, true),
    (v_id, $q$Threads$q$, $q$Threads$q$, $q$number$q$, NULL, NULL, NULL, NULL, NULL, 3, true),
    (v_id, $q$Thread Pitch$q$, $q$Thread Pitch (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 4, true),
    (v_id, $q$Cutting Speed$q$, $q$Cutting Speed (m/min)$q$, $q$number$q$, $q$m/min$q$, $q$machining_lookup$q$, $q$tblTapping$q$, $q$CuttingSpeedMPerMin$q$, NULL, 5, true),
    (v_id, $q$Spindle Speed$q$, $q$Spindle Speed (rpm)$q$, $q$calculated$q$, $q$rpm$q$, NULL, NULL, NULL, $q${Cutting Speed} * 1000 / (pi * {Thread Diameter})$q$, 6, false),
    (v_id, $q$Feed Rate$q$, $q$Feed Rate (mm/min)$q$, $q$calculated$q$, $q$mm/min$q$, NULL, NULL, NULL, $q${Spindle Speed} * {Thread Pitch}$q$, 7, false),
    (v_id, $q$Time per Thread$q$, $q$Time per Thread (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q$2 * {Thread Depth} / {Feed Rate} * 60$q$, 8, false),
    (v_id, $q$Cycle Time$q$, $q$Cycle Time (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Time per Thread} * {Threads}$q$, 9, false);

  INSERT INTO public.process_calculator_mappings
    (process_group, process_route, operation, calculator_id, calculator_name, is_active, display_order, machine_class, canonical_process_id)
  SELECT 'Machining', s.station, $q$Tapping$q$, v_id, $q$Machining - Rigid Tapping$q$, true, 705, s.cls,
         (SELECT pt.id FROM public.process_taxonomy pt WHERE pt.process_group = 'Machining' AND pt.process_name = s.station LIMIT 1)
  FROM (VALUES ($q$2_axis_lathe$q$, $q$2 Axis Lathe$q$), ($q$3_axis_lathe$q$, $q$3 Axis Lathe$q$), ($q$2_axis_bar_feed_lathe_with_sub_spindle$q$, $q$2 Axis Bar Feed Lathe with Sub Spindle$q$), ($q$3_axis_bar_feed_lathe_with_sub_spindle$q$, $q$3 Axis Bar Feed Lathe with Sub Spindle$q$), ($q$simultaneous_turning$q$, $q$Simultaneous Turning$q$), ($q$machining_millturn$q$, $q$MillTurn$q$), ($q$3_axis_mill$q$, $q$3 Axis Mill$q$), ($q$4_axis_mill$q$, $q$4 Axis Mill$q$), ($q$5_axis_mill$q$, $q$5 Axis Mill$q$)) AS s(cls, station)
  ON CONFLICT (process_group, process_route, operation) DO UPDATE
  SET calculator_id = EXCLUDED.calculator_id,
      calculator_name = EXCLUDED.calculator_name,
      machine_class = EXCLUDED.machine_class,
      is_active = true,
      canonical_process_id = EXCLUDED.canonical_process_id;
END
$calc$;

-- Machining - Jig Boring
DO $calc$
DECLARE v_id UUID;
BEGIN
  SELECT id INTO v_id FROM public.calculators WHERE name = $q$Machining - Jig Boring$q$ AND user_id IS NULL AND retired_at IS NULL;
  IF v_id IS NULL THEN
    INSERT INTO public.calculators (user_id, name, calc_category, calculator_type, is_template, is_public, is_global, description)
    VALUES (NULL, $q$Machining - Jig Boring$q$, 'process', 'single', false, true, true, $q$Jig boring: finish-boring physics from tblBoringV2 repeated the number of passes tblGtolProcessCapabilities gives for jig boring.$q$)
    RETURNING id INTO v_id;
  ELSE
    UPDATE public.calculators SET description = $q$Jig boring: finish-boring physics from tblBoringV2 repeated the number of passes tblGtolProcessCapabilities gives for jig boring.$q$, updated_at = now() WHERE id = v_id;
  END IF;

  DELETE FROM public.calculator_fields WHERE calculator_id = v_id;
  INSERT INTO public.calculator_fields
    (calculator_id, field_name, display_label, field_type, unit, data_source, source_table, source_field, default_value, display_order, is_required)
  VALUES
    (v_id, $q$Hole Diameter$q$, $q$Hole Diameter (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 1, true),
    (v_id, $q$Hole Depth$q$, $q$Hole Depth (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 2, true),
    (v_id, $q$Holes$q$, $q$Holes$q$, $q$number$q$, NULL, NULL, NULL, NULL, NULL, 3, true),
    (v_id, $q$Cutting Speed$q$, $q$Cutting Speed (m/min)$q$, $q$number$q$, $q$m/min$q$, $q$machining_lookup$q$, $q$tblBoringV2$q$, $q$cutting_speed_m_min$q$, NULL, 4, true),
    (v_id, $q$Feed$q$, $q$Feed (mm/rev)$q$, $q$number$q$, $q$mm/rev$q$, $q$machining_lookup$q$, $q$tblBoringV2$q$, $q$feed_mm_rev$q$, NULL, 5, true),
    (v_id, $q$Repetitions$q$, $q$Repetitions$q$, $q$number$q$, NULL, $q$machining_lookup$q$, $q$tblGtolProcessCapabilities$q$, $q$Num Repetitions$q$, NULL, 6, true),
    (v_id, $q$Spindle Speed$q$, $q$Spindle Speed (rpm)$q$, $q$calculated$q$, $q$rpm$q$, NULL, NULL, NULL, $q${Cutting Speed} * 1000 / (pi * {Hole Diameter})$q$, 7, false),
    (v_id, $q$Feed Rate$q$, $q$Feed Rate (mm/min)$q$, $q$calculated$q$, $q$mm/min$q$, NULL, NULL, NULL, $q${Spindle Speed} * {Feed}$q$, 8, false),
    (v_id, $q$Time per Pass$q$, $q$Time per Pass (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Hole Depth} / {Feed Rate} * 60$q$, 9, false),
    (v_id, $q$Cycle Time$q$, $q$Cycle Time (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Time per Pass} * {Repetitions} * {Holes}$q$, 10, false);

  INSERT INTO public.process_calculator_mappings
    (process_group, process_route, operation, calculator_id, calculator_name, is_active, display_order, machine_class, canonical_process_id)
  SELECT 'Machining', s.station, $q$Jig Boring$q$, v_id, $q$Machining - Jig Boring$q$, true, 706, s.cls,
         (SELECT pt.id FROM public.process_taxonomy pt WHERE pt.process_group = 'Machining' AND pt.process_name = s.station LIMIT 1)
  FROM (VALUES ($q$jig_bore$q$, $q$Jig Bore$q$)) AS s(cls, station)
  ON CONFLICT (process_group, process_route, operation) DO UPDATE
  SET calculator_id = EXCLUDED.calculator_id,
      calculator_name = EXCLUDED.calculator_name,
      machine_class = EXCLUDED.machine_class,
      is_active = true,
      canonical_process_id = EXCLUDED.canonical_process_id;
END
$calc$;

-- Machining - Gun Drilling
DO $calc$
DECLARE v_id UUID;
BEGIN
  SELECT id INTO v_id FROM public.calculators WHERE name = $q$Machining - Gun Drilling$q$ AND user_id IS NULL AND retired_at IS NULL;
  IF v_id IS NULL THEN
    INSERT INTO public.calculators (user_id, name, calc_category, calculator_type, is_template, is_public, is_global, description)
    VALUES (NULL, $q$Machining - Gun Drilling$q$, 'process', 'single', false, true, true, $q$Deep-hole gun drilling: CAD hole diameter and depth, speed and feed from tblGunDrilling.$q$)
    RETURNING id INTO v_id;
  ELSE
    UPDATE public.calculators SET description = $q$Deep-hole gun drilling: CAD hole diameter and depth, speed and feed from tblGunDrilling.$q$, updated_at = now() WHERE id = v_id;
  END IF;

  DELETE FROM public.calculator_fields WHERE calculator_id = v_id;
  INSERT INTO public.calculator_fields
    (calculator_id, field_name, display_label, field_type, unit, data_source, source_table, source_field, default_value, display_order, is_required)
  VALUES
    (v_id, $q$Hole Diameter$q$, $q$Hole Diameter (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 1, true),
    (v_id, $q$Hole Depth$q$, $q$Hole Depth (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 2, true),
    (v_id, $q$Holes$q$, $q$Holes$q$, $q$number$q$, NULL, NULL, NULL, NULL, NULL, 3, true),
    (v_id, $q$Cutting Speed$q$, $q$Cutting Speed (m/min)$q$, $q$number$q$, $q$m/min$q$, $q$machining_lookup$q$, $q$tblGunDrilling$q$, $q$Cutting Speed (m / min)$q$, NULL, 4, true),
    (v_id, $q$Feed$q$, $q$Feed (mm/rev)$q$, $q$number$q$, $q$mm/rev$q$, $q$machining_lookup$q$, $q$tblGunDrilling$q$, $q$Feed (mm / rev)$q$, NULL, 5, true),
    (v_id, $q$Spindle Speed$q$, $q$Spindle Speed (rpm)$q$, $q$calculated$q$, $q$rpm$q$, NULL, NULL, NULL, $q${Cutting Speed} * 1000 / (pi * {Hole Diameter})$q$, 6, false),
    (v_id, $q$Feed Rate$q$, $q$Feed Rate (mm/min)$q$, $q$calculated$q$, $q$mm/min$q$, NULL, NULL, NULL, $q${Spindle Speed} * {Feed}$q$, 7, false),
    (v_id, $q$Time per Hole$q$, $q$Time per Hole (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Hole Depth} / {Feed Rate} * 60$q$, 8, false),
    (v_id, $q$Cycle Time$q$, $q$Cycle Time (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Time per Hole} * {Holes}$q$, 9, false);

  INSERT INTO public.process_calculator_mappings
    (process_group, process_route, operation, calculator_id, calculator_name, is_active, display_order, machine_class, canonical_process_id)
  SELECT 'Machining', s.station, $q$Gun Drilling$q$, v_id, $q$Machining - Gun Drilling$q$, true, 707, s.cls,
         (SELECT pt.id FROM public.process_taxonomy pt WHERE pt.process_group = 'Machining' AND pt.process_name = s.station LIMIT 1)
  FROM (VALUES ($q$gun_drill$q$, $q$Gun Drill$q$)) AS s(cls, station)
  ON CONFLICT (process_group, process_route, operation) DO UPDATE
  SET calculator_id = EXCLUDED.calculator_id,
      calculator_name = EXCLUDED.calculator_name,
      machine_class = EXCLUDED.machine_class,
      is_active = true,
      canonical_process_id = EXCLUDED.canonical_process_id;
END
$calc$;

-- Machining - Deep Bore
DO $calc$
DECLARE v_id UUID;
BEGIN
  SELECT id INTO v_id FROM public.calculators WHERE name = $q$Machining - Deep Bore$q$ AND user_id IS NULL AND retired_at IS NULL;
  IF v_id IS NULL THEN
    INSERT INTO public.calculators (user_id, name, calc_category, calculator_type, is_template, is_public, is_global, description)
    VALUES (NULL, $q$Machining - Deep Bore$q$, 'process', 'single', false, true, true, $q$Deep-hole boring: CAD hole diameter and depth, speed and feed from the deep bore drill lookup.$q$)
    RETURNING id INTO v_id;
  ELSE
    UPDATE public.calculators SET description = $q$Deep-hole boring: CAD hole diameter and depth, speed and feed from the deep bore drill lookup.$q$, updated_at = now() WHERE id = v_id;
  END IF;

  DELETE FROM public.calculator_fields WHERE calculator_id = v_id;
  INSERT INTO public.calculator_fields
    (calculator_id, field_name, display_label, field_type, unit, data_source, source_table, source_field, default_value, display_order, is_required)
  VALUES
    (v_id, $q$Hole Diameter$q$, $q$Hole Diameter (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 1, true),
    (v_id, $q$Hole Depth$q$, $q$Hole Depth (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 2, true),
    (v_id, $q$Holes$q$, $q$Holes$q$, $q$number$q$, NULL, NULL, NULL, NULL, NULL, 3, true),
    (v_id, $q$Cutting Speed$q$, $q$Cutting Speed (m/min)$q$, $q$number$q$, $q$m/min$q$, $q$machining_lookup$q$, $q$deep_bore_drill_lookup$q$, $q$cutting_speed_m_min$q$, NULL, 4, true),
    (v_id, $q$Feed$q$, $q$Feed (mm/rev)$q$, $q$number$q$, $q$mm/rev$q$, $q$machining_lookup$q$, $q$deep_bore_drill_lookup$q$, $q$feed_mm_rev$q$, NULL, 5, true),
    (v_id, $q$Spindle Speed$q$, $q$Spindle Speed (rpm)$q$, $q$calculated$q$, $q$rpm$q$, NULL, NULL, NULL, $q${Cutting Speed} * 1000 / (pi * {Hole Diameter})$q$, 6, false),
    (v_id, $q$Feed Rate$q$, $q$Feed Rate (mm/min)$q$, $q$calculated$q$, $q$mm/min$q$, NULL, NULL, NULL, $q${Spindle Speed} * {Feed}$q$, 7, false),
    (v_id, $q$Time per Hole$q$, $q$Time per Hole (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Hole Depth} / {Feed Rate} * 60$q$, 8, false),
    (v_id, $q$Cycle Time$q$, $q$Cycle Time (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Time per Hole} * {Holes}$q$, 9, false);

  INSERT INTO public.process_calculator_mappings
    (process_group, process_route, operation, calculator_id, calculator_name, is_active, display_order, machine_class, canonical_process_id)
  SELECT 'Machining', s.station, $q$Deep Bore Machine$q$, v_id, $q$Machining - Deep Bore$q$, true, 708, s.cls,
         (SELECT pt.id FROM public.process_taxonomy pt WHERE pt.process_group = 'Machining' AND pt.process_name = s.station LIMIT 1)
  FROM (VALUES ($q$deep_bore_machine$q$, $q$Deep Bore Machine$q$)) AS s(cls, station)
  ON CONFLICT (process_group, process_route, operation) DO UPDATE
  SET calculator_id = EXCLUDED.calculator_id,
      calculator_name = EXCLUDED.calculator_name,
      machine_class = EXCLUDED.machine_class,
      is_active = true,
      canonical_process_id = EXCLUDED.canonical_process_id;
END
$calc$;

-- Machining - Cylindrical Grinding
DO $calc$
DECLARE v_id UUID;
BEGIN
  SELECT id INTO v_id FROM public.calculators WHERE name = $q$Machining - Cylindrical Grinding$q$ AND user_id IS NULL AND retired_at IS NULL;
  IF v_id IS NULL THEN
    INSERT INTO public.calculators (user_id, name, calc_category, calculator_type, is_template, is_public, is_global, description)
    VALUES (NULL, $q$Machining - Cylindrical Grinding$q$, 'process', 'single', false, true, true, $q$Traverse grinding of a turned OD: CAD diameter/length, grinding allowance (variables finishGrindingDepth), wheel/work data from tblCylindricalGrinding.$q$)
    RETURNING id INTO v_id;
  ELSE
    UPDATE public.calculators SET description = $q$Traverse grinding of a turned OD: CAD diameter/length, grinding allowance (variables finishGrindingDepth), wheel/work data from tblCylindricalGrinding.$q$, updated_at = now() WHERE id = v_id;
  END IF;

  DELETE FROM public.calculator_fields WHERE calculator_id = v_id;
  INSERT INTO public.calculator_fields
    (calculator_id, field_name, display_label, field_type, unit, data_source, source_table, source_field, default_value, display_order, is_required)
  VALUES
    (v_id, $q$Grind Diameter$q$, $q$Grind Diameter (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 1, true),
    (v_id, $q$Grind Length$q$, $q$Grind Length (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 2, true),
    (v_id, $q$Surfaces$q$, $q$Surfaces$q$, $q$number$q$, NULL, NULL, NULL, NULL, NULL, 3, true),
    (v_id, $q$Grinding Allowance$q$, $q$Grinding Allowance (mm)$q$, $q$number$q$, $q$mm$q$, $q$machining_lookup$q$, $q$variables$q$, $q$value$q$, NULL, 4, true),
    (v_id, $q$Work Speed$q$, $q$Work Speed (m/min)$q$, $q$number$q$, $q$m/min$q$, $q$machining_lookup$q$, $q$tblCylindricalGrinding$q$, $q$work_speed_m_min$q$, NULL, 5, true),
    (v_id, $q$Rough Infeed$q$, $q$Rough Infeed (mm)$q$, $q$number$q$, $q$mm$q$, $q$machining_lookup$q$, $q$tblCylindricalGrinding$q$, $q$rough_infeed_mm$q$, NULL, 6, true),
    (v_id, $q$Finish Infeed$q$, $q$Finish Infeed (mm)$q$, $q$number$q$, $q$mm$q$, $q$machining_lookup$q$, $q$tblCylindricalGrinding$q$, $q$finish_infeed_mm$q$, NULL, 7, true),
    (v_id, $q$Rough Axial Feed$q$, $q$Rough Axial Feed (mm/rev)$q$, $q$number$q$, $q$mm/rev$q$, $q$machining_lookup$q$, $q$tblCylindricalGrinding$q$, $q$rough_axial_feed_rev_1$q$, NULL, 8, true),
    (v_id, $q$Finish Axial Feed$q$, $q$Finish Axial Feed (mm/rev)$q$, $q$number$q$, $q$mm/rev$q$, $q$machining_lookup$q$, $q$tblCylindricalGrinding$q$, $q$finish_axial_feed_rev_1$q$, NULL, 9, true),
    (v_id, $q$Spindle Speed$q$, $q$Spindle Speed (rpm)$q$, $q$calculated$q$, $q$rpm$q$, NULL, NULL, NULL, $q${Work Speed} * 1000 / (pi * {Grind Diameter})$q$, 10, false),
    (v_id, $q$Finish Stock$q$, $q$Finish Stock (mm)$q$, $q$calculated$q$, $q$mm$q$, NULL, NULL, NULL, $q$min({Finish Infeed}, {Grinding Allowance})$q$, 11, false),
    (v_id, $q$Rough Passes$q$, $q$Rough Passes$q$, $q$calculated$q$, NULL, NULL, NULL, NULL, $q$round(max({Grinding Allowance} - {Finish Stock}, 0) / {Rough Infeed})$q$, 12, false),
    (v_id, $q$Rough Pass Time$q$, $q$Rough Pass Time (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Grind Length} / ({Spindle Speed} * {Rough Axial Feed}) * 60$q$, 13, false),
    (v_id, $q$Finish Pass Time$q$, $q$Finish Pass Time (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Grind Length} / ({Spindle Speed} * {Finish Axial Feed}) * 60$q$, 14, false),
    (v_id, $q$Time per Surface$q$, $q$Time per Surface (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Rough Passes} * {Rough Pass Time} + {Finish Pass Time}$q$, 15, false),
    (v_id, $q$Cycle Time$q$, $q$Cycle Time (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Time per Surface} * {Surfaces}$q$, 16, false);

  INSERT INTO public.process_calculator_mappings
    (process_group, process_route, operation, calculator_id, calculator_name, is_active, display_order, machine_class, canonical_process_id)
  SELECT 'Machining', s.station, $q$Cylindrical Grinding$q$, v_id, $q$Machining - Cylindrical Grinding$q$, true, 709, s.cls,
         (SELECT pt.id FROM public.process_taxonomy pt WHERE pt.process_group = 'Machining' AND pt.process_name = s.station LIMIT 1)
  FROM (VALUES ($q$cylindrical_grinder$q$, $q$Cylindrical Grinder$q$)) AS s(cls, station)
  ON CONFLICT (process_group, process_route, operation) DO UPDATE
  SET calculator_id = EXCLUDED.calculator_id,
      calculator_name = EXCLUDED.calculator_name,
      machine_class = EXCLUDED.machine_class,
      is_active = true,
      canonical_process_id = EXCLUDED.canonical_process_id;
END
$calc$;

-- Machining - Internal Grinding
DO $calc$
DECLARE v_id UUID;
BEGIN
  SELECT id INTO v_id FROM public.calculators WHERE name = $q$Machining - Internal Grinding$q$ AND user_id IS NULL AND retired_at IS NULL;
  IF v_id IS NULL THEN
    INSERT INTO public.calculators (user_id, name, calc_category, calculator_type, is_template, is_public, is_global, description)
    VALUES (NULL, $q$Machining - Internal Grinding$q$, 'process', 'single', false, true, true, $q$Traverse grinding of a bore: CAD bore diameter/depth, grinding allowance (variables finishGrindingDepth), wheel/work data from tblInternalGrinding.$q$)
    RETURNING id INTO v_id;
  ELSE
    UPDATE public.calculators SET description = $q$Traverse grinding of a bore: CAD bore diameter/depth, grinding allowance (variables finishGrindingDepth), wheel/work data from tblInternalGrinding.$q$, updated_at = now() WHERE id = v_id;
  END IF;

  DELETE FROM public.calculator_fields WHERE calculator_id = v_id;
  INSERT INTO public.calculator_fields
    (calculator_id, field_name, display_label, field_type, unit, data_source, source_table, source_field, default_value, display_order, is_required)
  VALUES
    (v_id, $q$Grind Diameter$q$, $q$Grind Diameter (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 1, true),
    (v_id, $q$Grind Length$q$, $q$Grind Length (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 2, true),
    (v_id, $q$Surfaces$q$, $q$Surfaces$q$, $q$number$q$, NULL, NULL, NULL, NULL, NULL, 3, true),
    (v_id, $q$Grinding Allowance$q$, $q$Grinding Allowance (mm)$q$, $q$number$q$, $q$mm$q$, $q$machining_lookup$q$, $q$variables$q$, $q$value$q$, NULL, 4, true),
    (v_id, $q$Work Speed$q$, $q$Work Speed (m/min)$q$, $q$number$q$, $q$m/min$q$, $q$machining_lookup$q$, $q$tblInternalGrinding$q$, $q$Work Speed (m / min)$q$, NULL, 5, true),
    (v_id, $q$Rough Infeed$q$, $q$Rough Infeed (mm)$q$, $q$number$q$, $q$mm$q$, $q$machining_lookup$q$, $q$tblInternalGrinding$q$, $q$Rough Infeed (mm)$q$, NULL, 6, true),
    (v_id, $q$Finish Infeed$q$, $q$Finish Infeed (mm)$q$, $q$number$q$, $q$mm$q$, $q$machining_lookup$q$, $q$tblInternalGrinding$q$, $q$Finish Infeed (mm)$q$, NULL, 7, true),
    (v_id, $q$Rough Axial Feed$q$, $q$Rough Axial Feed (mm/rev)$q$, $q$number$q$, $q$mm/rev$q$, $q$machining_lookup$q$, $q$tblInternalGrinding$q$, $q$Rough Axial Feed (rev^-1)$q$, NULL, 8, true),
    (v_id, $q$Finish Axial Feed$q$, $q$Finish Axial Feed (mm/rev)$q$, $q$number$q$, $q$mm/rev$q$, $q$machining_lookup$q$, $q$tblInternalGrinding$q$, $q$Finish Axial Feed (rev^-1)$q$, NULL, 9, true),
    (v_id, $q$Spindle Speed$q$, $q$Spindle Speed (rpm)$q$, $q$calculated$q$, $q$rpm$q$, NULL, NULL, NULL, $q${Work Speed} * 1000 / (pi * {Grind Diameter})$q$, 10, false),
    (v_id, $q$Finish Stock$q$, $q$Finish Stock (mm)$q$, $q$calculated$q$, $q$mm$q$, NULL, NULL, NULL, $q$min({Finish Infeed}, {Grinding Allowance})$q$, 11, false),
    (v_id, $q$Rough Passes$q$, $q$Rough Passes$q$, $q$calculated$q$, NULL, NULL, NULL, NULL, $q$round(max({Grinding Allowance} - {Finish Stock}, 0) / {Rough Infeed})$q$, 12, false),
    (v_id, $q$Rough Pass Time$q$, $q$Rough Pass Time (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Grind Length} / ({Spindle Speed} * {Rough Axial Feed}) * 60$q$, 13, false),
    (v_id, $q$Finish Pass Time$q$, $q$Finish Pass Time (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Grind Length} / ({Spindle Speed} * {Finish Axial Feed}) * 60$q$, 14, false),
    (v_id, $q$Time per Surface$q$, $q$Time per Surface (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Rough Passes} * {Rough Pass Time} + {Finish Pass Time}$q$, 15, false),
    (v_id, $q$Cycle Time$q$, $q$Cycle Time (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Time per Surface} * {Surfaces}$q$, 16, false);

  INSERT INTO public.process_calculator_mappings
    (process_group, process_route, operation, calculator_id, calculator_name, is_active, display_order, machine_class, canonical_process_id)
  SELECT 'Machining', s.station, $q$Internal Grinding$q$, v_id, $q$Machining - Internal Grinding$q$, true, 710, s.cls,
         (SELECT pt.id FROM public.process_taxonomy pt WHERE pt.process_group = 'Machining' AND pt.process_name = s.station LIMIT 1)
  FROM (VALUES ($q$internal_grinder$q$, $q$Internal Grinder$q$)) AS s(cls, station)
  ON CONFLICT (process_group, process_route, operation) DO UPDATE
  SET calculator_id = EXCLUDED.calculator_id,
      calculator_name = EXCLUDED.calculator_name,
      machine_class = EXCLUDED.machine_class,
      is_active = true,
      canonical_process_id = EXCLUDED.canonical_process_id;
END
$calc$;

-- Machining - Jig Grind
DO $calc$
DECLARE v_id UUID;
BEGIN
  SELECT id INTO v_id FROM public.calculators WHERE name = $q$Machining - Jig Grind$q$ AND user_id IS NULL AND retired_at IS NULL;
  IF v_id IS NULL THEN
    INSERT INTO public.calculators (user_id, name, calc_category, calculator_type, is_template, is_public, is_global, description)
    VALUES (NULL, $q$Machining - Jig Grind$q$, 'process', 'single', false, true, true, $q$Jig grinding of a hardened bore: traverse bore-grinding values (tblInternalGrinding; memory/ has no jig-grinding table) repeated the number of passes tblGtolProcessCapabilities gives for jig grinding.$q$)
    RETURNING id INTO v_id;
  ELSE
    UPDATE public.calculators SET description = $q$Jig grinding of a hardened bore: traverse bore-grinding values (tblInternalGrinding; memory/ has no jig-grinding table) repeated the number of passes tblGtolProcessCapabilities gives for jig grinding.$q$, updated_at = now() WHERE id = v_id;
  END IF;

  DELETE FROM public.calculator_fields WHERE calculator_id = v_id;
  INSERT INTO public.calculator_fields
    (calculator_id, field_name, display_label, field_type, unit, data_source, source_table, source_field, default_value, display_order, is_required)
  VALUES
    (v_id, $q$Grind Diameter$q$, $q$Grind Diameter (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 1, true),
    (v_id, $q$Grind Length$q$, $q$Grind Length (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 2, true),
    (v_id, $q$Surfaces$q$, $q$Surfaces$q$, $q$number$q$, NULL, NULL, NULL, NULL, NULL, 3, true),
    (v_id, $q$Repetitions$q$, $q$Repetitions$q$, $q$number$q$, NULL, $q$machining_lookup$q$, $q$tblGtolProcessCapabilities$q$, $q$Num Repetitions$q$, NULL, 4, true),
    (v_id, $q$Grinding Allowance$q$, $q$Grinding Allowance (mm)$q$, $q$number$q$, $q$mm$q$, $q$machining_lookup$q$, $q$variables$q$, $q$value$q$, NULL, 5, true),
    (v_id, $q$Work Speed$q$, $q$Work Speed (m/min)$q$, $q$number$q$, $q$m/min$q$, $q$machining_lookup$q$, $q$tblInternalGrinding$q$, $q$Work Speed (m / min)$q$, NULL, 6, true),
    (v_id, $q$Rough Infeed$q$, $q$Rough Infeed (mm)$q$, $q$number$q$, $q$mm$q$, $q$machining_lookup$q$, $q$tblInternalGrinding$q$, $q$Rough Infeed (mm)$q$, NULL, 7, true),
    (v_id, $q$Finish Infeed$q$, $q$Finish Infeed (mm)$q$, $q$number$q$, $q$mm$q$, $q$machining_lookup$q$, $q$tblInternalGrinding$q$, $q$Finish Infeed (mm)$q$, NULL, 8, true),
    (v_id, $q$Rough Axial Feed$q$, $q$Rough Axial Feed (mm/rev)$q$, $q$number$q$, $q$mm/rev$q$, $q$machining_lookup$q$, $q$tblInternalGrinding$q$, $q$Rough Axial Feed (rev^-1)$q$, NULL, 9, true),
    (v_id, $q$Finish Axial Feed$q$, $q$Finish Axial Feed (mm/rev)$q$, $q$number$q$, $q$mm/rev$q$, $q$machining_lookup$q$, $q$tblInternalGrinding$q$, $q$Finish Axial Feed (rev^-1)$q$, NULL, 10, true),
    (v_id, $q$Spindle Speed$q$, $q$Spindle Speed (rpm)$q$, $q$calculated$q$, $q$rpm$q$, NULL, NULL, NULL, $q${Work Speed} * 1000 / (pi * {Grind Diameter})$q$, 11, false),
    (v_id, $q$Finish Stock$q$, $q$Finish Stock (mm)$q$, $q$calculated$q$, $q$mm$q$, NULL, NULL, NULL, $q$min({Finish Infeed}, {Grinding Allowance})$q$, 12, false),
    (v_id, $q$Rough Passes$q$, $q$Rough Passes$q$, $q$calculated$q$, NULL, NULL, NULL, NULL, $q$round(max({Grinding Allowance} - {Finish Stock}, 0) / {Rough Infeed})$q$, 13, false),
    (v_id, $q$Rough Pass Time$q$, $q$Rough Pass Time (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Grind Length} / ({Spindle Speed} * {Rough Axial Feed}) * 60$q$, 14, false),
    (v_id, $q$Finish Pass Time$q$, $q$Finish Pass Time (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Grind Length} / ({Spindle Speed} * {Finish Axial Feed}) * 60$q$, 15, false),
    (v_id, $q$Time per Surface$q$, $q$Time per Surface (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Rough Passes} * {Rough Pass Time} + {Finish Pass Time}$q$, 16, false),
    (v_id, $q$Cycle Time$q$, $q$Cycle Time (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Time per Surface} * {Repetitions} * {Surfaces}$q$, 17, false);

  INSERT INTO public.process_calculator_mappings
    (process_group, process_route, operation, calculator_id, calculator_name, is_active, display_order, machine_class, canonical_process_id)
  SELECT 'Machining', s.station, $q$Jig Grind$q$, v_id, $q$Machining - Jig Grind$q$, true, 711, s.cls,
         (SELECT pt.id FROM public.process_taxonomy pt WHERE pt.process_group = 'Machining' AND pt.process_name = s.station LIMIT 1)
  FROM (VALUES ($q$jig_grind$q$, $q$Jig Grind$q$)) AS s(cls, station)
  ON CONFLICT (process_group, process_route, operation) DO UPDATE
  SET calculator_id = EXCLUDED.calculator_id,
      calculator_name = EXCLUDED.calculator_name,
      machine_class = EXCLUDED.machine_class,
      is_active = true,
      canonical_process_id = EXCLUDED.canonical_process_id;
END
$calc$;

-- Machining - Surface Grinding
DO $calc$
DECLARE v_id UUID;
BEGIN
  SELECT id INTO v_id FROM public.calculators WHERE name = $q$Machining - Surface Grinding$q$ AND user_id IS NULL AND retired_at IS NULL;
  IF v_id IS NULL THEN
    INSERT INTO public.calculators (user_id, name, calc_category, calculator_type, is_template, is_public, is_global, description)
    VALUES (NULL, $q$Machining - Surface Grinding$q$, 'process', 'single', false, true, true, $q$Traverse surface grinding of a flat face on a reciprocating grinder: CAD face length and width, grinding allowance (variables finishGrindingDepth), table speed, down-feeds and crossfeed from tblReciprocatingSurfaceGrinding (crossfeed capped at its fraction of the tblGrinding wheel width). Each pass strokes the face length once per crossfeed step across its width.$q$)
    RETURNING id INTO v_id;
  ELSE
    UPDATE public.calculators SET description = $q$Traverse surface grinding of a flat face on a reciprocating grinder: CAD face length and width, grinding allowance (variables finishGrindingDepth), table speed, down-feeds and crossfeed from tblReciprocatingSurfaceGrinding (crossfeed capped at its fraction of the tblGrinding wheel width). Each pass strokes the face length once per crossfeed step across its width.$q$, updated_at = now() WHERE id = v_id;
  END IF;

  DELETE FROM public.calculator_fields WHERE calculator_id = v_id;
  INSERT INTO public.calculator_fields
    (calculator_id, field_name, display_label, field_type, unit, data_source, source_table, source_field, default_value, display_order, is_required)
  VALUES
    (v_id, $q$Grind Length$q$, $q$Grind Length (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 1, true),
    (v_id, $q$Grind Width$q$, $q$Grind Width (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 2, true),
    (v_id, $q$Faces$q$, $q$Faces$q$, $q$number$q$, NULL, NULL, NULL, NULL, NULL, 3, true),
    (v_id, $q$Grinding Allowance$q$, $q$Grinding Allowance (mm)$q$, $q$number$q$, $q$mm$q$, $q$machining_lookup$q$, $q$variables$q$, $q$value$q$, NULL, 4, true),
    (v_id, $q$Table Speed$q$, $q$Table Speed (m/min)$q$, $q$number$q$, $q$m/min$q$, $q$machining_lookup$q$, $q$tblReciprocatingSurfaceGrinding$q$, $q$TableSpeedMPerMin$q$, NULL, 5, true),
    (v_id, $q$Rough Downfeed$q$, $q$Rough Downfeed (mm)$q$, $q$number$q$, $q$mm$q$, $q$machining_lookup$q$, $q$tblReciprocatingSurfaceGrinding$q$, $q$RoughDownfeedMm$q$, NULL, 6, true),
    (v_id, $q$Finish Downfeed$q$, $q$Finish Downfeed (mm)$q$, $q$number$q$, $q$mm$q$, $q$machining_lookup$q$, $q$tblReciprocatingSurfaceGrinding$q$, $q$FinishDownfeedMm$q$, NULL, 7, true),
    (v_id, $q$Crossfeed$q$, $q$Crossfeed (mm)$q$, $q$number$q$, $q$mm$q$, $q$machining_lookup$q$, $q$tblReciprocatingSurfaceGrinding$q$, $q$AbsoluteCrossfeedMm$q$, NULL, 8, true),
    (v_id, $q$Finish Stock$q$, $q$Finish Stock (mm)$q$, $q$calculated$q$, $q$mm$q$, NULL, NULL, NULL, $q$min({Finish Downfeed}, {Grinding Allowance})$q$, 9, false),
    (v_id, $q$Rough Passes$q$, $q$Rough Passes$q$, $q$calculated$q$, NULL, NULL, NULL, NULL, $q$round(max({Grinding Allowance} - {Finish Stock}, 0) / {Rough Downfeed})$q$, 10, false),
    (v_id, $q$Strokes per Pass$q$, $q$Strokes per Pass$q$, $q$calculated$q$, NULL, NULL, NULL, NULL, $q$CEIL({Grind Width} / {Crossfeed})$q$, 11, false),
    (v_id, $q$Stroke Time$q$, $q$Stroke Time (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Grind Length} / ({Table Speed} * 1000 / 60)$q$, 12, false),
    (v_id, $q$Time per Face$q$, $q$Time per Face (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q$({Rough Passes} + 1) * {Strokes per Pass} * {Stroke Time}$q$, 13, false),
    (v_id, $q$Cycle Time$q$, $q$Cycle Time (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Time per Face} * {Faces}$q$, 14, false);

  INSERT INTO public.process_calculator_mappings
    (process_group, process_route, operation, calculator_id, calculator_name, is_active, display_order, machine_class, canonical_process_id)
  SELECT 'Machining', s.station, $q$Surface Grinding$q$, v_id, $q$Machining - Surface Grinding$q$, true, 712, s.cls,
         (SELECT pt.id FROM public.process_taxonomy pt WHERE pt.process_group = 'Machining' AND pt.process_name = s.station LIMIT 1)
  FROM (VALUES ($q$reciprocating_surface_grinder$q$, $q$Reciprocating Surface Grinder$q$)) AS s(cls, station)
  ON CONFLICT (process_group, process_route, operation) DO UPDATE
  SET calculator_id = EXCLUDED.calculator_id,
      calculator_name = EXCLUDED.calculator_name,
      machine_class = EXCLUDED.machine_class,
      is_active = true,
      canonical_process_id = EXCLUDED.canonical_process_id;
END
$calc$;

-- Machining - Keyway Broaching
DO $calc$
DECLARE v_id UUID;
BEGIN
  SELECT id INTO v_id FROM public.calculators WHERE name = $q$Machining - Keyway Broaching$q$ AND user_id IS NULL AND retired_at IS NULL;
  IF v_id IS NULL THEN
    INSERT INTO public.calculators (user_id, name, calc_category, calculator_type, is_template, is_public, is_global, description)
    VALUES (NULL, $q$Machining - Keyway Broaching$q$, 'process', 'single', false, true, true, $q$Keyway broaching with the reference broach for the keyway width and length: a pull-type broach (single pass) when one fits, else a shim-type broach (one pass per shim plus the first). Each pass strokes the broach (teeth x pitch) plus the keyway length at the broach cutting speed; the broach is repositioned between passes (variables).$q$)
    RETURNING id INTO v_id;
  ELSE
    UPDATE public.calculators SET description = $q$Keyway broaching with the reference broach for the keyway width and length: a pull-type broach (single pass) when one fits, else a shim-type broach (one pass per shim plus the first). Each pass strokes the broach (teeth x pitch) plus the keyway length at the broach cutting speed; the broach is repositioned between passes (variables).$q$, updated_at = now() WHERE id = v_id;
  END IF;

  DELETE FROM public.calculator_fields WHERE calculator_id = v_id;
  INSERT INTO public.calculator_fields
    (calculator_id, field_name, display_label, field_type, unit, data_source, source_table, source_field, default_value, display_order, is_required)
  VALUES
    (v_id, $q$Keyway Length$q$, $q$Keyway Length (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 1, true),
    (v_id, $q$Keyway Width$q$, $q$Keyway Width (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 2, true),
    (v_id, $q$Keyways$q$, $q$Keyways$q$, $q$number$q$, NULL, NULL, NULL, NULL, NULL, 3, true),
    (v_id, $q$Broach Teeth$q$, $q$Broach Teeth$q$, $q$number$q$, NULL, $q$machining_lookup$q$, $q$tblPullTypeKeywayBroach$q$, $q$Teeth$q$, NULL, 4, true),
    (v_id, $q$Broach Pitch$q$, $q$Broach Pitch (mm)$q$, $q$number$q$, $q$mm$q$, $q$machining_lookup$q$, $q$tblPullTypeKeywayBroach$q$, $q$Pitch (mm)$q$, NULL, 5, true),
    (v_id, $q$Cutting Speed$q$, $q$Cutting Speed (m/min)$q$, $q$number$q$, $q$m/min$q$, $q$machining_lookup$q$, $q$tblPullTypeKeywayBroach$q$, $q$Cutting Speed (m / min)$q$, NULL, 6, true),
    (v_id, $q$Passes$q$, $q$Passes$q$, $q$number$q$, NULL, $q$machining_lookup$q$, $q$tblPullTypeKeywayBroach$q$, $q$Passes$q$, NULL, 7, true),
    (v_id, $q$Positioning Time$q$, $q$Positioning Time (s)$q$, $q$number$q$, $q$s$q$, $q$machining_lookup$q$, $q$variables$q$, $q$value$q$, NULL, 8, true),
    (v_id, $q$Broach Length$q$, $q$Broach Length (mm)$q$, $q$calculated$q$, $q$mm$q$, NULL, NULL, NULL, $q${Broach Teeth} * {Broach Pitch}$q$, 9, false),
    (v_id, $q$Stroke Time$q$, $q$Stroke Time (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q$({Broach Length} + {Keyway Length}) / ({Cutting Speed} * 1000 / 60)$q$, 10, false),
    (v_id, $q$Time per Keyway$q$, $q$Time per Keyway (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Passes} * {Stroke Time} + ({Passes} - 1) * {Positioning Time}$q$, 11, false),
    (v_id, $q$Cycle Time$q$, $q$Cycle Time (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Time per Keyway} * {Keyways}$q$, 12, false);

  INSERT INTO public.process_calculator_mappings
    (process_group, process_route, operation, calculator_id, calculator_name, is_active, display_order, machine_class, canonical_process_id)
  SELECT 'Machining', s.station, $q$Keyway Broaching$q$, v_id, $q$Machining - Keyway Broaching$q$, true, 713, s.cls,
         (SELECT pt.id FROM public.process_taxonomy pt WHERE pt.process_group = 'Machining' AND pt.process_name = s.station LIMIT 1)
  FROM (VALUES ($q$broach$q$, $q$Broach$q$)) AS s(cls, station)
  ON CONFLICT (process_group, process_route, operation) DO UPDATE
  SET calculator_id = EXCLUDED.calculator_id,
      calculator_name = EXCLUDED.calculator_name,
      machine_class = EXCLUDED.machine_class,
      is_active = true,
      canonical_process_id = EXCLUDED.canonical_process_id;
END
$calc$;

-- Machining - Wire EDM
DO $calc$
DECLARE v_id UUID;
BEGIN
  SELECT id INTO v_id FROM public.calculators WHERE name = $q$Machining - Wire EDM$q$ AND user_id IS NULL AND retired_at IS NULL;
  IF v_id IS NULL THEN
    INSERT INTO public.calculators (user_id, name, calc_category, calculator_type, is_template, is_public, is_global, description)
    VALUES (NULL, $q$Machining - Wire EDM$q$, 'process', 'single', false, true, true, $q$One roughing and one finishing wire pass over the CAD cut path, feed rates from tblWireEDMing.$q$)
    RETURNING id INTO v_id;
  ELSE
    UPDATE public.calculators SET description = $q$One roughing and one finishing wire pass over the CAD cut path, feed rates from tblWireEDMing.$q$, updated_at = now() WHERE id = v_id;
  END IF;

  DELETE FROM public.calculator_fields WHERE calculator_id = v_id;
  INSERT INTO public.calculator_fields
    (calculator_id, field_name, display_label, field_type, unit, data_source, source_table, source_field, default_value, display_order, is_required)
  VALUES
    (v_id, $q$Cut Length$q$, $q$Cut Length (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 1, true),
    (v_id, $q$Cuts$q$, $q$Cuts$q$, $q$number$q$, NULL, NULL, NULL, NULL, NULL, 2, true),
    (v_id, $q$Rough Feed Rate$q$, $q$Rough Feed Rate (mm/min)$q$, $q$number$q$, $q$mm/min$q$, $q$machining_lookup$q$, $q$tblWireEDMing$q$, $q$FeedRateMmPerMin$q$, NULL, 3, true),
    (v_id, $q$Finish Feed Rate$q$, $q$Finish Feed Rate (mm/min)$q$, $q$number$q$, $q$mm/min$q$, $q$machining_lookup$q$, $q$tblWireEDMing$q$, $q$FeedRateMmPerMin$q$, NULL, 4, true),
    (v_id, $q$Rough Pass Time$q$, $q$Rough Pass Time (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Cut Length} / {Rough Feed Rate} * 60$q$, 5, false),
    (v_id, $q$Finish Pass Time$q$, $q$Finish Pass Time (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Cut Length} / {Finish Feed Rate} * 60$q$, 6, false),
    (v_id, $q$Cycle Time$q$, $q$Cycle Time (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q$({Rough Pass Time} + {Finish Pass Time}) * {Cuts}$q$, 7, false);

  INSERT INTO public.process_calculator_mappings
    (process_group, process_route, operation, calculator_id, calculator_name, is_active, display_order, machine_class, canonical_process_id)
  SELECT 'Machining', s.station, $q$Wire EDM$q$, v_id, $q$Machining - Wire EDM$q$, true, 714, s.cls,
         (SELECT pt.id FROM public.process_taxonomy pt WHERE pt.process_group = 'Machining' AND pt.process_name = s.station LIMIT 1)
  FROM (VALUES ($q$wire_edm$q$, $q$Wire EDM$q$)) AS s(cls, station)
  ON CONFLICT (process_group, process_route, operation) DO UPDATE
  SET calculator_id = EXCLUDED.calculator_id,
      calculator_name = EXCLUDED.calculator_name,
      machine_class = EXCLUDED.machine_class,
      is_active = true,
      canonical_process_id = EXCLUDED.canonical_process_id;
END
$calc$;

-- Machining - Deburring
DO $calc$
DECLARE v_id UUID;
BEGIN
  SELECT id INTO v_id FROM public.calculators WHERE name = $q$Machining - Deburring$q$ AND user_id IS NULL AND retired_at IS NULL;
  IF v_id IS NULL THEN
    INSERT INTO public.calculators (user_id, name, calc_category, calculator_type, is_template, is_public, is_global, description)
    VALUES (NULL, $q$Machining - Deburring$q$, 'process', 'single', false, true, true, $q$Deburring every sharp edge: CAD sharp-edge length (seams and tangent edges excluded) at the tblDeburring edge speed for the material.$q$)
    RETURNING id INTO v_id;
  ELSE
    UPDATE public.calculators SET description = $q$Deburring every sharp edge: CAD sharp-edge length (seams and tangent edges excluded) at the tblDeburring edge speed for the material.$q$, updated_at = now() WHERE id = v_id;
  END IF;

  DELETE FROM public.calculator_fields WHERE calculator_id = v_id;
  INSERT INTO public.calculator_fields
    (calculator_id, field_name, display_label, field_type, unit, data_source, source_table, source_field, default_value, display_order, is_required)
  VALUES
    (v_id, $q$Sharp Edge Length$q$, $q$Sharp Edge Length (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 1, true),
    (v_id, $q$Edge Speed$q$, $q$Edge Speed (mm/s)$q$, $q$number$q$, $q$mm/s$q$, $q$machining_lookup$q$, $q$tblDeburring$q$, $q$linear_speed_mm_s$q$, NULL, 2, true),
    (v_id, $q$Cycle Time$q$, $q$Cycle Time (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Sharp Edge Length} / {Edge Speed}$q$, 3, false);

  INSERT INTO public.process_calculator_mappings
    (process_group, process_route, operation, calculator_id, calculator_name, is_active, display_order, machine_class, canonical_process_id)
  SELECT 'Machining', s.station, $q$Deburring$q$, v_id, $q$Machining - Deburring$q$, true, 715, s.cls,
         (SELECT pt.id FROM public.process_taxonomy pt WHERE pt.process_group = 'Machining' AND pt.process_name = s.station LIMIT 1)
  FROM (VALUES ($q$manual_deburr$q$, $q$Manual Deburr$q$)) AS s(cls, station)
  ON CONFLICT (process_group, process_route, operation) DO UPDATE
  SET calculator_id = EXCLUDED.calculator_id,
      calculator_name = EXCLUDED.calculator_name,
      machine_class = EXCLUDED.machine_class,
      is_active = true,
      canonical_process_id = EXCLUDED.canonical_process_id;
END
$calc$;

-- Machining - Index Transfer
DO $calc$
DECLARE v_id UUID;
BEGIN
  SELECT id INTO v_id FROM public.calculators WHERE name = $q$Machining - Index Transfer$q$ AND user_id IS NULL AND retired_at IS NULL;
  IF v_id IS NULL THEN
    INSERT INTO public.calculators (user_id, name, calc_category, calculator_type, is_template, is_public, is_global, description)
    VALUES (NULL, $q$Machining - Index Transfer$q$, 'process', 'single', false, true, true, $q$Multi-spindle index cycle per part: drum index, transfer, stock feed and speed synchronisation times from the machine record.$q$)
    RETURNING id INTO v_id;
  ELSE
    UPDATE public.calculators SET description = $q$Multi-spindle index cycle per part: drum index, transfer, stock feed and speed synchronisation times from the machine record.$q$, updated_at = now() WHERE id = v_id;
  END IF;

  DELETE FROM public.calculator_fields WHERE calculator_id = v_id;
  INSERT INTO public.calculator_fields
    (calculator_id, field_name, display_label, field_type, unit, data_source, source_table, source_field, default_value, display_order, is_required)
  VALUES
    (v_id, $q$Drum Index Time$q$, $q$Drum Index Time (s)$q$, $q$number$q$, $q$s$q$, NULL, NULL, NULL, NULL, 1, true),
    (v_id, $q$Transfer Time$q$, $q$Transfer Time (s)$q$, $q$number$q$, $q$s$q$, NULL, NULL, NULL, NULL, 2, true),
    (v_id, $q$Stock Feed Time$q$, $q$Stock Feed Time (s)$q$, $q$number$q$, $q$s$q$, NULL, NULL, NULL, NULL, 3, true),
    (v_id, $q$Speed Synchronization Time$q$, $q$Speed Synchronization Time (s)$q$, $q$number$q$, $q$s$q$, NULL, NULL, NULL, NULL, 4, true),
    (v_id, $q$Cycle Time$q$, $q$Cycle Time (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Drum Index Time} + {Transfer Time} + {Stock Feed Time} + {Speed Synchronization Time}$q$, 5, false);

  INSERT INTO public.process_calculator_mappings
    (process_group, process_route, operation, calculator_id, calculator_name, is_active, display_order, machine_class, canonical_process_id)
  SELECT 'Machining', s.station, $q$Index Transfer$q$, v_id, $q$Machining - Index Transfer$q$, true, 716, s.cls,
         (SELECT pt.id FROM public.process_taxonomy pt WHERE pt.process_group = 'Machining' AND pt.process_name = s.station LIMIT 1)
  FROM (VALUES ($q$simultaneous_turning$q$, $q$Simultaneous Turning$q$)) AS s(cls, station)
  ON CONFLICT (process_group, process_route, operation) DO UPDATE
  SET calculator_id = EXCLUDED.calculator_id,
      calculator_name = EXCLUDED.calculator_name,
      machine_class = EXCLUDED.machine_class,
      is_active = true,
      canonical_process_id = EXCLUDED.canonical_process_id;
END
$calc$;

-- Machining - Secondary Setup
DO $calc$
DECLARE v_id UUID;
BEGIN
  SELECT id INTO v_id FROM public.calculators WHERE name = $q$Machining - Secondary Setup$q$ AND user_id IS NULL AND retired_at IS NULL;
  IF v_id IS NULL THEN
    INSERT INTO public.calculators (user_id, name, calc_category, calculator_type, is_template, is_public, is_global, description)
    VALUES (NULL, $q$Machining - Secondary Setup$q$, 'process', 'single', false, true, true, $q$A second chucking for features a 2-axis lathe cannot reach in one setup: workholder install-and-remove time from tblInstallingTurningWorkholders, spread over the batch.$q$)
    RETURNING id INTO v_id;
  ELSE
    UPDATE public.calculators SET description = $q$A second chucking for features a 2-axis lathe cannot reach in one setup: workholder install-and-remove time from tblInstallingTurningWorkholders, spread over the batch.$q$, updated_at = now() WHERE id = v_id;
  END IF;

  DELETE FROM public.calculator_fields WHERE calculator_id = v_id;
  INSERT INTO public.calculator_fields
    (calculator_id, field_name, display_label, field_type, unit, data_source, source_table, source_field, default_value, display_order, is_required)
  VALUES
    (v_id, $q$Workholder Install and Remove Time$q$, $q$Workholder Install and Remove Time (min)$q$, $q$number$q$, $q$min$q$, $q$machining_lookup$q$, $q$tblInstallingTurningWorkholders$q$, $q$Install And Remove Time (min)$q$, NULL, 1, true),
    (v_id, $q$Batch Size$q$, $q$Batch Size$q$, $q$number$q$, NULL, NULL, NULL, NULL, NULL, 2, true),
    (v_id, $q$Cycle Time$q$, $q$Cycle Time (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Workholder Install and Remove Time} * 60 / {Batch Size}$q$, 3, false);

  INSERT INTO public.process_calculator_mappings
    (process_group, process_route, operation, calculator_id, calculator_name, is_active, display_order, machine_class, canonical_process_id)
  SELECT 'Machining', s.station, $q$Secondary Setup (Rechuck)$q$, v_id, $q$Machining - Secondary Setup$q$, true, 717, s.cls,
         (SELECT pt.id FROM public.process_taxonomy pt WHERE pt.process_group = 'Machining' AND pt.process_name = s.station LIMIT 1)
  FROM (VALUES ($q$2_axis_lathe$q$, $q$2 Axis Lathe$q$), ($q$3_axis_lathe$q$, $q$3 Axis Lathe$q$), ($q$2_axis_bar_feed_lathe_with_sub_spindle$q$, $q$2 Axis Bar Feed Lathe with Sub Spindle$q$), ($q$3_axis_bar_feed_lathe_with_sub_spindle$q$, $q$3 Axis Bar Feed Lathe with Sub Spindle$q$), ($q$simultaneous_turning$q$, $q$Simultaneous Turning$q$), ($q$machining_millturn$q$, $q$MillTurn$q$)) AS s(cls, station)
  ON CONFLICT (process_group, process_route, operation) DO UPDATE
  SET calculator_id = EXCLUDED.calculator_id,
      calculator_name = EXCLUDED.calculator_name,
      machine_class = EXCLUDED.machine_class,
      is_active = true,
      canonical_process_id = EXCLUDED.canonical_process_id;
END
$calc$;

-- Machining - Inspection
DO $calc$
DECLARE v_id UUID;
BEGIN
  SELECT id INTO v_id FROM public.calculators WHERE name = $q$Machining - Inspection$q$ AND user_id IS NULL AND retired_at IS NULL;
  IF v_id IS NULL THEN
    INSERT INTO public.calculators (user_id, name, calc_category, calculator_type, is_template, is_public, is_global, description)
    VALUES (NULL, $q$Machining - Inspection$q$, 'process', 'single', false, true, true, $q$Inspection time per part: per-piece measurement (allowances are database defaults — no reference source maps features to tblInspection analyses), spread over first-article / in-process / final sampling.$q$)
    RETURNING id INTO v_id;
  ELSE
    UPDATE public.calculators SET description = $q$Inspection time per part: per-piece measurement (allowances are database defaults — no reference source maps features to tblInspection analyses), spread over first-article / in-process / final sampling.$q$, updated_at = now() WHERE id = v_id;
  END IF;

  DELETE FROM public.calculator_fields WHERE calculator_id = v_id;
  INSERT INTO public.calculator_fields
    (calculator_id, field_name, display_label, field_type, unit, data_source, source_table, source_field, default_value, display_order, is_required)
  VALUES
    (v_id, $q$Holes$q$, $q$Holes$q$, $q$number$q$, NULL, NULL, NULL, NULL, NULL, 1, true),
    (v_id, $q$Threads$q$, $q$Threads$q$, $q$number$q$, NULL, NULL, NULL, NULL, NULL, 2, true),
    (v_id, $q$Tightest Tolerance$q$, $q$Tightest Tolerance (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 3, true),
    (v_id, $q$GDT Time$q$, $q$GDT Time (min)$q$, $q$number$q$, $q$min$q$, NULL, NULL, NULL, NULL, 4, true),
    (v_id, $q$Batch Size$q$, $q$Batch Size$q$, $q$number$q$, NULL, NULL, NULL, NULL, NULL, 5, true),
    (v_id, $q$First Article Pieces$q$, $q$First Article Pieces$q$, $q$number$q$, NULL, NULL, NULL, NULL, NULL, 6, true),
    (v_id, $q$In-process 1 in N$q$, $q$In-process 1 in N$q$, $q$number$q$, NULL, NULL, NULL, NULL, NULL, 7, true),
    (v_id, $q$Final Check 1 in N$q$, $q$Final Check 1 in N$q$, $q$number$q$, NULL, NULL, NULL, NULL, NULL, 8, true),
    (v_id, $q$Final Check Time$q$, $q$Final Check Time (min)$q$, $q$number$q$, $q$min$q$, NULL, NULL, NULL, NULL, 9, true),
    (v_id, $q$Positioning Time$q$, $q$Positioning Time (min)$q$, $q$number$q$, $q$min$q$, NULL, NULL, NULL, $q$5$q$, 10, true),
    (v_id, $q$Hole Sample Rate$q$, $q$Hole Sample Rate$q$, $q$number$q$, NULL, NULL, NULL, NULL, $q$5$q$, 11, true),
    (v_id, $q$Max Holes Sampled$q$, $q$Max Holes Sampled$q$, $q$number$q$, NULL, NULL, NULL, NULL, $q$15$q$, 12, true),
    (v_id, $q$Time per Sampled Hole$q$, $q$Time per Sampled Hole (min)$q$, $q$number$q$, $q$min$q$, NULL, NULL, NULL, $q$0.5$q$, 13, true),
    (v_id, $q$Max Threads Checked$q$, $q$Max Threads Checked$q$, $q$number$q$, NULL, NULL, NULL, NULL, $q$6$q$, 14, true),
    (v_id, $q$Time per Thread Gauge$q$, $q$Time per Thread Gauge (min)$q$, $q$number$q$, $q$min$q$, NULL, NULL, NULL, $q$0.4$q$, 15, true),
    (v_id, $q$Tight Tolerance Threshold$q$, $q$Tight Tolerance Threshold (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, $q$0.05$q$, 16, true),
    (v_id, $q$Tight Tolerance CMM Time$q$, $q$Tight Tolerance CMM Time (min)$q$, $q$number$q$, $q$min$q$, NULL, NULL, NULL, $q$8$q$, 17, true),
    (v_id, $q$Holes Sampled$q$, $q$Holes Sampled$q$, $q$calculated$q$, NULL, NULL, NULL, NULL, $q$min(ceil({Holes} / {Hole Sample Rate}), {Max Holes Sampled})$q$, 18, false),
    (v_id, $q$Threads Checked$q$, $q$Threads Checked$q$, $q$calculated$q$, NULL, NULL, NULL, NULL, $q$min({Threads}, {Max Threads Checked})$q$, 19, false),
    (v_id, $q$Tight Tolerance Time$q$, $q$Tight Tolerance Time (min)$q$, $q$calculated$q$, $q$min$q$, NULL, NULL, NULL, $q$IF({Tightest Tolerance} > 0 and {Tightest Tolerance} <= {Tight Tolerance Threshold}, {Tight Tolerance CMM Time}, 0)$q$, 20, false),
    (v_id, $q$Inspection per Piece$q$, $q$Inspection per Piece (min)$q$, $q$calculated$q$, $q$min$q$, NULL, NULL, NULL, $q${Positioning Time} + {Holes Sampled} * {Time per Sampled Hole} + {Threads Checked} * {Time per Thread Gauge} + {Tight Tolerance Time} + {GDT Time}$q$, 21, false),
    (v_id, $q$In-process Pieces$q$, $q$In-process Pieces$q$, $q$calculated$q$, NULL, NULL, NULL, NULL, $q$floor(max({Batch Size} - {First Article Pieces}, 0) / {In-process 1 in N})$q$, 22, false),
    (v_id, $q$Final Check Pieces$q$, $q$Final Check Pieces$q$, $q$calculated$q$, NULL, NULL, NULL, NULL, $q$ceil({Batch Size} / {Final Check 1 in N})$q$, 23, false),
    (v_id, $q$Measured Minutes per Batch$q$, $q$Measured Minutes per Batch (min)$q$, $q$calculated$q$, $q$min$q$, NULL, NULL, NULL, $q${Inspection per Piece} * ({First Article Pieces} + {In-process Pieces}) + {Final Check Time} * {Final Check Pieces}$q$, 24, false),
    (v_id, $q$Cycle Time$q$, $q$Cycle Time (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Measured Minutes per Batch} / {Batch Size} * 60$q$, 25, false);

  INSERT INTO public.process_calculator_mappings
    (process_group, process_route, operation, calculator_id, calculator_name, is_active, display_order, machine_class, canonical_process_id)
  SELECT 'Machining', s.station, $q$Inspection$q$, v_id, $q$Machining - Inspection$q$, true, 718, s.cls,
         (SELECT pt.id FROM public.process_taxonomy pt WHERE pt.process_group = 'Machining' AND pt.process_name = s.station LIMIT 1)
  FROM (VALUES ($q$machining_inspection$q$, $q$Inspection$q$), ($q$special_inspection$q$, $q$Special Inspection$q$)) AS s(cls, station)
  ON CONFLICT (process_group, process_route, operation) DO UPDATE
  SET calculator_id = EXCLUDED.calculator_id,
      calculator_name = EXCLUDED.calculator_name,
      machine_class = EXCLUDED.machine_class,
      is_active = true,
      canonical_process_id = EXCLUDED.canonical_process_id;
END
$calc$;

-- Machining - Hobbing
DO $calc$
DECLARE v_id UUID;
BEGIN
  SELECT id INTO v_id FROM public.calculators WHERE name = $q$Machining - Hobbing$q$ AND user_id IS NULL AND retired_at IS NULL;
  IF v_id IS NULL THEN
    INSERT INTO public.calculators (user_id, name, calc_category, calculator_type, is_template, is_public, is_global, description)
    VALUES (NULL, $q$Machining - Hobbing$q$, 'process', 'single', false, true, true, $q$Hobbing a gear: CAD teeth, face width, module (tip diameter / (teeth + 2)) and tooth depth ((tip - root) / 2); ANSI hob diameter and starts (tblAnsiHobbing, variables defaultNumStarts); cutting speed and axial feed (tblHobbing). The hob travels the face width plus its approach (the chord of a hob of that diameter entering the tooth depth); the gear turns teeth / starts revolutions per hob revolution.$q$)
    RETURNING id INTO v_id;
  ELSE
    UPDATE public.calculators SET description = $q$Hobbing a gear: CAD teeth, face width, module (tip diameter / (teeth + 2)) and tooth depth ((tip - root) / 2); ANSI hob diameter and starts (tblAnsiHobbing, variables defaultNumStarts); cutting speed and axial feed (tblHobbing). The hob travels the face width plus its approach (the chord of a hob of that diameter entering the tooth depth); the gear turns teeth / starts revolutions per hob revolution.$q$, updated_at = now() WHERE id = v_id;
  END IF;

  DELETE FROM public.calculator_fields WHERE calculator_id = v_id;
  INSERT INTO public.calculator_fields
    (calculator_id, field_name, display_label, field_type, unit, data_source, source_table, source_field, default_value, display_order, is_required)
  VALUES
    (v_id, $q$Teeth$q$, $q$Teeth$q$, $q$number$q$, NULL, NULL, NULL, NULL, NULL, 1, true),
    (v_id, $q$Face Width$q$, $q$Face Width (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 2, true),
    (v_id, $q$Module$q$, $q$Module (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 3, true),
    (v_id, $q$Tooth Depth$q$, $q$Tooth Depth (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 4, true),
    (v_id, $q$Hob Diameter$q$, $q$Hob Diameter (mm)$q$, $q$number$q$, $q$mm$q$, $q$machining_lookup$q$, $q$tblAnsiHobbing$q$, $q$hob_diameter_mm$q$, NULL, 5, true),
    (v_id, $q$Starts$q$, $q$Starts$q$, $q$number$q$, NULL, $q$machining_lookup$q$, $q$variables$q$, $q$value$q$, NULL, 6, true),
    (v_id, $q$Cutting Speed$q$, $q$Cutting Speed (m/min)$q$, $q$number$q$, $q$m/min$q$, $q$machining_lookup$q$, $q$tblHobbing$q$, $q$Cutting Speed (m / min)$q$, NULL, 7, true),
    (v_id, $q$Axial Feed$q$, $q$Axial Feed (mm/rev)$q$, $q$number$q$, $q$mm/rev$q$, $q$machining_lookup$q$, $q$tblHobbing$q$, $q$Feed (mm / rev)$q$, NULL, 8, true),
    (v_id, $q$Hob Speed$q$, $q$Hob Speed (rpm)$q$, $q$calculated$q$, $q$rpm$q$, NULL, NULL, NULL, $q${Cutting Speed} * 1000 / (pi * {Hob Diameter})$q$, 9, false),
    (v_id, $q$Approach$q$, $q$Approach (mm)$q$, $q$calculated$q$, $q$mm$q$, NULL, NULL, NULL, $q$sqrt({Tooth Depth} * ({Hob Diameter} - {Tooth Depth}))$q$, 10, false),
    (v_id, $q$Axial Travel$q$, $q$Axial Travel (mm)$q$, $q$calculated$q$, $q$mm$q$, NULL, NULL, NULL, $q${Face Width} + {Approach}$q$, 11, false),
    (v_id, $q$Cycle Time$q$, $q$Cycle Time (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Axial Travel} * {Teeth} / ({Hob Speed} * {Starts} * {Axial Feed}) * 60$q$, 12, false);

  INSERT INTO public.process_calculator_mappings
    (process_group, process_route, operation, calculator_id, calculator_name, is_active, display_order, machine_class, canonical_process_id)
  SELECT 'Machining', s.station, $q$Hobbing$q$, v_id, $q$Machining - Hobbing$q$, true, 719, s.cls,
         (SELECT pt.id FROM public.process_taxonomy pt WHERE pt.process_group = 'Machining' AND pt.process_name = s.station LIMIT 1)
  FROM (VALUES ($q$hob_machine$q$, $q$Hob Machine$q$)) AS s(cls, station)
  ON CONFLICT (process_group, process_route, operation) DO UPDATE
  SET calculator_id = EXCLUDED.calculator_id,
      calculator_name = EXCLUDED.calculator_name,
      machine_class = EXCLUDED.machine_class,
      is_active = true,
      canonical_process_id = EXCLUDED.canonical_process_id;
END
$calc$;

-- Machining - Shaving
DO $calc$
DECLARE v_id UUID;
BEGIN
  SELECT id INTO v_id FROM public.calculators WHERE name = $q$Machining - Shaving$q$ AND user_id IS NULL AND retired_at IS NULL;
  IF v_id IS NULL THEN
    INSERT INTO public.calculators (user_id, name, calc_category, calculator_type, is_template, is_public, is_global, description)
    VALUES (NULL, $q$Machining - Shaving$q$, 'process', 'single', false, true, true, $q$Gear shaving after hobbing: CAD teeth, module and face width; strokes, cutting speed and feed per workpiece revolution from tblShaving; workpiece speed capped at variables maxShavingWorkpieceSpeed. Each stroke traverses the face width.$q$)
    RETURNING id INTO v_id;
  ELSE
    UPDATE public.calculators SET description = $q$Gear shaving after hobbing: CAD teeth, module and face width; strokes, cutting speed and feed per workpiece revolution from tblShaving; workpiece speed capped at variables maxShavingWorkpieceSpeed. Each stroke traverses the face width.$q$, updated_at = now() WHERE id = v_id;
  END IF;

  DELETE FROM public.calculator_fields WHERE calculator_id = v_id;
  INSERT INTO public.calculator_fields
    (calculator_id, field_name, display_label, field_type, unit, data_source, source_table, source_field, default_value, display_order, is_required)
  VALUES
    (v_id, $q$Teeth$q$, $q$Teeth$q$, $q$number$q$, NULL, NULL, NULL, NULL, NULL, 1, true),
    (v_id, $q$Module$q$, $q$Module (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 2, true),
    (v_id, $q$Face Width$q$, $q$Face Width (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 3, true),
    (v_id, $q$Strokes$q$, $q$Strokes$q$, $q$number$q$, NULL, $q$machining_lookup$q$, $q$tblShaving$q$, $q$Strokes$q$, NULL, 4, true),
    (v_id, $q$Cutting Speed$q$, $q$Cutting Speed (m/min)$q$, $q$number$q$, $q$m/min$q$, $q$machining_lookup$q$, $q$tblShaving$q$, $q$Cutting Speed (m / min)$q$, NULL, 5, true),
    (v_id, $q$Feed$q$, $q$Feed (mm/rev)$q$, $q$number$q$, $q$mm/rev$q$, $q$machining_lookup$q$, $q$tblShaving$q$, $q$Feed Per Rev (mm / rev)$q$, NULL, 6, true),
    (v_id, $q$Max Workpiece Speed$q$, $q$Max Workpiece Speed (rpm)$q$, $q$number$q$, $q$rpm$q$, $q$machining_lookup$q$, $q$variables$q$, $q$value$q$, NULL, 7, true),
    (v_id, $q$Pitch Diameter$q$, $q$Pitch Diameter (mm)$q$, $q$calculated$q$, $q$mm$q$, NULL, NULL, NULL, $q${Module} * {Teeth}$q$, 8, false),
    (v_id, $q$Workpiece Speed$q$, $q$Workpiece Speed (rpm)$q$, $q$calculated$q$, $q$rpm$q$, NULL, NULL, NULL, $q$min({Cutting Speed} * 1000 / (pi * {Pitch Diameter}), {Max Workpiece Speed})$q$, 9, false),
    (v_id, $q$Stroke Time$q$, $q$Stroke Time (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Face Width} / ({Feed} * {Workpiece Speed}) * 60$q$, 10, false),
    (v_id, $q$Cycle Time$q$, $q$Cycle Time (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Strokes} * {Stroke Time}$q$, 11, false);

  INSERT INTO public.process_calculator_mappings
    (process_group, process_route, operation, calculator_id, calculator_name, is_active, display_order, machine_class, canonical_process_id)
  SELECT 'Machining', s.station, $q$Shaving$q$, v_id, $q$Machining - Shaving$q$, true, 720, s.cls,
         (SELECT pt.id FROM public.process_taxonomy pt WHERE pt.process_group = 'Machining' AND pt.process_name = s.station LIMIT 1)
  FROM (VALUES ($q$shaver$q$, $q$Shaver$q$)) AS s(cls, station)
  ON CONFLICT (process_group, process_route, operation) DO UPDATE
  SET calculator_id = EXCLUDED.calculator_id,
      calculator_name = EXCLUDED.calculator_name,
      machine_class = EXCLUDED.machine_class,
      is_active = true,
      canonical_process_id = EXCLUDED.canonical_process_id;
END
$calc$;

-- Machining - Rotary Broaching
DO $calc$
DECLARE v_id UUID;
BEGIN
  SELECT id INTO v_id FROM public.calculators WHERE name = $q$Machining - Rotary Broaching$q$ AND user_id IS NULL AND retired_at IS NULL;
  IF v_id IS NULL THEN
    INSERT INTO public.calculators (user_id, name, calc_category, calculator_type, is_template, is_public, is_global, description)
    VALUES (NULL, $q$Machining - Rotary Broaching$q$, 'process', 'single', false, true, true, $q$Rotary broaching a polygon socket (drawing polygon callout + CAD polygon ring): depth from CAD; RPM and feed from tblRotaryBroaching (depth within the broach reach), feed calibrated by variables rotaryBroachFeedAdjustment. The pilot hole is priced by the Drilling calculator.$q$)
    RETURNING id INTO v_id;
  ELSE
    UPDATE public.calculators SET description = $q$Rotary broaching a polygon socket (drawing polygon callout + CAD polygon ring): depth from CAD; RPM and feed from tblRotaryBroaching (depth within the broach reach), feed calibrated by variables rotaryBroachFeedAdjustment. The pilot hole is priced by the Drilling calculator.$q$, updated_at = now() WHERE id = v_id;
  END IF;

  DELETE FROM public.calculator_fields WHERE calculator_id = v_id;
  INSERT INTO public.calculator_fields
    (calculator_id, field_name, display_label, field_type, unit, data_source, source_table, source_field, default_value, display_order, is_required)
  VALUES
    (v_id, $q$Polygon Depth$q$, $q$Polygon Depth (mm)$q$, $q$number$q$, $q$mm$q$, NULL, NULL, NULL, NULL, 1, true),
    (v_id, $q$Polygons$q$, $q$Polygons$q$, $q$number$q$, NULL, NULL, NULL, NULL, NULL, 2, true),
    (v_id, $q$RPM$q$, $q$RPM (rpm)$q$, $q$number$q$, $q$rpm$q$, $q$machining_lookup$q$, $q$tblRotaryBroaching$q$, $q$RPM$q$, NULL, 3, true),
    (v_id, $q$Feed$q$, $q$Feed (mm/rev)$q$, $q$number$q$, $q$mm/rev$q$, $q$machining_lookup$q$, $q$tblRotaryBroaching$q$, $q$FeedMmPerRev$q$, NULL, 4, true),
    (v_id, $q$Feed Adjustment$q$, $q$Feed Adjustment$q$, $q$number$q$, NULL, $q$machining_lookup$q$, $q$variables$q$, $q$value$q$, NULL, 5, true),
    (v_id, $q$Time per Polygon$q$, $q$Time per Polygon (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Polygon Depth} / ({RPM} * {Feed} * {Feed Adjustment}) * 60$q$, 6, false),
    (v_id, $q$Cycle Time$q$, $q$Cycle Time (s)$q$, $q$calculated$q$, $q$s$q$, NULL, NULL, NULL, $q${Time per Polygon} * {Polygons}$q$, 7, false);

  INSERT INTO public.process_calculator_mappings
    (process_group, process_route, operation, calculator_id, calculator_name, is_active, display_order, machine_class, canonical_process_id)
  SELECT 'Machining', s.station, $q$Rotary Broaching$q$, v_id, $q$Machining - Rotary Broaching$q$, true, 721, s.cls,
         (SELECT pt.id FROM public.process_taxonomy pt WHERE pt.process_group = 'Machining' AND pt.process_name = s.station LIMIT 1)
  FROM (VALUES ($q$2_axis_lathe$q$, $q$2 Axis Lathe$q$), ($q$3_axis_lathe$q$, $q$3 Axis Lathe$q$), ($q$2_axis_bar_feed_lathe_with_sub_spindle$q$, $q$2 Axis Bar Feed Lathe with Sub Spindle$q$), ($q$3_axis_bar_feed_lathe_with_sub_spindle$q$, $q$3 Axis Bar Feed Lathe with Sub Spindle$q$), ($q$simultaneous_turning$q$, $q$Simultaneous Turning$q$), ($q$machining_millturn$q$, $q$MillTurn$q$), ($q$3_axis_mill$q$, $q$3 Axis Mill$q$), ($q$4_axis_mill$q$, $q$4 Axis Mill$q$), ($q$5_axis_mill$q$, $q$5 Axis Mill$q$)) AS s(cls, station)
  ON CONFLICT (process_group, process_route, operation) DO UPDATE
  SET calculator_id = EXCLUDED.calculator_id,
      calculator_name = EXCLUDED.calculator_name,
      machine_class = EXCLUDED.machine_class,
      is_active = true,
      canonical_process_id = EXCLUDED.canonical_process_id;
END
$calc$;

-- Post-check: every calculator exists once, with all its fields and mappings.
DO $post$
DECLARE bad TEXT;
BEGIN
  SELECT string_agg(e.name, ', ') INTO bad
  FROM (VALUES
    ($q$Machining - Drilling$q$, 9, 9),
    ($q$Machining - Rough Turning$q$, 14, 6),
    ($q$Machining - Finish Turning$q$, 7, 6),
    ($q$Machining - Parting$q$, 7, 6),
    ($q$Machining - Reaming$q$, 9, 9),
    ($q$Machining - Rigid Tapping$q$, 9, 9),
    ($q$Machining - Jig Boring$q$, 10, 1),
    ($q$Machining - Gun Drilling$q$, 9, 1),
    ($q$Machining - Deep Bore$q$, 9, 1),
    ($q$Machining - Cylindrical Grinding$q$, 16, 1),
    ($q$Machining - Internal Grinding$q$, 16, 1),
    ($q$Machining - Jig Grind$q$, 17, 1),
    ($q$Machining - Surface Grinding$q$, 14, 1),
    ($q$Machining - Keyway Broaching$q$, 12, 1),
    ($q$Machining - Wire EDM$q$, 7, 1),
    ($q$Machining - Deburring$q$, 3, 1),
    ($q$Machining - Index Transfer$q$, 5, 1),
    ($q$Machining - Secondary Setup$q$, 3, 6),
    ($q$Machining - Inspection$q$, 25, 2),
    ($q$Machining - Hobbing$q$, 12, 1),
    ($q$Machining - Shaving$q$, 11, 1),
    ($q$Machining - Rotary Broaching$q$, 7, 9)
  ) AS e(name, field_count, mapping_count)
  LEFT JOIN public.calculators c ON c.name = e.name AND c.user_id IS NULL AND c.retired_at IS NULL
  WHERE c.id IS NULL
     OR (SELECT count(*) FROM public.calculator_fields f WHERE f.calculator_id = c.id) <> e.field_count
     OR (SELECT count(*) FROM public.process_calculator_mappings m WHERE m.calculator_id = c.id AND m.is_active) <> e.mapping_count;
  IF bad IS NOT NULL THEN
    RAISE EXCEPTION 'migration 804: calculators incomplete: %', bad;
  END IF;
END
$post$;

COMMIT;
