-- ============================================================================
-- Migration 806: Seed mhr_records with the real CMM Inspection machines
-- ============================================================================
-- Generated by scripts/gen_806_seed_cmm_inspection_mhr_records.js -- do not
-- hand-edit, re-run the generator and diff instead.
--
-- Source: memory/Secondary process/machines/cmm_inspection_machines.csv
-- (11 real USA machines). Restores the cost engine cmm class, which
-- migration 805 left with no machine in any location because every row that
-- served it had no memory/ source key.
--
-- MHR = Direct OH + Indirect OH (migration 581). LHR = the source labour rate.
-- wage_grade = 2 - Metal (memory/Secondary process/wage_grade_associations.csv).
-- process_group = Other Secondary Processes (the group migration 790 seeded
-- CMM Inspection under). process_family left NULL: not family-specific.
--
-- USA only: the source file carries no other location. Other locations stay
-- without a CMM rate until real memory/ data exists for them.
--
-- Idempotent: skips any (machine_class, location, machine_name) already present.
-- ============================================================================

INSERT INTO mhr_records (
  machine_class, location, machine_name, currency_code, country_code, source_type, process_group, operators, setup_time_hr, landed_machine_cost, direct_overhead_rate, indirect_overhead_rate, benchmark_direct_overhead_rate_usd_hr, benchmark_indirect_overhead_rate_usd_hr, total_machine_hour_rate, mhr_usd_per_hour, usd_labor_rate_per_hr, benchmark_labor_rate_usd_hr, usd_lhr_total, work_center_labor_rate_factor, labor_time_standard, wage_grade, machine_price_usd, machine_length_mm, machine_width_mm, footprint_allowance_factor, machine_power_kw, machine_life_yr, installation_factor_pct, machine_uptime_pct, annual_maintenance_factor_pct, salvage_value_factor_pct, supplies_cost_per_year, avg_utilization, good_part_yield, manufacturer_country, benchmark_source_key
)
SELECT v.* FROM (VALUES
  ($str$cmm$str$, $str$USA$str$, $str$Axiom Too 1200$str$, $str$USD$str$, $str$US$str$, $str$BENCHMARK$str$, $str$Other Secondary Processes$str$, 0.5, 0.5, 30627, 1.85, 14.06, 1.85, 14.06, 15.91, 15.91, 29.95, 29.95, 29.95, 1, 1, $str$2 - Metal$str$, 30627, 1200, 1130, 2, 0, 10, 20, 80, 5, 0, 0, 0, 1, $str$USA$str$, $str$CMM Inspection:Axiom Too 1200$str$),
  ($str$cmm$str$, $str$USA$str$, $str$Axiom Too 1500$str$, $str$USD$str$, $str$US$str$, $str$BENCHMARK$str$, $str$Other Secondary Processes$str$, 0.5, 0.5, 35175, 2.13, 14.12, 2.13, 14.12, 16.25, 16.25, 29.95, 29.95, 29.95, 1, 1, $str$2 - Metal$str$, 35175, 1500, 1130, 2, 0, 10, 20, 80, 5, 0, 0, 0, 1, $str$USA$str$, $str$CMM Inspection:Axiom Too 1500$str$),
  ($str$cmm$str$, $str$USA$str$, $str$Axiom Too 1800$str$, $str$USD$str$, $str$US$str$, $str$BENCHMARK$str$, $str$Other Secondary Processes$str$, 0.5, 0.5, 41327, 2.5, 14.18, 2.5, 14.18, 16.68, 16.68, 29.95, 29.95, 29.95, 1, 1, $str$2 - Metal$str$, 41327, 1800, 1130, 2, 0, 10, 20, 80, 5, 0, 0, 0, 1, $str$USA$str$, $str$CMM Inspection:Axiom Too 1800$str$),
  ($str$cmm$str$, $str$USA$str$, $str$Axiom Too 900$str$, $str$USD$str$, $str$US$str$, $str$BENCHMARK$str$, $str$Other Secondary Processes$str$, 0.5, 0.5, 26949, 1.63, 14.01, 1.63, 14.01, 15.64, 15.64, 29.95, 29.95, 29.95, 1, 1, $str$2 - Metal$str$, 26949, 900, 1130, 2, 0, 10, 20, 80, 5, 0, 0, 0, 1, $str$USA$str$, $str$CMM Inspection:Axiom Too 900$str$),
  ($str$cmm$str$, $str$USA$str$, $str$Axiom Xtreme 350$str$, $str$USD$str$, $str$US$str$, $str$BENCHMARK$str$, $str$Other Secondary Processes$str$, 0.5, 0.5, 24241, 1.47, 13.95, 1.47, 13.95, 15.42, 15.42, 29.95, 29.95, 29.95, 1, 1, $str$2 - Metal$str$, 24241, 900, 790, 2, 0, 10, 20, 80, 5, 0, 0, 0, 1, $str$USA$str$, $str$CMM Inspection:Axiom Xtreme 350$str$),
  ($str$cmm$str$, $str$USA$str$, $str$Axiom Xtreme 500$str$, $str$USD$str$, $str$US$str$, $str$BENCHMARK$str$, $str$Other Secondary Processes$str$, 0.5, 0.5, 28300, 1.71, 14.01, 1.71, 14.01, 15.72, 15.72, 29.95, 29.95, 29.95, 1, 1, $str$2 - Metal$str$, 28300, 1140, 905, 2, 0, 10, 20, 80, 5, 0, 0, 0, 1, $str$USA$str$, $str$CMM Inspection:Axiom Xtreme 500$str$),
  ($str$cmm$str$, $str$USA$str$, $str$Axiom Zenith 1000$str$, $str$USD$str$, $str$US$str$, $str$BENCHMARK$str$, $str$Other Secondary Processes$str$, 0.5, 0.5, 43467, 2.63, 14.27, 2.63, 14.27, 16.9, 16.9, 29.95, 29.95, 29.95, 1, 1, $str$2 - Metal$str$, 43467, 1700, 1520, 2, 0, 10, 20, 80, 5, 0, 0, 0, 1, $str$USA$str$, $str$CMM Inspection:Axiom Zenith 1000$str$),
  ($str$cmm$str$, $str$USA$str$, $str$Axiom Zenith 1500$str$, $str$USD$str$, $str$US$str$, $str$BENCHMARK$str$, $str$Other Secondary Processes$str$, 0.5, 0.5, 50455, 3.05, 14.4, 3.05, 14.4, 17.45, 17.45, 29.95, 29.95, 29.95, 1, 1, $str$2 - Metal$str$, 50455, 2200, 1520, 2, 0, 10, 20, 80, 5, 0, 0, 0, 1, $str$USA$str$, $str$CMM Inspection:Axiom Zenith 1500$str$),
  ($str$cmm$str$, $str$USA$str$, $str$Axiom Zenith 2000$str$, $str$USD$str$, $str$US$str$, $str$BENCHMARK$str$, $str$Other Secondary Processes$str$, 0.5, 0.5, 57443, 3.48, 14.53, 3.48, 14.53, 18.01, 18.01, 29.95, 29.95, 29.95, 1, 1, $str$2 - Metal$str$, 57443, 2700, 1520, 2, 0, 10, 20, 80, 5, 0, 0, 0, 1, $str$USA$str$, $str$CMM Inspection:Axiom Zenith 2000$str$),
  ($str$cmm$str$, $str$USA$str$, $str$Axiom Zenith 2500$str$, $str$USD$str$, $str$US$str$, $str$BENCHMARK$str$, $str$Other Secondary Processes$str$, 0.5, 0.5, 64431, 3.9, 14.66, 3.9, 14.66, 18.56, 18.56, 29.95, 29.95, 29.95, 1, 1, $str$2 - Metal$str$, 64431, 3200, 1520, 2, 0, 10, 20, 80, 5, 0, 0, 0, 1, $str$USA$str$, $str$CMM Inspection:Axiom Zenith 2500$str$),
  ($str$cmm$str$, $str$USA$str$, $str$Axiom Zenith 3000$str$, $str$USD$str$, $str$US$str$, $str$BENCHMARK$str$, $str$Other Secondary Processes$str$, 0.5, 0.5, 72890, 4.41, 14.79, 4.41, 14.79, 19.2, 19.2, 29.95, 29.95, 29.95, 1, 1, $str$2 - Metal$str$, 72890, 3700, 1520, 2, 0, 10, 20, 80, 5, 0, 0, 0, 1, $str$USA$str$, $str$CMM Inspection:Axiom Zenith 3000$str$)
) AS v(machine_class, location, machine_name, currency_code, country_code, source_type, process_group, operators, setup_time_hr, landed_machine_cost, direct_overhead_rate, indirect_overhead_rate, benchmark_direct_overhead_rate_usd_hr, benchmark_indirect_overhead_rate_usd_hr, total_machine_hour_rate, mhr_usd_per_hour, usd_labor_rate_per_hr, benchmark_labor_rate_usd_hr, usd_lhr_total, work_center_labor_rate_factor, labor_time_standard, wage_grade, machine_price_usd, machine_length_mm, machine_width_mm, footprint_allowance_factor, machine_power_kw, machine_life_yr, installation_factor_pct, machine_uptime_pct, annual_maintenance_factor_pct, salvage_value_factor_pct, supplies_cost_per_year, avg_utilization, good_part_yield, manufacturer_country, benchmark_source_key)
WHERE NOT EXISTS (
  SELECT 1 FROM mhr_records m
  WHERE m.machine_class = v.machine_class
    AND m.location = v.location
    AND lower(trim(m.machine_name)) = lower(trim(v.machine_name))
);

-- Verify (expect 11 rows, mhr = direct + indirect on every one):
-- SELECT machine_name, direct_overhead_rate, indirect_overhead_rate,
--        total_machine_hour_rate, usd_lhr_total, benchmark_source_key
-- FROM mhr_records WHERE machine_class = 'cmm' AND location = 'USA'
-- ORDER BY machine_name;
