-- ============================================================================
-- Migration 829: India machine rates from every India file in memory/
-- ============================================================================
-- Generated by scripts/gen_829_seed_india_machine_rates.js -- do not hand-edit,
-- re-run the generator and diff instead. The generator header documents the
-- matching rules; this header records what they decided.
--
-- Sources (rates only, USD/hr, transcribed from screenshots):
--   Secondary process/machines/India/India_Secondary_Process_Machine_Data_SingleSheet.xlsx
--   Plastic Modeling/machine/India/machine_rates.csv, machine_rates_2.csv
--   Machining/machine/India/machining_final.csv, all_machines_master.csv
--   (Secondary .../all_machines_master (1).xlsx is the same 412 rows as the csv.)
-- 825 rows read, 477 distinct India machines after merging.
--
-- Transcription errors resolved to the one unclaimed USA machine name:
--   Ultrasonic C-Scan - 6.09m x 3.85m x 1.82m  ->  Ultrasonic C-Scan - 6.09m x 3.65m x 1.82m  (edit distance 1)
--   Allendale-Ultrasonics 38 Litre  ->  Allendale-Ultrasonics 36 Litre  (edit distance 1)
--   Allendale-Ultrasonics 93 Litre  ->  Allendale-Ultrasonics 90 Litre  (edit distance 1)
--   DoAll C-455NC  ->  DoAll C-455CNC  (edit distance 1)
--   Karmatorsk KJ1910  ->  Kramatorsk KJ1910  (edit distance 2)
--   GLT Toyoda  ->  GL7 Toyoda  (edit distance 1)
--   Nachi NIUV-20-23  ->  Nachi NUV-20-23  (edit distance 1)
--   Gleason Phoenix II 800HC  ->  Gleason Phoenix II 600HC  (edit distance 1)
--   Thermwood Multipurpose 60, 5' x 10'  ->  Thermwood Multipurpose 67, 5' x 10'  (edit distance 1)
--   Thermwood Multipurpose 60, 5' x 12'  ->  Thermwood Multipurpose 67, 5' x 12'  (edit distance 1)
--   Thermwood Multipurpose 60, 5' x 5'  ->  Thermwood Multipurpose 67, 5' x 5'  (edit distance 1)
--   Sodick MC940L  ->  Sodick MC640L  (edit distance 1)
--   Miyano BND-20SS  ->  Miyano BND-20S5  (edit distance 1)
--   Miyano BND-34TS  ->  Miyano BND-34T5  (edit distance 1)
--   Sydexic SRD 350  ->  Syderic SRD 350  (edit distance 1)
--   Honge XE 10000  ->  Honge XL 10000  (edit distance 1)
--   Studer CT350  ->  Studer CT550  (edit distance 1)
--   DMG Mori GMC2510M-6  ->  DMG Mori GMC25ISM-6  (edit distance 2)
--   Doosan Puma TT2500SY  ->  Dooson Puma TT2500SY  (edit distance 1)
--   Tsugami M88SY  ->  Tsugami M08SY  (edit distance 1)
--   Virtual CNC Multi-Spindle, 6 Spindle, Large  ->  Virtual CNC Multi-Spindle, 6 Spindles, Large  (edit distance 1)
--   Virtual CNC Multi-Spindle, 6 Spindle, Small  ->  Virtual CNC Multi-Spindle, 6 Spindles, Small  (edit distance 1)
--   Virtual CNC Multi-Spindle, 8 Spindle, Large  ->  Virtual CNC Multi-Spindle, 8 Spindles, Large  (edit distance 1)
--   Virtual CNC Multi-Spindle, 8 Spindle, Small  ->  Virtual CNC Multi-Spindle, 8 Spindles, Small  (edit distance 1)
--   Hydraulic Compression Molding Press - 10000kN | 2.0m x 1.8m  ->  Hydraulic Compression Molding Press - 10,000kN | 2.0m x 1.8m  (edit distance 1)
--   Hydraulic Compression Molding Press - 20000kN | 3.0m x 2.0m  ->  Hydraulic Compression Molding Press - 20,000kN | 3.0m x 2.0m  (edit distance 1)
--   Hydraulic Compression Molding Press - 3000kN | 1.25m x 1.0m  ->  Hydraulic Compression Molding Press - 3,000kN | 1.25m x 1.0m  (edit distance 1)
--   Hydraulic Compression Molding Press - 30000kN | 3.4m x 2.4m  ->  Hydraulic Compression Molding Press - 30,000kN | 3.4m x 2.4m  (edit distance 1)
--   Hydraulic Compression Molding Press - 40000kN | 4.0m x 3.0m  ->  Hydraulic Compression Molding Press - 40,000kN | 4.0m x 3.0m  (edit distance 1)
--   Hydraulic Compression Molding Press - 5000kN | 1.8m x 1.2m  ->  Hydraulic Compression Molding Press - 5,000kN | 1.6m x 1.2m  (edit distance 2)
--   Hydraulic Compression Molding Press - 50000kN | 5.0m x 3.0m  ->  Hydraulic Compression Molding Press - 50,000kN | 5.0m x 3.0m  (edit distance 1)
--   Hydraulic Compression Molding Press - 8000kN | 2.4m x 1.7m  ->  Hydraulic Compression Molding Press - 8,000kN | 2.4m x 1.7m  (edit distance 1)
--   Arburg Allrounder 320 C 800 - 250  ->  Arburg Allrounder 320 C 600 - 250  (edit distance 1)
--   Engel DUO 130000 / 5500  ->  Engel DUO 130000 / 3500  (edit distance 1)
--   Engel DUO 2550 / 850  ->  Engel DUO 2550 / 650  (edit distance 1)
--   Engel DUO 25050 / 3200  ->  Engel DUO 35050 / 3200  (edit distance 1)
--   Netstal Synergy 900  ->  Netstal Synergy 800  (edit distance 1)
--   Structural Foam Molder - 5,000kN Clamp Force  ->  Structural Form Molder - 5,000kN Clamp Force  (edit distance 1)
--   Structural Foam Molder - 7,500kN Clamp Force  ->  Structural Form Molder - 7,500kN Clamp Force  (edit distance 1)
--   Structural Foam Molder - 10,000kN Clamp Force  ->  Structural Form Molder - 10,000kN Clamp Force  (edit distance 1)
--   Structural Foam Molder - 25,000kN Clamp Force  ->  Structural Form Molder - 25,000kN Clamp Force  (edit distance 1)
--   Uniloy 750MSWP-2x423  ->  Uniloy 750MWP-2x423  (edit distance 1)
--   Uniloy 750MSWP-2x646  ->  Uniloy 800MSWP-2x646  (edit distance 2)
--   Uniloy 800MSWP-2x423  ->  Uniloy 800MWP-2x423  (edit distance 1)
--
-- Unlabeled screenshot rows: machine_rates.csv screenshots 4, 6 and 12 are the
-- "Default" machines of CT Scan, Hydrostatic Leak Testing and Xray Inspection.
--
-- Duplicates resolved by the labour rate their process shares:
--   Elmasonic xtra ST 2500H-215 Litre (Ultrasonic Cleaning): labour 1.57 shared by its process (other value dropped)
--
-- NOT inserted (listed again by the NOTICE when run):
--   no USA machine within edit distance 2 (India-only machines; seeded only
--   when their process names exactly one USA category, else skipped):
--     Gleason 300 TWG; Gleason Genesis 160TWG; Reishauer RZ 1000; Reishauer RZ 550; Reishauer RZ 60; Fanuc 0id; Fanuc 1id; Makino DUO43; Mitsubishi BA24; Mitsubishi FA-50V; Mitsubishi MD+PRO II
--   rate conflicts the data cannot settle:
--     none
--
-- Every India row clones its USA twin (all columns, read from
-- information_schema), overriding location, country, rates and
-- benchmark_source_key (suffixed :India). Rates stay USD, as in migration 594.
-- Existing India rows are never overwritten. One DO block. Run it LAST, after
-- every USA machine seed (806, 815, 818, 820, 824, 826, 828), so each India row
-- finds its USA twin.
-- ============================================================================

DO $india829$
DECLARE
  cols text; sel text;
  r record; t record;
  n_twin integer := 0; n_only integer := 0;
  skipped text[] := '{}';
  used uuid[] := '{}';
  cat_class text; cat_group text; cat_grade text; n_class integer;
BEGIN
  SELECT
    string_agg(quote_ident(c.column_name), ', ' ORDER BY c.ordinal_position),
    string_agg(
      CASE c.column_name
        WHEN 'location'                                THEN '''India'''
        WHEN 'country_code'                            THEN '''IN'''
        WHEN 'direct_overhead_rate'                    THEN '$2'
        WHEN 'indirect_overhead_rate'                  THEN '$3'
        WHEN 'benchmark_direct_overhead_rate_usd_hr'   THEN '$2'
        WHEN 'benchmark_indirect_overhead_rate_usd_hr' THEN '$3'
        WHEN 'total_machine_hour_rate'                 THEN 'ROUND(($2 + $3)::numeric, 2)'
        WHEN 'mhr_usd_per_hour'                        THEN 'ROUND(($2 + $3)::numeric, 2)'
        WHEN 'manual_mhr_value'                        THEN 'ROUND(($2 + $3)::numeric, 2)'
        WHEN 'fully_burdened_local_per_hr'             THEN 'ROUND(($2 + $3)::numeric, 2)'
        WHEN 'usd_labor_rate_per_hr'                   THEN '$4'
        WHEN 'benchmark_labor_rate_usd_hr'             THEN '$4'
        WHEN 'usd_lhr_total'                           THEN '$4'
        WHEN 'benchmark_source_key'                    THEN 'usa.benchmark_source_key || '':India'''
        ELSE 'usa.' || quote_ident(c.column_name)
      END, ', ' ORDER BY c.ordinal_position)
  INTO cols, sel
  FROM information_schema.columns c
  WHERE c.table_schema = 'public' AND c.table_name = 'mhr_records'
    AND c.column_name NOT IN ('id', 'created_at', 'updated_at')
    AND c.is_generated = 'NEVER' AND c.identity_generation IS NULL;

  -- Pass 1 matches rows with a named process (and unique names); pass 2 gives
  -- UNIDENTIFIED-process rows the one USA twin their name has left.
  FOR r IN
    SELECT *, CASE WHEN unidentified IS NULL THEN 1 ELSE 2 END AS pass FROM (VALUES
      ($str$COMBI 2-EZ$str$, $str$Carton Forming$str$, NULL, 1.57, 1.47, 1.09, NULL, NULL, NULL, NULL),
      ($str$COMBI 2-EZ XL$str$, $str$Carton Forming$str$, NULL, 1.57, 2.08, 1.34, NULL, NULL, NULL, NULL),
      ($str$Manual Former$str$, $str$Carton Forming$str$, NULL, 1.57, 0, 0.88, NULL, NULL, NULL, NULL),
      ($str$Trayfecta M1200$str$, $str$Carton Forming$str$, NULL, 1.57, 3.91, 1.23, NULL, NULL, NULL, NULL),
      ($str$Trayfecta M1500$str$, $str$Carton Forming$str$, NULL, 1.57, 4.16, 1.29, NULL, NULL, NULL, NULL),
      ($str$3M 800r$str$, $str$Carton Sealing$str$, NULL, 1.57, 0.63, 0.93, NULL, NULL, NULL, NULL),
      ($str$Adjustable Flap Folding Case Sealer$str$, $str$Carton Sealing$str$, NULL, 1.57, 0.99, 1, NULL, NULL, NULL, NULL),
      ($str$Manual Carton Sealer$str$, $str$Carton Sealing$str$, NULL, 1.57, 0, 0.88, NULL, NULL, NULL, NULL),
      ($str$Axiom Too 1200$str$, $str$CMM Inspection$str$, NULL, 1.65, 1.49, 0.94, NULL, NULL, NULL, NULL),
      ($str$Axiom Too 1500$str$, $str$CMM Inspection$str$, NULL, 1.65, 1.71, 0.96, NULL, NULL, NULL, NULL),
      ($str$Axiom Too 1800$str$, $str$CMM Inspection$str$, NULL, 1.65, 2.01, 0.98, NULL, NULL, NULL, NULL),
      ($str$Axiom Too 900$str$, $str$CMM Inspection$str$, NULL, 1.65, 1.31, 0.92, NULL, NULL, NULL, NULL),
      ($str$Axiom Xtreme 350$str$, $str$CMM Inspection$str$, NULL, 1.65, 1.18, 0.9, NULL, NULL, NULL, NULL),
      ($str$Axiom Xtreme 500$str$, $str$CMM Inspection$str$, NULL, 1.65, 1.37, 0.92, NULL, NULL, NULL, NULL),
      ($str$Axiom Zenith 1000$str$, $str$CMM Inspection$str$, NULL, 1.65, 2.11, 1.01, NULL, NULL, NULL, NULL),
      ($str$Axiom Zenith 1500$str$, $str$CMM Inspection$str$, NULL, 1.65, 2.45, 1.06, NULL, NULL, NULL, NULL),
      ($str$Axiom Zenith 2000$str$, $str$CMM Inspection$str$, NULL, 1.65, 2.79, 1.1, NULL, NULL, NULL, NULL),
      ($str$Axiom Zenith 2500$str$, $str$CMM Inspection$str$, NULL, 1.65, 3.13, 1.15, NULL, NULL, NULL, NULL),
      ($str$Axiom Zenith 3000$str$, $str$CMM Inspection$str$, NULL, 1.65, 3.54, 1.19, NULL, NULL, NULL, NULL),
      ($str$Default$str$, $str$CT Scan$str$, NULL, 1.65, 1.92, 9.82, NULL, NULL, NULL, NULL),
      ($str$AIM 1836W$str$, $str$Fluorescent Penetrant Testing$str$, NULL, 2.3, 0.78, 2.23, NULL, NULL, NULL, NULL),
      ($str$Default$str$, $str$Hydrostatic Leak Testing$str$, NULL, 2.3, 1.1, 1.27, NULL, NULL, NULL, NULL),
      ($str$WHM-4102$str$, $str$Magnetic Particle Testing$str$, NULL, 2.3, 3.82, 1.3, NULL, NULL, NULL, NULL),
      ($str$WHM-4400$str$, $str$Magnetic Particle Testing$str$, NULL, 2.3, 3.58, 1.09, NULL, NULL, NULL, NULL),
      ($str$WHM-4600$str$, $str$Magnetic Particle Testing$str$, NULL, 2.3, 3.7, 1.2, NULL, NULL, NULL, NULL),
      ($str$ZTISA-600$str$, $str$Pack & Load$str$, NULL, 1.57, 0.13, 0.9, NULL, NULL, NULL, NULL),
      ($str$ZTISA-450$str$, $str$Pack & Load$str$, NULL, 1.57, 0.12, 0.9, NULL, NULL, NULL, NULL),
      ($str$Manual Pack & Loader$str$, $str$Pack & Load$str$, NULL, 1.57, 0, 0.88, NULL, NULL, NULL, NULL),
      ($str$Accu-Seal HDMP3-632$str$, $str$Pack & Load$str$, NULL, 1.57, 0.72, 0.89, NULL, NULL, NULL, NULL),
      ($str$Accu-Seal HDMP3-532$str$, $str$Pack & Load$str$, NULL, 1.57, 0.67, 0.89, NULL, NULL, NULL, NULL),
      ($str$Accu-Seal HDMP3-332$str$, $str$Pack & Load$str$, NULL, 1.57, 0.61, 0.88, NULL, NULL, NULL, NULL),
      ($str$Ultrasonic A-Scan - 12.19m x 3.66m x 1.21m$str$, $str$Ultrasonic A-Scan$str$, NULL, 3.52, 14.87, 2.29, NULL, NULL, NULL, NULL),
      ($str$Ultrasonic A-Scan - 3.05m x 0.91m x 0.84m$str$, $str$Ultrasonic A-Scan$str$, NULL, 3.52, 5.11, 0.95, NULL, NULL, NULL, NULL),
      ($str$Ultrasonic A-Scan - 6.09m x 1.83m x 1.01m$str$, $str$Ultrasonic A-Scan$str$, NULL, 3.52, 8.36, 1.22, NULL, NULL, NULL, NULL),
      ($str$Ultrasonic C-Scan - 12.19m x 7.31m x 3.65m$str$, $str$Ultrasonic C-Scan$str$, NULL, 3.52, 25.71, 3.72, NULL, NULL, NULL, NULL),
      ($str$Ultrasonic C-Scan - 3.04m x 1.82m x 0.91m$str$, $str$Ultrasonic C-Scan$str$, NULL, 3.52, 8.29, 1.04, NULL, NULL, NULL, NULL),
      ($str$Ultrasonic C-Scan - 6.09m x 3.65m x 1.82m$str$, $str$Ultrasonic C-Scan$str$, NULL, 3.52, 14.1, 1.58, NULL, NULL, NULL, NULL),
      ($str$Allendale-Ultrasonics 112 Litre$str$, $str$Ultrasonic Cleaning$str$, NULL, 1.57, 0.85, 0.87, NULL, NULL, NULL, NULL),
      ($str$Allendale-Ultrasonics 13 Litre$str$, $str$Ultrasonic Cleaning$str$, NULL, 1.57, 0.11, 0.87, NULL, NULL, NULL, NULL),
      ($str$Allendale-Ultrasonics 145 Litre$str$, $str$Ultrasonic Cleaning$str$, NULL, 1.57, 1.09, 0.87, NULL, NULL, NULL, NULL),
      ($str$Allendale-Ultrasonics 20 Litre$str$, $str$Ultrasonic Cleaning$str$, NULL, 1.57, 0.14, 0.87, NULL, NULL, NULL, NULL),
      ($str$Allendale-Ultrasonics 235 Litre$str$, $str$Ultrasonic Cleaning$str$, NULL, 1.57, 1.24, 0.87, NULL, NULL, NULL, NULL),
      ($str$Allendale-Ultrasonics 27 Litre$str$, $str$Ultrasonic Cleaning$str$, NULL, 1.57, 0.27, 0.87, NULL, NULL, NULL, NULL),
      ($str$Allendale-Ultrasonics 288 Litre$str$, $str$Ultrasonic Cleaning$str$, NULL, 1.57, 1.4, 0.88, NULL, NULL, NULL, NULL),
      ($str$Allendale-Ultrasonics 3 Litre$str$, $str$Ultrasonic Cleaning$str$, NULL, 1.57, 0.03, 0.86, NULL, NULL, NULL, NULL),
      ($str$Allendale-Ultrasonics 36 Litre$str$, $str$Ultrasonic Cleaning$str$, NULL, 1.57, 0.19, 0.87, NULL, NULL, NULL, NULL),
      ($str$Allendale-Ultrasonics 57 Litre$str$, $str$Ultrasonic Cleaning$str$, NULL, 1.57, 0.6, 0.87, NULL, NULL, NULL, NULL),
      ($str$Allendale-Ultrasonics 9 Litre$str$, $str$Ultrasonic Cleaning$str$, NULL, 1.57, 0.08, 0.86, NULL, NULL, NULL, NULL),
      ($str$Allendale-Ultrasonics 90 Litre$str$, $str$Ultrasonic Cleaning$str$, NULL, 1.57, 0.43, 0.87, NULL, NULL, NULL, NULL),
      ($str$Elmasonic xtra ST 2500H-215 Litre$str$, $str$Ultrasonic Cleaning$str$, NULL, 1.57, 1.97, 0.89, NULL, NULL, NULL, NULL),
      ($str$Default$str$, $str$Xray Inspection$str$, NULL, 2.3, 1.92, 9.82, NULL, NULL, NULL, NULL),
      ($str$BLIN HDS-J150$str$, NULL, NULL, 1.65, 10.55, 3.47, NULL, NULL, NULL, NULL),
      ($str$BLIN HDS-J160$str$, NULL, NULL, 1.65, 11.28, 3.59, NULL, NULL, NULL, NULL),
      ($str$BLIN HDS-J180$str$, NULL, NULL, 1.65, 12.49, 3.79, NULL, NULL, NULL, NULL),
      ($str$BLIN HDS-J200$str$, NULL, NULL, 1.65, 15.42, 5.01, NULL, NULL, NULL, NULL),
      ($str$DoAll 3613-1 Vert$str$, NULL, NULL, 1.65, 1.3, 1.22, NULL, NULL, NULL, NULL),
      ($str$DoAll 500-SNC$str$, NULL, NULL, 1.65, 1.78, 1.99, NULL, NULL, NULL, NULL),
      ($str$DoAll C-330NC$str$, NULL, NULL, 1.65, 1.87, 2, NULL, NULL, NULL, NULL),
      ($str$DoAll C-455CNC$str$, NULL, NULL, 1.65, 3.66, 2, NULL, NULL, NULL, NULL),
      ($str$DoAll C-650NC$str$, NULL, NULL, 1.65, 5.45, 2.01, NULL, NULL, NULL, NULL),
      ($str$DoAll DC-560NC$str$, NULL, NULL, 1.65, 4.31, 2.01, NULL, NULL, NULL, NULL),
      ($str$DoAll DC-700NC$str$, NULL, NULL, 1.65, 6.02, 2.08, NULL, NULL, NULL, NULL),
      ($str$DoAll DC-800NC$str$, NULL, NULL, 1.65, 8.82, 2.39, NULL, NULL, NULL, NULL),
      ($str$Peddinghaus 1250-510$str$, NULL, NULL, 1.65, 7.49, 1.23, NULL, NULL, NULL, NULL),
      ($str$Default Material Stock$str$, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL),
      ($str$DeMask Cell - 10m x 10m Footprint$str$, $str$Demasking$str$, NULL, 1.65, 0.25, 3.77, NULL, NULL, NULL, NULL),
      ($str$DeMask Cell - 12m x 10m Footprint$str$, $str$Demasking$str$, NULL, 1.65, 0.25, 4.36, NULL, NULL, NULL, NULL),
      ($str$Fortune 2225$str$, NULL, $str$UNIDENTIFIED-01$str$, 1.73, 9.81, 6.9, NULL, NULL, NULL, NULL),
      ($str$Fortune 2235$str$, NULL, $str$UNIDENTIFIED-01$str$, 1.73, 9.81, 6.91, NULL, NULL, NULL, NULL),
      ($str$Kramatorsk KJ1910$str$, NULL, $str$UNIDENTIFIED-01$str$, 1.73, 27.62, 7.56, NULL, NULL, NULL, NULL),
      ($str$Nanjing SZT2120Q$str$, NULL, $str$UNIDENTIFIED-01$str$, 1.73, 49.8, 5.94, NULL, NULL, NULL, NULL),
      ($str$Nanjing ZT2115Q$str$, NULL, $str$UNIDENTIFIED-01$str$, 1.73, 27.95, 8.92, NULL, NULL, NULL, NULL),
      ($str$Nanjing ZT2118Q$str$, NULL, $str$UNIDENTIFIED-01$str$, 1.73, 40.48, 4.8, NULL, NULL, NULL, NULL),
      ($str$Toyoda GE4 Cylindrical Grinder$str$, $str$Cylindrical Grinding$str$, NULL, 1.65, 10.8, 2.32, NULL, NULL, NULL, NULL),
      ($str$Toyoda G Cylindrical Grinder$str$, $str$Cylindrical Grinding$str$, NULL, 1.65, 9.49, 2.15, NULL, NULL, NULL, NULL),
      ($str$Grindor Junker$str$, $str$Cylindrical Grinding$str$, NULL, 1.65, 11.91, 2.32, NULL, NULL, NULL, NULL),
      ($str$GL7 Toyoda$str$, $str$Cylindrical Grinding$str$, NULL, 1.65, 27.12, 2.81, NULL, NULL, NULL, NULL),
      ($str$Flex Grind Schaudt XXL$str$, $str$Cylindrical Grinding$str$, NULL, 1.65, 28.26, 2.49, NULL, NULL, NULL, NULL),
      ($str$Flex Grind Schaudt M$str$, $str$Cylindrical Grinding$str$, NULL, 1.65, 28.26, 2.49, NULL, NULL, NULL, NULL),
      ($str$Nachi NUV-20-23$str$, $str$Broaching$str$, NULL, 1.73, 12.83, 1.39, NULL, NULL, NULL, NULL),
      ($str$Pioneer H1560$str$, $str$Broaching$str$, NULL, 1.73, 7.75, 1.17, NULL, NULL, NULL, NULL),
      ($str$Pioneer VT1040$str$, $str$Broaching$str$, NULL, 1.73, 6.04, 1.1, NULL, NULL, NULL, NULL),
      ($str$Cell-Mate$str$, $str$Broaching$str$, NULL, 1.73, 11.24, 1.48, NULL, NULL, NULL, NULL),
      ($str$Gleason Coniflex 104$str$, $str$Bevel Gear Cutting$str$, NULL, 1.73, 39.44, 1.55, NULL, NULL, NULL, NULL),
      ($str$Gleason Phoenix II 275HC$str$, $str$Bevel Gear Cutting$str$, NULL, 1.73, 42.37, 1.56, NULL, NULL, NULL, NULL),
      ($str$Gleason Phoenix II 600HC$str$, $str$Bevel Gear Cutting$str$, NULL, 1.73, 66.02, 2.23, NULL, NULL, NULL, NULL),
      ($str$Klingelnberg-Oerlikon C27$str$, $str$Bevel Gear Cutting$str$, NULL, 1.73, 43.04, 1.51, NULL, NULL, NULL, NULL),
      ($str$Klingelnberg-Oerlikon C29$str$, $str$Bevel Gear Cutting$str$, NULL, 1.73, 43.04, 1.55, NULL, NULL, NULL, NULL),
      ($str$Manual Bench Cell - 16m x 4m Footprint$str$, $str$Manual Bench Cell$str$, NULL, 1.73, 0.37, 2.73, NULL, NULL, NULL, NULL),
      ($str$Manual Bench Cell - 2m x 2m Footprint$str$, $str$Manual Bench Cell$str$, NULL, 1.73, 0.12, 0.98, NULL, NULL, NULL, NULL),
      ($str$Manual Bench Cell - 4m x 4m Footprint$str$, $str$Manual Bench Cell$str$, NULL, 1.73, 0.12, 1.33, NULL, NULL, NULL, NULL),
      ($str$Manual Bench Cell - 8m x 4m Footprint$str$, $str$Manual Bench Cell$str$, NULL, 1.73, 0.25, 1.79, NULL, NULL, NULL, NULL),
      ($str$Default Automated Deburr$str$, $str$Automated Deburring$str$, NULL, 1.65, 20.4, 0.9, NULL, NULL, NULL, NULL),
      ($str$Thermwood Multipurpose 67, 5' x 10'$str$, $str$5 Axis Router$str$, NULL, 2.75, 10.07, 1.29, NULL, NULL, NULL, NULL),
      ($str$Thermwood Multipurpose 67, 5' x 12'$str$, $str$5 Axis Router$str$, NULL, 2.75, 11.72, 1.37, NULL, NULL, NULL, NULL),
      ($str$Thermwood Multipurpose 67, 5' x 5'$str$, $str$5 Axis Router$str$, NULL, 2.75, 8.67, 1.07, NULL, NULL, NULL, NULL),
      ($str$Thermwood Multipurpose 90, 5' x 10'$str$, $str$5 Axis Router$str$, NULL, 2.75, 18.43, 1.29, NULL, NULL, NULL, NULL),
      ($str$Thermwood Multipurpose 90, 5' x 5'$str$, $str$5 Axis Router$str$, NULL, 2.75, 13.87, 1.07, NULL, NULL, NULL, NULL),
      ($str$Virtual 5 Axis Router - Large$str$, $str$5 Axis Router$str$, NULL, 2.75, 17.5, 1.28, NULL, NULL, NULL, NULL),
      ($str$Virtual 5 Axis Router - Small$str$, $str$5 Axis Router$str$, NULL, 2.75, 8.43, 1.06, NULL, NULL, NULL, NULL),
      ($str$DMG MORI DMU 105 monoBLOCK$str$, $str$5 Axis Mill$str$, NULL, 2.75, 20.51, 2.63, NULL, NULL, NULL, NULL),
      ($str$DMG MORI DMU 125 monoBLOCK$str$, $str$5 Axis Mill$str$, NULL, 2.75, 27.47, 3.56, NULL, NULL, NULL, NULL),
      ($str$DMG MORI DMU 60 eVo Linear$str$, $str$5 Axis Mill$str$, NULL, 2.75, 21.49, 2.66, NULL, NULL, NULL, NULL),
      ($str$DMG MORI DMU 65 monoBLOCK$str$, $str$5 Axis Mill$str$, NULL, 2.75, 22.63, 1.68, NULL, NULL, NULL, NULL),
      ($str$DMG MORI DMU 85 monoBLOCK$str$, $str$5 Axis Mill$str$, NULL, 2.75, 22.12, 2.08, NULL, NULL, NULL, NULL),
      ($str$DMU 160 P duoBlock$str$, $str$5 Axis Mill$str$, NULL, 2.75, 51.41, 5.46, NULL, NULL, NULL, NULL),
      ($str$DMU 40 eVo Linear$str$, $str$5 Axis Mill$str$, NULL, 2.75, 21.05, 2.78, NULL, NULL, NULL, NULL),
      ($str$DMU 600P$str$, $str$5 Axis Mill$str$, NULL, 2.75, 62.77, 13.67, NULL, NULL, NULL, NULL),
      ($str$Fooke Endura 1005$str$, $str$5 Axis Mill$str$, NULL, 2.75, 119.37, 29.92, NULL, NULL, NULL, NULL),
      ($str$Makino D300$str$, $str$5 Axis Mill$str$, NULL, 2.75, 18.91, 1.47, NULL, NULL, NULL, NULL),
      ($str$Makino D500$str$, $str$5 Axis Mill$str$, NULL, 2.75, 21.45, 2.26, NULL, NULL, NULL, NULL),
      ($str$Makino D800Z$str$, $str$5 Axis Mill$str$, NULL, 2.75, 51.59, 2.26, NULL, NULL, NULL, NULL),
      ($str$Makino V33i-5XB$str$, $str$5 Axis Mill$str$, NULL, 2.75, 15.15, 1.36, NULL, NULL, NULL, NULL),
      ($str$Mazak Variaxis 500-5X II$str$, $str$5 Axis Mill$str$, NULL, 2.75, 17.4, 1.57, NULL, NULL, NULL, NULL),
      ($str$Mazak Variaxis 630-5X II$str$, $str$5 Axis Mill$str$, NULL, 2.75, 19.83, 1.14, NULL, NULL, NULL, NULL),
      ($str$Mazak Variaxis 630-5X II T$str$, $str$5 Axis Mill$str$, NULL, 2.75, 24.36, 1.74, NULL, NULL, NULL, NULL),
      ($str$Mazak Variaxis 730-5X II$str$, $str$5 Axis Mill$str$, NULL, 2.75, 27.66, 2.06, NULL, NULL, NULL, NULL),
      ($str$Mazak Vortex 1400$str$, $str$5 Axis Mill$str$, NULL, 2.75, 56.83, 6.63, NULL, NULL, NULL, NULL),
      ($str$Mazak Vortex 815/120$str$, $str$5 Axis Mill$str$, NULL, 2.75, 53.68, 4.5, NULL, NULL, NULL, NULL),
      ($str$Mazak Vortex 815/80$str$, $str$5 Axis Mill$str$, NULL, 2.75, 53.6, 4.5, NULL, NULL, NULL, NULL),
      ($str$Virtual 5 Axis Mill - Gantry$str$, $str$5 Axis Mill$str$, NULL, 2.75, 53.39, 7.41, NULL, NULL, NULL, NULL),
      ($str$Virtual 5 Axis Mill - Large$str$, $str$5 Axis Mill$str$, NULL, 2.75, 44.21, 2.54, NULL, NULL, NULL, NULL),
      ($str$Virtual 5 Axis Mill - Medium$str$, $str$5 Axis Mill$str$, NULL, 2.75, 23.22, 1.88, NULL, NULL, NULL, NULL),
      ($str$Virtual 5 Axis Mill - Small$str$, $str$5 Axis Mill$str$, NULL, 2.75, 17.47, 1.52, NULL, NULL, NULL, NULL),
      ($str$Multicam 7000 Series CNC Router, Model 103$str$, $str$3 Axis Router$str$, NULL, 2.75, 5.39, 1.21, NULL, NULL, NULL, NULL),
      ($str$Multicam 7000 Series CNC Router, Model 306$str$, $str$3 Axis Router$str$, NULL, 2.75, 7.88, 1.76, NULL, NULL, NULL, NULL),
      ($str$Multicam APEX1R CNC Router, Model 103$str$, $str$3 Axis Router$str$, NULL, 2.75, 3.16, 1.09, NULL, NULL, NULL, NULL),
      ($str$Multicam APEX1R CNC Router, Model 304$str$, $str$3 Axis Router$str$, NULL, 2.75, 4.87, 1.25, NULL, NULL, NULL, NULL),
      ($str$Virtual 3 Axis Router - Large$str$, $str$3 Axis Router$str$, NULL, 2.75, 7.42, 1.78, NULL, NULL, NULL, NULL),
      ($str$Virtual 3 Axis Router - Small$str$, $str$3 Axis Router$str$, NULL, 2.75, 3.25, 1.08, NULL, NULL, NULL, NULL),
      ($str$Giddings & Lewis H60F$str$, $str$3 Axis Mill$str$, NULL, 2.75, 13.78, 2.16, NULL, NULL, NULL, NULL),
      ($str$Giddings & Lewis H70F$str$, $str$3 Axis Mill$str$, NULL, 2.75, 16.13, 2.16, NULL, NULL, NULL, NULL),
      ($str$Haas VF10/50$str$, $str$3 Axis Mill$str$, NULL, 2.75, 14.95, 2.89, NULL, NULL, NULL, NULL),
      ($str$Hermle B300$str$, $str$3 Axis Mill$str$, NULL, 2.75, 10.14, 2.74, NULL, NULL, NULL, NULL),
      ($str$Makino FB127$str$, $str$3 Axis Mill$str$, NULL, 2.75, 18.11, 1.88, NULL, NULL, NULL, NULL),
      ($str$Makino IQ300$str$, $str$3 Axis Mill$str$, NULL, 2.75, 13.8, 1.27, NULL, NULL, NULL, NULL),
      ($str$Makino IQ500$str$, $str$3 Axis Mill$str$, NULL, 2.75, 14.49, 1.36, NULL, NULL, NULL, NULL),
      ($str$Makino V22$str$, $str$3 Axis Mill$str$, NULL, 2.75, 8.57, 1.12, NULL, NULL, NULL, NULL),
      ($str$Makino V33i$str$, $str$3 Axis Mill$str$, NULL, 2.75, 12.53, 1.36, NULL, NULL, NULL, NULL),
      ($str$Makino V56i$str$, $str$3 Axis Mill$str$, NULL, 2.75, 15.07, 1.42, NULL, NULL, NULL, NULL),
      ($str$Mazak FH 12800$str$, $str$3 Axis Mill$str$, NULL, 2.75, 55.76, 2.16, NULL, NULL, NULL, NULL),
      ($str$Mazak FH 6000$str$, $str$3 Axis Mill$str$, NULL, 2.75, 30.38, 2.16, NULL, NULL, NULL, NULL),
      ($str$Mazak FH 8800$str$, $str$3 Axis Mill$str$, NULL, 2.75, 38.35, 2.16, NULL, NULL, NULL, NULL),
      ($str$Mazak PFH M 5800$str$, $str$3 Axis Mill$str$, NULL, 2.75, 26.53, 2.16, NULL, NULL, NULL, NULL),
      ($str$Mikron HSM 400$str$, $str$3 Axis Mill$str$, NULL, 2.75, 19.07, 1.96, NULL, NULL, NULL, NULL),
      ($str$Okuma MB-46VA$str$, $str$3 Axis Mill$str$, NULL, 2.75, 8.43, 1.35, NULL, NULL, NULL, NULL),
      ($str$Okuma MB-56VA$str$, $str$3 Axis Mill$str$, NULL, 2.75, 9.74, 1.56, NULL, NULL, NULL, NULL),
      ($str$Okuma MB-66VA$str$, $str$3 Axis Mill$str$, NULL, 2.75, 10.83, 1.74, NULL, NULL, NULL, NULL),
      ($str$Sodick MC640L$str$, $str$3 Axis Mill$str$, NULL, 2.75, 9.91, 2.16, NULL, NULL, NULL, NULL),
      ($str$Virtual 3 Axis Mill - Large$str$, $str$3 Axis Mill$str$, NULL, 2.75, 23.06, 3.43, NULL, NULL, NULL, NULL),
      ($str$Virtual 3 Axis Mill - Medium$str$, $str$3 Axis Mill$str$, NULL, 2.75, 11.22, 1.65, NULL, NULL, NULL, NULL),
      ($str$Virtual 3 Axis Mill - Small$str$, $str$3 Axis Mill$str$, NULL, 2.75, 9.86, 1.47, NULL, NULL, NULL, NULL),
      ($str$Boehringer VDF 400$str$, $str$3 Axis Lathe$str$, NULL, 2.75, 32.81, 2.48, NULL, NULL, NULL, NULL),
      ($str$Daewoo Puma 600$str$, $str$3 Axis Lathe$str$, NULL, 2.75, 16.93, 2.21, NULL, NULL, NULL, NULL),
      ($str$Daewoo Puma 700$str$, $str$3 Axis Lathe$str$, NULL, 2.75, 21.83, 2.69, NULL, NULL, NULL, NULL),
      ($str$Daewoo Puma 800$str$, $str$3 Axis Lathe$str$, NULL, 2.75, 26.68, 2.69, NULL, NULL, NULL, NULL),
      ($str$Daewoo Puma MX 2000/2500S$str$, $str$3 Axis Lathe$str$, NULL, 2.75, 23.36, 2.32, NULL, NULL, NULL, NULL),
      ($str$Daewoo Puma MX 2000/2500T$str$, $str$3 Axis Lathe$str$, NULL, 2.75, 21.15, 2.32, NULL, NULL, NULL, NULL),
      ($str$Haas SL 20$str$, $str$3 Axis Lathe$str$, NULL, 2.75, 7.23, 1.02, NULL, NULL, NULL, NULL),
      ($str$Haas SL 40L$str$, $str$3 Axis Lathe$str$, NULL, 2.75, 15.66, 2.25, NULL, NULL, NULL, NULL),
      ($str$Hardinge Quest 6/42 SP$str$, $str$3 Axis Lathe$str$, NULL, 2.75, 12.94, 1.15, NULL, NULL, NULL, NULL),
      ($str$Hardinge Quest 8/51 SP$str$, $str$3 Axis Lathe$str$, NULL, 2.75, 14.74, 1.15, NULL, NULL, NULL, NULL),
      ($str$INDEX Speedline C100$str$, $str$3 Axis Lathe$str$, NULL, 2.75, 10.95, 2.02, NULL, NULL, NULL, NULL),
      ($str$Miyano BNC-20$str$, $str$3 Axis Lathe$str$, NULL, 2.75, 4.73, 1.15, NULL, NULL, NULL, NULL),
      ($str$Miyano BND-20S5$str$, $str$3 Axis Lathe$str$, NULL, 2.75, 4.58, 1.15, NULL, NULL, NULL, NULL),
      ($str$Miyano BND-34T5$str$, $str$3 Axis Lathe$str$, NULL, 2.75, 8.46, 1.21, NULL, NULL, NULL, NULL),
      ($str$Miyano BND-34TR$str$, $str$3 Axis Lathe$str$, NULL, 2.75, 6.65, 1.21, NULL, NULL, NULL, NULL),
      ($str$Okuma 2SP-V760EX (M)$str$, $str$3 Axis Lathe$str$, NULL, 2.75, 20.75, 1.74, NULL, NULL, NULL, NULL),
      ($str$Okuma LB2000 EXII (M) Cx300$str$, $str$3 Axis Lathe$str$, NULL, 2.75, 11.15, 1.16, NULL, NULL, NULL, NULL),
      ($str$Okuma LB2000 EXII (M) Cx500$str$, $str$3 Axis Lathe$str$, NULL, 2.75, 11.46, 1.21, NULL, NULL, NULL, NULL),
      ($str$Okuma LB3000 EXII (M) T$str$, $str$3 Axis Lathe$str$, NULL, 2.75, 11.57, 1.28, NULL, NULL, NULL, NULL),
      ($str$Okuma V760EX (M)$str$, $str$3 Axis Lathe$str$, NULL, 2.75, 15.07, 1.3, NULL, NULL, NULL, NULL),
      ($str$Virtual 3 Axis Lathe - Large$str$, $str$3 Axis Lathe$str$, NULL, 2.75, 27.79, 2.14, NULL, NULL, NULL, NULL),
      ($str$Virtual 3 Axis Lathe - Medium$str$, $str$3 Axis Lathe$str$, NULL, 2.75, 11.96, 1.81, NULL, NULL, NULL, NULL),
      ($str$Virtual 3 Axis Lathe - Small$str$, $str$3 Axis Lathe$str$, NULL, 2.75, 7.32, 1.18, NULL, NULL, NULL, NULL),
      ($str$Haas DS-30 with BAR3010SS Feeder$str$, $str$Lathe with Bar Feeder$str$, NULL, 2.75, 11.84, 2.76, NULL, NULL, NULL, NULL),
      ($str$Haas DS-30SS with BAR3010SS Feeder$str$, $str$Lathe with Bar Feeder$str$, NULL, 2.75, 12.08, 2.76, NULL, NULL, NULL, NULL),
      ($str$Haas DS-30SSY with BAR3010SS Feeder$str$, $str$Lathe with Bar Feeder$str$, NULL, 2.75, 13.29, 2.76, NULL, NULL, NULL, NULL),
      ($str$Haas DS-30Y with BAR3010SS Feeder$str$, $str$Lathe with Bar Feeder$str$, NULL, 2.75, 13.05, 2.76, NULL, NULL, NULL, NULL),
      ($str$Acra 2800 CET$str$, $str$2 Axis Lathe$str$, NULL, 2.75, 5.19, 1.15, NULL, NULL, NULL, NULL),
      ($str$Acra 4400 HLA$str$, $str$2 Axis Lathe$str$, NULL, 2.75, 10.59, 1.15, NULL, NULL, NULL, NULL),
      ($str$Acra MT-34$str$, $str$2 Axis Lathe$str$, NULL, 2.75, 2.87, 1.27, NULL, NULL, NULL, NULL),
      ($str$Amera-Seiki T-90$str$, $str$2 Axis Lathe$str$, NULL, 2.75, 15.65, 1.63, NULL, NULL, NULL, NULL),
      ($str$Atrump 940C$str$, $str$2 Axis Lathe$str$, NULL, 2.75, 3.62, 1.11, NULL, NULL, NULL, NULL),
      ($str$Binns & Berry Data 2000 - 1250$str$, $str$2 Axis Lathe$str$, NULL, 2.75, 23.83, 1.15, NULL, NULL, NULL, NULL),
      ($str$Binns & Berry Data 3000 - 1250$str$, $str$2 Axis Lathe$str$, NULL, 2.75, 26.26, 1.15, NULL, NULL, NULL, NULL),
      ($str$DMG Mori Wasino G-07$str$, $str$2 Axis Lathe$str$, NULL, 2.75, 5.82, 1.07, NULL, NULL, NULL, NULL),
      ($str$DMG Mori Wasino J-1$str$, $str$2 Axis Lathe$str$, NULL, 2.75, 5.63, 1.08, NULL, NULL, NULL, NULL),
      ($str$Daewoo Puma 300 LC$str$, $str$2 Axis Lathe$str$, NULL, 2.75, 10.28, 1.55, NULL, NULL, NULL, NULL),
      ($str$Danobat VTC-1600$str$, $str$2 Axis Lathe$str$, NULL, 2.75, 78.8, 2.83, NULL, NULL, NULL, NULL),
      ($str$Danobat VTC-8000H$str$, $str$2 Axis Lathe$str$, NULL, 2.75, 245.92, 36.82, NULL, NULL, NULL, NULL),
      ($str$INDEX SpeedLine ABC$str$, $str$2 Axis Lathe$str$, NULL, 2.75, 13.92, 2.17, NULL, NULL, NULL, NULL),
      ($str$Mazak 6G$str$, $str$2 Axis Lathe$str$, NULL, 2.75, 2.6, 1.35, NULL, NULL, NULL, NULL),
      ($str$Mazak 6T$str$, $str$2 Axis Lathe$str$, NULL, 2.75, 2.84, 1.35, NULL, NULL, NULL, NULL),
      ($str$Mazak HQR-150MSY$str$, $str$2 Axis Lathe$str$, NULL, 2.75, 18.93, 1.43, NULL, NULL, NULL, NULL),
      ($str$Mazak HQR-200MS$str$, $str$2 Axis Lathe$str$, NULL, 2.75, 23, 1.66, NULL, NULL, NULL, NULL),
      ($str$Okuma Genos L250II$str$, $str$2 Axis Lathe$str$, NULL, 2.75, 9.84, 1.1, NULL, NULL, NULL, NULL),
      ($str$Okuma Genos L400II$str$, $str$2 Axis Lathe$str$, NULL, 2.75, 11.33, 1.23, NULL, NULL, NULL, NULL),
      ($str$Okuma HL - 20$str$, $str$2 Axis Lathe$str$, NULL, 2.75, 6.59, 1.12, NULL, NULL, NULL, NULL),
      ($str$Okuma HL - 35$str$, $str$2 Axis Lathe$str$, NULL, 2.75, 7.77, 1.21, NULL, NULL, NULL, NULL),
      ($str$Virtual 2 Axis Lathe - Large$str$, $str$2 Axis Lathe$str$, NULL, 2.75, 25.35, 2.14, NULL, NULL, NULL, NULL),
      ($str$Virtual 2 Axis Lathe - Medium$str$, $str$2 Axis Lathe$str$, NULL, 2.75, 9.12, 1.81, NULL, NULL, NULL, NULL),
      ($str$Virtual 2 Axis Lathe - Small$str$, $str$2 Axis Lathe$str$, NULL, 2.75, 5.38, 1.16, NULL, NULL, NULL, NULL),
      ($str$Carlton 5 ft X 13 in$str$, $str$Drilling$str$, NULL, 1.65, 1.84, 1.27, NULL, NULL, NULL, NULL),
      ($str$Cincinnati HD 8 X 20$str$, $str$Drilling$str$, NULL, 1.65, 2.51, 1.25, NULL, NULL, NULL, NULL),
      ($str$Delta 15-331$str$, $str$Drilling$str$, NULL, 1.65, 0.58, 0.99, NULL, NULL, NULL, NULL),
      ($str$Delta 15-344$str$, $str$Drilling$str$, NULL, 1.65, 0.65, 1, NULL, NULL, NULL, NULL),
      ($str$Jet JDP- 20Vs$str$, $str$Drilling$str$, NULL, 1.65, 0.49, 0.95, NULL, NULL, NULL, NULL),
      ($str$Knuth R100$str$, $str$Drilling$str$, NULL, 1.65, 3.2, 1.54, NULL, NULL, NULL, NULL),
      ($str$Rigid$str$, $str$Drilling$str$, NULL, 1.65, 0.62, 1.27, NULL, NULL, NULL, NULL),
      ($str$Syderic SRD 350$str$, $str$Drilling$str$, NULL, 1.65, 0.44, 1.27, NULL, NULL, NULL, NULL),
      ($str$Weiler Vo75$str$, $str$Drilling$str$, NULL, 1.65, 1.47, 1.31, NULL, NULL, NULL, NULL),
      ($str$Etch Cell - 1.8m x 1.0m x 1.2m Tank Size$str$, $str$Etching$str$, NULL, 2.75, 14.48, 1.19, NULL, NULL, NULL, NULL),
      ($str$Etch Cell - 12.2m x 2.1m x 3.0m Tank Size$str$, $str$Etching$str$, NULL, 2.75, 174.81, 5.41, NULL, NULL, NULL, NULL),
      ($str$Etch Cell - 3.6m x 2.1m x 2.4m Tank Size$str$, $str$Etching$str$, NULL, 2.75, 51.77, 2.18, NULL, NULL, NULL, NULL),
      ($str$Etch Cell - 7.2m x 4.2m x 4.8m Tank Size$str$, $str$Etching$str$, NULL, 2.75, 196.74, 6.14, NULL, NULL, NULL, NULL),
      ($str$Honge XE 1200-CNC$str$, $str$Deep Hole Drilling$str$, NULL, 1.65, 6.01, 3.48, NULL, NULL, NULL, NULL),
      ($str$Honge XL 10000$str$, $str$Deep Hole Drilling$str$, NULL, 1.65, 12.52, 4.53, NULL, NULL, NULL, NULL),
      ($str$Honge XL 9999$str$, $str$Deep Hole Drilling$str$, NULL, 1.65, 8.02, 2.49, NULL, NULL, NULL, NULL),
      ($str$Honge Xt 2500-CNC$str$, $str$Deep Hole Drilling$str$, NULL, 1.65, 7.19, 4.31, NULL, NULL, NULL, NULL),
      ($str$TechniDrill HS 375 CR$str$, $str$Deep Hole Drilling$str$, NULL, 1.65, 19.31, 2.49, NULL, NULL, NULL, NULL),
      ($str$TechniDrill TDS 100$str$, $str$Deep Hole Drilling$str$, NULL, 1.65, 12.91, 2.49, NULL, NULL, NULL, NULL),
      ($str$TechniDrill TDS 200$str$, $str$Deep Hole Drilling$str$, NULL, 1.65, 19.53, 2.49, NULL, NULL, NULL, NULL),
      ($str$TechniDrill TDS 50$str$, $str$Deep Hole Drilling$str$, NULL, 1.65, 9.82, 2.49, NULL, NULL, NULL, NULL),
      ($str$Gleason Genesis 130H Vertical$str$, $str$Gear Hobbing$str$, NULL, 1.73, 28.11, 1.46, NULL, NULL, NULL, NULL),
      ($str$Gleason Genesis 400GH Medium Cylindrical$str$, $str$Gear Hobbing$str$, NULL, 1.73, 33.95, 1.37, NULL, NULL, NULL, NULL),
      ($str$Gleason P60 Horizontal$str$, $str$Gear Hobbing$str$, NULL, 1.73, 26.37, 1.79, NULL, NULL, NULL, NULL),
      ($str$Gleason P800 Large Cylindrical$str$, $str$Gear Hobbing$str$, NULL, 1.73, 49.89, 4.36, NULL, NULL, NULL, NULL),
      ($str$Danobat Overbeck IC/ID$str$, NULL, $str$UNIDENTIFIED-04$str$, 1.65, 9.93, 2.49, NULL, NULL, NULL, NULL),
      ($str$Danobat Overbeck IG$str$, NULL, $str$UNIDENTIFIED-04$str$, 1.65, 8.61, 2.49, NULL, NULL, NULL, NULL),
      ($str$FlexGrind M$str$, NULL, $str$UNIDENTIFIED-04$str$, 1.65, 21.08, 2.49, NULL, NULL, NULL, NULL),
      ($str$FlexGrind S$str$, NULL, $str$UNIDENTIFIED-04$str$, 1.65, 17.54, 2.49, NULL, NULL, NULL, NULL),
      ($str$Kellenberger KEL Universal$str$, NULL, $str$UNIDENTIFIED-04$str$, 1.65, 22.33, 1.88, NULL, NULL, NULL, NULL),
      ($str$Kellenberger KEL VARIA$str$, NULL, $str$UNIDENTIFIED-04$str$, 1.65, 17.1, 1.67, NULL, NULL, NULL, NULL),
      ($str$Matrix 6950$str$, NULL, $str$UNIDENTIFIED-04$str$, 1.65, 17.9, 1.93, NULL, NULL, NULL, NULL),
      ($str$Studer CT550$str$, NULL, $str$UNIDENTIFIED-04$str$, 1.65, 17.9, 2.49, NULL, NULL, NULL, NULL),
      ($str$Studer s120$str$, NULL, $str$UNIDENTIFIED-04$str$, 1.65, 16.61, 1.94, NULL, NULL, NULL, NULL),
      ($str$Studer s145$str$, NULL, $str$UNIDENTIFIED-04$str$, 1.65, 16.33, 2.17, NULL, NULL, NULL, NULL),
      ($str$Danobat RTU$str$, NULL, $str$UNIDENTIFIED-05$str$, 1.73, 13.88, 1.27, NULL, NULL, NULL, NULL),
      ($str$Delta LB 300$str$, NULL, $str$UNIDENTIFIED-05$str$, 1.73, 1.13, 0.93, NULL, NULL, NULL, NULL),
      ($str$Delta LP 500$str$, NULL, $str$UNIDENTIFIED-05$str$, 1.73, 1.59, 0.95, NULL, NULL, NULL, NULL),
      ($str$Huron 1730 x 930 x 550$str$, NULL, $str$UNIDENTIFIED-05$str$, 1.73, 5.1, 1.27, NULL, NULL, NULL, NULL),
      ($str$Huron 3200 x 1580 x 630$str$, NULL, $str$UNIDENTIFIED-05$str$, 1.73, 7.01, 1.27, NULL, NULL, NULL, NULL),
      ($str$Loeser FS 386$str$, NULL, $str$UNIDENTIFIED-05$str$, 1.73, 3.38, 1.27, NULL, NULL, NULL, NULL),
      ($str$Loeser FS 387$str$, NULL, $str$UNIDENTIFIED-05$str$, 1.73, 3.83, 1.27, NULL, NULL, NULL, NULL),
      ($str$Wolters TFG 150$str$, NULL, $str$UNIDENTIFIED-05$str$, 1.73, 13.93, 1.16, NULL, NULL, NULL, NULL),
      ($str$ABA Z&B MR$str$, NULL, $str$UNIDENTIFIED-06$str$, 1.65, 17.68, 2.49, NULL, NULL, NULL, NULL),
      ($str$ABA Z&B MRV$str$, NULL, $str$UNIDENTIFIED-06$str$, 1.65, 20.68, 2.49, NULL, NULL, NULL, NULL),
      ($str$Danobat DAN-VTG$str$, NULL, $str$UNIDENTIFIED-06$str$, 1.65, 33.76, 2.49, NULL, NULL, NULL, NULL),
      ($str$Danobat IEV$str$, NULL, $str$UNIDENTIFIED-06$str$, 1.65, 19.27, 2.49, NULL, NULL, NULL, NULL),
      ($str$Delta LC 500$str$, NULL, $str$UNIDENTIFIED-06$str$, 1.65, 16.37, 2.49, NULL, NULL, NULL, NULL),
      ($str$Delta LF 350$str$, NULL, $str$UNIDENTIFIED-06$str$, 1.65, 16.37, 2.49, NULL, NULL, NULL, NULL),
      ($str$SIP Hydroptic 6A$str$, $str$Jig Boring$str$, NULL, 1.65, 7.44, 1.09, NULL, NULL, NULL, NULL),
      ($str$Virtual CNC Jig Bore$str$, $str$Jig Boring$str$, NULL, 1.65, 19.51, 1.09, NULL, NULL, NULL, NULL),
      ($str$Virtual Manual Jig Bore$str$, $str$Jig Boring$str$, NULL, 1.65, 7.44, 1.09, NULL, NULL, NULL, NULL),
      ($str$YASDA YBM1218V Jig Bore$str$, $str$Jig Boring$str$, NULL, 1.65, 19.51, 1.09, NULL, NULL, NULL, NULL),
      ($str$Hauser S3-DR$str$, $str$Jig Grinding$str$, NULL, 1.65, 7.75, 1.09, NULL, NULL, NULL, NULL),
      ($str$Mitsui Seiki J4GDN CNC Jig Grinder$str$, $str$Jig Grinding$str$, NULL, 1.65, 14.24, 1.09, NULL, NULL, NULL, NULL),
      ($str$Virtual CNC Jig Grinder$str$, $str$Jig Grinding$str$, NULL, 1.65, 14.24, 1.09, NULL, NULL, NULL, NULL),
      ($str$Virtual Manual Jig Grinder$str$, $str$Jig Grinding$str$, NULL, 1.65, 7.75, 1.09, NULL, NULL, NULL, NULL),
      ($str$Default Manual Deburr$str$, $str$Manual Deburring$str$, NULL, 1.65, 0.21, 0.88, NULL, NULL, NULL, NULL),
      ($str$Curing Oven - 1.3m x 1.3m x 1.4m Useable Oven Size$str$, $str$Curing and Drying$str$, NULL, 1.65, 1.38, 1.04, NULL, NULL, NULL, NULL),
      ($str$Curing Oven - 12.1m x 2.1m x 4.0m Useable Oven Size$str$, $str$Curing and Drying$str$, NULL, 1.65, 29.89, 2.17, NULL, NULL, NULL, NULL),
      ($str$Curing Oven - 2.9m x 2.5m x 2.0m Useable Oven Size$str$, $str$Curing and Drying$str$, NULL, 1.65, 4.84, 1.33, NULL, NULL, NULL, NULL),
      ($str$Curing Oven - 5.5m x 4.1m x 3.0m Useable Oven Size$str$, $str$Curing and Drying$str$, NULL, 1.65, 19.98, 1.88, NULL, NULL, NULL, NULL),
      ($str$Curing Oven Overhead Conveyor - 5.9m x 3.3m x 2.8m Useable Oven Size$str$, $str$Curing and Drying$str$, NULL, 1.65, 16.07, 2.03, NULL, NULL, NULL, NULL),
      ($str$Drying Room - 1.3m x 1.3m x 1.4m Useable Drying Room Size$str$, $str$Curing and Drying$str$, NULL, 1.65, 0.17, 1.04, NULL, NULL, NULL, NULL),
      ($str$Drying Room - 12.1m x 2.1m x 4.0m Useable Drying Room Size$str$, $str$Curing and Drying$str$, NULL, 1.65, 3.74, 2.17, NULL, NULL, NULL, NULL),
      ($str$Drying Room - 2.9m x 2.5m x 2.0m Useable Drying Room Size$str$, $str$Curing and Drying$str$, NULL, 1.65, 0.61, 1.33, NULL, NULL, NULL, NULL),
      ($str$Drying Room - 5.5m x 4.1m x 3.0m Useable Drying Room Size$str$, $str$Curing and Drying$str$, NULL, 1.65, 2.5, 1.88, NULL, NULL, NULL, NULL),
      ($str$Drying Room Overhead Conveyor - 5.9m x 3.3m x 2.8m Useable Drying Room Size$str$, $str$Curing and Drying$str$, NULL, 1.65, 2.01, 2.03, NULL, NULL, NULL, NULL),
      ($str$GILDEMEISTER GMX 400 LINEAR$str$, $str$Mill Turn$str$, NULL, 2.75, 30.03, 3.34, NULL, NULL, NULL, NULL),
      ($str$INDEX RatioLine G200$str$, $str$Mill Turn$str$, NULL, 2.75, 27.42, 1.65, NULL, NULL, NULL, NULL),
      ($str$Mazak Integrex e-410H-S II$str$, $str$Mill Turn$str$, NULL, 2.75, 42.43, 2.85, NULL, NULL, NULL, NULL),
      ($str$Mazak Integrex e-500H-S II$str$, $str$Mill Turn$str$, NULL, 2.75, 53.21, 3.81, NULL, NULL, NULL, NULL),
      ($str$Mazak Integrex e-650H-S II$str$, $str$Mill Turn$str$, NULL, 2.75, 67.34, 4.35, NULL, NULL, NULL, NULL),
      ($str$Mazak Integrex e650$str$, $str$Mill Turn$str$, NULL, 2.75, 58.45, 3.69, NULL, NULL, NULL, NULL),
      ($str$Virtual MillTurn$str$, $str$Mill Turn$str$, NULL, 2.75, 40.51, 1.66, NULL, NULL, NULL, NULL),
      ($str$Gleason 300 TWG$str$, $str$Threaded Wheel Gear Grinder$str$, NULL, 1.73, 87.67, 2.89, NULL, NULL, NULL, NULL),
      ($str$Gleason Genesis 160TWG$str$, $str$Threaded Wheel Gear Grinder$str$, NULL, 1.73, 78.15, 1.54, NULL, NULL, NULL, NULL),
      ($str$Gleason P 2400 G$str$, $str$Profile Gear Grinder$str$, NULL, 1.73, 87.55, 7.16, NULL, NULL, NULL, NULL),
      ($str$Gleason P 3200 G$str$, $str$Profile Gear Grinder$str$, NULL, 1.73, 96.95, 10.18, NULL, NULL, NULL, NULL),
      ($str$Gleason P 6000 G$str$, $str$Profile Gear Grinder$str$, NULL, 1.73, 120.44, 7.16, NULL, NULL, NULL, NULL),
      ($str$Gleason P 800 G$str$, $str$Profile Gear Grinder$str$, NULL, 1.73, 78.15, 5.82, NULL, NULL, NULL, NULL),
      ($str$Gleason P 90 G$str$, $str$Profile Gear Grinder$str$, NULL, 1.73, 67.52, 2.09, NULL, NULL, NULL, NULL),
      ($str$Gleason Titan 1200G$str$, $str$Gear Grinding$str$, NULL, 1.73, 97.2, 3.83, NULL, NULL, NULL, NULL),
      ($str$Reishauer RZ 1000$str$, $str$Gear Grinding$str$, NULL, 1.73, 92.3, 1.78, NULL, NULL, NULL, NULL),
      ($str$Reishauer RZ 550$str$, $str$Gear Grinding$str$, NULL, 1.73, 82.85, 1.74, NULL, NULL, NULL, NULL),
      ($str$Reishauer RZ 60$str$, $str$Gear Grinding$str$, NULL, 1.73, 72.21, 1.74, NULL, NULL, NULL, NULL),
      ($str$Laser Scribe - 0.35m x 0.35m x 0.35m Bed Size$str$, $str$Laser Processing$str$, NULL, 2.75, 10.48, 1.08, NULL, NULL, NULL, NULL),
      ($str$Laserdyne Systems 450$str$, $str$Laser Processing$str$, NULL, 2.75, 10.48, 1.08, NULL, NULL, NULL, NULL),
      ($str$Laserdyne Systems 795XL$str$, $str$Laser Processing$str$, NULL, 2.75, 22.67, 1.39, NULL, NULL, NULL, NULL),
      ($str$Laser Scribe - 1.5m x 1m x 1m Bed Size$str$, $str$Laser Processing$str$, NULL, 2.75, 21.46, 1.34, NULL, NULL, NULL, NULL),
      ($str$Laserdyne Systems 795XS$str$, $str$Laser Processing$str$, NULL, 2.75, 20.25, 1.3, NULL, NULL, NULL, NULL),
      ($str$Gantry Laser Scribe - 15m x 4m x 1.5m Bed Size$str$, $str$Laser Processing$str$, NULL, 2.75, 92.62, 8.14, NULL, NULL, NULL, NULL),
      ($str$Gantry Laser Scribe - 2.4m x 1.8m x 0.9m Bed Size$str$, $str$Laser Processing$str$, NULL, 2.75, 39.11, 1.88, NULL, NULL, NULL, NULL),
      ($str$Laserdyne Systems 890$str$, $str$Laser Processing$str$, NULL, 2.75, 39.11, 1.88, NULL, NULL, NULL, NULL),
      ($str$mTorres TorresLaser$str$, $str$Laser Processing$str$, NULL, 2.75, 92.62, 8.14, NULL, NULL, NULL, NULL),
      ($str$Gleason 800ES Shaper$str$, $str$Gear Shaping$str$, NULL, 1.65, 57.84, 6.82, NULL, NULL, NULL, NULL),
      ($str$Gleason GP300S Shaper$str$, $str$Gear Shaping$str$, NULL, 1.65, 55.1, 3.54, NULL, NULL, NULL, NULL),
      ($str$Mitsubishi SE15A$str$, $str$Gear Shaping$str$, NULL, 1.65, 29.49, 1.97, NULL, NULL, NULL, NULL),
      ($str$Gleason Genesis 130 SV$str$, $str$Gear Shaving$str$, NULL, 1.73, 34.07, 1.43, NULL, NULL, NULL, NULL),
      ($str$Gleason ZS300 Gear Shaver$str$, $str$Gear Shaving$str$, NULL, 1.73, 37.41, 1.57, NULL, NULL, NULL, NULL),
      ($str$DMG Mori GMC25ISM-6$str$, $str$Multi-Spindle Turning$str$, NULL, 2.75, 41.84, 1.55, NULL, NULL, NULL, NULL),
      ($str$Dooson Puma TT2500SY$str$, $str$Multi-Spindle Turning$str$, NULL, 2.75, 22.97, 1.66, NULL, NULL, NULL, NULL),
      ($str$HAAS DS-30Y$str$, $str$Multi-Spindle Turning$str$, NULL, 2.75, 11.99, 2.07, NULL, NULL, NULL, NULL),
      ($str$Index MS16C-6$str$, $str$Multi-Spindle Turning$str$, NULL, 2.75, 54.6, 1.16, NULL, NULL, NULL, NULL),
      ($str$Index MS22-8$str$, $str$Multi-Spindle Turning$str$, NULL, 2.75, 92.04, 1.46, NULL, NULL, NULL, NULL),
      ($str$Index MS32-6$str$, $str$Multi-Spindle Turning$str$, NULL, 2.75, 72.28, 1.44, NULL, NULL, NULL, NULL),
      ($str$Index MS40-8$str$, $str$Multi-Spindle Turning$str$, NULL, 2.75, 100.24, 1.61, NULL, NULL, NULL, NULL),
      ($str$Tsugami M08SY$str$, $str$Multi-Spindle Turning$str$, NULL, 2.75, 10.14, 1.26, NULL, NULL, NULL, NULL),
      ($str$Virtual CNC Multi-Spindle, 6 Spindles, Large$str$, $str$Multi-Spindle Turning$str$, NULL, 2.75, 74.74, 1.73, NULL, NULL, NULL, NULL),
      ($str$Virtual CNC Multi-Spindle, 6 Spindles, Small$str$, $str$Multi-Spindle Turning$str$, NULL, 2.75, 43.78, 1.16, NULL, NULL, NULL, NULL),
      ($str$Virtual CNC Multi-Spindle, 8 Spindles, Large$str$, $str$Multi-Spindle Turning$str$, NULL, 2.75, 100.24, 2.84, NULL, NULL, NULL, NULL),
      ($str$Virtual CNC Multi-Spindle, 8 Spindles, Small$str$, $str$Multi-Spindle Turning$str$, NULL, 2.75, 80.85, 1.47, NULL, NULL, NULL, NULL),
      ($str$Virtual CNC Turning Center with Sub Spindle, Large$str$, $str$Multi-Spindle Turning$str$, NULL, 2.75, 25.39, 2.04, NULL, NULL, NULL, NULL),
      ($str$Virtual CNC Turning Center with Sub Spindle, Medium$str$, $str$Multi-Spindle Turning$str$, NULL, 2.75, 15.28, 1.47, NULL, NULL, NULL, NULL),
      ($str$Virtual CNC Turning Center with Sub Spindle, Small$str$, $str$Multi-Spindle Turning$str$, NULL, 2.75, 11, 1.12, NULL, NULL, NULL, NULL),
      ($str$Default$str$, NULL, $str$UNIDENTIFIED-03$str$, 2.75, 0.86, 0.88, NULL, NULL, NULL, NULL),
      ($str$Yieh Chen YC-800$str$, $str$Spline Rolling$str$, NULL, 2.3, 10.22, 1.85, NULL, NULL, NULL, NULL),
      ($str$Default$str$, NULL, $str$UNIDENTIFIED-02$str$, 2.3, 0.24, 0.88, NULL, NULL, NULL, NULL),
      ($str$Acra 2800 CET$str$, NULL, $str$UNIDENTIFIED-07$str$, 1.73, 5.19, 1.7, NULL, NULL, NULL, NULL),
      ($str$Acra 4400 HLA$str$, NULL, $str$UNIDENTIFIED-07$str$, 1.73, 10.59, 1.7, NULL, NULL, NULL, NULL),
      ($str$Acra MT-34$str$, NULL, $str$UNIDENTIFIED-07$str$, 1.73, 2.87, 1.27, NULL, NULL, NULL, NULL),
      ($str$Amera-Seiki T-90$str$, NULL, $str$UNIDENTIFIED-07$str$, 1.73, 15.65, 1.63, NULL, NULL, NULL, NULL),
      ($str$Atrump 940C$str$, NULL, $str$UNIDENTIFIED-07$str$, 1.73, 3.62, 1.11, NULL, NULL, NULL, NULL),
      ($str$Binns & Berry Data 2000 - 1250$str$, NULL, $str$UNIDENTIFIED-07$str$, 1.73, 23.83, 1.15, NULL, NULL, NULL, NULL),
      ($str$Binns & Berry Data 3000 - 1250$str$, NULL, $str$UNIDENTIFIED-07$str$, 1.73, 26.26, 1.15, NULL, NULL, NULL, NULL),
      ($str$Boehringer VDF 400$str$, NULL, $str$UNIDENTIFIED-07$str$, 1.73, 32.81, 1.44, NULL, NULL, NULL, NULL),
      ($str$Daewoo Puma 300 LC$str$, NULL, $str$UNIDENTIFIED-07$str$, 1.73, 10.28, 1.55, NULL, NULL, NULL, NULL),
      ($str$Daewoo Puma 600$str$, NULL, $str$UNIDENTIFIED-07$str$, 1.73, 16.93, 2.21, NULL, NULL, NULL, NULL),
      ($str$Daewoo Puma 700$str$, NULL, $str$UNIDENTIFIED-07$str$, 1.73, 21.83, 2.69, NULL, NULL, NULL, NULL),
      ($str$Daewoo Puma 800$str$, NULL, $str$UNIDENTIFIED-07$str$, 1.73, 26.68, 2.69, NULL, NULL, NULL, NULL),
      ($str$Daewoo Puma MX 2000/2500S$str$, NULL, $str$UNIDENTIFIED-07$str$, 1.73, 23.36, 2.32, NULL, NULL, NULL, NULL),
      ($str$Daewoo Puma MX 2000/2500T$str$, NULL, $str$UNIDENTIFIED-07$str$, 1.73, 21.15, 2.32, NULL, NULL, NULL, NULL),
      ($str$Haas SL 20$str$, NULL, $str$UNIDENTIFIED-07$str$, 1.73, 7.23, 1.02, NULL, NULL, NULL, NULL),
      ($str$Haas SL 40L$str$, NULL, $str$UNIDENTIFIED-07$str$, 1.73, 15.66, 2.25, NULL, NULL, NULL, NULL),
      ($str$Hardinge Quest 6/42 SP$str$, NULL, $str$UNIDENTIFIED-07$str$, 1.73, 12.94, 1.12, NULL, NULL, NULL, NULL),
      ($str$Hardinge Quest 8/51 SP$str$, NULL, $str$UNIDENTIFIED-07$str$, 1.73, 14.74, 1.15, NULL, NULL, NULL, NULL),
      ($str$Mazak 6G$str$, NULL, $str$UNIDENTIFIED-07$str$, 1.73, 2.6, 1.35, NULL, NULL, NULL, NULL),
      ($str$Mazak 6T$str$, NULL, $str$UNIDENTIFIED-07$str$, 1.73, 2.84, 1.35, NULL, NULL, NULL, NULL),
      ($str$Miyano BNC-20$str$, NULL, $str$UNIDENTIFIED-07$str$, 1.73, 4.73, 1.15, NULL, NULL, NULL, NULL),
      ($str$Miyano BND-20S5$str$, NULL, $str$UNIDENTIFIED-07$str$, 1.73, 4.58, 1.15, NULL, NULL, NULL, NULL),
      ($str$Miyano BND-34T5$str$, NULL, $str$UNIDENTIFIED-07$str$, 1.73, 8.46, 1.21, NULL, NULL, NULL, NULL),
      ($str$Miyano BND-34TR$str$, NULL, $str$UNIDENTIFIED-07$str$, 1.73, 6.65, 1.21, NULL, NULL, NULL, NULL),
      ($str$Fanuc 0id$str$, $str$Wire EDM$str$, NULL, 2.75, 7.71, 1.32, $str$16.1 hp, 28 in max part length, 24 in max part width$str$, 12.005768, 711.2, 609.6),
      ($str$Fanuc 1id$str$, $str$Wire EDM$str$, NULL, 2.75, 8.23, 1.84, $str$20.1 hp, 30 in max part length, 24 in max part width$str$, 14.988567, 762, 609.6),
      ($str$Makino DUO43$str$, $str$Wire EDM$str$, NULL, 2.75, 7.48, 2.49, $str$13.4 hp, 34 in max part length, 30 in max part width$str$, 9.992378, 863.6, 762),
      ($str$Mitsubishi BA24$str$, $str$Wire EDM$str$, NULL, 2.75, 7, 2.49, $str$10.9 hp, 35 in max part length, 27 in max part width$str$, 8.128129, 889, 685.8),
      ($str$Mitsubishi FA-50V$str$, $str$Wire EDM$str$, NULL, 2.75, 7.16, 2.49, $str$12.75 hp, 65 in max part length, 54 in max part width$str$, 9.507673, 1651, 1371.6),
      ($str$Mitsubishi MD+PRO II$str$, $str$Wire EDM$str$, NULL, 2.75, 7, 2.49, $str$10.9 hp, 28 in max part length, 22 in max part width$str$, 8.128129, 711.2, 558.8),
      ($str$Accurl Hydraulic Press HBP-40$str$, NULL, NULL, 1.49, 2.44, 1.1, NULL, NULL, NULL, NULL),
      ($str$Accurl Hydraulic Press HSP-200$str$, NULL, NULL, 1.49, 12.43, 1.34, NULL, NULL, NULL, NULL),
      ($str$Accurl Hydraulic Press HSP-250$str$, NULL, NULL, 1.49, 15.85, 1.38, NULL, NULL, NULL, NULL),
      ($str$Accurl Hydraulic Press HSP-315$str$, NULL, NULL, 1.49, 19.87, 1.92, NULL, NULL, NULL, NULL),
      ($str$Accurl Hydraulic Press HSP-400$str$, NULL, NULL, 1.49, 24.86, 1.71, NULL, NULL, NULL, NULL),
      ($str$Accurl Hydraulic Press HSP-500$str$, NULL, NULL, 1.49, 31.7, 1.57, NULL, NULL, NULL, NULL),
      ($str$Accurl Hydraulic Press HSP-630$str$, NULL, NULL, 1.49, 38.01, 2.12, NULL, NULL, NULL, NULL),
      ($str$Accurl Hydraulic Press HSP-800$str$, NULL, NULL, 1.49, 47.99, 2.04, NULL, NULL, NULL, NULL),
      ($str$Hydraulic Compression Molding Press - 10,000kN | 2.0m x 1.8m$str$, NULL, NULL, 1.49, 68.14, 2.04, NULL, NULL, NULL, NULL),
      ($str$Hydraulic Compression Molding Press - 20,000kN | 3.0m x 2.0m$str$, NULL, NULL, 1.49, 123.9, 3.09, NULL, NULL, NULL, NULL),
      ($str$Hydraulic Compression Molding Press - 3,000kN | 1.25m x 1.0m$str$, NULL, NULL, 1.49, 17.04, 1.38, NULL, NULL, NULL, NULL),
      ($str$Hydraulic Compression Molding Press - 30,000kN | 3.4m x 2.4m$str$, NULL, NULL, 1.49, 175.94, 5.02, NULL, NULL, NULL, NULL),
      ($str$Hydraulic Compression Molding Press - 40,000kN | 4.0m x 3.0m$str$, NULL, NULL, 1.49, 241.61, 5.02, NULL, NULL, NULL, NULL),
      ($str$Hydraulic Compression Molding Press - 5,000kN | 1.6m x 1.2m$str$, NULL, NULL, 1.49, 30.46, 1.64, NULL, NULL, NULL, NULL),
      ($str$Hydraulic Compression Molding Press - 50,000kN | 5.0m x 3.0m$str$, NULL, NULL, 1.49, 322.14, 7.99, NULL, NULL, NULL, NULL),
      ($str$Hydraulic Compression Molding Press - 8,000kN | 2.4m x 1.7m$str$, NULL, NULL, 1.49, 47.5, 2.1, NULL, NULL, NULL, NULL),
      ($str$Pengda Hydraulic Press YP78-1000$str$, NULL, NULL, 1.49, 68.14, 2.04, NULL, NULL, NULL, NULL),
      ($str$Pengda Hydraulic Press YP78-1500$str$, NULL, NULL, 1.49, 97.88, 2.46, NULL, NULL, NULL, NULL),
      ($str$Pengda Hydraulic Press YP78-2000$str$, NULL, NULL, 1.49, 123.9, 3.09, NULL, NULL, NULL, NULL),
      ($str$Pengda Hydraulic Press YP78-2500$str$, NULL, NULL, 1.49, 146.2, 4.36, NULL, NULL, NULL, NULL),
      ($str$Pengda Hydraulic Press YP78-3000$str$, NULL, NULL, 1.49, 175.94, 5.02, NULL, NULL, NULL, NULL),
      ($str$Pengda Hydraulic Press YP78-4000$str$, NULL, NULL, 1.49, 241.61, 5.02, NULL, NULL, NULL, NULL),
      ($str$Pengda Hydraulic Press YP78-500$str$, NULL, NULL, 1.49, 47.5, 1.68, NULL, NULL, NULL, NULL),
      ($str$Arburg Allrounder 221 K$str$, NULL, NULL, 1.65, 4.11, 1.07, NULL, NULL, NULL, NULL),
      ($str$Arburg Allrounder 270 C 300 - 100$str$, NULL, NULL, 1.65, 3.86, 1.18, NULL, NULL, NULL, NULL),
      ($str$Arburg Allrounder 320 C 600 - 250$str$, NULL, NULL, 1.65, 6.57, 1.18, NULL, NULL, NULL, NULL),
      ($str$Arburg Allrounder 370 C 800 - 250$str$, NULL, NULL, 1.65, 7.51, 1.43, NULL, NULL, NULL, NULL),
      ($str$Arburg Allrounder 420 C 1300 - 350$str$, NULL, NULL, 1.65, 11.48, 1.26, NULL, NULL, NULL, NULL),
      ($str$Arburg Allrounder 520 C 2000 - 800$str$, NULL, NULL, 1.65, 16.82, 1.48, NULL, NULL, NULL, NULL),
      ($str$Engel DUO 130000 / 3500$str$, NULL, NULL, 1.65, 225.97, 6.81, NULL, NULL, NULL, NULL),
      ($str$Engel DUO 16050 / 2300$str$, NULL, NULL, 1.65, 151.29, 4.47, NULL, NULL, NULL, NULL),
      ($str$Engel DUO 2550 / 650$str$, NULL, NULL, 1.65, 39.65, 2.13, NULL, NULL, NULL, NULL),
      ($str$Engel DUO 35050 / 3200$str$, NULL, NULL, 1.65, 215.3, 5.74, NULL, NULL, NULL, NULL),
      ($str$Engel DUO 4550 / 900$str$, NULL, NULL, 1.65, 59.9, 2.58, NULL, NULL, NULL, NULL),
      ($str$Engel DUO 7050 / 1500$str$, NULL, NULL, 1.65, 96.64, 3.36, NULL, NULL, NULL, NULL),
      ($str$Engel DUO 75050 / 4000$str$, NULL, NULL, 1.65, 269.75, 7.49, NULL, NULL, NULL, NULL),
      ($str$Injection Molder 1,000kN Clamp Force$str$, NULL, NULL, 1.65, 6.61, 1.19, NULL, NULL, NULL, NULL),
      ($str$Injection Molder 2,000kN Clamp Force$str$, NULL, NULL, 1.65, 16.1, 1.6, NULL, NULL, NULL, NULL),
      ($str$Injection Molder 3,500kN Clamp Force$str$, NULL, NULL, 1.65, 23.55, 2.17, NULL, NULL, NULL, NULL),
      ($str$Injection Molder 5,000kN Clamp Force$str$, NULL, NULL, 1.65, 36.76, 2.9, NULL, NULL, NULL, NULL),
      ($str$Injection Molder 7,500kN Clamp Force$str$, NULL, NULL, 1.65, 55.17, 4.53, NULL, NULL, NULL, NULL),
      ($str$Injection Molder 10,000kN Clamp Force$str$, NULL, NULL, 1.65, 92.34, 6.36, NULL, NULL, NULL, NULL),
      ($str$Injection Molder 30,000kN Clamp Force$str$, NULL, NULL, 1.65, 173.85, 8.93, NULL, NULL, NULL, NULL),
      ($str$Injection Molder 50,000kN Clamp Force$str$, NULL, NULL, 1.65, 306.15, 11.05, NULL, NULL, NULL, NULL),
      ($str$Kawaguchi KM50$str$, NULL, NULL, 1.65, 4.4, 1.06, NULL, NULL, NULL, NULL),
      ($str$Kawaguchi KM80$str$, NULL, NULL, 1.65, 6.63, 1.09, NULL, NULL, NULL, NULL),
      ($str$Kawaguchi KM100$str$, NULL, NULL, 1.65, 8.23, 1.16, NULL, NULL, NULL, NULL),
      ($str$Kawaguchi KM140$str$, NULL, NULL, 1.65, 10.77, 1.24, NULL, NULL, NULL, NULL),
      ($str$Kawaguchi KM180$str$, NULL, NULL, 1.65, 13.96, 1.3, NULL, NULL, NULL, NULL),
      ($str$Kawaguchi KM220$str$, NULL, NULL, 1.65, 16.21, 1.36, NULL, NULL, NULL, NULL),
      ($str$Kawaguchi KM280$str$, NULL, NULL, 1.65, 20.14, 1.51, NULL, NULL, NULL, NULL),
      ($str$Kawaguchi KM360$str$, NULL, NULL, 1.65, 25.5, 1.6, NULL, NULL, NULL, NULL),
      ($str$Kawaguchi KM450$str$, NULL, NULL, 1.65, 31.56, 1.68, NULL, NULL, NULL, NULL),
      ($str$Kawaguchi KM550$str$, NULL, NULL, 1.65, 38.61, 1.77, NULL, NULL, NULL, NULL),
      ($str$Kawaguchi KM650$str$, NULL, NULL, 1.65, 46.77, 1.9, NULL, NULL, NULL, NULL),
      ($str$KraussMaffei 35 CX - 180$str$, NULL, NULL, 1.65, 4.01, 1.16, NULL, NULL, NULL, NULL),
      ($str$KraussMaffei 50 AX - 100$str$, NULL, NULL, 1.65, 4.28, 1.26, NULL, NULL, NULL, NULL),
      ($str$KraussMaffei 160 CX - 380$str$, NULL, NULL, 1.65, 11.61, 1.29, NULL, NULL, NULL, NULL),
      ($str$KraussMaffei 200 AX - 1400$str$, NULL, NULL, 1.65, 15.97, 1.72, NULL, NULL, NULL, NULL),
      ($str$KraussMaffei 240 EX - 1000$str$, NULL, NULL, 1.65, 23.9, 1.82, NULL, NULL, NULL, NULL),
      ($str$KraussMaffei 300 AX - 2000$str$, NULL, NULL, 1.65, 23.27, 1.99, NULL, NULL, NULL, NULL),
      ($str$KraussMaffei 350 CX - 2000$str$, NULL, NULL, 1.65, 25.7, 1.77, NULL, NULL, NULL, NULL),
      ($str$KraussMaffei 650 CX - 8100$str$, NULL, NULL, 1.65, 44.11, 2.61, NULL, NULL, NULL, NULL),
      ($str$KraussMaffei 1000 MX - 17200$str$, NULL, NULL, 1.65, 84.68, 3.4, NULL, NULL, NULL, NULL),
      ($str$KraussMaffei 1600 MX - 12000$str$, NULL, NULL, 1.65, 99.36, 4.05, NULL, NULL, NULL, NULL),
      ($str$KraussMaffei 3200 MX - 24500$str$, NULL, NULL, 1.65, 165.22, 6.01, NULL, NULL, NULL, NULL),
      ($str$KraussMaffei 4000 MX - 75000$str$, NULL, NULL, 1.65, 206.41, 7.38, NULL, NULL, NULL, NULL),
      ($str$Milacron 225$str$, NULL, NULL, 1.65, 15.31, 1.49, NULL, NULL, NULL, NULL),
      ($str$Milacron 310 WP$str$, NULL, NULL, 1.65, 22.17, 1.73, NULL, NULL, NULL, NULL),
      ($str$Milacron 450$str$, NULL, NULL, 1.65, 30.44, 1.77, NULL, NULL, NULL, NULL),
      ($str$Milacron 550$str$, NULL, NULL, 1.65, 39.5, 2.03, NULL, NULL, NULL, NULL),
      ($str$Milacron 580 WP$str$, NULL, NULL, 1.65, 40.91, 2.23, NULL, NULL, NULL, NULL),
      ($str$Milacron 725$str$, NULL, NULL, 1.65, 47.7, 2.31, NULL, NULL, NULL, NULL),
      ($str$Milacron 880 WP$str$, NULL, NULL, 1.65, 59.84, 2.35, NULL, NULL, NULL, NULL),
      ($str$Milacron 1000$str$, NULL, NULL, 1.65, 63.03, 2.99, NULL, NULL, NULL, NULL),
      ($str$Milacron 1100$str$, NULL, NULL, 1.65, 65.96, 2.99, NULL, NULL, NULL, NULL),
      ($str$Milacron 1500$str$, NULL, NULL, 1.65, 87.27, 3.29, NULL, NULL, NULL, NULL),
      ($str$Milacron 1760$str$, NULL, NULL, 1.65, 99.21, 3.96, NULL, NULL, NULL, NULL),
      ($str$Milacron 2200$str$, NULL, NULL, 1.65, 123.2, 4.91, NULL, NULL, NULL, NULL),
      ($str$Milacron 3000$str$, NULL, NULL, 1.65, 164.03, 5.56, NULL, NULL, NULL, NULL),
      ($str$Milacron 3500$str$, NULL, NULL, 1.65, 181.37, 5.56, NULL, NULL, NULL, NULL),
      ($str$Milacron 4000$str$, NULL, NULL, 1.65, 207.77, 6.1, NULL, NULL, NULL, NULL),
      ($str$Milacron MAGNA T170$str$, NULL, NULL, 1.65, 11.96, 2.14, NULL, NULL, NULL, NULL),
      ($str$Milacron MAGNA T225$str$, NULL, NULL, 1.65, 15.91, 2.88, NULL, NULL, NULL, NULL),
      ($str$Milacron MAGNA T310$str$, NULL, NULL, 1.65, 22.53, 4.32, NULL, NULL, NULL, NULL),
      ($str$Milacron MAGNA T310WP$str$, NULL, NULL, 1.65, 21.12, 3.65, NULL, NULL, NULL, NULL),
      ($str$Milacron MAGNA T450$str$, NULL, NULL, 1.65, 28.15, 3.61, NULL, NULL, NULL, NULL),
      ($str$Milacron Power line 220$str$, NULL, NULL, 1.65, 15, 3.6, NULL, NULL, NULL, NULL),
      ($str$Milacron Power line 330$str$, NULL, NULL, 1.65, 20.52, 3.6, NULL, NULL, NULL, NULL),
      ($str$Milacron Power line 440$str$, NULL, NULL, 1.65, 32.34, 3.6, NULL, NULL, NULL, NULL),
      ($str$Milacron Power line 550$str$, NULL, NULL, 1.65, 37.48, 4.16, NULL, NULL, NULL, NULL),
      ($str$Milacron Power line 750$str$, NULL, NULL, 1.65, 52, 5.01, NULL, NULL, NULL, NULL),
      ($str$Milacron Power line 935$str$, NULL, NULL, 1.65, 60.93, 5.52, NULL, NULL, NULL, NULL),
      ($str$Milacron Power line 1125$str$, NULL, NULL, 1.65, 80.82, 3.63, NULL, NULL, NULL, NULL),
      ($str$Netstal Synergy 600$str$, NULL, NULL, 1.65, 9.57, 1.5, NULL, NULL, NULL, NULL),
      ($str$Netstal Synergy 800$str$, NULL, NULL, 1.65, 10.1, 1.5, NULL, NULL, NULL, NULL),
      ($str$Netstal Synergy 1000$str$, NULL, NULL, 1.65, 11.69, 1.8, NULL, NULL, NULL, NULL),
      ($str$Netstal Synergy 1200$str$, NULL, NULL, 1.65, 12.71, 1.45, NULL, NULL, NULL, NULL),
      ($str$Netstal Synergy 1500$str$, NULL, NULL, 1.65, 19.8, 1.74, NULL, NULL, NULL, NULL),
      ($str$Netstal Synergy 2000$str$, NULL, NULL, 1.65, 24.69, 2.6, NULL, NULL, NULL, NULL),
      ($str$Toyo TM-100H2$str$, NULL, NULL, 1.65, 7.98, 1.15, NULL, NULL, NULL, NULL),
      ($str$Toyo TM-180H2$str$, NULL, NULL, 1.65, 12.84, 1.23, NULL, NULL, NULL, NULL),
      ($str$Toyo TM-220H2$str$, NULL, NULL, 1.65, 16.11, 1.29, NULL, NULL, NULL, NULL),
      ($str$Toyo TM-350H2$str$, NULL, NULL, 1.65, 25.25, 1.47, NULL, NULL, NULL, NULL),
      ($str$Gusmer-Decker Reactor IP-40$str$, NULL, NULL, 1.65, 4.29, 0.89, NULL, NULL, NULL, NULL),
      ($str$Reaction Injection Molder - 10,000kN Clamp Force$str$, NULL, NULL, 1.65, 4.29, 0.89, NULL, NULL, NULL, NULL),
      ($str$Structural Form Molder - 5,000kN Clamp Force$str$, NULL, NULL, 1.65, 87.65, 3.52, NULL, NULL, NULL, NULL),
      ($str$Structural Form Molder - 7,500kN Clamp Force$str$, NULL, NULL, 1.65, 110.92, 4.52, NULL, NULL, NULL, NULL),
      ($str$Structural Form Molder - 10,000kN Clamp Force$str$, NULL, NULL, 1.65, 135.27, 5.26, NULL, NULL, NULL, NULL),
      ($str$Structural Form Molder - 25,000kN Clamp Force$str$, NULL, NULL, 1.65, 156.37, 6.41, NULL, NULL, NULL, NULL),
      ($str$Milacron LP500M-423$str$, NULL, NULL, 1.65, 85.3, 3.82, NULL, NULL, NULL, NULL),
      ($str$Milacron LP750MWP-646$str$, NULL, NULL, 1.65, 112.5, 5.07, NULL, NULL, NULL, NULL),
      ($str$Milacron LP750MWP-2x630$str$, NULL, NULL, 1.65, 169.52, 6.39, NULL, NULL, NULL, NULL),
      ($str$Milacron LP1000MWP-660$str$, NULL, NULL, 1.65, 120.49, 4.91, NULL, NULL, NULL, NULL),
      ($str$Milacron LP1000MSWP-2x630$str$, NULL, NULL, 1.65, 158.91, 6.39, NULL, NULL, NULL, NULL),
      ($str$Milacron LP1000MWP-2x630$str$, NULL, NULL, 1.65, 182.47, 6.39, NULL, NULL, NULL, NULL),
      ($str$Milacron LP1500MHP-2x630$str$, NULL, NULL, 1.65, 192.98, 6.39, NULL, NULL, NULL, NULL),
      ($str$Milacron LP2500MHMWP-2x646$str$, NULL, NULL, 1.65, 190.5, 7.27, NULL, NULL, NULL, NULL),
      ($str$Uniloy 750M-646$str$, NULL, NULL, 1.65, 101.35, 3.54, NULL, NULL, NULL, NULL),
      ($str$Uniloy 750MWP-2x423$str$, NULL, NULL, 1.65, 125.44, 4.65, NULL, NULL, NULL, NULL),
      ($str$Uniloy 800MSWP-2x646$str$, NULL, NULL, 1.65, 113.74, 6.4, NULL, NULL, NULL, NULL),
      ($str$Uniloy 800MWP-2x423$str$, NULL, NULL, 1.65, 121.18, 4.15, NULL, NULL, NULL, NULL),
      ($str$Uniloy 800MWP-2x630$str$, NULL, NULL, 1.65, 113.74, 6.14, NULL, NULL, NULL, NULL),
      ($str$Uniloy 1000MHP-660$str$, NULL, NULL, 1.65, 116.79, 5.39, NULL, NULL, NULL, NULL),
      ($str$Uniloy 1000MSWP-2x423$str$, NULL, NULL, 1.65, 134.12, 4.15, NULL, NULL, NULL, NULL),
      ($str$Uniloy 1000MWP-2x646$str$, NULL, NULL, 1.65, 139.08, 4.89, NULL, NULL, NULL, NULL)
    ) v(name, category, unidentified, labor, direct, indirect, description, power_kw, max_x, max_y)
    ORDER BY pass
  LOOP
    SELECT usa.id, usa.machine_class, usa.machine_name INTO t
    FROM mhr_records usa
    WHERE usa.location = 'USA' AND usa.benchmark_source_key IS NOT NULL
      AND lower(trim(usa.machine_name)) = lower(trim(r.name))
      AND NOT (usa.id = ANY (used))
      AND (
        -- one twin left for this name
        (SELECT count(*) FROM mhr_records u2
          WHERE u2.location = 'USA' AND u2.benchmark_source_key IS NOT NULL
            AND lower(trim(u2.machine_name)) = lower(trim(r.name)) AND NOT (u2.id = ANY (used))) = 1
        -- or the twin in this row's own category
        OR split_part(usa.benchmark_source_key, ':', 1) = r.category
      )
    ORDER BY (split_part(usa.benchmark_source_key, ':', 1) = r.category) DESC
    LIMIT 1;

    IF t.id IS NOT NULL THEN
      used := used || t.id;
      IF NOT EXISTS (SELECT 1 FROM mhr_records m WHERE m.location = 'India'
                     AND m.machine_class = t.machine_class AND lower(trim(m.machine_name)) = lower(trim(t.machine_name))) THEN
        EXECUTE format('INSERT INTO mhr_records (%s) SELECT %s FROM mhr_records usa WHERE usa.id = $1', cols, sel)
          USING t.id, r.direct, r.indirect, r.labor;
        n_twin := n_twin + 1;
      END IF;
    ELSIF r.category IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM mhr_records usa WHERE usa.location = 'USA' AND usa.benchmark_source_key IS NOT NULL
              AND lower(trim(usa.machine_name)) = lower(trim(r.name))) THEN
      -- India-only machine: its process must name exactly one USA category/class.
      SELECT count(DISTINCT machine_class), min(machine_class), min(process_group), min(wage_grade)
        INTO n_class, cat_class, cat_group, cat_grade
      FROM mhr_records WHERE location = 'USA' AND benchmark_source_key LIKE r.category || ':%';
      IF n_class = 1 AND NOT EXISTS (SELECT 1 FROM mhr_records m WHERE m.location = 'India'
                                     AND m.machine_class = cat_class AND lower(trim(m.machine_name)) = lower(trim(r.name))) THEN
        INSERT INTO mhr_records (machine_class, location, machine_name, machine_description, currency_code, country_code,
          source_type, process_group, wage_grade, direct_overhead_rate, indirect_overhead_rate,
          benchmark_direct_overhead_rate_usd_hr, benchmark_indirect_overhead_rate_usd_hr,
          total_machine_hour_rate, mhr_usd_per_hour, usd_labor_rate_per_hr, benchmark_labor_rate_usd_hr, usd_lhr_total,
          machine_power_kw, max_x_mm, max_y_mm, capability_source, benchmark_source_key)
        VALUES (cat_class, 'India', r.name, r.description, 'USD', 'IN', 'BENCHMARK', cat_group, cat_grade,
          r.direct, r.indirect, r.direct, r.indirect,
          ROUND((r.direct + r.indirect)::numeric, 2), ROUND((r.direct + r.indirect)::numeric, 2), r.labor, r.labor, r.labor,
          r.power_kw, r.max_x, r.max_y, CASE WHEN r.max_x IS NOT NULL THEN 'imported' END,
          r.category || ':' || r.name || ':India');
        n_only := n_only + 1;
      ELSE
        skipped := skipped || (r.name || ' (' || r.category || ')');
      END IF;
    ELSE
      skipped := skipped || (r.name || COALESCE(' (' || COALESCE(r.category, r.unidentified) || ')', ''));
    END IF;
  END LOOP;

  RAISE NOTICE 'India rows cloned from a USA twin: %, India-only machines: %', n_twin, n_only;
  RAISE NOTICE 'Not inserted: %', CASE WHEN cardinality(skipped) = 0 THEN 'none' ELSE array_to_string(skipped, '; ') END;
END
$india829$;

NOTIFY pgrst, 'reload schema';

-- Verify: SELECT process_group, count(*) FROM mhr_records WHERE location = 'India'
-- AND benchmark_source_key LIKE '%:India' GROUP BY 1 ORDER BY 1;
