-- Migration 855 part 18 of 21

-- ── Ferrous & Non-Ferrous: core columns (101 materials, policy attach)
WITH src AS (
  SELECT v.*,
    v.material AS material_name
  FROM (VALUES
  ($str$Generic Aluminum, AA 1100$str$, $str$Aluminum, AA 1100$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, AA 2219$str$, $str$Aluminum, AA 2219$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, AA 3105$str$, $str$Aluminum, AA 3105$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, AA 383.0$str$, $str$Aluminum, AA 383.0$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, AA 7003$str$, $str$Aluminum, AA 7003$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 1050A$str$, $str$Aluminum, ANSI 1050A$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 2007$str$, $str$Aluminum, ANSI 2007$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 2017$str$, $str$Aluminum, ANSI 2017$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 2024$str$, $str$Aluminum, ANSI 2024$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 2030$str$, $str$Aluminum, ANSI 2030$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 3003$str$, $str$Aluminum, ANSI 3003$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 3103$str$, $str$Aluminum, ANSI 3103$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 5005$str$, $str$Aluminum, ANSI 5005$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 5005A$str$, $str$Aluminum, ANSI 5005A$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 5019$str$, $str$Aluminum, ANSI 5019$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 5052$str$, $str$Aluminum, ANSI 5052$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 5083$str$, $str$Aluminum, ANSI 5083$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 5119$str$, $str$Aluminum, ANSI 5119$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 5251$str$, $str$Aluminum, ANSI 5251$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 5454$str$, $str$Aluminum, ANSI 5454$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 5754$str$, $str$Aluminum, ANSI 5754$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 6012$str$, $str$Aluminum, ANSI 6012$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 6060$str$, $str$Aluminum, ANSI 6060$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 6061$str$, $str$Aluminum, ANSI 6061$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 6082$str$, $str$Aluminum, ANSI 6082$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 7020$str$, $str$Aluminum, ANSI 7020$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 7022$str$, $str$Aluminum, ANSI 7022$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 7050$str$, $str$Aluminum, ANSI 7050$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 7075$str$, $str$Aluminum, ANSI 7075$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Brass, UNS C36000$str$, $str$Brass, UNS C36000$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 200, NULL, NULL, NULL, NULL),
  ($str$Generic C60$str$, $str$C60$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 170, NULL, NULL, NULL, NULL),
  ($str$Generic C60E$str$, $str$C60E$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 170, NULL, NULL, NULL, NULL),
  ($str$Generic Copper, UNS C11000$str$, $str$Copper, UNS C11000$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 100, NULL, NULL, NULL, NULL),
  ($str$Generic Copper, UNS C18150$str$, $str$Copper, UNS C18150$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 100, NULL, NULL, NULL, NULL),
  ($str$Generic Copper, UNS C27200$str$, $str$Copper, UNS C27200$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 100, NULL, NULL, NULL, NULL),
  ($str$Generic Copper, UNS C28000$str$, $str$Copper, UNS C28000$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 100, NULL, NULL, NULL, NULL),
  ($str$Generic Copper, UNS C51900$str$, $str$Copper, UNS C51900$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 100, NULL, NULL, NULL, NULL),
  ($str$Generic Copper, UNS C62730$str$, $str$Copper, UNS C62730$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 100, NULL, NULL, NULL, NULL),
  ($str$Generic Galv. Steel, Hot Worked, AISI 1010$str$, $str$Galv. Steel, Hot Worked, AISI 1010$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 125, NULL, NULL, NULL, NULL),
  ($str$Generic Galv. Steel, Hot Worked, AISI 1012$str$, $str$Galv. Steel, Hot Worked, AISI 1012$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 125, NULL, NULL, NULL, NULL),
  ($str$Generic Galv. Steel, Hot Worked, AISI 1020$str$, $str$Galv. Steel, Hot Worked, AISI 1020$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 125, NULL, NULL, NULL, NULL),
  ($str$Generic Galv. Steel, Hot Worked, DX51D$str$, $str$Galv. Steel, Hot Worked, DX51D$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 170, NULL, NULL, NULL, NULL),
  ($str$Generic Galv. Steel, Hot Worked, DX54$str$, $str$Galv. Steel, Hot Worked, DX54$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 220, NULL, NULL, NULL, NULL),
  ($str$Generic Hastelloy C-276$str$, $str$Hastelloy C-276$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 275, NULL, NULL, NULL, NULL),
  ($str$Generic Hastelloy X$str$, $str$Hastelloy X$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 200, NULL, NULL, NULL, NULL),
  ($str$Generic Haynes alloy 230$str$, $str$Haynes alloy 230$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 190, NULL, NULL, NULL, NULL),
  ($str$Generic Inconel 625$str$, $str$Inconel 625$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 195, NULL, NULL, NULL, NULL),
  ($str$Generic Inconel 718$str$, $str$Inconel 718$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 350, NULL, NULL, NULL, NULL),
  ($str$Generic Stainless Steel, 15-5PH$str$, $str$Stainless Steel, 15-5PH$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 330, NULL, NULL, NULL, NULL),
  ($str$Generic Stainless Steel, 17-4PH$str$, $str$Stainless Steel, 17-4PH$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 345, NULL, NULL, NULL, NULL),
  ($str$Generic Stainless Steel, 440B$str$, $str$Stainless Steel, 440B$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 260, NULL, NULL, NULL, NULL),
  ($str$Generic Stainless Steel, A240$str$, $str$Stainless Steel, A240$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 260, NULL, NULL, NULL, NULL),
  ($str$Generic Stainless Steel, A351 CF8$str$, $str$Stainless Steel, A351 CF8$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 260, NULL, NULL, NULL, NULL),
  ($str$Generic Stainless Steel, AISI 301$str$, $str$Stainless Steel, AISI 301$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 330, NULL, NULL, NULL, NULL),
  ($str$Generic Stainless Steel, AISI 303$str$, $str$Stainless Steel, AISI 303$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 175, NULL, NULL, NULL, NULL),
  ($str$Generic Stainless Steel, AISI 304$str$, $str$Stainless Steel, AISI 304$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 210, NULL, NULL, NULL, NULL),
  ($str$Generic Stainless Steel, AISI 304L$str$, $str$Stainless Steel, AISI 304L$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 235, NULL, NULL, NULL, NULL),
  ($str$Generic Stainless Steel, AISI 316$str$, $str$Stainless Steel, AISI 316$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 290, NULL, NULL, NULL, NULL),
  ($str$Generic Stainless Steel, AISI 316L$str$, $str$Stainless Steel, AISI 316L$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 535, NULL, NULL, NULL, NULL),
  ($str$Generic Stainless Steel, AISI 316Ti$str$, $str$Stainless Steel, AISI 316Ti$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 295, NULL, NULL, NULL, NULL),
  ($str$Generic Stainless Steel, AISI 321$str$, $str$Stainless Steel, AISI 321$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 260, NULL, NULL, NULL, NULL),
  ($str$Generic Stainless Steel, AISI 441$str$, $str$Stainless Steel, AISI 441$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 528, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, AISI 1035$str$, $str$Steel, AISI 1035$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 150, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, AISI 4140, Medium-Carbon$str$, $str$Steel, AISI 4140, Medium-Carbon$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 180, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Cold Worked, AISI 1005$str$, $str$Steel, Cold Worked, AISI 1005$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 95, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Cold Worked, AISI 1008$str$, $str$Steel, Cold Worked, AISI 1008$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 125, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Cold Worked, AISI 1010$str$, $str$Steel, Cold Worked, AISI 1010$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 125, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Cold Worked, AISI 1012$str$, $str$Steel, Cold Worked, AISI 1012$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 130, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Cold Worked, AISI 1018$str$, $str$Steel, Cold Worked, AISI 1018$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 130, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Cold Worked, AISI 1020$str$, $str$Steel, Cold Worked, AISI 1020$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 220, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Cold Worked, AISI 1050$str$, $str$Steel, Cold Worked, AISI 1050$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 210, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Cold Worked, AISI 4130$str$, $str$Steel, Cold Worked, AISI 4130$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 220, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Cold Worked, AISI 4340$str$, $str$Steel, Cold Worked, AISI 4340$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 330, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Cold Worked, AISI 5210$str$, $str$Steel, Cold Worked, AISI 5210$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 207, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Cold Worked, AISI 8620$str$, $str$Steel, Cold Worked, AISI 8620$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 125, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Cold Worked, DC06$str$, $str$Steel, Cold Worked, DC06$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 125, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 1006$str$, $str$Steel, Hot Worked, AISI 1006$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 125, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 1008$str$, $str$Steel, Hot Worked, AISI 1008$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 125, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 1010$str$, $str$Steel, Hot Worked, AISI 1010$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 125, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 1012$str$, $str$Steel, Hot Worked, AISI 1012$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 130, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 1018$str$, $str$Steel, Hot Worked, AISI 1018$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 150, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 1020$str$, $str$Steel, Hot Worked, AISI 1020$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 150, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 1042$str$, $str$Steel, Hot Worked, AISI 1042$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 200, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 1045$str$, $str$Steel, Hot Worked, AISI 1045$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 200, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 1049$str$, $str$Steel, Hot Worked, AISI 1049$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 200, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 1050$str$, $str$Steel, Hot Worked, AISI 1050$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 125, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 1075$str$, $str$Steel, Hot Worked, AISI 1075$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 125, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 1095$str$, $str$Steel, Hot Worked, AISI 1095$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1034, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 1213$str$, $str$Steel, Hot Worked, AISI 1213$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 125, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 12L13$str$, $str$Steel, Hot Worked, AISI 12L13$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 180, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 1513$str$, $str$Steel, Hot Worked, AISI 1513$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 180, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 4140$str$, $str$Steel, Hot Worked, AISI 4140$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 125, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 4140H$str$, $str$Steel, Hot Worked, AISI 4140H$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 210, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 5115$str$, $str$Steel, Hot Worked, AISI 5115$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 210, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 6150$str$, $str$Steel, Hot Worked, AISI 6150$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 210, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, ASTM A36$str$, $str$Steel, Hot Worked, ASTM A36$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 115, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, ASTM A572 Grade 50$str$, $str$Steel, Hot Worked, ASTM A572 Grade 50$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 310, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, Grade S235JR$str$, $str$Steel, Hot Worked, Grade S235JR$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 950, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, S900MC$str$, $str$Steel, Hot Worked, S900MC$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ($str$Generic Titanium, Ti-5Al-2.5Sn$str$, $str$Titanium, Ti-5Al-2.5Sn$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ($str$Generic Titanium, Ti-6Al-4V$str$, $str$Titanium, Ti-6Al-4V$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
  ) AS v(material, material_grade, material_type, material_group, cut_code, cost, cost_usa, cost_units, base_cost_per_unit_usd, currency, density_kg_m3, density, hardness, hardness_system, description, data_source, usa_name)
)
INSERT INTO raw_materials (material, material_grade, material_type, material_group, cut_code, cost, cost_usa, cost_units, base_cost_per_unit_usd, currency, density_kg_m3, density, hardness, hardness_system, description, data_source, usa_name)
SELECT s.material_name, s.material_grade, s.material_type, s.material_group, CAST(s.cut_code AS NUMERIC), CAST(s.cost AS NUMERIC), CAST(s.cost_usa AS NUMERIC), s.cost_units, CAST(s.base_cost_per_unit_usd AS NUMERIC), s.currency, CAST(s.density_kg_m3 AS NUMERIC), CAST(s.density AS NUMERIC), CAST(s.hardness AS NUMERIC), s.hardness_system, s.description, s.data_source, s.usa_name
FROM src s
WHERE NOT EXISTS (SELECT 1 FROM raw_materials rm WHERE rm.material = s.material_name);
