-- Migration 855 part 18 of 21

-- ── Bar and Tube Fabrication: properties 4/4
WITH src AS (
  SELECT v.*,
    CASE WHEN EXISTS (SELECT 1 FROM raw_materials rm WHERE rm.material = v.material AND rm.material_group IS DISTINCT FROM 'Bar and Tube Fabrication')
         THEN v.material || ' (Bar and Tube Fabrication)' ELSE v.material END AS material_name
  FROM (VALUES
  ($str$Generic Titanium, Ti-6Al-4V$str$, $str$Titanium, Ti-6Al-4V$str$, $str$Titanium$str$, $str$Bar and Tube Fabrication$str$, 23.21, NULL, NULL, NULL, NULL, NULL, 4430, 4.43, 950, $str$Tensile Strength$str$, NULL, $str$reference export baseline$str$, $str$Titanium, Ti-6Al-4V$str$),
  ($str$Generic Titanium, Ti-5Al-2.5Sn$str$, $str$Titanium, Ti-5Al-2.5Sn$str$, $str$Titanium$str$, $str$Bar and Tube Fabrication$str$, 23.21, NULL, NULL, NULL, NULL, NULL, 4480, 4.48, 950, $str$Tensile Strength$str$, NULL, $str$reference export baseline$str$, $str$Titanium, Ti-5Al-2.5Sn$str$),
  ($str$Generic Steel, SAE 1580$str$, $str$Steel, SAE 1580$str$, $str$Steel$str$, $str$Bar and Tube Fabrication$str$, 1.1, NULL, NULL, NULL, NULL, NULL, 7850, 7.85, 125, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Steel, SAE 1580$str$),
  ($str$Generic Steel, Hot Worked, S900MC$str$, $str$Steel, Hot Worked, S900MC$str$, $str$Steel$str$, $str$Bar and Tube Fabrication$str$, 1.2, NULL, NULL, NULL, NULL, NULL, 7800, 7.8, 310, $str$Brinell$str$, $str$Grade S900MC$str$, $str$reference export baseline$str$, $str$Steel, Hot Worked, S900MC$str$),
  ($str$Generic Steel, Hot Worked, Grade S235JR$str$, $str$Steel, Hot Worked, Grade S235JR$str$, $str$Steel$str$, $str$Bar and Tube Fabrication$str$, 1.2, NULL, NULL, NULL, NULL, NULL, 7800, 7.8, 115, $str$Brinell$str$, $str$Grade S235JR$str$, $str$reference export baseline$str$, $str$Steel, Hot Worked, Grade S235JR$str$),
  ($str$Generic Steel, Hot Worked, ASTM A572 Grade 50$str$, $str$Steel, Hot Worked, ASTM A572 Grade 50$str$, $str$Steel$str$, $str$Bar and Tube Fabrication$str$, 1.2, NULL, NULL, NULL, NULL, NULL, 7800, 7.8, 150, $str$Brinell$str$, $str$Grade 50$str$, $str$reference export baseline$str$, $str$Steel, Hot Worked, ASTM A572 Grade 50$str$),
  ($str$Generic Steel, Hot Worked, ASTM A36$str$, $str$Steel, Hot Worked, ASTM A36$str$, $str$Steel$str$, $str$Bar and Tube Fabrication$str$, 1.1, NULL, NULL, NULL, NULL, NULL, 7850, 7.85, 125, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Steel, Hot Worked, ASTM A36$str$),
  ($str$Generic Steel, Hot Worked, AISI 6150$str$, $str$Steel, Hot Worked, AISI 6150$str$, $str$Steel$str$, $str$Bar and Tube Fabrication$str$, 2.1, NULL, NULL, NULL, NULL, NULL, 7850, 7.85, 180, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Steel, Hot Worked, AISI 6150$str$),
  ($str$Generic Steel, Hot Worked, AISI 5115$str$, $str$Steel, Hot Worked, AISI 5115$str$, $str$Steel$str$, $str$Bar and Tube Fabrication$str$, 2.1, NULL, NULL, NULL, NULL, NULL, 7850, 7.85, 180, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Steel, Hot Worked, AISI 5115$str$),
  ($str$Generic Steel, Hot Worked, AISI 4140H$str$, $str$Steel, Hot Worked, AISI 4140H$str$, $str$Steel$str$, $str$Bar and Tube Fabrication$str$, 2.1, NULL, NULL, NULL, NULL, NULL, 7850, 7.85, 180, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Steel, Hot Worked, AISI 4140H$str$),
  ($str$Generic Steel, Hot Worked, AISI 4140$str$, $str$Steel, Hot Worked, AISI 4140$str$, $str$Steel$str$, $str$Bar and Tube Fabrication$str$, 2.1, NULL, NULL, NULL, NULL, NULL, 7850, 7.85, 180, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Steel, Hot Worked, AISI 4140$str$),
  ($str$Generic Steel, Hot Worked, AISI 1513$str$, $str$Steel, Hot Worked, AISI 1513$str$, $str$Steel$str$, $str$Bar and Tube Fabrication$str$, 1.1, NULL, NULL, NULL, NULL, NULL, 7850, 7.85, 125, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Steel, Hot Worked, AISI 1513$str$),
  ($str$Generic Steel, Hot Worked, AISI 12L13$str$, $str$Steel, Hot Worked, AISI 12L13$str$, $str$Steel$str$, $str$Bar and Tube Fabrication$str$, 1.1, NULL, NULL, NULL, NULL, NULL, 7870, 7.87, 125, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Steel, Hot Worked, AISI 12L13$str$),
  ($str$Generic Steel, Hot Worked, AISI 1213$str$, $str$Steel, Hot Worked, AISI 1213$str$, $str$Steel$str$, $str$Bar and Tube Fabrication$str$, 1.1, NULL, NULL, NULL, NULL, NULL, 7870, 7.87, 125, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Steel, Hot Worked, AISI 1213$str$),
  ($str$Generic Steel, Hot Worked, AISI 1095$str$, $str$Steel, Hot Worked, AISI 1095$str$, $str$Steel$str$, $str$Bar and Tube Fabrication$str$, 1.4, NULL, NULL, NULL, NULL, NULL, 7850, 7.85, 210, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Steel, Hot Worked, AISI 1095$str$),
  ($str$Generic Steel, Hot Worked, AISI 1075$str$, $str$Steel, Hot Worked, AISI 1075$str$, $str$Steel$str$, $str$Bar and Tube Fabrication$str$, 1.4, NULL, NULL, NULL, NULL, NULL, 7850, 7.85, 210, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Steel, Hot Worked, AISI 1075$str$),
  ($str$Generic Steel, Hot Worked, AISI 1050$str$, $str$Steel, Hot Worked, AISI 1050$str$, $str$Steel$str$, $str$Bar and Tube Fabrication$str$, 1.2, NULL, NULL, NULL, NULL, NULL, 7800, 7.8, 200, $str$Brinell$str$, $str$Grade 1050$str$, $str$reference export baseline$str$, $str$Steel, Hot Worked, AISI 1050$str$),
  ($str$Generic Steel, Hot Worked, AISI 1049$str$, $str$Steel, Hot Worked, AISI 1049$str$, $str$Steel$str$, $str$Bar and Tube Fabrication$str$, 1.2, NULL, NULL, NULL, NULL, NULL, 7850, 7.85, 150, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Steel, Hot Worked, AISI 1049$str$),
  ($str$Generic Steel, Hot Worked, AISI 1045$str$, $str$Steel, Hot Worked, AISI 1045$str$, $str$Steel$str$, $str$Bar and Tube Fabrication$str$, 1.2, NULL, NULL, NULL, NULL, NULL, 7850, 7.85, 150, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Steel, Hot Worked, AISI 1045$str$),
  ($str$Generic Steel, Hot Worked, AISI 1042$str$, $str$Steel, Hot Worked, AISI 1042$str$, $str$Steel$str$, $str$Bar and Tube Fabrication$str$, 1.2, NULL, NULL, NULL, NULL, NULL, 7850, 7.85, 150, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Steel, Hot Worked, AISI 1042$str$),
  ($str$Generic Steel, Hot Worked, AISI 1020$str$, $str$Steel, Hot Worked, AISI 1020$str$, $str$Steel$str$, $str$Bar and Tube Fabrication$str$, 1.1, NULL, NULL, NULL, NULL, NULL, 7850, 7.85, 125, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Steel, Hot Worked, AISI 1020$str$),
  ($str$Generic Steel, Hot Worked, AISI 1018$str$, $str$Steel, Hot Worked, AISI 1018$str$, $str$Steel$str$, $str$Bar and Tube Fabrication$str$, 1.2, NULL, NULL, NULL, NULL, NULL, 7900, 7.9, 130, $str$Brinell$str$, $str$Grade 1018$str$, $str$reference export baseline$str$, $str$Steel, Hot Worked, AISI 1018$str$),
  ($str$Generic Steel, Hot Worked, AISI 1012$str$, $str$Steel, Hot Worked, AISI 1012$str$, $str$Steel$str$, $str$Bar and Tube Fabrication$str$, 1.1, NULL, NULL, NULL, NULL, NULL, 7850, 7.85, 125, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Steel, Hot Worked, AISI 1012$str$),
  ($str$Generic Steel, Hot Worked, AISI 1010$str$, $str$Steel, Hot Worked, AISI 1010$str$, $str$Steel$str$, $str$Bar and Tube Fabrication$str$, 1.1, NULL, NULL, NULL, NULL, NULL, 7850, 7.85, 125, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Steel, Hot Worked, AISI 1010$str$),
  ($str$Generic Steel, Hot Worked, AISI 1008$str$, $str$Steel, Hot Worked, AISI 1008$str$, $str$Steel$str$, $str$Bar and Tube Fabrication$str$, 1.1, NULL, NULL, NULL, NULL, NULL, 7850, 7.85, 125, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Steel, Hot Worked, AISI 1008$str$),
  ($str$Generic Steel, Hot Worked, AISI 1006$str$, $str$Steel, Hot Worked, AISI 1006$str$, $str$Steel$str$, $str$Bar and Tube Fabrication$str$, 1.1, NULL, NULL, NULL, NULL, NULL, 7850, 7.85, 125, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Steel, Hot Worked, AISI 1006$str$),
  ($str$Generic Steel, Cold Worked, DC06$str$, $str$Steel, Cold Worked, DC06$str$, $str$Steel$str$, $str$Bar and Tube Fabrication$str$, 1.2, NULL, NULL, NULL, NULL, NULL, 7900, 7.9, 125, $str$Brinell$str$, $str$Grade DC06$str$, $str$reference export baseline$str$, $str$Steel, Cold Worked, DC06$str$),
  ($str$Generic Steel, Cold Worked, AISI 8620$str$, $str$Steel, Cold Worked, AISI 8620$str$, $str$Steel$str$, $str$Bar and Tube Fabrication$str$, 1.2, NULL, NULL, NULL, NULL, NULL, 7800, 7.8, 210, $str$Brinell$str$, $str$Grade 8620$str$, $str$reference export baseline$str$, $str$Steel, Cold Worked, AISI 8620$str$),
  ($str$Generic Steel, Cold Worked, AISI 5210$str$, $str$Steel, Cold Worked, AISI 5210$str$, $str$Steel$str$, $str$Bar and Tube Fabrication$str$, 1.2, NULL, NULL, NULL, NULL, NULL, 7800, 7.8, 207, $str$Brinell$str$, $str$Grade 5210$str$, $str$reference export baseline$str$, $str$Steel, Cold Worked, AISI 5210$str$),
  ($str$Generic Steel, Cold Worked, AISI 4340$str$, $str$Steel, Cold Worked, AISI 4340$str$, $str$Steel$str$, $str$Bar and Tube Fabrication$str$, 2.2, NULL, NULL, NULL, NULL, NULL, 7850, 7.85, 330, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Steel, Cold Worked, AISI 4340$str$),
  ($str$Generic Steel, Cold Worked, AISI 4130$str$, $str$Steel, Cold Worked, AISI 4130$str$, $str$Steel$str$, $str$Bar and Tube Fabrication$str$, 1.2, NULL, NULL, NULL, NULL, NULL, 7800, 7.8, 210, $str$Brinell$str$, $str$Grade 4130$str$, $str$reference export baseline$str$, $str$Steel, Cold Worked, AISI 4130$str$),
  ($str$Generic Steel, Cold Worked, AISI 1050$str$, $str$Steel, Cold Worked, AISI 1050$str$, $str$Steel$str$, $str$Bar and Tube Fabrication$str$, 1.2, NULL, NULL, NULL, NULL, NULL, 7800, 7.8, 220, $str$Brinell$str$, $str$Grade 1050$str$, $str$reference export baseline$str$, $str$Steel, Cold Worked, AISI 1050$str$),
  ($str$Generic Steel, Cold Worked, AISI 1020$str$, $str$Steel, Cold Worked, AISI 1020$str$, $str$Steel$str$, $str$Bar and Tube Fabrication$str$, 1.1, NULL, NULL, NULL, NULL, NULL, 7850, 7.85, 125, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Steel, Cold Worked, AISI 1020$str$),
  ($str$Generic Steel, Cold Worked, AISI 1018$str$, $str$Steel, Cold Worked, AISI 1018$str$, $str$Steel$str$, $str$Bar and Tube Fabrication$str$, 1.2, NULL, NULL, NULL, NULL, NULL, 7900, 7.9, 140, $str$Brinell$str$, $str$Grade 1018$str$, $str$reference export baseline$str$, $str$Steel, Cold Worked, AISI 1018$str$),
  ($str$Generic Steel, Cold Worked, AISI 1012$str$, $str$Steel, Cold Worked, AISI 1012$str$, $str$Steel$str$, $str$Bar and Tube Fabrication$str$, 1.1, NULL, NULL, NULL, NULL, NULL, 7850, 7.85, 125, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Steel, Cold Worked, AISI 1012$str$),
  ($str$Generic Steel, Cold Worked, AISI 1010$str$, $str$Steel, Cold Worked, AISI 1010$str$, $str$Steel$str$, $str$Bar and Tube Fabrication$str$, 1.1, NULL, NULL, NULL, NULL, NULL, 7850, 7.85, 125, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Steel, Cold Worked, AISI 1010$str$),
  ($str$Generic Steel, Cold Worked, AISI 1008$str$, $str$Steel, Cold Worked, AISI 1008$str$, $str$Steel$str$, $str$Bar and Tube Fabrication$str$, 1.1, NULL, NULL, NULL, NULL, NULL, 7850, 7.85, 125, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Steel, Cold Worked, AISI 1008$str$),
  ($str$Generic Steel, Cold Worked, AISI 1005$str$, $str$Steel, Cold Worked, AISI 1005$str$, $str$Steel$str$, $str$Bar and Tube Fabrication$str$, 1.2, NULL, NULL, NULL, NULL, NULL, 7900, 7.9, 95, $str$Brinell$str$, $str$Grade 1005$str$, $str$reference export baseline$str$, $str$Steel, Cold Worked, AISI 1005$str$),
  ($str$Generic Stainless Steel, AISI 441$str$, $str$Stainless Steel, AISI 441$str$, $str$Stainless Steel$str$, $str$Bar and Tube Fabrication$str$, 5.21, NULL, NULL, NULL, NULL, NULL, 7700, 7.7, 200, $str$Brinell$str$, $str$Grade 441$str$, $str$reference export baseline$str$, $str$Stainless Steel, AISI 441$str$),
  ($str$Generic Stainless Steel, AISI 430$str$, $str$Stainless Steel, AISI 430$str$, $str$Stainless Steel$str$, $str$Bar and Tube Fabrication$str$, 5.11, NULL, NULL, NULL, NULL, NULL, 7740, 7.74, 200, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Stainless Steel, AISI 430$str$),
  ($str$Generic Stainless Steel, AISI 410$str$, $str$Stainless Steel, AISI 410$str$, $str$Stainless Steel$str$, $str$Bar and Tube Fabrication$str$, 5.11, NULL, NULL, NULL, NULL, NULL, 7740, 7.74, 200, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Stainless Steel, AISI 410$str$),
  ($str$Generic Stainless Steel, AISI 316L$str$, $str$Stainless Steel, AISI 316L$str$, $str$Stainless Steel$str$, $str$Bar and Tube Fabrication$str$, 5.21, NULL, NULL, NULL, NULL, NULL, 8073, 8.073, 200, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Stainless Steel, AISI 316L$str$),
  ($str$Generic Stainless Steel, AISI 316$str$, $str$Stainless Steel, AISI 316$str$, $str$Stainless Steel$str$, $str$Bar and Tube Fabrication$str$, 5.21, NULL, NULL, NULL, NULL, NULL, 8073, 8.073, 200, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Stainless Steel, AISI 316$str$),
  ($str$Generic Stainless Steel, AISI 304L$str$, $str$Stainless Steel, AISI 304L$str$, $str$Stainless Steel$str$, $str$Bar and Tube Fabrication$str$, 5.21, NULL, NULL, NULL, NULL, NULL, 7800, 7.8, 255, $str$Brinell$str$, $str$Grade 304L$str$, $str$reference export baseline$str$, $str$Stainless Steel, AISI 304L$str$),
  ($str$Generic Stainless Steel, AISI 304$str$, $str$Stainless Steel, AISI 304$str$, $str$Stainless Steel$str$, $str$Bar and Tube Fabrication$str$, 5.21, NULL, NULL, NULL, NULL, NULL, 8073, 8.073, 200, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Stainless Steel, AISI 304$str$),
  ($str$Generic Stainless Steel, AISI 303$str$, $str$Stainless Steel, AISI 303$str$, $str$Stainless Steel$str$, $str$Bar and Tube Fabrication$str$, 5.2, NULL, NULL, NULL, NULL, NULL, 8073, 8.073, 175, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Stainless Steel, AISI 303$str$),
  ($str$Generic Stainless Steel, A240$str$, $str$Stainless Steel, A240$str$, $str$Stainless Steel$str$, $str$Bar and Tube Fabrication$str$, 5.21, NULL, NULL, NULL, NULL, NULL, 7800, 7.8, 200, $str$Brinell$str$, $str$Grade A240$str$, $str$reference export baseline$str$, $str$Stainless Steel, A240$str$),
  ($str$Generic Stainless Steel, 440B$str$, $str$Stainless Steel, 440B$str$, $str$Stainless Steel$str$, $str$Bar and Tube Fabrication$str$, 5.52, NULL, NULL, NULL, NULL, NULL, 8073, 8.073, 260, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Stainless Steel, 440B$str$),
  ($str$Generic Stainless Steel, 17-4PH$str$, $str$Stainless Steel, 17-4PH$str$, $str$Stainless Steel$str$, $str$Bar and Tube Fabrication$str$, 5.21, NULL, NULL, NULL, NULL, NULL, 7800, 7.8, 360, $str$Brinell$str$, $str$Grade 17-4PH$str$, $str$reference export baseline$str$, $str$Stainless Steel, 17-4PH$str$),
  ($str$Generic Stainless Steel, 15-5PH$str$, $str$Stainless Steel, 15-5PH$str$, $str$Stainless Steel$str$, $str$Bar and Tube Fabrication$str$, 5.12, NULL, NULL, NULL, NULL, NULL, 8073, 8.073, 330, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Stainless Steel, 15-5PH$str$),
  ($str$Generic Inconel 718$str$, $str$Inconel 718$str$, $str$Heat Resistant Super Alloys$str$, $str$Bar and Tube Fabrication$str$, 20.22, NULL, NULL, NULL, NULL, NULL, 8190, 8.19, 350, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Inconel 718$str$),
  ($str$Generic Inconel 625$str$, $str$Inconel 625$str$, $str$Heat Resistant Super Alloys$str$, $str$Bar and Tube Fabrication$str$, 20.21, NULL, NULL, NULL, NULL, NULL, 8440, 8.44, 250, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Inconel 625$str$),
  ($str$Generic Haynes alloy 230$str$, $str$Haynes alloy 230$str$, $str$Heat Resistant Super Alloys$str$, $str$Bar and Tube Fabrication$str$, 20.31, NULL, NULL, NULL, NULL, NULL, 8970, 8.97, 200, $str$Brinell$str$, $str$Carbide strengthened nickel-chromium-tungsten-molybdenum alloy$str$, $str$reference export baseline$str$, $str$Haynes alloy 230$str$),
  ($str$Generic Hastelloy X$str$, $str$Hastelloy X$str$, $str$Heat Resistant Super Alloys$str$, $str$Bar and Tube Fabrication$str$, 20.23, NULL, NULL, NULL, NULL, NULL, 8220, 8.22, 275, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Hastelloy X$str$),
  ($str$Generic Hastelloy C-276$str$, $str$Hastelloy C-276$str$, $str$Heat Resistant Super Alloys$str$, $str$Bar and Tube Fabrication$str$, 20.23, NULL, NULL, NULL, NULL, NULL, 8890, 8.89, 275, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Hastelloy C-276$str$),
  ($str$Generic Galv. Steel, Hot Worked, DX54$str$, $str$Galv. Steel, Hot Worked, DX54$str$, $str$Galvanized Steel$str$, $str$Bar and Tube Fabrication$str$, 1.1, NULL, NULL, NULL, NULL, NULL, 7800, 7.8, 125, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Galv. Steel, Hot Worked, DX54$str$),
  ($str$Generic Galv. Steel, Hot Worked, DX51D$str$, $str$Galv. Steel, Hot Worked, DX51D$str$, $str$Galvanized Steel$str$, $str$Bar and Tube Fabrication$str$, 1.1, NULL, NULL, NULL, NULL, NULL, 7800, 7.8, 125, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Galv. Steel, Hot Worked, DX51D$str$),
  ($str$Generic Galv. Steel, Hot Worked, AISI 1020$str$, $str$Galv. Steel, Hot Worked, AISI 1020$str$, $str$Galvanized Steel$str$, $str$Bar and Tube Fabrication$str$, 1.1, NULL, NULL, NULL, NULL, NULL, 7850, 7.85, 125, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Galv. Steel, Hot Worked, AISI 1020$str$),
  ($str$Generic Galv. Steel, Hot Worked, AISI 1012$str$, $str$Galv. Steel, Hot Worked, AISI 1012$str$, $str$Galvanized Steel$str$, $str$Bar and Tube Fabrication$str$, 1.1, NULL, NULL, NULL, NULL, NULL, 7850, 7.85, 125, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Galv. Steel, Hot Worked, AISI 1012$str$),
  ($str$Generic Galv. Steel, Hot Worked, AISI 1010$str$, $str$Galv. Steel, Hot Worked, AISI 1010$str$, $str$Galvanized Steel$str$, $str$Bar and Tube Fabrication$str$, 1.1, NULL, NULL, NULL, NULL, NULL, 7850, 7.85, 125, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Galv. Steel, Hot Worked, AISI 1010$str$),
  ($str$Generic Copper, UNS C62730$str$, $str$Copper, UNS C62730$str$, $str$Copper$str$, $str$Bar and Tube Fabrication$str$, 33.3, NULL, NULL, NULL, NULL, NULL, 8930, 8.93, 100, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Copper, UNS C62730$str$),
  ($str$Generic Copper, UNS C51900$str$, $str$Copper, UNS C51900$str$, $str$Copper$str$, $str$Bar and Tube Fabrication$str$, 33.3, NULL, NULL, NULL, NULL, NULL, 8930, 8.93, 100, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Copper, UNS C51900$str$),
  ($str$Generic Copper, UNS C28000$str$, $str$Copper, UNS C28000$str$, $str$Copper$str$, $str$Bar and Tube Fabrication$str$, 33.3, NULL, NULL, NULL, NULL, NULL, 8930, 8.93, 100, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Copper, UNS C28000$str$),
  ($str$Generic Copper, UNS C27200$str$, $str$Copper, UNS C27200$str$, $str$Copper$str$, $str$Bar and Tube Fabrication$str$, 33.3, NULL, NULL, NULL, NULL, NULL, 8930, 8.93, 100, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Copper, UNS C27200$str$),
  ($str$Generic Copper, UNS C18150$str$, $str$Copper, UNS C18150$str$, $str$Copper$str$, $str$Bar and Tube Fabrication$str$, 33.3, NULL, NULL, NULL, NULL, NULL, 8930, 8.93, 100, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Copper, UNS C18150$str$),
  ($str$Generic Copper, UNS C11000$str$, $str$Copper, UNS C11000$str$, $str$Copper$str$, $str$Bar and Tube Fabrication$str$, 33.3, NULL, NULL, NULL, NULL, NULL, 8930, 8.93, 100, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Copper, UNS C11000$str$),
  ($str$Generic Brass, UNS C36000$str$, $str$Brass, UNS C36000$str$, $str$Brass$str$, $str$Bar and Tube Fabrication$str$, 33.3, NULL, NULL, NULL, NULL, NULL, 8200, 8.2, 110, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Brass, UNS C36000$str$),
  ($str$Generic Brass, CW617N$str$, $str$Brass, CW617N$str$, $str$Brass$str$, $str$Bar and Tube Fabrication$str$, 33.3, NULL, NULL, NULL, NULL, NULL, 8430, 8.43, 120, $str$Brinell$str$, $str$Grade CW617N$str$, $str$reference export baseline$str$, $str$Brass, CW617N$str$),
  ($str$Generic Aluminum, ANSI 7075$str$, $str$Aluminum, ANSI 7075$str$, $str$Aluminum$str$, $str$Bar and Tube Fabrication$str$, 30.11, NULL, NULL, NULL, NULL, NULL, 2810, 2.81, 60, $str$Brinell$str$, $str$Grade 7075$str$, $str$reference export baseline$str$, $str$Aluminum, ANSI 7075$str$),
  ($str$Generic Aluminum, ANSI 7050$str$, $str$Aluminum, ANSI 7050$str$, $str$Aluminum$str$, $str$Bar and Tube Fabrication$str$, 30.11, NULL, NULL, NULL, NULL, NULL, 2700, 2.7, 60, $str$Brinell$str$, $str$Grade 7050$str$, $str$reference export baseline$str$, $str$Aluminum, ANSI 7050$str$),
  ($str$Generic Aluminum, ANSI 7022$str$, $str$Aluminum, ANSI 7022$str$, $str$Aluminum$str$, $str$Bar and Tube Fabrication$str$, 30.11, NULL, NULL, NULL, NULL, NULL, 2780, 2.78, 60, $str$Brinell$str$, $str$Grade 7022$str$, $str$reference export baseline$str$, $str$Aluminum, ANSI 7022$str$),
  ($str$Generic Aluminum, ANSI 7020$str$, $str$Aluminum, ANSI 7020$str$, $str$Aluminum$str$, $str$Bar and Tube Fabrication$str$, 30.11, NULL, NULL, NULL, NULL, NULL, 2770, 2.77, 60, $str$Brinell$str$, $str$Grade 7020$str$, $str$reference export baseline$str$, $str$Aluminum, ANSI 7020$str$),
  ($str$Generic Aluminum, ANSI 6082$str$, $str$Aluminum, ANSI 6082$str$, $str$Aluminum$str$, $str$Bar and Tube Fabrication$str$, 30.11, NULL, NULL, NULL, NULL, NULL, 2700, 2.7, 60, $str$Brinell$str$, $str$Grade 6082$str$, $str$reference export baseline$str$, $str$Aluminum, ANSI 6082$str$),
  ($str$Generic Aluminum, ANSI 6061$str$, $str$Aluminum, ANSI 6061$str$, $str$Aluminum$str$, $str$Bar and Tube Fabrication$str$, 30.11, NULL, NULL, NULL, NULL, NULL, 2700, 2.7, 60, $str$Brinell$str$, NULL, $str$reference export baseline$str$, $str$Aluminum, ANSI 6061$str$),
  ($str$Generic Aluminum, ANSI 6060$str$, $str$Aluminum, ANSI 6060$str$, $str$Aluminum$str$, $str$Bar and Tube Fabrication$str$, 30.11, NULL, NULL, NULL, NULL, NULL, 2700, 2.7, 60, $str$Brinell$str$, $str$Grade 6060$str$, $str$reference export baseline$str$, $str$Aluminum, ANSI 6060$str$),
  ($str$Generic Aluminum, ANSI 6012$str$, $str$Aluminum, ANSI 6012$str$, $str$Aluminum$str$, $str$Bar and Tube Fabrication$str$, 30.11, NULL, NULL, NULL, NULL, NULL, 2750, 2.75, 60, $str$Brinell$str$, $str$Grade 6012$str$, $str$reference export baseline$str$, $str$Aluminum, ANSI 6012$str$),
  ($str$Generic Aluminum, ANSI 5754$str$, $str$Aluminum, ANSI 5754$str$, $str$Aluminum$str$, $str$Bar and Tube Fabrication$str$, 30.11, NULL, NULL, NULL, NULL, NULL, 2750, 2.75, 60, $str$Brinell$str$, $str$Grade Aluminum 5754$str$, $str$reference export baseline$str$, $str$Aluminum, ANSI 5754$str$),
  ($str$Generic Aluminum, ANSI 5454$str$, $str$Aluminum, ANSI 5454$str$, $str$Aluminum$str$, $str$Bar and Tube Fabrication$str$, 30.11, NULL, NULL, NULL, NULL, NULL, 2700, 2.7, 60, $str$Brinell$str$, $str$Grade 5454$str$, $str$reference export baseline$str$, $str$Aluminum, ANSI 5454$str$),
  ($str$Generic Aluminum, ANSI 5251$str$, $str$Aluminum, ANSI 5251$str$, $str$Aluminum$str$, $str$Bar and Tube Fabrication$str$, 30.11, NULL, NULL, NULL, NULL, NULL, 2680, 2.68, 60, $str$Brinell$str$, $str$Grade 5251$str$, $str$reference export baseline$str$, $str$Aluminum, ANSI 5251$str$),
  ($str$Generic Aluminum, ANSI 5119$str$, $str$Aluminum, ANSI 5119$str$, $str$Aluminum$str$, $str$Bar and Tube Fabrication$str$, 30.11, NULL, NULL, NULL, NULL, NULL, 2640, 2.64, 60, $str$Brinell$str$, $str$Grade Aluminum 5119$str$, $str$reference export baseline$str$, $str$Aluminum, ANSI 5119$str$),
  ($str$Generic Aluminum, ANSI 5083$str$, $str$Aluminum, ANSI 5083$str$, $str$Aluminum$str$, $str$Bar and Tube Fabrication$str$, 30.11, NULL, NULL, NULL, NULL, NULL, 2700, 2.7, 60, $str$Brinell$str$, $str$Grade 5083$str$, $str$reference export baseline$str$, $str$Aluminum, ANSI 5083$str$),
  ($str$Generic Aluminum, ANSI 5005A$str$, $str$Aluminum, ANSI 5005A$str$, $str$Aluminum$str$, $str$Bar and Tube Fabrication$str$, 30.11, NULL, NULL, NULL, NULL, NULL, 2700, 2.7, 60, $str$Brinell$str$, $str$Grade 5005A$str$, $str$reference export baseline$str$, $str$Aluminum, ANSI 5005A$str$),
  ($str$Generic Aluminum, ANSI 3103$str$, $str$Aluminum, ANSI 3103$str$, $str$Aluminum$str$, $str$Bar and Tube Fabrication$str$, 30.11, NULL, NULL, NULL, NULL, NULL, 2730, 2.73, 60, $str$Brinell$str$, $str$Grade 3103$str$, $str$reference export baseline$str$, $str$Aluminum, ANSI 3103$str$),
  ($str$Generic Aluminum, ANSI 3003$str$, $str$Aluminum, ANSI 3003$str$, $str$Aluminum$str$, $str$Bar and Tube Fabrication$str$, 30.11, NULL, NULL, NULL, NULL, NULL, 2730, 2.73, 60, $str$Brinell$str$, $str$Grade 3003$str$, $str$reference export baseline$str$, $str$Aluminum, ANSI 3003$str$),
  ($str$Generic Aluminum, ANSI 2030$str$, $str$Aluminum, ANSI 2030$str$, $str$Aluminum$str$, $str$Bar and Tube Fabrication$str$, 30.11, NULL, NULL, NULL, NULL, NULL, 2820, 2.82, 60, $str$Brinell$str$, $str$Grade 2030$str$, $str$reference export baseline$str$, $str$Aluminum, ANSI 2030$str$),
  ($str$Generic Aluminum, ANSI 2007$str$, $str$Aluminum, ANSI 2007$str$, $str$Aluminum$str$, $str$Bar and Tube Fabrication$str$, 30.11, NULL, NULL, NULL, NULL, NULL, 2850, 2.85, 60, $str$Brinell$str$, $str$Grade 2007$str$, $str$reference export baseline$str$, $str$Aluminum, ANSI 2007$str$),
  ($str$Generic Aluminum, ANSI 1050A$str$, $str$Aluminum, ANSI 1050A$str$, $str$Aluminum$str$, $str$Bar and Tube Fabrication$str$, 30.11, NULL, NULL, NULL, NULL, NULL, 2700, 2.7, 60, $str$Brinell$str$, $str$Grade 1050A$str$, $str$reference export baseline$str$, $str$Aluminum, ANSI 1050A$str$),
  ($str$Generic Aluminum, AA 7003$str$, $str$Aluminum, AA 7003$str$, $str$Aluminum$str$, $str$Bar and Tube Fabrication$str$, 30.11, NULL, NULL, NULL, NULL, NULL, 2900, 2.9, 60, $str$Brinell$str$, $str$Grade 7003$str$, $str$reference export baseline$str$, $str$Aluminum, AA 7003$str$),
  ($str$Generic Aluminum, AA 383.0$str$, $str$Aluminum, AA 383.0$str$, $str$Aluminum$str$, $str$Bar and Tube Fabrication$str$, 30.11, NULL, NULL, NULL, NULL, NULL, 2800, 2.8, 60, $str$Brinell$str$, $str$Grade 383$str$, $str$reference export baseline$str$, $str$Aluminum, AA 383.0$str$),
  ($str$Generic Aluminum, AA 380.0$str$, $str$Aluminum, AA 380.0$str$, $str$Aluminum$str$, $str$Bar and Tube Fabrication$str$, 30.11, NULL, NULL, NULL, NULL, NULL, 2900, 2.9, 80, $str$Brinell$str$, $str$Grade 380$str$, $str$reference export baseline$str$, $str$Aluminum, AA 380.0$str$),
  ($str$Generic Aluminum, AA 3105$str$, $str$Aluminum, AA 3105$str$, $str$Aluminum$str$, $str$Bar and Tube Fabrication$str$, 30.11, NULL, NULL, NULL, NULL, NULL, 2800, 2.8, 60, $str$Brinell$str$, $str$Grade 3105$str$, $str$reference export baseline$str$, $str$Aluminum, AA 3105$str$),
  ($str$Generic Aluminum, AA 2219$str$, $str$Aluminum, AA 2219$str$, $str$Aluminum$str$, $str$Bar and Tube Fabrication$str$, 30.11, NULL, NULL, NULL, NULL, NULL, 3100, 3.1, 60, $str$Brinell$str$, $str$Grade 2219$str$, $str$reference export baseline$str$, $str$Aluminum, AA 2219$str$),
  ($str$Generic Aluminum, AA 1100$str$, $str$Aluminum, AA 1100$str$, $str$Aluminum$str$, $str$Bar and Tube Fabrication$str$, 30.11, NULL, NULL, NULL, NULL, NULL, 2700, 2.7, 60, $str$Brinell$str$, $str$Grade 1100$str$, $str$reference export baseline$str$, $str$Aluminum, AA 1100$str$)
  ) AS v(material, material_grade, material_type, material_group, cut_code, cost, cost_usa, cost_units, base_cost_per_unit_usd, currency, density_kg_m3, density, hardness, hardness_system, description, data_source, usa_name)
),
props(source_name, property_key, value_num, value_text, unit) AS (VALUES
  ($str$Generic Aluminum, AA 2219$str$, $str$ultimate_tensile_strength$str$, 330, NULL, $str$MPa$str$),
  ($str$Generic Aluminum, AA 2219$str$, $str$milling_speed$str$, 0, NULL, $str$m / min$str$),
  ($str$Generic Aluminum, AA 2219$str$, $str$turning_speed$str$, 0, NULL, $str$m / min$str$),
  ($str$Generic Aluminum, AA 2219$str$, $str$specific_heat_rt$str$, 900, NULL, $str$J / kg * K$str$),
  ($str$Generic Aluminum, AA 2219$str$, $str$heat_of_fusion$str$, 390000, NULL, $str$J / kg$str$),
  ($str$Generic Aluminum, AA 2219$str$, $str$solidus_temp$str$, 543, NULL, $str$C$str$),
  ($str$Generic Aluminum, AA 2219$str$, $str$thermal_conductivity$str$, 140, NULL, $str$Watts / m * C$str$),
  ($str$Generic Aluminum, AA 2219$str$, $str$minimum_extrusion_exit_speed$str$, 46.68, NULL, $str$mm / s$str$),
  ($str$Generic Aluminum, AA 2219$str$, $str$maximum_extrusion_exit_speed$str$, 100.2, NULL, $str$mm / s$str$),
  ($str$Generic Aluminum, AA 2219$str$, $str$gap_filled_fields$str$, NULL, $str$Round Bar/Round Tube/Sheet/Square Bar/Square Tube/T-Beam costs$str$, NULL),
  ($str$Generic Aluminum, AA 2219$str$, $str$gap_fill_basis$str$, NULL, $str$Derived: form-cost ratio to angle bar taken from AA 3105 full record$str$, NULL),
  ($str$Generic Aluminum, AA 1100$str$, $str$din_name$str$, NULL, $str$Aluminum, AA 1100$str$, NULL),
  ($str$Generic Aluminum, AA 1100$str$, $str$en_name$str$, NULL, $str$EN AW-1100$str$, NULL),
  ($str$Generic Aluminum, AA 1100$str$, $str$gb_name$str$, NULL, $str$Aluminum, AA 1100$str$, NULL),
  ($str$Generic Aluminum, AA 1100$str$, $str$jis_name$str$, NULL, $str$Aluminum, AA 1100$str$, NULL),
  ($str$Generic Aluminum, AA 1100$str$, $str$angle_bar_unit_cost$str$, 7.561, NULL, $str$USD / kg$str$),
  ($str$Generic Aluminum, AA 1100$str$, $str$angle_bar_cost_units$str$, NULL, $str$Cost per KG$str$, NULL),
  ($str$Generic Aluminum, AA 1100$str$, $str$base_angle_bar_cost_per_unit$str$, 7.56, NULL, $str$USD$str$),
  ($str$Generic Aluminum, AA 1100$str$, $str$channel_bar_unit_cost$str$, 7.163, NULL, $str$USD / kg$str$),
  ($str$Generic Aluminum, AA 1100$str$, $str$channel_bar_cost_units$str$, NULL, $str$Cost per KG$str$, NULL),
  ($str$Generic Aluminum, AA 1100$str$, $str$base_channel_bar_cost_per_unit$str$, 7.16, NULL, $str$USD$str$),
  ($str$Generic Aluminum, AA 1100$str$, $str$hex_bar_unit_cost$str$, 7.629, NULL, $str$USD / kg$str$),
  ($str$Generic Aluminum, AA 1100$str$, $str$hex_bar_cost_units$str$, NULL, $str$Cost per KG$str$, NULL),
  ($str$Generic Aluminum, AA 1100$str$, $str$base_hex_bar_cost_per_unit$str$, 7.63, NULL, $str$USD$str$),
  ($str$Generic Aluminum, AA 1100$str$, $str$i_beam_unit_cost$str$, 6.454, NULL, $str$USD / kg$str$),
  ($str$Generic Aluminum, AA 1100$str$, $str$i_beam_cost_units$str$, NULL, $str$Cost per KG$str$, NULL),
  ($str$Generic Aluminum, AA 1100$str$, $str$base_i_beam_cost_per_unit$str$, 6.45, NULL, $str$USD$str$),
  ($str$Generic Aluminum, AA 1100$str$, $str$rectangular_bar_unit_cost$str$, 8.236, NULL, $str$USD / kg$str$),
  ($str$Generic Aluminum, AA 1100$str$, $str$rectangular_bar_cost_units$str$, NULL, $str$Cost per KG$str$, NULL),
  ($str$Generic Aluminum, AA 1100$str$, $str$base_rectangular_bar_cost_per_unit$str$, 8.24, NULL, $str$USD$str$),
  ($str$Generic Aluminum, AA 1100$str$, $str$rectangular_tube_unit_cost$str$, 8.034, NULL, $str$USD / kg$str$),
  ($str$Generic Aluminum, AA 1100$str$, $str$rectangular_tube_cost_units$str$, NULL, $str$Cost per KG$str$, NULL),
  ($str$Generic Aluminum, AA 1100$str$, $str$base_rectangular_tube_cost_per_unit$str$, 8.03, NULL, $str$USD$str$),
  ($str$Generic Aluminum, AA 1100$str$, $str$round_bar_unit_cost$str$, 6.751, NULL, $str$USD / kg$str$),
  ($str$Generic Aluminum, AA 1100$str$, $str$round_bar_cost_units$str$, NULL, $str$Cost per KG$str$, NULL),
  ($str$Generic Aluminum, AA 1100$str$, $str$base_round_bar_cost_per_unit$str$, 6.75, NULL, $str$USD$str$),
  ($str$Generic Aluminum, AA 1100$str$, $str$round_tube_unit_cost$str$, 8.884, NULL, $str$USD / kg$str$),
  ($str$Generic Aluminum, AA 1100$str$, $str$round_tube_cost_units$str$, NULL, $str$Cost per KG$str$, NULL),
  ($str$Generic Aluminum, AA 1100$str$, $str$base_round_tube_cost_per_unit$str$, 8.88, NULL, $str$USD$str$),
  ($str$Generic Aluminum, AA 1100$str$, $str$sheet_unit_cost$str$, 6.603, NULL, $str$USD / kg$str$),
  ($str$Generic Aluminum, AA 1100$str$, $str$sheet_cost_units$str$, NULL, $str$Cost per KG$str$, NULL),
  ($str$Generic Aluminum, AA 1100$str$, $str$base_sheet_cost_per_unit$str$, 6.6, NULL, $str$USD$str$),
  ($str$Generic Aluminum, AA 1100$str$, $str$square_bar_unit_cost$str$, 7.864, NULL, $str$USD / kg$str$),
  ($str$Generic Aluminum, AA 1100$str$, $str$square_bar_cost_units$str$, NULL, $str$Cost per KG$str$, NULL),
  ($str$Generic Aluminum, AA 1100$str$, $str$base_square_bar_cost_per_unit$str$, 7.86, NULL, $str$USD$str$),
  ($str$Generic Aluminum, AA 1100$str$, $str$square_tube_unit_cost$str$, 6.852, NULL, $str$USD / kg$str$),
  ($str$Generic Aluminum, AA 1100$str$, $str$square_tube_cost_units$str$, NULL, $str$Cost per KG$str$, NULL),
  ($str$Generic Aluminum, AA 1100$str$, $str$base_square_tube_cost_per_unit$str$, 6.85, NULL, $str$USD$str$),
  ($str$Generic Aluminum, AA 1100$str$, $str$t_beam_unit_cost$str$, 6.224, NULL, $str$USD / kg$str$),
  ($str$Generic Aluminum, AA 1100$str$, $str$t_beam_cost_units$str$, NULL, $str$Cost per KG$str$, NULL),
  ($str$Generic Aluminum, AA 1100$str$, $str$base_t_beam_cost_per_unit$str$, 6.22, NULL, $str$USD$str$),
  ($str$Generic Aluminum, AA 1100$str$, $str$shear_strength$str$, 75, NULL, $str$MPa$str$),
  ($str$Generic Aluminum, AA 1100$str$, $str$tensile_yield_strength$str$, 89, NULL, $str$MPa$str$),
  ($str$Generic Aluminum, AA 1100$str$, $str$ultimate_tensile_strength$str$, 128, NULL, $str$MPa$str$),
  ($str$Generic Aluminum, AA 1100$str$, $str$milling_speed$str$, 0, NULL, $str$m / min$str$),
  ($str$Generic Aluminum, AA 1100$str$, $str$turning_speed$str$, 0, NULL, $str$m / min$str$),
  ($str$Generic Aluminum, AA 1100$str$, $str$specific_heat_rt$str$, 900, NULL, $str$J / kg * K$str$),
  ($str$Generic Aluminum, AA 1100$str$, $str$heat_of_fusion$str$, 400000, NULL, $str$J / kg$str$),
  ($str$Generic Aluminum, AA 1100$str$, $str$solidus_temp$str$, 570, NULL, $str$C$str$),
  ($str$Generic Aluminum, AA 1100$str$, $str$thermal_conductivity$str$, 220, NULL, $str$Watts / m * C$str$),
  ($str$Generic Aluminum, AA 1100$str$, $str$minimum_extrusion_exit_speed$str$, 46.68, NULL, $str$mm / s$str$),
  ($str$Generic Aluminum, AA 1100$str$, $str$maximum_extrusion_exit_speed$str$, 100.2, NULL, $str$mm / s$str$),
  ($str$Generic Aluminum, AA 1100$str$, $str$gap_filled_fields$str$, NULL, $str$Round Bar/Round Tube/Sheet/Square Bar/Square Tube/T-Beam costs$str$, NULL),
  ($str$Generic Aluminum, AA 1100$str$, $str$gap_fill_basis$str$, NULL, $str$Derived: form-cost ratio to angle bar taken from AA 3105 full record$str$, NULL)
)
INSERT INTO raw_material_properties (raw_material_id, property_key, value_num, value_text, unit, source_version)
SELECT t.id, p.property_key, CAST(p.value_num AS NUMERIC), CAST(p.value_text AS TEXT), CAST(p.unit AS TEXT), '2026-BarTube'
FROM props p
JOIN src s ON s.material = p.source_name
JOIN LATERAL (
  SELECT rm.id FROM raw_materials rm
  WHERE rm.material = s.material_name
  ORDER BY (rm.material_group = 'Bar and Tube Fabrication') DESC
  LIMIT 1
) t ON true
ON CONFLICT (raw_material_id, property_key) DO NOTHING;

-- ── Ferrous & Non-Ferrous: core columns (101 materials, policy attach)
WITH src AS (
  SELECT v.*,
    v.material AS material_name
  FROM (VALUES
  ($str$Generic Aluminum, AA 1100$str$, $str$Aluminum, AA 1100$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, AA 2219$str$, $str$Aluminum, AA 2219$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, AA 3105$str$, $str$Aluminum, AA 3105$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, AA 383.0$str$, $str$Aluminum, AA 383.0$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, AA 7003$str$, $str$Aluminum, AA 7003$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 1050A$str$, $str$Aluminum, ANSI 1050A$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 2007$str$, $str$Aluminum, ANSI 2007$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 2017$str$, $str$Aluminum, ANSI 2017$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 2024$str$, $str$Aluminum, ANSI 2024$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 2030$str$, $str$Aluminum, ANSI 2030$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 3003$str$, $str$Aluminum, ANSI 3003$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 3103$str$, $str$Aluminum, ANSI 3103$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 5005$str$, $str$Aluminum, ANSI 5005$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 5005A$str$, $str$Aluminum, ANSI 5005A$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 5019$str$, $str$Aluminum, ANSI 5019$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 5052$str$, $str$Aluminum, ANSI 5052$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 5083$str$, $str$Aluminum, ANSI 5083$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 5119$str$, $str$Aluminum, ANSI 5119$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 5251$str$, $str$Aluminum, ANSI 5251$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 5454$str$, $str$Aluminum, ANSI 5454$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 5754$str$, $str$Aluminum, ANSI 5754$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 6012$str$, $str$Aluminum, ANSI 6012$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 6060$str$, $str$Aluminum, ANSI 6060$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 6061$str$, $str$Aluminum, ANSI 6061$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 6082$str$, $str$Aluminum, ANSI 6082$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 7020$str$, $str$Aluminum, ANSI 7020$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 7022$str$, $str$Aluminum, ANSI 7022$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 7050$str$, $str$Aluminum, ANSI 7050$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Aluminum, ANSI 7075$str$, $str$Aluminum, ANSI 7075$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL),
  ($str$Generic Brass, UNS C36000$str$, $str$Brass, UNS C36000$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 200, NULL, NULL, NULL, NULL),
  ($str$Generic C60$str$, $str$C60$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 170, NULL, NULL, NULL, NULL),
  ($str$Generic C60E$str$, $str$C60E$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 170, NULL, NULL, NULL, NULL),
  ($str$Generic Copper, UNS C11000$str$, $str$Copper, UNS C11000$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 100, NULL, NULL, NULL, NULL),
  ($str$Generic Copper, UNS C18150$str$, $str$Copper, UNS C18150$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 100, NULL, NULL, NULL, NULL),
  ($str$Generic Copper, UNS C27200$str$, $str$Copper, UNS C27200$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 100, NULL, NULL, NULL, NULL),
  ($str$Generic Copper, UNS C28000$str$, $str$Copper, UNS C28000$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 100, NULL, NULL, NULL, NULL),
  ($str$Generic Copper, UNS C51900$str$, $str$Copper, UNS C51900$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 100, NULL, NULL, NULL, NULL),
  ($str$Generic Copper, UNS C62730$str$, $str$Copper, UNS C62730$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 100, NULL, NULL, NULL, NULL),
  ($str$Generic Galv. Steel, Hot Worked, AISI 1010$str$, $str$Galv. Steel, Hot Worked, AISI 1010$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 125, NULL, NULL, NULL, NULL),
  ($str$Generic Galv. Steel, Hot Worked, AISI 1012$str$, $str$Galv. Steel, Hot Worked, AISI 1012$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 125, NULL, NULL, NULL, NULL),
  ($str$Generic Galv. Steel, Hot Worked, AISI 1020$str$, $str$Galv. Steel, Hot Worked, AISI 1020$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 125, NULL, NULL, NULL, NULL),
  ($str$Generic Galv. Steel, Hot Worked, DX51D$str$, $str$Galv. Steel, Hot Worked, DX51D$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 170, NULL, NULL, NULL, NULL),
  ($str$Generic Galv. Steel, Hot Worked, DX54$str$, $str$Galv. Steel, Hot Worked, DX54$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 220, NULL, NULL, NULL, NULL),
  ($str$Generic Hastelloy C-276$str$, $str$Hastelloy C-276$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 275, NULL, NULL, NULL, NULL),
  ($str$Generic Hastelloy X$str$, $str$Hastelloy X$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 200, NULL, NULL, NULL, NULL),
  ($str$Generic Haynes alloy 230$str$, $str$Haynes alloy 230$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 190, NULL, NULL, NULL, NULL),
  ($str$Generic Inconel 625$str$, $str$Inconel 625$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 195, NULL, NULL, NULL, NULL),
  ($str$Generic Inconel 718$str$, $str$Inconel 718$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 350, NULL, NULL, NULL, NULL),
  ($str$Generic Stainless Steel, 15-5PH$str$, $str$Stainless Steel, 15-5PH$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 330, NULL, NULL, NULL, NULL),
  ($str$Generic Stainless Steel, 17-4PH$str$, $str$Stainless Steel, 17-4PH$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 345, NULL, NULL, NULL, NULL),
  ($str$Generic Stainless Steel, 440B$str$, $str$Stainless Steel, 440B$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 260, NULL, NULL, NULL, NULL),
  ($str$Generic Stainless Steel, A240$str$, $str$Stainless Steel, A240$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 260, NULL, NULL, NULL, NULL),
  ($str$Generic Stainless Steel, A351 CF8$str$, $str$Stainless Steel, A351 CF8$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 260, NULL, NULL, NULL, NULL),
  ($str$Generic Stainless Steel, AISI 301$str$, $str$Stainless Steel, AISI 301$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 330, NULL, NULL, NULL, NULL),
  ($str$Generic Stainless Steel, AISI 303$str$, $str$Stainless Steel, AISI 303$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 175, NULL, NULL, NULL, NULL),
  ($str$Generic Stainless Steel, AISI 304$str$, $str$Stainless Steel, AISI 304$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 210, NULL, NULL, NULL, NULL),
  ($str$Generic Stainless Steel, AISI 304L$str$, $str$Stainless Steel, AISI 304L$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 235, NULL, NULL, NULL, NULL),
  ($str$Generic Stainless Steel, AISI 316$str$, $str$Stainless Steel, AISI 316$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 290, NULL, NULL, NULL, NULL),
  ($str$Generic Stainless Steel, AISI 316L$str$, $str$Stainless Steel, AISI 316L$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 535, NULL, NULL, NULL, NULL),
  ($str$Generic Stainless Steel, AISI 316Ti$str$, $str$Stainless Steel, AISI 316Ti$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 295, NULL, NULL, NULL, NULL),
  ($str$Generic Stainless Steel, AISI 321$str$, $str$Stainless Steel, AISI 321$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 260, NULL, NULL, NULL, NULL),
  ($str$Generic Stainless Steel, AISI 441$str$, $str$Stainless Steel, AISI 441$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 528, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, AISI 1035$str$, $str$Steel, AISI 1035$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 150, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, AISI 4140, Medium-Carbon$str$, $str$Steel, AISI 4140, Medium-Carbon$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 180, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Cold Worked, AISI 1005$str$, $str$Steel, Cold Worked, AISI 1005$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 95, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Cold Worked, AISI 1008$str$, $str$Steel, Cold Worked, AISI 1008$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 125, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Cold Worked, AISI 1010$str$, $str$Steel, Cold Worked, AISI 1010$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 125, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Cold Worked, AISI 1012$str$, $str$Steel, Cold Worked, AISI 1012$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 130, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Cold Worked, AISI 1018$str$, $str$Steel, Cold Worked, AISI 1018$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 130, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Cold Worked, AISI 1020$str$, $str$Steel, Cold Worked, AISI 1020$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 220, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Cold Worked, AISI 1050$str$, $str$Steel, Cold Worked, AISI 1050$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 210, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Cold Worked, AISI 4130$str$, $str$Steel, Cold Worked, AISI 4130$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 220, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Cold Worked, AISI 4340$str$, $str$Steel, Cold Worked, AISI 4340$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 330, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Cold Worked, AISI 5210$str$, $str$Steel, Cold Worked, AISI 5210$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 207, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Cold Worked, AISI 8620$str$, $str$Steel, Cold Worked, AISI 8620$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 125, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Cold Worked, DC06$str$, $str$Steel, Cold Worked, DC06$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 125, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 1006$str$, $str$Steel, Hot Worked, AISI 1006$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 125, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 1008$str$, $str$Steel, Hot Worked, AISI 1008$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 125, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 1010$str$, $str$Steel, Hot Worked, AISI 1010$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 125, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 1012$str$, $str$Steel, Hot Worked, AISI 1012$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 130, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 1018$str$, $str$Steel, Hot Worked, AISI 1018$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 150, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 1020$str$, $str$Steel, Hot Worked, AISI 1020$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 150, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 1042$str$, $str$Steel, Hot Worked, AISI 1042$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 200, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 1045$str$, $str$Steel, Hot Worked, AISI 1045$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 200, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 1049$str$, $str$Steel, Hot Worked, AISI 1049$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 200, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 1050$str$, $str$Steel, Hot Worked, AISI 1050$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 125, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 1075$str$, $str$Steel, Hot Worked, AISI 1075$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 125, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 1095$str$, $str$Steel, Hot Worked, AISI 1095$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1034, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 1213$str$, $str$Steel, Hot Worked, AISI 1213$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 125, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 12L13$str$, $str$Steel, Hot Worked, AISI 12L13$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 180, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 1513$str$, $str$Steel, Hot Worked, AISI 1513$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 180, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 4140$str$, $str$Steel, Hot Worked, AISI 4140$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 125, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 4140H$str$, $str$Steel, Hot Worked, AISI 4140H$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 210, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 5115$str$, $str$Steel, Hot Worked, AISI 5115$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 210, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, AISI 6150$str$, $str$Steel, Hot Worked, AISI 6150$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 210, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, ASTM A36$str$, $str$Steel, Hot Worked, ASTM A36$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 115, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, ASTM A572 Grade 50$str$, $str$Steel, Hot Worked, ASTM A572 Grade 50$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 310, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, Grade S235JR$str$, $str$Steel, Hot Worked, Grade S235JR$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 950, NULL, NULL, NULL, NULL),
  ($str$Generic Steel, Hot Worked, S900MC$str$, $str$Steel, Hot Worked, S900MC$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ($str$Generic Titanium, Ti-5Al-2.5Sn$str$, $str$Titanium, Ti-5Al-2.5Sn$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ($str$Generic Titanium, Ti-6Al-4V$str$, $str$Titanium, Ti-6Al-4V$str$, NULL, $str$Ferrous & Non-Ferrous$str$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
  ) AS v(material, material_grade, material_type, material_group, cut_code, cost, cost_usa, cost_units, base_cost_per_unit_usd, currency, density_kg_m3, density, hardness, hardness_system, description, data_source, usa_name)
)
INSERT INTO raw_materials (material, material_grade, material_type, material_group, cut_code, cost, cost_usa, cost_units, base_cost_per_unit_usd, currency, density_kg_m3, density, hardness, hardness_system, description, data_source, usa_name)
SELECT s.material_name, s.material_grade, s.material_type, s.material_group, CAST(s.cut_code AS NUMERIC), CAST(s.cost AS NUMERIC), CAST(s.cost_usa AS NUMERIC), s.cost_units, CAST(s.base_cost_per_unit_usd AS NUMERIC), s.currency, CAST(s.density_kg_m3 AS NUMERIC), CAST(s.density AS NUMERIC), CAST(s.hardness AS NUMERIC), s.hardness_system, s.description, s.data_source, s.usa_name
FROM src s
WHERE NOT EXISTS (SELECT 1 FROM raw_materials rm WHERE rm.material = s.material_name);
