-- ============================================================================
-- Migration 861: USA unit cost for the plastic materials (materials_final.csv)
-- ============================================================================
-- Source: memory/Plastic Modeling/materials_final.csv, cost.unitCostUsdPerKg, USD/kg.
-- Sets cost and cost_usa only where they are still empty, so a value already set
-- elsewhere is never overwritten. Matched by Source Name. Idempotent.
-- 109 materials in the file with a cost.
-- ============================================================================

WITH v(material, cost) AS (VALUES
  ($str$Generic ABS$str$, 3.046),
  ($str$Generic ABS, 10% Glass$str$, 4.025),
  ($str$Generic ABS, 30% Glass$str$, 3.895),
  ($str$Generic ABS, Fittings$str$, 2.935),
  ($str$Generic ABS, Flame Ret$str$, 3.807),
  ($str$Generic ABS, Hi Heat$str$, 3.136),
  ($str$Generic ABS, Hi Impact$str$, 2.663),
  ($str$Generic ABS, PC-ABS$str$, 3.623),
  ($str$Generic ABS, Plating$str$, 4.762),
  ($str$Generic ABS, Transparent$str$, 4.892),
  ($str$Generic ABS, X-Hi Impact$str$, 3.751),
  ($str$Generic Acetal, Copolymer$str$, 3.519),
  ($str$Generic Acetal, Copolymer 25% Glass$str$, 5.329),
  ($str$Generic Acetal, Homopol$str$, 4.692),
  ($str$Generic Acetal, Homopol 20% Glass$str$, 6.029),
  ($str$Generic Acrylic, PMMA$str$, 1.968),
  ($str$Generic Epoxy, CF50$str$, 35.207),
  ($str$Generic Epoxy, CF60$str$, 42.382),
  ($str$Generic Nylon, Transparent Amorphous$str$, 7.868),
  ($str$Generic Nylon, Type 11$str$, 10.867),
  ($str$Generic Nylon, Type 11 30% Glass$str$, 11.059),
  ($str$Generic Nylon, Type 11 40% Glass$str$, 11.486),
  ($str$Generic Nylon, Type 12$str$, 8.538),
  ($str$Generic Nylon, Type 12 30% Glass$str$, 8.773),
  ($str$Generic Nylon, Type 12 50% Glass$str$, 8.279),
  ($str$Generic Nylon, Type 46$str$, 7.644),
  ($str$Generic Nylon, Type 6$str$, 4.124),
  ($str$Generic Nylon, Type 6 30% Glass$str$, 4.187),
  ($str$Generic Nylon, Type 6 Min Filled$str$, 3.64),
  ($str$Generic Nylon, Type 6/10$str$, 7.762),
  ($str$Generic Nylon, Type 612$str$, 10.372),
  ($str$Generic Nylon, Type 612 30% Glass$str$, 8.032),
  ($str$Generic Nylon, Type 612 40% Glass$str$, 8.009),
  ($str$Generic Nylon, Type 66$str$, 4.363),
  ($str$Generic Nylon, Type 66 30% Glass$str$, 4.387),
  ($str$Generic Nylon, Type 66 Min Filled$str$, 4.022),
  ($str$Generic Nylon, Type 69$str$, 6.821),
  ($str$Generic PET 30% Glass$str$, 3.704),
  ($str$Generic PET 30% Glass Flame Ret$str$, 4.163),
  ($str$Generic PET 55% Glass$str$, 4.07),
  ($str$Generic PET, Bottle (rcar)$str$, 3.169),
  ($str$Generic PET, Injection$str$, 2.736),
  ($str$Generic PETG Copol$str$, 3.216),
  ($str$Generic Polybutylene Terephthalate$str$, 2.2),
  ($str$Generic Polybutylene Terephthalate GF30$str$, 3.2),
  ($str$Generic Polybutylene Terephthalate GF40$str$, 4.3),
  ($str$Generic Polycarbonate$str$, 6.059),
  ($str$Generic Polycarbonate 20% Glass$str$, 7.248),
  ($str$Generic Polycarbonate 30% Glass$str$, 5.773),
  ($str$Generic Polycarbonate, CD$str$, 5.595),
  ($str$Generic Polycarbonate, FR$str$, 7.549),
  ($str$Generic Polyphenylene Sulfide$str$, 3.5),
  ($str$Generic Polyphenylene Sulfide GF30$str$, 4),
  ($str$Generic Polyphenylene Sulfide GF40$str$, 6.5),
  ($str$Generic Polypropylene Ext. Fiber$str$, 0.931),
  ($str$Generic Polypropylene G-P H$str$, 1.077),
  ($str$Generic Polypropylene Hi Impact Copol$str$, 1.437),
  ($str$Generic Polypropylene Med Impact Copol$str$, 1.18),
  ($str$Generic Polypropylene Profiles$str$, 1.186),
  ($str$Generic Polypropylene Random Copol$str$, 1.269),
  ($str$Generic Polystyrene$str$, 2.977),
  ($str$Generic Polystyrene FR$str$, 3.843),
  ($str$Generic Polystyrene G-P Crystal$str$, 2.494),
  ($str$Generic Polystyrene Hi Heat$str$, 2.635),
  ($str$Generic Polystyrene HIPS$str$, 2.862),
  ($str$Generic Polystyrene Super Hi Impact$str$, 2.76),
  ($str$Generic Polyurethane, 80/20 TDI$str$, 2.789),
  ($str$Generic Polyurethane, Polymeric MDI$str$, 2.668),
  ($str$Generic TPA$str$, 15.088),
  ($str$Generic TPE$str$, 8.916),
  ($str$Generic TPO$str$, 3.292),
  ($str$Generic TPS$str$, 4.115),
  ($str$Generic TPU$str$, 9.602),
  ($str$Generic TPV$str$, 5.839),
  ($str$Generic Unsaturated Polyester, CF50$str$, 27.477),
  ($str$Generic Unsaturated Polyester, CF53$str$, 28.811),
  ($str$Generic Unsaturated Polyester, CF55$str$, 29.7),
  ($str$Generic Unsaturated Polyester, GF10-FR$str$, 2.038),
  ($str$Generic Unsaturated Polyester, GF10-FRLS$str$, 1.91),
  ($str$Generic Unsaturated Polyester, GF12-FR$str$, 1.972),
  ($str$Generic Unsaturated Polyester, GF15-FR$str$, 1.741),
  ($str$Generic Unsaturated Polyester, GF15-FRLS$str$, 2.495),
  ($str$Generic Unsaturated Polyester, GF15-LS$str$, 1.925),
  ($str$Generic Unsaturated Polyester, GF15-SR$str$, 1.884),
  ($str$Generic Unsaturated Polyester, GF18-FR$str$, 2.028),
  ($str$Generic Unsaturated Polyester, GF20-FR$str$, 1.925),
  ($str$Generic Unsaturated Polyester, GF20-FRLS$str$, 1.796),
  ($str$Generic Unsaturated Polyester, GF20-LS$str$, 1.67),
  ($str$Generic Unsaturated Polyester, GF22-FR$str$, 1.923),
  ($str$Generic Unsaturated Polyester, GF24-GP$str$, 1.806),
  ($str$Generic Unsaturated Polyester, GF25-FR$str$, 2.221),
  ($str$Generic Unsaturated Polyester, GF25-GA$str$, 1.781),
  ($str$Generic Unsaturated Polyester, GF25-GP$str$, 2.36),
  ($str$Generic Unsaturated Polyester, GF25-LS$str$, 2.25),
  ($str$Generic Unsaturated Polyester, GF27-LPA$str$, 2.95),
  ($str$Generic Unsaturated Polyester, GF28-GP$str$, 1.87),
  ($str$Generic Unsaturated Polyester, GF28-LD$str$, 2.42),
  ($str$Generic Unsaturated Polyester, GF30-LP$str$, 2.36),
  ($str$Generic Unsaturated Polyester, GF30-LPA$str$, 2.95),
  ($str$Generic Unsaturated Polyester, GF30-LS$str$, 2.25),
  ($str$Generic Unsaturated Polyester, GF33-GP$str$, 1.9),
  ($str$Generic Unsaturated Polyester, GF35-LD$str$, 2.45),
  ($str$Generic Unsaturated Polyester, GF38-LPA$str$, 3),
  ($str$Generic Unsaturated Polyester, GF45-GP$str$, 2.7),
  ($str$Generic Unsaturated Polyester, GF63-GP$str$, 2.8),
  ($str$Generic Unsaturated Polyester, GF8-CA$str$, 1.957),
  ($str$Generic Unsaturated Polyester, GFCF55$str$, 15.4),
  ($str$Generic Vinyl Ester, CF50$str$, 31.798),
  ($str$Generic Vinyl Ester, CF60$str$, 36.374)
)
UPDATE raw_materials rm
SET cost = v.cost, cost_usa = v.cost
FROM v
WHERE rm.material = v.material
  AND rm.cost_usa IS NULL;

NOTIFY pgrst, 'reload schema';

-- Verify: SELECT count(*) FROM raw_materials rm WHERE rm.material_group = 'Plastic Molding' AND rm.cost_usa IS NULL;
