-- 868: India stock prices (502 rows, 90 materials), the INSERT from migration 833 on its own.
-- Migration 833 ran as one transaction; its link step failed on the renamed column, which rolled
-- back this insert too. This file has the insert only. Idempotent (ON CONFLICT DO UPDATE).
-- Link to raw_materials is done by 867.

INSERT INTO material_stock_prices (reference_material, stock_form, location, price_per_kg, currency_code, source)
VALUES
  ($str$Steel, Hot Worked, AISI 1006$str$, $str$hex_bar$str$, $str$India$str$, 0.837, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1006$str$, $str$plate$str$, $str$India$str$, 0.938, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1006$str$, $str$rectangular_bar$str$, $str$India$str$, 0.904, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1006$str$, $str$round_bar$str$, $str$India$str$, 0.741, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1006$str$, $str$round_tube$str$, $str$India$str$, 0.975, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1006$str$, $str$square_bar$str$, $str$India$str$, 0.863, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1005$str$, $str$hex_bar$str$, $str$India$str$, 0.837, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1005$str$, $str$plate$str$, $str$India$str$, 0.938, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1005$str$, $str$rectangular_bar$str$, $str$India$str$, 0.904, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1005$str$, $str$round_bar$str$, $str$India$str$, 0.741, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1005$str$, $str$round_tube$str$, $str$India$str$, 0.975, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1005$str$, $str$square_bar$str$, $str$India$str$, 0.863, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1008$str$, $str$hex_bar$str$, $str$India$str$, 0.838, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1008$str$, $str$plate$str$, $str$India$str$, 0.939, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1008$str$, $str$rectangular_bar$str$, $str$India$str$, 0.905, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1008$str$, $str$round_bar$str$, $str$India$str$, 0.741, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1008$str$, $str$round_tube$str$, $str$India$str$, 0.976, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1008$str$, $str$square_bar$str$, $str$India$str$, 0.864, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1010$str$, $str$hex_bar$str$, $str$India$str$, 0.838, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1010$str$, $str$plate$str$, $str$India$str$, 0.939, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1010$str$, $str$rectangular_bar$str$, $str$India$str$, 0.905, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1010$str$, $str$round_bar$str$, $str$India$str$, 0.742, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1010$str$, $str$round_tube$str$, $str$India$str$, 0.976, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1010$str$, $str$square_bar$str$, $str$India$str$, 0.864, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, ASTM A36$str$, $str$hex_bar$str$, $str$India$str$, 0.84, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, ASTM A36$str$, $str$plate$str$, $str$India$str$, 0.941, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, ASTM A36$str$, $str$rectangular_bar$str$, $str$India$str$, 0.906, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, ASTM A36$str$, $str$round_bar$str$, $str$India$str$, 0.743, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, ASTM A36$str$, $str$round_tube$str$, $str$India$str$, 0.978, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, ASTM A36$str$, $str$square_bar$str$, $str$India$str$, 0.866, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1045$str$, $str$hex_bar$str$, $str$India$str$, 0.841, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1045$str$, $str$plate$str$, $str$India$str$, 0.942, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1045$str$, $str$rectangular_bar$str$, $str$India$str$, 0.908, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1045$str$, $str$round_bar$str$, $str$India$str$, 0.744, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1045$str$, $str$round_tube$str$, $str$India$str$, 0.979, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1045$str$, $str$square_bar$str$, $str$India$str$, 0.867, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1042$str$, $str$hex_bar$str$, $str$India$str$, 0.841, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1042$str$, $str$plate$str$, $str$India$str$, 0.942, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1042$str$, $str$rectangular_bar$str$, $str$India$str$, 0.908, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1042$str$, $str$round_bar$str$, $str$India$str$, 0.744, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1042$str$, $str$round_tube$str$, $str$India$str$, 0.979, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1042$str$, $str$square_bar$str$, $str$India$str$, 0.867, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1050$str$, $str$hex_bar$str$, $str$India$str$, 0.842, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1050$str$, $str$plate$str$, $str$India$str$, 0.943, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1050$str$, $str$rectangular_bar$str$, $str$India$str$, 0.909, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1050$str$, $str$round_bar$str$, $str$India$str$, 0.745, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1050$str$, $str$round_tube$str$, $str$India$str$, 0.98, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1050$str$, $str$square_bar$str$, $str$India$str$, 0.868, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1018$str$, $str$hex_bar$str$, $str$India$str$, 0.842, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1018$str$, $str$plate$str$, $str$India$str$, 0.943, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1018$str$, $str$rectangular_bar$str$, $str$India$str$, 0.909, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1018$str$, $str$round_bar$str$, $str$India$str$, 0.745, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1018$str$, $str$round_tube$str$, $str$India$str$, 0.98, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1018$str$, $str$square_bar$str$, $str$India$str$, 0.868, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1213$str$, $str$hex_bar$str$, $str$India$str$, 0.846, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1213$str$, $str$plate$str$, $str$India$str$, 0.948, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1213$str$, $str$rectangular_bar$str$, $str$India$str$, 0.913, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1213$str$, $str$round_bar$str$, $str$India$str$, 0.748, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1213$str$, $str$round_tube$str$, $str$India$str$, 0.985, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1213$str$, $str$square_bar$str$, $str$India$str$, 0.872, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1012$str$, $str$hex_bar$str$, $str$India$str$, 0.847, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1012$str$, $str$plate$str$, $str$India$str$, 0.949, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1012$str$, $str$rectangular_bar$str$, $str$India$str$, 0.914, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1012$str$, $str$round_bar$str$, $str$India$str$, 0.749, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1012$str$, $str$round_tube$str$, $str$India$str$, 0.986, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1012$str$, $str$square_bar$str$, $str$India$str$, 0.873, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, ASTM A572 Grade 50$str$, $str$hex_bar$str$, $str$India$str$, 0.847, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, ASTM A572 Grade 50$str$, $str$plate$str$, $str$India$str$, 0.949, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, ASTM A572 Grade 50$str$, $str$rectangular_bar$str$, $str$India$str$, 0.915, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, ASTM A572 Grade 50$str$, $str$round_bar$str$, $str$India$str$, 0.75, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, ASTM A572 Grade 50$str$, $str$round_tube$str$, $str$India$str$, 0.987, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, ASTM A572 Grade 50$str$, $str$square_bar$str$, $str$India$str$, 0.874, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1513$str$, $str$hex_bar$str$, $str$India$str$, 0.847, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1513$str$, $str$plate$str$, $str$India$str$, 0.949, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1513$str$, $str$rectangular_bar$str$, $str$India$str$, 0.915, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1513$str$, $str$round_bar$str$, $str$India$str$, 0.75, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1513$str$, $str$round_tube$str$, $str$India$str$, 0.987, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1513$str$, $str$square_bar$str$, $str$India$str$, 0.874, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 12L13$str$, $str$hex_bar$str$, $str$India$str$, 0.849, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 12L13$str$, $str$plate$str$, $str$India$str$, 0.952, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 12L13$str$, $str$rectangular_bar$str$, $str$India$str$, 0.917, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 12L13$str$, $str$round_bar$str$, $str$India$str$, 0.752, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 12L13$str$, $str$round_tube$str$, $str$India$str$, 0.989, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 12L13$str$, $str$square_bar$str$, $str$India$str$, 0.876, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, DC06$str$, $str$hex_bar$str$, $str$India$str$, 0.85, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, DC06$str$, $str$plate$str$, $str$India$str$, 0.952, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, DC06$str$, $str$rectangular_bar$str$, $str$India$str$, 0.918, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, DC06$str$, $str$round_bar$str$, $str$India$str$, 0.752, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, DC06$str$, $str$round_tube$str$, $str$India$str$, 0.99, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, DC06$str$, $str$square_bar$str$, $str$India$str$, 0.876, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, SAE 1580$str$, $str$hex_bar$str$, $str$India$str$, 0.853, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, SAE 1580$str$, $str$plate$str$, $str$India$str$, 0.956, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, SAE 1580$str$, $str$rectangular_bar$str$, $str$India$str$, 0.921, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, SAE 1580$str$, $str$round_bar$str$, $str$India$str$, 0.755, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, SAE 1580$str$, $str$round_tube$str$, $str$India$str$, 0.994, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, SAE 1580$str$, $str$square_bar$str$, $str$India$str$, 0.88, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 5115$str$, $str$hex_bar$str$, $str$India$str$, 0.872, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 5115$str$, $str$plate$str$, $str$India$str$, 0.977, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 5115$str$, $str$rectangular_bar$str$, $str$India$str$, 0.941, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 5115$str$, $str$round_bar$str$, $str$India$str$, 0.771, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 5115$str$, $str$round_tube$str$, $str$India$str$, 1.015, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 5115$str$, $str$square_bar$str$, $str$India$str$, 0.899, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 5210$str$, $str$hex_bar$str$, $str$India$str$, 0.876, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 5210$str$, $str$plate$str$, $str$India$str$, 0.982, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 5210$str$, $str$rectangular_bar$str$, $str$India$str$, 0.946, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 5210$str$, $str$round_bar$str$, $str$India$str$, 0.775, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 5210$str$, $str$round_tube$str$, $str$India$str$, 1.02, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 5210$str$, $str$square_bar$str$, $str$India$str$, 0.903, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1020$str$, $str$hex_bar$str$, $str$India$str$, 0.888, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1020$str$, $str$plate$str$, $str$India$str$, 0.995, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1020$str$, $str$rectangular_bar$str$, $str$India$str$, 0.959, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1020$str$, $str$round_bar$str$, $str$India$str$, 0.786, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1020$str$, $str$round_tube$str$, $str$India$str$, 1.034, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1020$str$, $str$square_bar$str$, $str$India$str$, 0.916, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, Grade S235JR$str$, $str$hex_bar$str$, $str$India$str$, 0.897, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, Grade S235JR$str$, $str$plate$str$, $str$India$str$, 1.005, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, Grade S235JR$str$, $str$rectangular_bar$str$, $str$India$str$, 0.969, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, Grade S235JR$str$, $str$round_bar$str$, $str$India$str$, 0.794, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, Grade S235JR$str$, $str$round_tube$str$, $str$India$str$, 1.045, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, Grade S235JR$str$, $str$square_bar$str$, $str$India$str$, 0.925, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 6150$str$, $str$hex_bar$str$, $str$India$str$, 0.901, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 6150$str$, $str$plate$str$, $str$India$str$, 1.01, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 6150$str$, $str$rectangular_bar$str$, $str$India$str$, 0.973, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 6150$str$, $str$round_bar$str$, $str$India$str$, 0.798, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 6150$str$, $str$round_tube$str$, $str$India$str$, 1.05, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 6150$str$, $str$square_bar$str$, $str$India$str$, 0.929, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, S900MC$str$, $str$hex_bar$str$, $str$India$str$, 0.908, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, S900MC$str$, $str$plate$str$, $str$India$str$, 1.017, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, S900MC$str$, $str$rectangular_bar$str$, $str$India$str$, 0.98, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, S900MC$str$, $str$round_bar$str$, $str$India$str$, 0.803, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, S900MC$str$, $str$round_tube$str$, $str$India$str$, 1.057, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, S900MC$str$, $str$square_bar$str$, $str$India$str$, 0.936, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1095$str$, $str$hex_bar$str$, $str$India$str$, 0.935, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1095$str$, $str$plate$str$, $str$India$str$, 1.047, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1095$str$, $str$rectangular_bar$str$, $str$India$str$, 1.009, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1095$str$, $str$round_bar$str$, $str$India$str$, 0.827, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1095$str$, $str$round_tube$str$, $str$India$str$, 1.089, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1095$str$, $str$square_bar$str$, $str$India$str$, 0.964, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1049$str$, $str$hex_bar$str$, $str$India$str$, 0.937, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1049$str$, $str$plate$str$, $str$India$str$, 1.05, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1049$str$, $str$rectangular_bar$str$, $str$India$str$, 1.012, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1049$str$, $str$round_bar$str$, $str$India$str$, 0.829, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1049$str$, $str$round_tube$str$, $str$India$str$, 1.091, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1049$str$, $str$square_bar$str$, $str$India$str$, 0.966, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1075$str$, $str$hex_bar$str$, $str$India$str$, 0.938, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1075$str$, $str$plate$str$, $str$India$str$, 1.051, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1075$str$, $str$rectangular_bar$str$, $str$India$str$, 1.013, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1075$str$, $str$round_bar$str$, $str$India$str$, 0.83, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1075$str$, $str$round_tube$str$, $str$India$str$, 1.093, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 1075$str$, $str$square_bar$str$, $str$India$str$, 0.967, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Galv. Steel, Hot Worked, AISI 1010$str$, $str$hex_bar$str$, $str$India$str$, 0.947, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Galv. Steel, Hot Worked, AISI 1010$str$, $str$plate$str$, $str$India$str$, 1.061, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Galv. Steel, Hot Worked, AISI 1010$str$, $str$rectangular_bar$str$, $str$India$str$, 1.023, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Galv. Steel, Hot Worked, AISI 1010$str$, $str$round_bar$str$, $str$India$str$, 0.838, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Galv. Steel, Hot Worked, AISI 1010$str$, $str$round_tube$str$, $str$India$str$, 1.103, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Galv. Steel, Hot Worked, AISI 1010$str$, $str$square_bar$str$, $str$India$str$, 0.977, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Galv. Steel, Hot Worked, AISI 1012$str$, $str$hex_bar$str$, $str$India$str$, 0.947, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Galv. Steel, Hot Worked, AISI 1012$str$, $str$plate$str$, $str$India$str$, 1.061, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Galv. Steel, Hot Worked, AISI 1012$str$, $str$rectangular_bar$str$, $str$India$str$, 1.023, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Galv. Steel, Hot Worked, AISI 1012$str$, $str$round_bar$str$, $str$India$str$, 0.838, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Galv. Steel, Hot Worked, AISI 1012$str$, $str$round_tube$str$, $str$India$str$, 1.103, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Galv. Steel, Hot Worked, AISI 1012$str$, $str$square_bar$str$, $str$India$str$, 0.977, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1008$str$, $str$hex_bar$str$, $str$India$str$, 0.955, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1008$str$, $str$plate$str$, $str$India$str$, 1.07, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1008$str$, $str$rectangular_bar$str$, $str$India$str$, 1.031, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1008$str$, $str$round_bar$str$, $str$India$str$, 0.845, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1008$str$, $str$round_tube$str$, $str$India$str$, 1.112, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1008$str$, $str$square_bar$str$, $str$India$str$, 0.985, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1012$str$, $str$hex_bar$str$, $str$India$str$, 0.956, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1012$str$, $str$plate$str$, $str$India$str$, 1.071, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1012$str$, $str$rectangular_bar$str$, $str$India$str$, 1.032, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1012$str$, $str$round_bar$str$, $str$India$str$, 0.846, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1012$str$, $str$round_tube$str$, $str$India$str$, 1.113, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1012$str$, $str$square_bar$str$, $str$India$str$, 0.985, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1010$str$, $str$hex_bar$str$, $str$India$str$, 0.956, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1010$str$, $str$plate$str$, $str$India$str$, 1.071, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1010$str$, $str$rectangular_bar$str$, $str$India$str$, 1.032, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1010$str$, $str$round_bar$str$, $str$India$str$, 0.846, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1010$str$, $str$round_tube$str$, $str$India$str$, 1.113, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1010$str$, $str$square_bar$str$, $str$India$str$, 0.985, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1050$str$, $str$hex_bar$str$, $str$India$str$, 0.96, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1050$str$, $str$plate$str$, $str$India$str$, 1.075, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1050$str$, $str$rectangular_bar$str$, $str$India$str$, 1.036, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1050$str$, $str$round_bar$str$, $str$India$str$, 0.849, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1050$str$, $str$round_tube$str$, $str$India$str$, 1.118, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1050$str$, $str$square_bar$str$, $str$India$str$, 0.989, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1018$str$, $str$hex_bar$str$, $str$India$str$, 0.96, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1018$str$, $str$plate$str$, $str$India$str$, 1.075, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1018$str$, $str$rectangular_bar$str$, $str$India$str$, 1.036, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1018$str$, $str$round_bar$str$, $str$India$str$, 0.849, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1018$str$, $str$round_tube$str$, $str$India$str$, 1.118, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1018$str$, $str$square_bar$str$, $str$India$str$, 0.989, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 4130$str$, $str$hex_bar$str$, $str$India$str$, 0.963, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 4130$str$, $str$plate$str$, $str$India$str$, 1.079, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 4130$str$, $str$rectangular_bar$str$, $str$India$str$, 1.04, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 4130$str$, $str$round_bar$str$, $str$India$str$, 0.852, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 4130$str$, $str$round_tube$str$, $str$India$str$, 1.121, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 4130$str$, $str$square_bar$str$, $str$India$str$, 0.993, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Galv. Steel, Hot Worked, DX54$str$, $str$hex_bar$str$, $str$India$str$, 0.965, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Galv. Steel, Hot Worked, DX54$str$, $str$plate$str$, $str$India$str$, 1.081, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Galv. Steel, Hot Worked, DX54$str$, $str$rectangular_bar$str$, $str$India$str$, 1.042, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Galv. Steel, Hot Worked, DX54$str$, $str$round_bar$str$, $str$India$str$, 0.854, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Galv. Steel, Hot Worked, DX54$str$, $str$round_tube$str$, $str$India$str$, 1.124, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Galv. Steel, Hot Worked, DX54$str$, $str$square_bar$str$, $str$India$str$, 0.995, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 4140H$str$, $str$hex_bar$str$, $str$India$str$, 0.981, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 4140H$str$, $str$plate$str$, $str$India$str$, 1.099, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 4140H$str$, $str$rectangular_bar$str$, $str$India$str$, 1.059, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 4140H$str$, $str$round_bar$str$, $str$India$str$, 0.868, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 4140H$str$, $str$round_tube$str$, $str$India$str$, 1.142, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 4140H$str$, $str$square_bar$str$, $str$India$str$, 1.011, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 4140$str$, $str$hex_bar$str$, $str$India$str$, 0.981, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 4140$str$, $str$plate$str$, $str$India$str$, 1.099, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 4140$str$, $str$rectangular_bar$str$, $str$India$str$, 1.059, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 4140$str$, $str$round_bar$str$, $str$India$str$, 0.868, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 4140$str$, $str$round_tube$str$, $str$India$str$, 1.142, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Hot Worked, AISI 4140$str$, $str$square_bar$str$, $str$India$str$, 1.011, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Galv. Steel, Hot Worked, AISI 1020$str$, $str$hex_bar$str$, $str$India$str$, 1.004, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Galv. Steel, Hot Worked, AISI 1020$str$, $str$plate$str$, $str$India$str$, 1.124, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Galv. Steel, Hot Worked, AISI 1020$str$, $str$rectangular_bar$str$, $str$India$str$, 1.083, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Galv. Steel, Hot Worked, AISI 1020$str$, $str$round_bar$str$, $str$India$str$, 0.888, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Galv. Steel, Hot Worked, AISI 1020$str$, $str$round_tube$str$, $str$India$str$, 1.169, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Galv. Steel, Hot Worked, AISI 1020$str$, $str$square_bar$str$, $str$India$str$, 1.035, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 8620$str$, $str$hex_bar$str$, $str$India$str$, 1.004, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 8620$str$, $str$plate$str$, $str$India$str$, 1.125, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 8620$str$, $str$rectangular_bar$str$, $str$India$str$, 1.084, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 8620$str$, $str$round_bar$str$, $str$India$str$, 0.889, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 8620$str$, $str$round_tube$str$, $str$India$str$, 1.17, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 8620$str$, $str$square_bar$str$, $str$India$str$, 1.035, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1020$str$, $str$hex_bar$str$, $str$India$str$, 1.012, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1020$str$, $str$plate$str$, $str$India$str$, 1.134, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1020$str$, $str$rectangular_bar$str$, $str$India$str$, 1.093, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1020$str$, $str$round_bar$str$, $str$India$str$, 0.896, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1020$str$, $str$round_tube$str$, $str$India$str$, 1.179, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 1020$str$, $str$square_bar$str$, $str$India$str$, 1.044, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Galv. Steel, Hot Worked, DX51D$str$, $str$hex_bar$str$, $str$India$str$, 1.044, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Galv. Steel, Hot Worked, DX51D$str$, $str$plate$str$, $str$India$str$, 1.169, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Galv. Steel, Hot Worked, DX51D$str$, $str$rectangular_bar$str$, $str$India$str$, 1.127, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Galv. Steel, Hot Worked, DX51D$str$, $str$round_bar$str$, $str$India$str$, 0.923, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Galv. Steel, Hot Worked, DX51D$str$, $str$round_tube$str$, $str$India$str$, 1.215, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Galv. Steel, Hot Worked, DX51D$str$, $str$square_bar$str$, $str$India$str$, 1.076, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 4340$str$, $str$hex_bar$str$, $str$India$str$, 1.152, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 4340$str$, $str$plate$str$, $str$India$str$, 1.29, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 4340$str$, $str$rectangular_bar$str$, $str$India$str$, 1.243, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 4340$str$, $str$round_bar$str$, $str$India$str$, 1.019, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 4340$str$, $str$round_tube$str$, $str$India$str$, 1.341, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Steel, Cold Worked, AISI 4340$str$, $str$square_bar$str$, $str$India$str$, 1.187, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 410$str$, $str$hex_bar$str$, $str$India$str$, 1.174, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 410$str$, $str$plate$str$, $str$India$str$, 1.315, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 410$str$, $str$rectangular_bar$str$, $str$India$str$, 1.267, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 410$str$, $str$round_bar$str$, $str$India$str$, 1.038, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 410$str$, $str$round_tube$str$, $str$India$str$, 1.367, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 410$str$, $str$square_bar$str$, $str$India$str$, 1.21, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 430$str$, $str$hex_bar$str$, $str$India$str$, 1.301, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 430$str$, $str$plate$str$, $str$India$str$, 1.458, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 430$str$, $str$rectangular_bar$str$, $str$India$str$, 1.405, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 430$str$, $str$round_bar$str$, $str$India$str$, 1.151, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 430$str$, $str$round_tube$str$, $str$India$str$, 1.515, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 430$str$, $str$square_bar$str$, $str$India$str$, 1.341, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, A240$str$, $str$hex_bar$str$, $str$India$str$, 1.344, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, A240$str$, $str$plate$str$, $str$India$str$, 1.506, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, A240$str$, $str$rectangular_bar$str$, $str$India$str$, 1.451, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, A240$str$, $str$round_bar$str$, $str$India$str$, 1.189, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, A240$str$, $str$round_tube$str$, $str$India$str$, 1.565, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, A240$str$, $str$square_bar$str$, $str$India$str$, 1.386, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 441$str$, $str$hex_bar$str$, $str$India$str$, 1.521, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 441$str$, $str$plate$str$, $str$India$str$, 1.704, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 441$str$, $str$rectangular_bar$str$, $str$India$str$, 1.643, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 441$str$, $str$round_bar$str$, $str$India$str$, 1.346, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 441$str$, $str$round_tube$str$, $str$India$str$, 1.772, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 441$str$, $str$square_bar$str$, $str$India$str$, 1.569, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, 440B$str$, $str$hex_bar$str$, $str$India$str$, 1.886, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, 440B$str$, $str$plate$str$, $str$India$str$, 2.113, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, 440B$str$, $str$rectangular_bar$str$, $str$India$str$, 2.036, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, 440B$str$, $str$round_bar$str$, $str$India$str$, 1.669, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, 440B$str$, $str$round_tube$str$, $str$India$str$, 2.196, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, 440B$str$, $str$square_bar$str$, $str$India$str$, 1.944, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, 15-5PH$str$, $str$hex_bar$str$, $str$India$str$, 1.944, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, 15-5PH$str$, $str$plate$str$, $str$India$str$, 2.178, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, 15-5PH$str$, $str$rectangular_bar$str$, $str$India$str$, 2.099, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, 15-5PH$str$, $str$round_bar$str$, $str$India$str$, 1.72, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, 15-5PH$str$, $str$round_tube$str$, $str$India$str$, 2.264, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, 15-5PH$str$, $str$square_bar$str$, $str$India$str$, 2.004, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 303$str$, $str$hex_bar$str$, $str$India$str$, 2.158, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 303$str$, $str$plate$str$, $str$India$str$, 2.417, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 303$str$, $str$rectangular_bar$str$, $str$India$str$, 2.329, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 303$str$, $str$round_bar$str$, $str$India$str$, 1.909, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 303$str$, $str$round_tube$str$, $str$India$str$, 2.513, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 303$str$, $str$square_bar$str$, $str$India$str$, 2.224, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 304$str$, $str$hex_bar$str$, $str$India$str$, 2.187, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 304$str$, $str$plate$str$, $str$India$str$, 2.45, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 304$str$, $str$rectangular_bar$str$, $str$India$str$, 2.361, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 304$str$, $str$round_bar$str$, $str$India$str$, 1.935, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 304$str$, $str$round_tube$str$, $str$India$str$, 2.547, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 304$str$, $str$square_bar$str$, $str$India$str$, 2.255, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 304L$str$, $str$hex_bar$str$, $str$India$str$, 2.275, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 304L$str$, $str$plate$str$, $str$India$str$, 2.549, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 304L$str$, $str$rectangular_bar$str$, $str$India$str$, 2.456, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 304L$str$, $str$round_bar$str$, $str$India$str$, 2.014, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 304L$str$, $str$round_tube$str$, $str$India$str$, 2.65, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 304L$str$, $str$square_bar$str$, $str$India$str$, 2.346, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Acetal$str$, $str$hex_bar$str$, $str$India$str$, 2.441, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Acetal$str$, $str$plate$str$, $str$India$str$, 2.735, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Acetal$str$, $str$rectangular_bar$str$, $str$India$str$, 2.636, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Acetal$str$, $str$round_bar$str$, $str$India$str$, 2.16, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Acetal$str$, $str$round_tube$str$, $str$India$str$, 2.843, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Acetal$str$, $str$square_bar$str$, $str$India$str$, 2.517, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$ABS, Hi Impact$str$, $str$hex_bar$str$, $str$India$str$, 2.465, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$ABS, Hi Impact$str$, $str$plate$str$, $str$India$str$, 2.762, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$ABS, Hi Impact$str$, $str$rectangular_bar$str$, $str$India$str$, 2.662, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$ABS, Hi Impact$str$, $str$round_bar$str$, $str$India$str$, 2.182, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$ABS, Hi Impact$str$, $str$round_tube$str$, $str$India$str$, 2.871, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$ABS, Hi Impact$str$, $str$square_bar$str$, $str$India$str$, 2.542, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Acrylic, PMMA$str$, $str$hex_bar$str$, $str$India$str$, 2.477, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Acrylic, PMMA$str$, $str$plate$str$, $str$India$str$, 2.775, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Acrylic, PMMA$str$, $str$rectangular_bar$str$, $str$India$str$, 2.674, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Acrylic, PMMA$str$, $str$round_bar$str$, $str$India$str$, 2.192, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Acrylic, PMMA$str$, $str$round_tube$str$, $str$India$str$, 2.885, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Acrylic, PMMA$str$, $str$square_bar$str$, $str$India$str$, 2.554, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Polycarbonate$str$, $str$hex_bar$str$, $str$India$str$, 2.541, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Polycarbonate$str$, $str$plate$str$, $str$India$str$, 2.846, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Polycarbonate$str$, $str$rectangular_bar$str$, $str$India$str$, 2.743, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Polycarbonate$str$, $str$round_bar$str$, $str$India$str$, 2.248, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Polycarbonate$str$, $str$round_tube$str$, $str$India$str$, 2.959, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Polycarbonate$str$, $str$square_bar$str$, $str$India$str$, 2.619, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Polybutylene Terephthalate$str$, $str$hex_bar$str$, $str$India$str$, 2.753, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Polybutylene Terephthalate$str$, $str$plate$str$, $str$India$str$, 3.084, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Polybutylene Terephthalate$str$, $str$rectangular_bar$str$, $str$India$str$, 2.972, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Polybutylene Terephthalate$str$, $str$round_bar$str$, $str$India$str$, 2.436, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Polybutylene Terephthalate$str$, $str$round_tube$str$, $str$India$str$, 3.206, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Polybutylene Terephthalate$str$, $str$square_bar$str$, $str$India$str$, 2.838, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, AA 7003$str$, $str$hex_bar$str$, $str$India$str$, 3.233, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, AA 7003$str$, $str$plate$str$, $str$India$str$, 3.622, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, AA 7003$str$, $str$rectangular_bar$str$, $str$India$str$, 3.49, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, AA 7003$str$, $str$round_bar$str$, $str$India$str$, 2.861, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, AA 7003$str$, $str$round_tube$str$, $str$India$str$, 3.765, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, AA 7003$str$, $str$square_bar$str$, $str$India$str$, 3.333, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, AA 383.0$str$, $str$hex_bar$str$, $str$India$str$, 3.255, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, AA 383.0$str$, $str$plate$str$, $str$India$str$, 3.647, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, AA 383.0$str$, $str$rectangular_bar$str$, $str$India$str$, 3.514, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, AA 383.0$str$, $str$round_bar$str$, $str$India$str$, 2.88, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, AA 383.0$str$, $str$round_tube$str$, $str$India$str$, 3.791, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, AA 383.0$str$, $str$square_bar$str$, $str$India$str$, 3.356, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, AA 380.0$str$, $str$hex_bar$str$, $str$India$str$, 3.266, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, AA 380.0$str$, $str$plate$str$, $str$India$str$, 3.659, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, AA 380.0$str$, $str$rectangular_bar$str$, $str$India$str$, 3.526, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, AA 380.0$str$, $str$round_bar$str$, $str$India$str$, 2.89, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, AA 380.0$str$, $str$round_tube$str$, $str$India$str$, 3.803, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, AA 380.0$str$, $str$square_bar$str$, $str$India$str$, 3.367, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 5119$str$, $str$hex_bar$str$, $str$India$str$, 3.266, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 5119$str$, $str$plate$str$, $str$India$str$, 3.659, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 5119$str$, $str$rectangular_bar$str$, $str$India$str$, 3.526, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 5119$str$, $str$round_bar$str$, $str$India$str$, 2.891, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 5119$str$, $str$round_tube$str$, $str$India$str$, 3.804, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 5119$str$, $str$square_bar$str$, $str$India$str$, 3.368, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 5083$str$, $str$hex_bar$str$, $str$India$str$, 3.271, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 5083$str$, $str$plate$str$, $str$India$str$, 3.665, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 5083$str$, $str$rectangular_bar$str$, $str$India$str$, 3.532, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 5083$str$, $str$round_bar$str$, $str$India$str$, 2.895, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 5083$str$, $str$round_tube$str$, $str$India$str$, 3.81, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 5083$str$, $str$square_bar$str$, $str$India$str$, 3.373, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 7022$str$, $str$hex_bar$str$, $str$India$str$, 3.279, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 7022$str$, $str$plate$str$, $str$India$str$, 3.673, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 7022$str$, $str$rectangular_bar$str$, $str$India$str$, 3.54, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 7022$str$, $str$round_bar$str$, $str$India$str$, 2.901, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 7022$str$, $str$round_tube$str$, $str$India$str$, 3.818, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 7022$str$, $str$square_bar$str$, $str$India$str$, 3.38, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 7020$str$, $str$hex_bar$str$, $str$India$str$, 3.288, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 7020$str$, $str$plate$str$, $str$India$str$, 3.684, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 7020$str$, $str$rectangular_bar$str$, $str$India$str$, 3.55, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 7020$str$, $str$round_bar$str$, $str$India$str$, 2.91, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 7020$str$, $str$round_tube$str$, $str$India$str$, 3.829, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 7020$str$, $str$square_bar$str$, $str$India$str$, 3.39, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 5454$str$, $str$hex_bar$str$, $str$India$str$, 3.306, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 5454$str$, $str$plate$str$, $str$India$str$, 3.704, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 5454$str$, $str$rectangular_bar$str$, $str$India$str$, 3.569, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 5454$str$, $str$round_bar$str$, $str$India$str$, 2.925, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 5454$str$, $str$round_tube$str$, $str$India$str$, 3.85, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 5454$str$, $str$square_bar$str$, $str$India$str$, 3.408, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 6012$str$, $str$hex_bar$str$, $str$India$str$, 3.307, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 6012$str$, $str$plate$str$, $str$India$str$, 3.705, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 6012$str$, $str$rectangular_bar$str$, $str$India$str$, 3.571, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 6012$str$, $str$round_bar$str$, $str$India$str$, 2.927, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 6012$str$, $str$round_tube$str$, $str$India$str$, 3.852, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 6012$str$, $str$square_bar$str$, $str$India$str$, 3.409, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 6082$str$, $str$hex_bar$str$, $str$India$str$, 3.308, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 6082$str$, $str$plate$str$, $str$India$str$, 3.706, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 6082$str$, $str$rectangular_bar$str$, $str$India$str$, 3.571, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 6082$str$, $str$round_bar$str$, $str$India$str$, 2.927, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 6082$str$, $str$round_tube$str$, $str$India$str$, 3.852, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 6082$str$, $str$square_bar$str$, $str$India$str$, 3.41, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 7075$str$, $str$hex_bar$str$, $str$India$str$, 3.314, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 7075$str$, $str$plate$str$, $str$India$str$, 3.713, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 7075$str$, $str$rectangular_bar$str$, $str$India$str$, 3.579, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 7075$str$, $str$round_bar$str$, $str$India$str$, 2.933, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 7075$str$, $str$round_tube$str$, $str$India$str$, 3.86, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 7075$str$, $str$square_bar$str$, $str$India$str$, 3.417, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 3103$str$, $str$hex_bar$str$, $str$India$str$, 3.317, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 3103$str$, $str$plate$str$, $str$India$str$, 3.716, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 3103$str$, $str$rectangular_bar$str$, $str$India$str$, 3.581, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 3103$str$, $str$round_bar$str$, $str$India$str$, 2.935, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 3103$str$, $str$round_tube$str$, $str$India$str$, 3.863, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 3103$str$, $str$square_bar$str$, $str$India$str$, 3.419, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 3003$str$, $str$hex_bar$str$, $str$India$str$, 3.321, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 3003$str$, $str$plate$str$, $str$India$str$, 3.72, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 3003$str$, $str$rectangular_bar$str$, $str$India$str$, 3.585, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 3003$str$, $str$round_bar$str$, $str$India$str$, 2.938, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 3003$str$, $str$round_tube$str$, $str$India$str$, 3.867, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 3003$str$, $str$square_bar$str$, $str$India$str$, 3.423, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 5251$str$, $str$hex_bar$str$, $str$India$str$, 3.322, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 5251$str$, $str$plate$str$, $str$India$str$, 3.722, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 5251$str$, $str$rectangular_bar$str$, $str$India$str$, 3.586, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 5251$str$, $str$round_bar$str$, $str$India$str$, 2.94, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 5251$str$, $str$round_tube$str$, $str$India$str$, 3.869, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 5251$str$, $str$square_bar$str$, $str$India$str$, 3.425, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, AA 3105$str$, $str$hex_bar$str$, $str$India$str$, 3.333, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, AA 3105$str$, $str$plate$str$, $str$India$str$, 3.734, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, AA 3105$str$, $str$rectangular_bar$str$, $str$India$str$, 3.599, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, AA 3105$str$, $str$round_bar$str$, $str$India$str$, 2.95, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, AA 3105$str$, $str$round_tube$str$, $str$India$str$, 3.882, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, AA 3105$str$, $str$square_bar$str$, $str$India$str$, 3.436, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 6061$str$, $str$hex_bar$str$, $str$India$str$, 3.339, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 6061$str$, $str$plate$str$, $str$India$str$, 3.741, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 6061$str$, $str$rectangular_bar$str$, $str$India$str$, 3.605, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 6061$str$, $str$round_bar$str$, $str$India$str$, 2.955, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 6061$str$, $str$round_tube$str$, $str$India$str$, 3.889, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Aluminum, ANSI 6061$str$, $str$square_bar$str$, $str$India$str$, 3.443, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 316$str$, $str$hex_bar$str$, $str$India$str$, 3.634, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 316$str$, $str$plate$str$, $str$India$str$, 4.072, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 316$str$, $str$rectangular_bar$str$, $str$India$str$, 3.924, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 316$str$, $str$round_bar$str$, $str$India$str$, 3.21, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 316L$str$, $str$hex_bar$str$, $str$India$str$, 3.634, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 316L$str$, $str$plate$str$, $str$India$str$, 4.072, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 316L$str$, $str$rectangular_bar$str$, $str$India$str$, 3.924, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, AISI 316L$str$, $str$round_bar$str$, $str$India$str$, 3.21, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, 17-4PH$str$, $str$hex_bar$str$, $str$India$str$, 4.084, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, 17-4PH$str$, $str$plate$str$, $str$India$str$, 4.576, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, 17-4PH$str$, $str$rectangular_bar$str$, $str$India$str$, 4.409, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Stainless Steel, 17-4PH$str$, $str$round_bar$str$, $str$India$str$, 3.61, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Nylon 6/6$str$, $str$hex_bar$str$, $str$India$str$, 5.675, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Nylon 6/6$str$, $str$plate$str$, $str$India$str$, 6.358, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Nylon 6/6$str$, $str$rectangular_bar$str$, $str$India$str$, 6.127, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Nylon 6/6$str$, $str$round_bar$str$, $str$India$str$, 5.02, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Copper, UNS C28000$str$, $str$hex_bar$str$, $str$India$str$, 6.12, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Copper, UNS C28000$str$, $str$plate$str$, $str$India$str$, 6.857, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Copper, UNS C28000$str$, $str$rectangular_bar$str$, $str$India$str$, 6.608, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Copper, UNS C28000$str$, $str$round_bar$str$, $str$India$str$, 5.41, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Copper, UNS C27200$str$, $str$hex_bar$str$, $str$India$str$, 6.441, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Copper, UNS C27200$str$, $str$plate$str$, $str$India$str$, 7.216, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Copper, UNS C27200$str$, $str$rectangular_bar$str$, $str$India$str$, 6.954, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Copper, UNS C27200$str$, $str$round_bar$str$, $str$India$str$, 5.7, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Copper, UNS C62730$str$, $str$hex_bar$str$, $str$India$str$, 8.203, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Copper, UNS C62730$str$, $str$plate$str$, $str$India$str$, 9.19, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Copper, UNS C62730$str$, $str$rectangular_bar$str$, $str$India$str$, 8.856, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Copper, UNS C62730$str$, $str$round_bar$str$, $str$India$str$, 7.25, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Inconel 718$str$, $str$hex_bar$str$, $str$India$str$, 8.596, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Inconel 718$str$, $str$plate$str$, $str$India$str$, 9.631, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Inconel 718$str$, $str$rectangular_bar$str$, $str$India$str$, 9.281, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Inconel 718$str$, $str$round_bar$str$, $str$India$str$, 7.6, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Polyimide$str$, $str$hex_bar$str$, $str$India$str$, 9.493, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Polyimide$str$, $str$plate$str$, $str$India$str$, 10.636, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Polyimide$str$, $str$rectangular_bar$str$, $str$India$str$, 10.249, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Polyimide$str$, $str$round_bar$str$, $str$India$str$, 8.4, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Copper, UNS C51900$str$, $str$hex_bar$str$, $str$India$str$, 10.18, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Copper, UNS C51900$str$, $str$plate$str$, $str$India$str$, 11.405, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Copper, UNS C51900$str$, $str$rectangular_bar$str$, $str$India$str$, 10.99, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Copper, UNS C51900$str$, $str$round_bar$str$, $str$India$str$, 9, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Inconel 625$str$, $str$hex_bar$str$, $str$India$str$, 12.074, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Inconel 625$str$, $str$plate$str$, $str$India$str$, 13.527, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Inconel 625$str$, $str$rectangular_bar$str$, $str$India$str$, 13.036, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Inconel 625$str$, $str$round_bar$str$, $str$India$str$, 10.68, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Hastelloy X$str$, $str$hex_bar$str$, $str$India$str$, 12.893, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Hastelloy X$str$, $str$plate$str$, $str$India$str$, 14.445, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Hastelloy X$str$, $str$rectangular_bar$str$, $str$India$str$, 13.92, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Hastelloy X$str$, $str$round_bar$str$, $str$India$str$, 11.41, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Haynes alloy 230$str$, $str$hex_bar$str$, $str$India$str$, 13.819, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Haynes alloy 230$str$, $str$plate$str$, $str$India$str$, 15.482, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Haynes alloy 230$str$, $str$rectangular_bar$str$, $str$India$str$, 14.919, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Haynes alloy 230$str$, $str$round_bar$str$, $str$India$str$, 12.22, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Polyetherimide (PEI)$str$, $str$hex_bar$str$, $str$India$str$, 15.129, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Polyetherimide (PEI)$str$, $str$plate$str$, $str$India$str$, 16.95, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Polyetherimide (PEI)$str$, $str$rectangular_bar$str$, $str$India$str$, 16.334, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Polyetherimide (PEI)$str$, $str$round_bar$str$, $str$India$str$, 13.38, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Titanium, Ti-6Al-4V$str$, $str$hex_bar$str$, $str$India$str$, 15.717, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Titanium, Ti-6Al-4V$str$, $str$plate$str$, $str$India$str$, 17.609, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Titanium, Ti-6Al-4V$str$, $str$rectangular_bar$str$, $str$India$str$, 16.969, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Titanium, Ti-6Al-4V$str$, $str$round_bar$str$, $str$India$str$, 13.9, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Titanium, Ti-5Al-2.5Sn$str$, $str$hex_bar$str$, $str$India$str$, 15.947, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Titanium, Ti-5Al-2.5Sn$str$, $str$plate$str$, $str$India$str$, 17.866, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Titanium, Ti-5Al-2.5Sn$str$, $str$rectangular_bar$str$, $str$India$str$, 17.217, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Titanium, Ti-5Al-2.5Sn$str$, $str$round_bar$str$, $str$India$str$, 14.11, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Hastelloy C-276$str$, $str$hex_bar$str$, $str$India$str$, 16.025, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Hastelloy C-276$str$, $str$plate$str$, $str$India$str$, 17.953, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Hastelloy C-276$str$, $str$rectangular_bar$str$, $str$India$str$, 17.301, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Hastelloy C-276$str$, $str$round_bar$str$, $str$India$str$, 14.18, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Polyetheretherketone, PEEK$str$, $str$hex_bar$str$, $str$India$str$, 50.738, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Polyetheretherketone, PEEK$str$, $str$plate$str$, $str$India$str$, 56.844, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Polyetheretherketone, PEEK$str$, $str$rectangular_bar$str$, $str$India$str$, 54.779, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Polyetheretherketone, PEEK$str$, $str$round_bar$str$, $str$India$str$, 44.9, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Polyamide-Imide (PAI)$str$, $str$hex_bar$str$, $str$India$str$, 112.698, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Polyamide-Imide (PAI)$str$, $str$plate$str$, $str$India$str$, 126.262, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Polyamide-Imide (PAI)$str$, $str$rectangular_bar$str$, $str$India$str$, 121.674, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$),
  ($str$Polyamide-Imide (PAI)$str$, $str$round_bar$str$, $str$India$str$, 99.73, 'USD', $str$memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv$str$)
ON CONFLICT (reference_material, stock_form, location)
DO UPDATE SET price_per_kg = EXCLUDED.price_per_kg, currency_code = EXCLUDED.currency_code, source = EXCLUDED.source, updated_at = now();
