-- 873: Sand Casting catalog rows, machine_class where still NULL.
-- Generated by scripts/gen_873_sand_casting_catalog_machine_class.js -- do not hand-edit,
-- re-run the generator and diff instead.
--
-- Migration 851 created the Sand Casting catalog and seeded its machines in the same pass,
-- but never linked process_taxonomy/process_calculator_mappings to the machine_class those
-- machines actually got. This closes that gap, the same step migration 845 (Die Casting) and
-- 872 (Casting Investment) already did for their own domains.
--
-- Linked: 22 of 25 real processes (excluding User-Defined
-- Process and No Cost Feature, same as 851).
-- Not linked, with the reason -- 851's own disclosed gap, no real machine file for these:
--   Core Refractory Coat, Mold Refractory Coat, Stock Core
-- Unmapped machine files (should be empty; 851 would already have failed on these): none
--
-- Idempotent: only rows still NULL are touched.
-- Verify: SELECT process_name, machine_class FROM process_taxonomy
--   WHERE process_group = 'Sand Casting' ORDER BY process_name;

UPDATE process_taxonomy pt
SET machine_class = v.machine_class
FROM (VALUES
  ('CO2 Cured', 'sand_casting_co2_cured'),
  ('Cleaning', 'sand_casting_cleaning'),
  ('Cooling', 'sand_casting_cooling'),
  ('Degating', 'sand_casting_degating'),
  ('Finishing', 'sand_casting_finishing'),
  ('Horizontal Automatic', 'sand_casting_horizontal_automatic'),
  ('Hot Box', 'sand_casting_hot_box'),
  ('Isocure Gas', 'sand_casting_isocure_gas'),
  ('Manual Coremaking', 'sand_casting_manual_coremaking'),
  ('Manual Floor Moldmaking', 'sand_casting_manual_floor_moldmaking'),
  ('Manual Pit Moldmaking', 'sand_casting_manual_pit_moldmaking'),
  ('Manual Std Moldmaking', 'sand_casting_manual_std_moldmaking'),
  ('Melting', 'sand_casting_melting'),
  ('No Bake', 'sand_casting_no_bake'),
  ('Oil Core', 'sand_casting_oil_core'),
  ('Pour', 'sand_casting_pour'),
  ('Refractory Coat Air Dry', 'sand_casting_refractory_coat_air_dry'),
  ('Refractory Coat Oven Dry', 'sand_casting_refractory_coat_oven_dry'),
  ('Shakeout', 'sand_casting_shakeout'),
  ('Shell', 'sand_casting_shell'),
  ('Vertical Automatic', 'sand_casting_vertical_automatic'),
  ('Visual Inspection', 'sand_casting_visual_inspection')
) AS v(process_name, machine_class)
WHERE pt.process_group = 'Sand Casting' AND pt.process_name = v.process_name AND pt.machine_class IS NULL;

UPDATE process_calculator_mappings pcm
SET machine_class = v.machine_class, updated_at = now()
FROM (VALUES
  ('CO2 Cured', 'sand_casting_co2_cured'),
  ('Cleaning', 'sand_casting_cleaning'),
  ('Cooling', 'sand_casting_cooling'),
  ('Degating', 'sand_casting_degating'),
  ('Finishing', 'sand_casting_finishing'),
  ('Horizontal Automatic', 'sand_casting_horizontal_automatic'),
  ('Hot Box', 'sand_casting_hot_box'),
  ('Isocure Gas', 'sand_casting_isocure_gas'),
  ('Manual Coremaking', 'sand_casting_manual_coremaking'),
  ('Manual Floor Moldmaking', 'sand_casting_manual_floor_moldmaking'),
  ('Manual Pit Moldmaking', 'sand_casting_manual_pit_moldmaking'),
  ('Manual Std Moldmaking', 'sand_casting_manual_std_moldmaking'),
  ('Melting', 'sand_casting_melting'),
  ('No Bake', 'sand_casting_no_bake'),
  ('Oil Core', 'sand_casting_oil_core'),
  ('Pour', 'sand_casting_pour'),
  ('Refractory Coat Air Dry', 'sand_casting_refractory_coat_air_dry'),
  ('Refractory Coat Oven Dry', 'sand_casting_refractory_coat_oven_dry'),
  ('Shakeout', 'sand_casting_shakeout'),
  ('Shell', 'sand_casting_shell'),
  ('Vertical Automatic', 'sand_casting_vertical_automatic'),
  ('Visual Inspection', 'sand_casting_visual_inspection')
) AS v(operation, machine_class)
WHERE pcm.process_group = 'Sand Casting' AND pcm.operation = v.operation AND pcm.machine_class IS NULL;

NOTIFY pgrst, 'reload schema';
