-- ============================================================================
-- Migration 878: Die Casting alloys completed from the rest of memory/
-- ============================================================================
-- Generated by scripts/gen_878_die_casting_alloy_gaps_from_casting.js -- do not
-- hand-edit, re-run the generator and diff instead.
--
-- Die Casting alloys (memory/Die Casting materials_master.csv, promoted by 855)
-- missing an input of the HPDC cost engine take it from the same alloy (by
-- Name) in the other memory/ folders, only where every one of them that states
-- it agrees. The Die Casting value wins wherever it exists. A file X_v2.csv
-- supersedes X.csv. Material Type also replaces a value every other folder
-- contradicts (the file has its identity columns shifted by one row from
-- Aluminum Bronze on). Property rows written here carry source_version
-- 2026-DieCasting-xref; the folders behind each value are listed below.
-- Chamber Type Hot/Cold is written in the Die Casting code: 1 hot, 2 cold.
--
-- Filled:
--   Aluminum Bronze: material_type=Aluminum Bronze [Casting, Casting Investment, Sand casting]
--   Aluminum, AA 1100: material_type=Aluminum (was Aluminum Bronze) [Bar and tube fab, Casting Investment, Forging, Multi-Spindle Maching, Sand casting, Sheet metal roll forming, Sheet metal stretch forming, Sheet metal transfer die, Stock Maching]
--   Aluminum, AA 383.0: material_type=Aluminum [Bar and tube fab, Casting Investment, Forging, Multi-Spindle Maching, Sand casting, Sheet metal roll forming, Sheet metal stretch forming, Sheet metal transfer die, Stock Maching]
--   Brass, CW617N: cooling_factor=0.47 [Sand casting]
--   Brass, Free-Cutting 360: cooling_factor=0.47 [Casting, Sand casting]
--   Brass, UNS C36000: cooling_factor=1 [Sand casting]
--   Brass, Yellow 270: cooling_factor=0.47 [Casting, Sand casting]
--   Bronze, Commercial 220: cooling_factor=0.47 [Casting, Sand casting]
--   Copper, UNS C11000: cooling_factor=0.47 [Sand casting]
--   Copper, UNS C18150: cooling_factor=0.47 [Sand casting]
--   Copper, UNS C27200: cooling_factor=0.47 [Sand casting]
--   Copper, UNS C28000: cooling_factor=0.47 [Sand casting]
--   Copper, UNS C51900: cooling_factor=0.47 [Sand casting]
--   Copper, UNS C62730: cooling_factor=0.47 [Sand casting]
--   Zinc-Aluminum ZA27: clamping_pressure=35 [Casting]; cooling_factor=0.42 [Casting, Sand casting]; injection_temp=430 [Casting, Sand casting]; liquidus_temp=385 [Casting, Casting Investment, Sand casting]; mold_temp=215 [Casting, Sand casting]; chamber_type=2 [Casting]; density=5000 [Casting, Casting Investment, Sand casting]
--   Aluminum, ANSI 5052: cooling_factor=0.47 [Sand casting]; injection_temp=690 [Sand casting]; liquidus_temp=636 [Casting Investment, Sand casting]; mold_temp=220 [Sand casting]; density=2680 [Casting Investment, Forging, Sand casting, Sheet metal roll forming, Sheet metal stretch forming, Sheet metal transfer die]
--
-- Left blank (the HPDC line names the missing input):
--   Aluminum, ANSI 5052: clamping_pressure not in memory/
--   Aluminum, ANSI 5052: chamber_type not in memory/
--
-- Idempotent: an existing non-null property value is never overwritten.
-- ============================================================================

DO $$
BEGIN
  INSERT INTO raw_material_properties (raw_material_id, property_key, value_num, value_text, unit, source_version)
  SELECT rm.id, p.property_key, p.value_num, NULL, p.unit, $str$2026-DieCasting-xref$str$
  FROM (VALUES
    ($str$Brass, CW617N$str$, $str$cooling_factor$str$, 0.47, $str$s/mm$str$),
    ($str$Brass, Free-Cutting 360$str$, $str$cooling_factor$str$, 0.47, $str$s/mm$str$),
    ($str$Brass, UNS C36000$str$, $str$cooling_factor$str$, 1, $str$s/mm$str$),
    ($str$Brass, Yellow 270$str$, $str$cooling_factor$str$, 0.47, $str$s/mm$str$),
    ($str$Bronze, Commercial 220$str$, $str$cooling_factor$str$, 0.47, $str$s/mm$str$),
    ($str$Copper, UNS C11000$str$, $str$cooling_factor$str$, 0.47, $str$s/mm$str$),
    ($str$Copper, UNS C18150$str$, $str$cooling_factor$str$, 0.47, $str$s/mm$str$),
    ($str$Copper, UNS C27200$str$, $str$cooling_factor$str$, 0.47, $str$s/mm$str$),
    ($str$Copper, UNS C28000$str$, $str$cooling_factor$str$, 0.47, $str$s/mm$str$),
    ($str$Copper, UNS C51900$str$, $str$cooling_factor$str$, 0.47, $str$s/mm$str$),
    ($str$Copper, UNS C62730$str$, $str$cooling_factor$str$, 0.47, $str$s/mm$str$),
    ($str$Zinc-Aluminum ZA27$str$, $str$clamping_pressure$str$, 35, $str$MPa$str$),
    ($str$Zinc-Aluminum ZA27$str$, $str$cooling_factor$str$, 0.42, $str$s/mm$str$),
    ($str$Zinc-Aluminum ZA27$str$, $str$injection_temp$str$, 430, $str$C$str$),
    ($str$Zinc-Aluminum ZA27$str$, $str$liquidus_temp$str$, 385, $str$C$str$),
    ($str$Zinc-Aluminum ZA27$str$, $str$mold_temp$str$, 215, $str$C$str$),
    ($str$Zinc-Aluminum ZA27$str$, $str$chamber_type$str$, 2, NULL),
    ($str$Aluminum, ANSI 5052$str$, $str$cooling_factor$str$, 0.47, $str$s/mm$str$),
    ($str$Aluminum, ANSI 5052$str$, $str$injection_temp$str$, 690, $str$C$str$),
    ($str$Aluminum, ANSI 5052$str$, $str$liquidus_temp$str$, 636, $str$C$str$),
    ($str$Aluminum, ANSI 5052$str$, $str$mold_temp$str$, 220, $str$C$str$)
  ) AS p(name, property_key, value_num, unit)
  JOIN raw_materials rm ON rm.name = p.name AND rm.material_group = 'Die Casting'
  ON CONFLICT (raw_material_id, property_key) DO UPDATE
    SET value_num = EXCLUDED.value_num, unit = EXCLUDED.unit, source_version = EXCLUDED.source_version
    WHERE raw_material_properties.value_num IS NULL;

  UPDATE raw_materials rm
  SET density_kg_m3 = v.density_kg_m3, density = v.density_kg_m3 / 1000.0
  FROM (VALUES
    ($str$Zinc-Aluminum ZA27$str$, 5000),
    ($str$Aluminum, ANSI 5052$str$, 2680)
  ) AS v(name, density_kg_m3)
  WHERE rm.name = v.name AND rm.material_group = 'Die Casting' AND rm.density_kg_m3 IS NULL;

  UPDATE raw_materials rm
  SET material_type = v.material_type
  FROM (VALUES
    ($str$Aluminum Bronze$str$, $str$Aluminum Bronze$str$),
    ($str$Aluminum, AA 1100$str$, $str$Aluminum$str$),
    ($str$Aluminum, AA 383.0$str$, $str$Aluminum$str$)
  ) AS v(name, material_type)
  WHERE rm.name = v.name AND rm.material_group = 'Die Casting' AND rm.material_type IS DISTINCT FROM v.material_type;
END $$;

NOTIFY pgrst, 'reload schema';

-- Verify:
--   SELECT rm.name, rm.material_type, rm.density_kg_m3, p.property_key, p.value_num
--   FROM raw_materials rm LEFT JOIN raw_material_properties p
--     ON p.raw_material_id = rm.id AND p.source_version = '2026-DieCasting-xref'
--   WHERE rm.material_group = 'Die Casting' ORDER BY rm.name, p.property_key;
