-- 845 verify: Sand Casting materials whose name ALREADY exists in raw_materials
-- (these were skipped by the NOT EXISTS guard, not overwritten).
SELECT rm.material, rm.material_group, rm.material_grade, rm.density, rm.cost
FROM raw_materials rm
WHERE rm.material IN (
  $str$Generic Aluminum Bronze$str$,
  $str$Generic Aluminum, AA 1100$str$,
  $str$Generic Aluminum, AA 2219$str$,
  $str$Generic Aluminum, AA 3105$str$,
  $str$Generic Aluminum, AA 380.0$str$,
  $str$Generic Aluminum, AA 383.0$str$,
  $str$Generic Aluminum, AA 7003$str$,
  $str$Generic Aluminum, ANSI 1050A$str$,
  $str$Generic Aluminum, ANSI 2007$str$,
  $str$Generic Aluminum, ANSI 2017$str$,
  $str$Generic Aluminum, ANSI 2024$str$,
  $str$Generic Aluminum, ANSI 2030$str$,
  $str$Generic Aluminum, ANSI 204.0$str$,
  $str$Generic Aluminum, ANSI 3003$str$,
  $str$Generic Aluminum, ANSI 303.0$str$,
  $str$Generic Aluminum, ANSI 3103$str$,
  $str$Generic Aluminum, ANSI 319.0$str$,
  $str$Generic Aluminum, ANSI 333.0$str$,
  $str$Generic Aluminum, ANSI 356.0$str$,
  $str$Generic Aluminum, ANSI 357.0$str$,
  $str$Generic Aluminum, ANSI 361.0$str$,
  $str$Generic Aluminum, ANSI 365.0$str$,
  $str$Generic Aluminum, ANSI 413.0$str$,
  $str$Generic Aluminum, ANSI 5005A$str$,
  $str$Generic Aluminum, ANSI 5019$str$,
  $str$Generic Aluminum, ANSI 5052$str$,
  $str$Generic Aluminum, ANSI 5083$str$,
  $str$Generic Aluminum, ANSI 5119$str$,
  $str$Generic Aluminum, ANSI 5251$str$,
  $str$Generic Aluminum, ANSI 5454$str$,
  $str$Generic Aluminum, ANSI 5754$str$,
  $str$Generic Aluminum, ANSI 6012$str$,
  $str$Generic Aluminum, ANSI 6060$str$,
  $str$Generic Aluminum, ANSI 6061$str$,
  $str$Generic Aluminum, ANSI 6082$str$,
  $str$Generic Aluminum, ANSI 7020$str$,
  $str$Generic Aluminum, ANSI 7022$str$,
  $str$Generic Aluminum, ANSI 7050$str$,
  $str$Generic Aluminum, ANSI 7075$str$,
  $str$Generic Aluminum, ANSI A413.0$str$,
  $str$Generic Aluminum, ANSI AL380.0$str$,
  $str$Generic Aluminum, ANSI B413.0$str$,
  $str$Generic ASTM A148 Grade 105-85$str$,
  $str$Generic ASTM A148 Grade 115-95$str$,
  $str$Generic ASTM A148 Grade 80-40$str$,
  $str$Generic ASTM A217 Grade CA15$str$,
  $str$Generic ASTM A27 Grade 65-35 [450-240]$str$,
  $str$Generic ASTM A27 Grade U-60-30 [415-205]$str$,
  $str$Generic ASTM A304 1330 H$str$,
  $str$Generic ASTM A352 Grade LCB$str$,
  $str$Generic ASTM A352 Grade LCC$str$,
  $str$Generic ASTM A743 Grade CA-6NM$str$,
  $str$Generic ASTM Grade 20 Gray Iron$str$,
  $str$Generic ASTM Grade 25 Gray Iron$str$,
  $str$Generic ASTM Grade 30 Gray Iron$str$,
  $str$Generic ASTM Grade 35 Gray Iron$str$,
  $str$Generic ASTM Grade 40 Gray Iron$str$,
  $str$Generic ASTM Grade 50 Gray Iron$str$,
  $str$Generic Brass, CW617N$str$,
  $str$Generic Brass, Free-Cutting 360$str$,
  $str$Generic Brass, UNS C36000$str$,
  $str$Generic Brass, Yellow 270$str$,
  $str$Generic Bronze, Commercial 220$str$,
  $str$Generic Copper, UNS C11000$str$,
  $str$Generic Copper, UNS C18150$str$,
  $str$Generic Copper, UNS C27200$str$,
  $str$Generic Copper, UNS C28000$str$,
  $str$Generic Copper, UNS C51900$str$,
  $str$Generic Copper, UNS C62730$str$,
  $str$Generic Ductile Iron A536$str$,
  $str$Generic Ductile Iron, ASTM A536, 100-70-03$str$,
  $str$Generic Ductile Iron, ASTM A536, 120-90-02$str$,
  $str$Generic Ductile Iron, ASTM A536, 60-40-18$str$,
  $str$Generic Ductile Iron, ASTM A536, 70-50-05$str$,
  $str$Generic Ductile Iron, ASTM A536, 80-60-03$str$,
  $str$Generic ISO JMB 300-6$str$,
  $str$Generic ISO JMB 350-10$str$,
  $str$Generic ISO JMB 450-6$str$,
  $str$Generic ISO JMB 500-5$str$,
  $str$Generic ISO JMB 550-4$str$,
  $str$Generic ISO JMB 600-3$str$,
  $str$Generic ISO JMB 650-2$str$,
  $str$Generic ISO JMB 700-2$str$,
  $str$Generic ISO JMB 800-1$str$,
  $str$Generic ISO JMW 350-4$str$,
  $str$Generic ISO JMW 360-12$str$,
  $str$Generic ISO JMW 400-5$str$,
  $str$Generic ISO JMW 450-7$str$,
  $str$Generic ISO JMW 550-4$str$,
  $str$Generic ISO JS 350-22/S$str$,
  $str$Generic ISO JS 450-10/S$str$,
  $str$Generic ISO JS 900-2/S$str$,
  $str$Generic Magnesium AM60B$str$,
  $str$Generic Magnesium AZ91D$str$,
  $str$Generic Magnesium AZ91E$str$,
  $str$Generic Manganese Bronze, 863$str$,
  $str$Generic Manganese Bronze, 865$str$,
  $str$Generic SAE 4118$str$,
  $str$Generic Silicon Brass 879$str$,
  $str$Generic Stainless Steel, 15-5PH$str$,
  $str$Generic Stainless Steel, 440B$str$,
  $str$Generic Stainless Steel, A351 CF8$str$,
  $str$Generic Stainless Steel, AISI 303$str$,
  $str$Generic Stainless Steel, AISI 304$str$,
  $str$Generic Stainless Steel, AISI 316$str$,
  $str$Generic Stainless Steel, AISI 316L$str$,
  $str$Generic Stainless Steel, AISI 410$str$,
  $str$Generic Stainless Steel, AISI 430$str$,
  $str$Generic Steel, AISI 1045, Medium-Carbon$str$,
  $str$Generic Steel, AISI 4140, Medium-Carbon$str$,
  $str$Generic Steel, ASTM A27 Grade 70-40 (485-275)$str$,
  $str$Generic Steel, ASTM A915 SC1020$str$,
  $str$Generic Zinc - Zamak$str$,
  $str$Generic Zinc - Zamak 5$str$,
  $str$Generic Zinc-Aluminum ZA12$str$,
  $str$Generic Zinc-Aluminum ZA27$str$,
  $str$Generic Zinc-Aluminum ZA8$str$
)
ORDER BY rm.material;
