-- Read-only: which of migrations 798-837 have landed in this database.
-- One statement. Each row tests an effect the migration leaves behind (a
-- column, a row count, a value), so it answers "is it applied", not "was the
-- file opened". Columns and tables a migration adds are tested through
-- information_schema / to_jsonb, so the query runs whatever is missing.
-- landed: true = applied, false = not applied, null = cannot be told from
-- the data (see detail).

WITH col AS (
  SELECT table_name, column_name FROM information_schema.columns WHERE table_schema = 'public'
)
SELECT migration, landed, detail FROM (VALUES
  ('798 + 801 machining feature vocabulary',
   NOT EXISTS (SELECT 1 FROM bom_items WHERE feature_graph ? 'cnc_features'),
   'no bom_items.feature_graph still has cnc_features (also true if none ever had)'),
  ('799 sheet-metal feature vocabulary', NULL::boolean,
   'rewrites rows in place and drops its functions; not detectable afterwards'),
  ('800 family values',
   NOT EXISTS (SELECT 1 FROM bom_items WHERE family_classification IN ('cnc_milled', 'cnc_turned', 'injection_molded')),
   'no cnc_milled / cnc_turned / injection_molded family values left'),
  ('802 machining catalog classes',
   NOT EXISTS (SELECT 1 FROM process_calculator_mappings WHERE process_group = 'Machining' AND machine_class LIKE 'cnc\_%'),
   'no Machining mapping on a retired cnc_* class'),
  ('803 exchange rates reference table',
   EXISTS (SELECT 1 FROM col WHERE table_name = 'exchange_rates' AND column_name = 'currency_name'),
   'exchange_rates.currency_name exists'),
  ('804 machining calculators',
   EXISTS (SELECT 1 FROM col WHERE table_name = 'calculators' AND column_name = 'retired_at'),
   'calculators.retired_at exists'),
  ('734 molding presses keyed (805 / 829 need it)',
   NOT EXISTS (SELECT 1 FROM mhr_records WHERE nullif(trim(benchmark_source_key), '') IS NULL
     AND machine_class IN ('injection_molding', 'compression_molding', 'structural_foam_molding', 'reaction_injection_molding')),
   (SELECT count(*) FROM mhr_records WHERE nullif(trim(benchmark_source_key), '') IS NULL
     AND machine_class IN ('injection_molding', 'compression_molding', 'structural_foam_molding', 'reaction_injection_molding'))::text || ' unkeyed molding presses (expect 0)'),
  ('829 India molding press rates',
   EXISTS (SELECT 1 FROM mhr_records WHERE location = 'India' AND machine_class IN ('injection_molding', 'compression_molding', 'structural_foam_molding', 'reaction_injection_molding')),
   (SELECT count(*) FROM mhr_records WHERE location = 'India' AND machine_class IN ('injection_molding', 'compression_molding', 'structural_foam_molding', 'reaction_injection_molding'))::text || ' India molding presses'),
  ('805 remove non-memory mhr_records',
   NOT EXISTS (SELECT 1 FROM mhr_records WHERE nullif(trim(benchmark_source_key), '') IS NULL),
   'every mhr_records row has a benchmark_source_key'),
  ('806 CMM inspection machines',
   (SELECT count(*) FROM mhr_records WHERE machine_class = 'cmm' AND location = 'USA' AND benchmark_source_key IS NOT NULL) >= 11,
   (SELECT count(*) FROM mhr_records WHERE machine_class = 'cmm' AND location = 'USA' AND benchmark_source_key IS NOT NULL)::text || ' USA cmm rows (expect 11)'),
  ('807 setup_time_source none',
   COALESCE((SELECT pg_get_constraintdef(oid) LIKE '%none%' FROM pg_constraint WHERE conname = 'ck_pcr_setup_time_source_known'), false),
   'ck_pcr_setup_time_source_known allows none'),
  ('808 drill press class',
   NOT EXISTS (SELECT 1 FROM mhr_records WHERE machine_class IN ('machining_drill_press', 'cnc_drill_press')),
   'no machining_drill_press / cnc_drill_press rows'),
  ('809-814 machining lookup tables',
   (SELECT count(*) FROM machining_reference_data WHERE category = 'lookup_table' AND source_version = '2026-03'
      AND key IN ('tblMilling', 'tblTapping', 'tblThreadMilling', 'tblInternalGrinding', 'tblGrinding', 'tblHobbing', 'tblShaping',
                  'tblShaving', 'tblMultiPassOperations', 'tblPullTypeKeywayBroach', 'tblShimTypeKeywayBroach', 'tblRadialGrooveMilling',
                  'tblSpiralBevelGearCutting', 'tblStraightBevelGearCutting', 'tblDovetailFinishingPassCharacteristics')) = 15,
   (SELECT count(*) FROM machining_reference_data WHERE category = 'lookup_table' AND source_version = '2026-03'
      AND key IN ('tblMilling', 'tblTapping', 'tblThreadMilling', 'tblInternalGrinding', 'tblGrinding', 'tblHobbing', 'tblShaping',
                  'tblShaving', 'tblMultiPassOperations', 'tblPullTypeKeywayBroach', 'tblShimTypeKeywayBroach', 'tblRadialGrooveMilling',
                  'tblSpiralBevelGearCutting', 'tblStraightBevelGearCutting', 'tblDovetailFinishingPassCharacteristics'))::text || ' of 15 tables (809 = tblMilling first)'),
  ('814a mhr_records.specs',
   EXISTS (SELECT 1 FROM col WHERE table_name = 'mhr_records' AND column_name = 'specs'),
   'mhr_records.specs exists'),
  ('815 band saw machines',
   (SELECT count(*) FROM mhr_records WHERE machine_class = 'band_saw' AND location = 'USA') >= 13,
   (SELECT count(*) FROM mhr_records WHERE machine_class = 'band_saw' AND location = 'USA')::text || ' USA band_saw rows (expect 13)'),
  ('816 stock machining reference',
   EXISTS (SELECT 1 FROM machining_reference_data WHERE source_version = '2026-Stock-Machining'),
   (SELECT count(*) FROM machining_reference_data WHERE source_version = '2026-Stock-Machining')::text || ' 2026-Stock-Machining rows (expect 59)'),
  ('817 secondary process reference',
   EXISTS (SELECT 1 FROM machining_reference_data WHERE source_version = '2026-Secondary'),
   (SELECT count(*) FROM machining_reference_data WHERE source_version = '2026-Secondary')::text || ' rows (expect 60)'),
  ('818 secondary process machines',
   EXISTS (SELECT 1 FROM mhr_records WHERE machine_class = 'carton_forming'),
   (SELECT count(*) FROM mhr_records WHERE process_group = 'Other Secondary Processes' AND location = 'USA')::text || ' USA secondary rows'),
  ('819 surface treatment reference',
   EXISTS (SELECT 1 FROM machining_reference_data WHERE source_version = '2026-SurfaceTrt'),
   (SELECT count(*) FROM machining_reference_data WHERE source_version = '2026-SurfaceTrt')::text || ' rows (expect 241)'),
  ('820 surface treatment machines',
   EXISTS (SELECT 1 FROM mhr_records WHERE machine_class = 'surface_anodize'),
   (SELECT count(*) FROM mhr_records WHERE process_group = 'Surface Treatment' AND benchmark_source_key IS NOT NULL)::text || ' surface treatment rows'),
  ('821 surface treatment catalog',
   EXISTS (SELECT 1 FROM process_taxonomy WHERE process_group = 'Surface Treatment' AND process_name = 'Bead Blast' AND machine_class = 'surface_bead_blast'),
   'Bead Blast on surface_bead_blast'),
  ('823 memory domains (9 parts)',
   (SELECT count(DISTINCT source_version) FROM machining_reference_data
     WHERE source_version IN ('2026-Additive', '2026-Assembly', '2026-Composites', '2026-Forging', '2026-HeatTreat',
                              '2026-Hydroform', '2026-PartAssembly', '2026-PCB', '2026-Plastic')) = 9,
   (SELECT coalesce(string_agg(source_version || ' ' || n, ', ' ORDER BY source_version), 'none')
      FROM (SELECT source_version, count(*) AS n FROM machining_reference_data
             WHERE source_version IN ('2026-Additive', '2026-Assembly', '2026-Composites', '2026-Forging', '2026-HeatTreat',
                                      '2026-Hydroform', '2026-PartAssembly', '2026-PCB', '2026-Plastic')
             GROUP BY 1) v)),
  ('824 forging machines',
   EXISTS (SELECT 1 FROM mhr_records WHERE machine_class = 'forging_hammer'),
   (SELECT count(*) FROM mhr_records WHERE process_group = 'Forging' AND location = 'USA')::text || ' USA forging rows'),
  ('826 heat treatment machines',
   EXISTS (SELECT 1 FROM mhr_records WHERE machine_class = 'heat_treat_carburize'),
   (SELECT count(*) FROM mhr_records WHERE process_group = 'Heat Treatment' AND location = 'USA')::text || ' USA heat treatment rows'),
  ('827 part assembly welding classes',
   EXISTS (SELECT 1 FROM mhr_records WHERE process_group = 'Part Assembly' AND machine_class LIKE 'part\_assembly\_%'),
   'Part Assembly rows on part_assembly_* classes'),
  ('828 hydroforming machines',
   EXISTS (SELECT 1 FROM mhr_records WHERE machine_class IN ('hydroform', 'hydroform_offline_blank')),
   (SELECT count(*) FROM mhr_records WHERE machine_class IN ('hydroform', 'hydroform_offline_blank'))::text || ' hydroform rows'),
  ('829 India machine rates',
   EXISTS (SELECT 1 FROM mhr_records WHERE location = 'India' AND benchmark_source_key LIKE '%:India'),
   (SELECT count(*) FROM mhr_records WHERE location = 'India' AND benchmark_source_key LIKE '%:India')::text || ' India rows'),
  ('830 sheet metal lookup tables (10 parts)',
   (SELECT count(*) FROM sm_reference_data WHERE category = 'lookup_table' AND source_version = '2026-SM-Lookup') = 57,
   (SELECT count(*) FROM sm_reference_data WHERE category = 'lookup_table' AND source_version = '2026-SM-Lookup')::text || ' of 57 tables (parts 4-10 fill rows)'),
  ('831 plastic reference properties',
   EXISTS (SELECT 1 FROM col WHERE table_name = 'raw_materials' AND column_name = 'im_reference_material'),
   'raw_materials.im_reference_material exists'),
  ('832 molding press specs',
   EXISTS (SELECT 1 FROM mhr_records m WHERE to_jsonb(m)->'specs' ? 'press_data_source'),
   (SELECT count(*) FROM mhr_records m WHERE to_jsonb(m)->'specs' ? 'press_data_source')::text || ' presses with specs'),
  ('833 material stock prices',
   to_regclass('public.material_stock_prices') IS NOT NULL,
   CASE WHEN to_regclass('public.material_stock_prices') IS NULL THEN 'table missing'
        ELSE (xpath('/row/n/text()', query_to_xml('SELECT count(*) AS n FROM material_stock_prices', false, true, '')))[1]::text || ' prices (expect 502)' END),
  ('834 reference plastics added',
   (SELECT count(*) FROM raw_materials r WHERE to_jsonb(r)->>'im_reference_material' IS NOT NULL) >= 109,
   (SELECT count(*) FROM raw_materials r WHERE to_jsonb(r)->>'im_reference_material' IS NOT NULL)::text || ' with reference (831 alone 39, with 834 = 109)'),
  ('835 thermoset cure time',
   (SELECT count(*) FROM raw_materials r WHERE to_jsonb(r)->>'im_reference_material' IS NOT NULL AND to_jsonb(r)->>'cure_time_min' IS NOT NULL) >= 35,
   (SELECT count(*) FROM raw_materials r WHERE to_jsonb(r)->>'im_reference_material' IS NOT NULL AND to_jsonb(r)->>'cure_time_min' IS NOT NULL)::text
     || ' reference materials with cure time (expect 35, the materials_final.csv rows with a cure time)'),
  ('836 sheet metal location rates re-staged',
   NOT EXISTS (SELECT 1 FROM sm_reference_data WHERE category = 'machine' AND source_version = '2026-08' AND key LIKE 'undefined:%'),
   (SELECT count(*) FROM sm_reference_data WHERE category = 'machine' AND source_version = '2026-08' AND key LIKE 'undefined:%')::text || ' undefined: keys left (expect 0)'),
  ('837 vendor name in machining reference',
   NOT EXISTS (SELECT 1 FROM machining_reference_data WHERE raw::text ~* 'a\s*priori'),
   (SELECT count(*) FROM machining_reference_data WHERE raw::text ~* 'a\s*priori')::text || ' rows still naming the vendor (expect 0)')
) AS s(migration, landed, detail);
