// Generator: stages the real Injection Molding "cmColorantMaterials"
// lookup-table export (memory/plastic modeling/lookup/cmColorantMaterials.json
// — 6 real colorant/pigment types with real USD/kg unit costs, and which
// one is the tool's own default) into im_reference_data category=
// 'lookup_table' — same shape and staging-only discipline as migrations
// 651/652.
//
// key = colorant_type, value = unit_cost_usd_per_kg, unit_type =
// 'Currency/kg', raw = full source record (incl. default_colorant flag).
//
// NOT wired into any cost calculation here — confirmed live 2026-09-03
// there is no existing colorant/pigment cost line item anywhere in the
// Plastic Molding costing engine (backend/src/modules/bom-items/costing/
// injection-molding/), and no colorant SELECTION concept anywhere in the
// schema or UI for a part to even carry which colorant (if any) it uses.
// This is a genuine capability gap, not a hardcoded value to replace —
// wiring it live would mean building a new selection feature (schema +
// UI), not a bug fix, so it stays staged-only pending that scoping
// decision.
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const COLORANTS_FILE = path.join(__dirname, '../../../memory/plastic modeling/lookup/cmColorantMaterials.json');
const OUT_SQL = path.join(__dirname, '../653_seed_im_lookup_colorant_materials.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(COLORANTS_FILE, 'utf8'));

const rows = data.records.map((r) => ({
  category: 'lookup_table',
  key: r.colorant_type,
  value: String(r.unit_cost_usd_per_kg),
  unit_type: 'Currency/kg',
  notes: r.default_colorant ? 'Tool default colorant (no additional colorant)' : 'Colorant/pigment additive cost',
  raw: r,
}));

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 653: Seed im_reference_data category = 'lookup_table'
-- (colorant materials) — schema: migration 636
--
-- Generated by gen_653_seed_im_lookup_colorant_materials.js.
-- Row count: ${rows.length} (memory/plastic modeling/lookup/cmColorantMaterials.json).
--
-- NOT wired into any cost calculation — staging only. See the generator
-- script header for why (genuine capability gap: no colorant selection
-- concept exists anywhere in this app today, not a hardcode to replace).
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
