#!/usr/bin/env node
// Generates migration 832: every column of the four molding press files in
// memory/Plastic Modeling/machine that migration 633 does not already store in
// a typed mhr_records column, into mhr_records.specs (merged), for every
// location's copy of the press (USA rows from 633, location twins from 829).
// Only location-independent machine facts are written here; rates stay with
// 633 / 829.
//
//   injection_molding_machines.csv, structural_foam_molding_machines.csv,
//   reaction_injection_molding_machines.csv, compression_molding_machines.csv
//
// The columns 633 maps are listed in MAPPED (see gen_633's header); every other
// data column becomes a specs key (the column's last path segment in
// snake_case, e.g. rates.injectionRateMm3PerS -> injection_rate_mm3_per_s).
// Nothing is derived or defaulted: a blank cell is left out.
//
// Run: node backend/migrations/scripts/gen_832_molding_press_specs.js

const path = require('path');
const fs = require('fs');
const { readCsv, sqlStr, sqlJsonb } = require('./lib/memory-machine-seed');

const ROOT = path.resolve(__dirname, '..', '..', '..');
const DIR = path.join(ROOT, 'memory', 'Plastic Modeling', 'machine');
const OUT = path.join(__dirname, '..', '832_molding_press_specs.sql');

const FILES = [
  { file: 'injection_molding_machines.csv', machineClass: 'injection_molding' },
  { file: 'structural_foam_molding_machines.csv', machineClass: 'structural_foam_molding' },
  { file: 'reaction_injection_molding_machines.csv', machineClass: 'reaction_injection_molding' },
  { file: 'compression_molding_machines.csv', machineClass: 'compression_molding' },
];

// Identity columns and the columns migration 633 stores in typed columns.
const IDENTITY = new Set(['sector', 'processCategory', 'machineCount', 'primaryId', 'name', 'manufacturerInformation.dataSource']);
const MAPPED = new Set([
  'accounting.numberOfOperators', 'time.setupTimeHr', 'time.dryCycleTimeS',
  'accounting.directOverheadRateUsdPerHr', 'accounting.indirectOverheadRateUsdPerHr', 'accounting.laborRateUsdPerHr',
  'accounting.workCenterLaborRateFactor', 'accounting.laborTimeStandard', 'accounting.wageGradeName',
  'machine.machinePriceUsd', 'machine.machineLengthMm', 'machine.machineWidthMm', 'machine.footprintAllowanceFactor',
  'bottomUpOverheadRateInputs.machinePowerKw', 'bottomUpOverheadRateInputs.machineLifeYr',
  'bottomUpOverheadRateInputs.installationFactorPct', 'bottomUpOverheadRateInputs.machineUptimePct',
  'bottomUpOverheadRateInputs.annualMaintenanceFactorPct', 'bottomUpOverheadRateInputs.salvageValueFactorPct',
  'bottomUpOverheadRateInputs.suppliesCostUsdPerYr', 'yields.avgUtilization', 'yields.goodPartYield',
  'manufacturerInformation.machineManufacturerLocation', 'limits.clampingForceKn', 'limits.pressForceKn',
  'limits.tieBarDistanceHorMm', 'limits.tieBarDistanceVertMm', 'limits.shotSizeGppsG', 'limits.shotSizeG',
  'limits.minMoldHeightMm', 'limits.maxMoldHeightMm',
]);
const keyOf = (col) => col.split('.').pop().replace(/([a-z0-9])([A-Z])/g, '$1_$2').replace(/([A-Z])([A-Z][a-z])/g, '$1_$2').toLowerCase();

const values = [];
const report = [];
for (const { file, machineClass } of FILES) {
  const { columns, rows } = readCsv(path.join(DIR, file));
  const specCols = columns.filter((c) => !IDENTITY.has(c) && !MAPPED.has(c));
  const keys = specCols.map(keyOf);
  if (new Set(keys).size !== keys.length) throw new Error(`${file}: two columns map to one specs key`);
  for (const r of rows) {
    const specs = { press_data_source: `memory/Plastic Modeling/machine/${file}` };
    for (const c of specCols) if (r[c] != null && r[c] !== '') specs[keyOf(c)] = r[c] === 'True' ? true : r[c] === 'False' ? false : r[c];
    values.push(`  (${sqlStr(machineClass)}, ${sqlStr(r.name)}, ${sqlJsonb(specs)})`);
  }
  report.push(`--   ${file.padEnd(42)} ${String(rows.length).padStart(3)} presses: ${keys.join(', ')}`);
}

const sql = `-- ============================================================================
-- Migration 832: molding press data not held by a typed column, into
-- mhr_records.specs
-- ============================================================================
-- Generated by scripts/gen_832_molding_press_specs.js -- do not hand-edit,
-- re-run the generator and diff instead.
--
-- Source: memory/Plastic Modeling/machine/*.csv. Migration 633 (its generator
-- now reads these same csv files; its output is unchanged) stores clamp, tie
-- bars, shot size, mold heights, dry cycle, economics and yields in typed
-- columns. Every other column is merged into specs here:
${report.join('\n')}
--
-- Written to every location copy of each press (by machine_class and
-- machine_name): these are machine facts, not rates. Merged with any specs a
-- row already has. Needs migration 814a (restores mhr_records.specs), 633 and,
-- for the location twins, 829. Idempotent.
-- ============================================================================

ALTER TABLE mhr_records ADD COLUMN IF NOT EXISTS specs JSONB;

UPDATE mhr_records m
SET specs = coalesce(m.specs, '{}'::jsonb) || v.specs::jsonb
FROM (VALUES
${values.join(',\n')}
) AS v(machine_class, machine_name, specs)
WHERE m.machine_class = v.machine_class AND m.machine_name = v.machine_name;

NOTIFY pgrst, 'reload schema';

-- Verify: SELECT machine_class, location, count(*), count(*) FILTER (WHERE specs ? 'press_data_source')
-- FROM mhr_records WHERE machine_class IN ('injection_molding','structural_foam_molding',
-- 'reaction_injection_molding','compression_molding') GROUP BY 1, 2 ORDER BY 1, 2;
`;
fs.writeFileSync(OUT, sql, 'utf8');
console.log(`Wrote ${path.relative(ROOT, OUT)}: ${values.length} presses`);
console.log(report.join('\n'));
