// Generator: stages the real Injection Molding "finishingHrsPerSqMeter"
// lookup-table export (memory/plastic modeling/lookup/finishingHrsPerSqMeter.json
// — 24 real (surface_area_m2, complexity) -> hrs_per_sq_meter breakpoints:
// cavity/core finishing/polishing labor hours per m^2, at 3 complexity
// tiers (Simple/Average/Complex) across 8 real surface-area breakpoints)
// into im_reference_data category='lookup_table' — same shape and
// staging-only discipline as migrations 651-660.
//
// key = "<surface_area_m2>_<complexity>" (composite -- surface_area_m2
// repeats 3x per breakpoint, once per complexity tier, so the bare area
// alone is not unique), value = hrs_per_sq_meter_hr_m2, unit_type =
// 'hr/m^2', raw = full source record.
//
// Notably keyed by real PART surface area (not mold base area) -- unlike
// the mold-base-area-keyed tables (654, 656), this axis is already a real,
// CAD-extracted quantity this app already computes for every part
// (summary.surfaceArea), so this table has no open blocking dependency the
// way those two do. Still NOT wired into any cost calculation here — same
// "combine once all lookup tables have arrived" sequencing as every prior
// lookup_table migration this batch.
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const FINISHING_FILE = path.join(__dirname, '../../../memory/plastic modeling/lookup/finishingHrsPerSqMeter.json');
const OUT_SQL = path.join(__dirname, '../661_seed_im_lookup_finishing_hrs_per_sqm.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(FINISHING_FILE, 'utf8'));

const rows = data.records.map((r) => ({
  category: 'lookup_table',
  key: `${r.surface_area_m2}_${r.complexity}`,
  value: String(r.hrs_per_sq_meter_hr_m2),
  unit_type: 'hr/m^2',
  notes: `Finishing/polishing rate for surface area <= ${r.surface_area_m2} m^2, ${r.complexity} complexity`,
  raw: r,
}));

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 661: Seed im_reference_data category = 'lookup_table'
-- (finishing hours per sq meter) — schema: migration 636
--
-- Generated by gen_661_seed_im_lookup_finishing_hrs_per_sqm.js.
-- Row count: ${rows.length} (memory/plastic modeling/lookup/finishingHrsPerSqMeter.json).
--
-- NOT wired into any cost calculation — staging only. See the generator
-- script header — unlike the mold-base-area-keyed tables, this one is
-- keyed by real part surface area, already computed for every part today.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
