// Generator: stages the real Injection Molding "cmToolAssemblyTimes"
// lookup-table export (memory/plastic modeling/lookup/cmToolAssemblyTimes.json
// — 15 real standard mold tooling components with real per-unit assembly
// labor time in hours) into im_reference_data category='lookup_table' —
// same shape and staging-only discipline as migrations 651-656.
//
// key = name, value = assembly_time_hr, raw = full source record.
//
// Direct companion to migration 655's cmStandardToolingComponents (unit
// costs + quantities) -- combined with a real hourly labor rate, this
// gives a real, itemized assembly-labor cost per component. NOT wired
// into any cost calculation here — same "combine once all lookup tables
// have arrived" sequencing as 654/655/656.
//
// Naming does NOT match 1:1 against migration 655's component names
// (e.g. "Ejector Guide Pin Bushing" there vs. "Ejector Guide Pin And
// Bushing" here; "Return Pin And Shoulder Bushing" there vs. both
// "Leader Pins And Shoulder Bushings" and "Return Pins And Shoulder
// Bushings" here) and introduces components 655 doesn't have (Heater
// Lines, Rib Insert, Socket Head Screws Short, Support Pillar,
// Thermocouples) — staged faithfully as its own real source; name
// reconciliation between the two tables is deferred to the eventual
// wiring pass, not resolved here.
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const TIMES_FILE = path.join(__dirname, '../../../memory/plastic modeling/lookup/cmToolAssemblyTimes.json');
const OUT_SQL = path.join(__dirname, '../657_seed_im_lookup_tool_assembly_times.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(TIMES_FILE, 'utf8'));

const rows = data.records.map((r) => ({
  category: 'lookup_table',
  key: r.name,
  value: String(r.assembly_time_hr),
  unit_type: 'hr',
  notes: 'Per-unit tool assembly labor time',
  raw: r,
}));

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 657: Seed im_reference_data category = 'lookup_table'
-- (tool assembly times) — schema: migration 636
--
-- Generated by gen_657_seed_im_lookup_tool_assembly_times.js.
-- Row count: ${rows.length} (memory/plastic modeling/lookup/cmToolAssemblyTimes.json).
--
-- NOT wired into any cost calculation — staging only. See the generator
-- script header for the naming mismatch against migration 655's component
-- list, deferred to the eventual wiring pass.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
