// Generator: stages the real Injection Molding "tblHrsPerSqInchAverage"
// lookup-table export (memory/plastic modeling/lookup/tblHrsPerSqInchAverage.json
// — 10 real (surface_area_in2 -> hrs_per_sq_inch) breakpoints: real
// finishing/polishing hours per in^2, imperial-unit counterpart to
// migration 661's finishingHrsPerSqMeter "Average" complexity tier) into
// im_reference_data category='lookup_table' — same shape and
// staging-only discipline as migrations 651-675.
//
// key = surface_area_in2 breakpoint (as string), value = hrs_per_sq_inch,
// unit_type = 'hr/in^2', raw = full source record.
//
// NOT wired into any cost calculation here — same "combine once all
// lookup tables have arrived" sequencing as every prior lookup_table
// migration this batch.
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const RATE_FILE = path.join(__dirname, '../../../memory/plastic modeling/lookup/tblHrsPerSqInchAverage.json');
const OUT_SQL = path.join(__dirname, '../676_seed_im_lookup_hrs_per_sq_inch_average.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(RATE_FILE, 'utf8'));

const rows = data.records.map((r) => {
  const hrs = r['Hrs Per Sq Inch Average (hr)'];
  const areaIn2 = r['Surface Area Average (in^2)'];
  return {
    category: 'lookup_table',
    key: `area_in2_${areaIn2}`,
    value: String(hrs),
    unit_type: 'hr/in^2',
    notes: `Average finishing rate for surface area <= ${areaIn2} in^2`,
    raw: { hrs_per_sq_inch: hrs, surface_area_in2: areaIn2 },
  };
});

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 676: Seed im_reference_data category = 'lookup_table'
-- (hours per sq inch average) — schema: migration 636
--
-- Generated by gen_676_seed_im_lookup_hrs_per_sq_inch_average.js.
-- Row count: ${rows.length} (memory/plastic modeling/lookup/tblHrsPerSqInchAverage.json).
--
-- NOT wired into any cost calculation — staging only. See the generator
-- script header — imperial-unit counterpart to migration 661.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
