// Generator: stages the real Injection Molding "tblSpiType" lookup-table
// export (memory/plastic modeling/lookup/tblSpiType.json — 5 real SPI
// mold classification records: SPI Type 101-105, each with a real
// Num Annual Mold Cycles rating and a real Use Insert flag) into
// im_reference_data category='lookup_table' — same shape and
// staging-only discipline as migrations 651-681.
//
// key = 'SPI ' + Spi Type (e.g. 'SPI 101'), value = Num Annual Mold
// Cycles, unit_type = 'cycles', raw = full source record (incl.
// Use Insert).
//
// IMPORTANT confirmed finding: this is the real source table for
// cost-injection-molding-engine.ts's SPI_MOLD_CLASSES constant — and it
// does NOT match what's live there today:
//   Class101: live lifeShotRating=1,000,000 vs real=9,999,999,999 (~unlimited)
//   Class102: live 1,000,000 vs real 1,000,000 (match)
//   Class103: live 500,000 vs real 500,000 (match)
//   Class104: live 100,000 vs real 100,000 (match)
//   Class105: live 500 vs real 5,000 (10x off)
// Classes 101 and 105 are wrong in the live engine today. This table also
// reveals "Use Insert" (true for 101/102, false for 103-105) — whether
// the mold uses a replaceable hardened cavity insert vs. molding directly
// into the plate — a real signal never modeled anywhere in this app.
// NOT wired into any cost calculation here — same "combine once all
// lookup tables have arrived" sequencing as every prior lookup_table
// migration this batch; the SPI_MOLD_CLASSES correction is a deliberate
// follow-up fix, not done silently here.
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const SPI_FILE = path.join(__dirname, '../../../memory/plastic modeling/lookup/tblSpiType.json');
const OUT_SQL = path.join(__dirname, '../682_seed_im_lookup_spi_type.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(SPI_FILE, 'utf8'));

const rows = data.records.map((r) => {
  const type = r['Spi Type'];
  const cycles = r['Num Annual Mold Cycles'];
  const useInsert = r['Use Insert'];
  return {
    category: 'lookup_table',
    key: `SPI ${type}`,
    value: String(cycles),
    unit_type: 'cycles',
    notes: `SPI Class ${type} — life shot rating; use insert: ${useInsert}`,
    raw: r,
  };
});

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 682: Seed im_reference_data category = 'lookup_table'
-- (SPI mold type) — schema: migration 636
--
-- Generated by gen_682_seed_im_lookup_spi_type.js.
-- Row count: ${rows.length} (memory/plastic modeling/lookup/tblSpiType.json).
--
-- NOT wired into any cost calculation — staging only. See the generator
-- script header — CONFIRMED real source table for
-- cost-injection-molding-engine.ts's SPI_MOLD_CLASSES, which has real
-- discrepancies for Class101 and Class105 today.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
