// Generator: stages the real Injection Molding "tblDTCLimits" lookup-table
// export (memory/plastic modeling/lookup/tblDTCLimits.json — 3 real
// Design-to-Cost limit records: Compression Molding cutout utilization
// threshold and max-thickness cure-time multiplier, plus one rule
// explicitly marked "Deprecated in CMV290" for blind-hole LD ratio) into
// im_reference_data category='lookup_table' — same shape and
// staging-only discipline as migrations 651-671.
//
// key = "<Process>_<Name>" (composite), value = Limit, raw = full source
// record (incl. the deprecation note verbatim — staged as-is, not
// filtered out, matching this session's lossless-staging discipline).
//
// NOT wired into any cost/DFM calculation here — same "combine once all
// lookup tables have arrived" sequencing as every prior lookup_table
// migration this batch.
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const LIMITS_FILE = path.join(__dirname, '../../../memory/plastic modeling/lookup/tblDTCLimits.json');
const OUT_SQL = path.join(__dirname, '../672_seed_im_lookup_dtc_limits.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(LIMITS_FILE, 'utf8'));

const rows = data.records.map((r) => ({
  category: 'lookup_table',
  key: `${r['Process']}_${r['Name']}`,
  value: String(r['Limit']),
  unit_type: null,
  notes: r['Notes'] || null,
  raw: r,
}));

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 672: Seed im_reference_data category = 'lookup_table'
-- (DTC limits) — schema: migration 636
--
-- Generated by gen_672_seed_im_lookup_dtc_limits.js.
-- Row count: ${rows.length} (memory/plastic modeling/lookup/tblDTCLimits.json).
--
-- NOT wired into any cost/DFM calculation — staging only.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
