// Generator: stages the FULL raw JSON of 141 real Machining machines
// (memory/machining/machine/machiningusa.json — 12 of the 43 real station
// categories from processes.json; user has confirmed the remaining
// station categories/regions will follow in a future session) into
// machining_reference_data category='machine' (schema: migration 638) —
// the Machining equivalent of sm_reference_data's 'machine' category
// (migration 479) and im_reference_data's 'machine' category (migration
// 648).
//
// Companion backend change: mhr.service.ts#getReferenceDetail gets a
// third fallback block (after sm_reference_data, im_reference_data) so
// the HR Rates "Edit MHR Record" dialog's read-only "Machine & Process
// Lookup" panel also resolves real Machining machines by name — exact
// same pattern as migration 648's im_reference_data fallback added for
// Injection Molding. Pure read-only lookup-panel support, not a cost-
// engine change — no calculation anywhere is touched by this migration.
//
// `raw` is the untouched, unflattened original machine object
// (accounting/time/limits/powers/rates/other/yields/
// bottomUpOverheadRateInputs/manufacturerInformation nesting preserved).
//
// key = "<categoryName>:<machine name>" (mirrors sm_reference_data's and
// im_reference_data's own "<category-prefix>:<name>" convention for this
// same 'machine' category). value = bottomUpOverheadRateInputs.
// machinePriceUsd (Machining's real per-machine price field lives there,
// unlike Injection Molding's file where it sat one level up under a
// `machine` wrapper key -- this file has no such wrapper, accounting/
// time/limits/etc. are already top-level per machine).
//
// Disclosed, NOT silently forced: one of the 12 real category names in
// this file, "Manual Bench Cell", has no exact match among the 43 real
// station names in process_taxonomy (migration 691) -- processes.json's
// own "Bench Operation" station lists "Manual Bench Cell - 16m x 4m
// Footprint" as its defaultMachine, so this is very likely the same real
// station under a different literal string in the two source files, but
// that reconciliation is not made here -- staged verbatim as its own
// category key, a disclosed near-miss for a future human decision (same
// discipline as migration 609's own unresolved-candidates list), not a
// guessed alias.
//
// Offline, file-in/file-out -- matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const MACHINE_FILE = path.join(__dirname, '../../../memory/machining/machine/machiningusa.json');
const OUT_SQL = path.join(__dirname, '../692_stage_machining_machine_reference_detail.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

// Real source data names the original tool verbatim in
// manufacturerInformation.dataSource (e.g. "aPriori Baseline") -- per this
// project's standing rule, rebranded to "eMithran" before staging.
function sanitize(v) {
  if (typeof v === 'string') return v.replace(/aPriori/g, 'eMithran');
  if (Array.isArray(v)) return v.map(sanitize);
  if (v && typeof v === 'object') {
    const out = {};
    for (const [k, val] of Object.entries(v)) out[k] = sanitize(val);
    return out;
  }
  return v;
}

const data = JSON.parse(fs.readFileSync(MACHINE_FILE, 'utf8'));

const rows = [];
for (const cat of data.machineCategories) {
  for (const m of cat.machines) {
    const name = m.name || m.primaryId;
    if (!name) continue;
    rows.push({
      key: `${cat.categoryName}:${name}`,
      value: m.bottomUpOverheadRateInputs?.machinePriceUsd != null ? String(m.bottomUpOverheadRateInputs.machinePriceUsd) : null,
      unit_type: 'Currency',
      notes: `Machining reference spec (${cat.categoryName})`,
      raw: sanitize(m),
    });
  }
}

const valuesSql = rows.map((r) => {
  return `('machine', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 692: Stage full raw JSON of 141 real Machining machines
-- into machining_reference_data category='machine' (schema: migration 638)
--
-- Generated by gen_692_stage_machining_machine_reference_detail.js.
-- Row count: ${rows.length} (12 of 43 real station categories from
-- memory/machining/machine/machiningusa.json -- remaining categories/
-- regions to follow in a future session per the user).
--
-- Powers the HR Rates "Edit MHR Record" dialog's read-only "Machine &
-- Process Lookup" panel for Machining machines, once the companion
-- mhr.service.ts#getReferenceDetail fallback is added (mirrors migration
-- 648's im_reference_data fallback exactly).
--
-- Disclosed gap: one category, "Manual Bench Cell", has no exact-name
-- match among process_taxonomy's 43 Machining station rows (migration
-- 691) -- see generator script header. Staged as-is, not aliased.
-- ============================================================================

INSERT INTO machining_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
