// Generator: stages the real Injection Molding "tblToolLife" lookup-table
// export (memory/plastic modeling/lookup/tblToolLife.json — 17 real
// material-specific mold tool-life records, each with a real Num Shots
// Per Tool figure ranging 144,000 (ABS/PBT/Polycarbonate/Polyurethane/PPS)
// to 428,000 (PET/Polystyrene/TPA/TPE/TPO/TPS/TPU/TPV)) into
// im_reference_data category='lookup_table' — same shape and staging-only
// discipline as migrations 651-684.
//
// key = Material Type, value = Num Shots Per Tool, unit_type = 'shots',
// raw = full source record.
//
// Distinct from migration 682's SPI_MOLD_CLASSES life-shot-rating (a
// generic mold-CLASS ceiling, independent of what's being molded) — this
// is the real per-MATERIAL abrasiveness-driven tool wear ceiling (e.g. an
// unfilled PET/PS/TP-elastomer part wears a mold 3x slower than an ABS/PC
// part). No existing consumer models material-specific tool wear anywhere
// in cost-injection-molding-engine.ts today — a genuine capability gap.
// NOT wired into any cost calculation here — same "combine once all
// lookup tables have arrived" sequencing as every prior lookup_table
// migration this batch.
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const LIFE_FILE = path.join(__dirname, '../../../memory/plastic modeling/lookup/tblToolLife.json');
const OUT_SQL = path.join(__dirname, '../685_seed_im_lookup_tool_life.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(LIFE_FILE, 'utf8'));

const rows = data.records.map((r) => {
  const material = r['Material Type'];
  const shots = r['Num Shots Per Tool'];
  return {
    category: 'lookup_table',
    key: material,
    value: String(shots),
    unit_type: 'shots',
    notes: `Tool life for ${material}: ${shots} shots per tool`,
    raw: r,
  };
});

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 685: Seed im_reference_data category = 'lookup_table'
-- (tool life by material) — schema: migration 636
--
-- Generated by gen_685_seed_im_lookup_tool_life.js.
-- Row count: ${rows.length} (memory/plastic modeling/lookup/tblToolLife.json).
--
-- NOT wired into any cost calculation — staging only. Genuine capability
-- gap: no per-material tool-wear modeling exists anywhere in this app
-- today. Distinct from migration 682's SPI mold-class life rating.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
