// Generator: stages the real Injection Molding "tblStandardWaterLineSizes"
// lookup-table export (memory/plastic modeling/lookup/tblStandardWaterLineSizes.json
// — 4 real standard mold cooling water-line diameters in mm: 6, 8, 10, 12)
// into im_reference_data category='lookup_table' — same shape and
// staging-only discipline as migrations 651-686.
//
// key = diameter value itself (as string, e.g. '6'), value = same
// diameter (mm), unit_type = 'mm', raw = full source record.
//
// This is the standard-size catalog for a mold's cooling-channel network
// — a genuine capability gap today: cycle-time.ts's cooling-time model
// (Menges cooling physics, per this repo's CLAUDE.md) computes a required
// cooling time from wall thickness/material but has no linkage to real
// discrete water-line diameters a moldmaker would actually drill/ream to.
// No existing consumer. NOT wired into any cost calculation here — same
// "combine once all lookup tables have arrived" sequencing as every prior
// lookup_table migration this batch.
//
// This was one of 2 files in memory/plastic modeling/lookup/ found NOT
// yet staged during a full directory reconciliation pass (the other is
// tblTolerances.json, migration 688) — both were present in the source
// directory but never explicitly handed over during the file-by-file
// sequence that produced migrations 651-686.
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const WATERLINE_FILE = path.join(__dirname, '../../../memory/plastic modeling/lookup/tblStandardWaterLineSizes.json');
const OUT_SQL = path.join(__dirname, '../687_seed_im_lookup_standard_water_line_sizes.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(WATERLINE_FILE, 'utf8'));

const rows = data.records.map((r) => {
  const dia = r['Water Line Diameter (mm)'];
  return {
    category: 'lookup_table',
    key: String(dia),
    value: String(dia),
    unit_type: 'mm',
    notes: `Standard mold cooling water-line diameter: ${dia} mm`,
    raw: r,
  };
});

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 687: Seed im_reference_data category = 'lookup_table'
-- (standard water line sizes) — schema: migration 636
--
-- Generated by gen_687_seed_im_lookup_standard_water_line_sizes.js.
-- Row count: ${rows.length} (memory/plastic modeling/lookup/tblStandardWaterLineSizes.json).
--
-- NOT wired into any cost calculation — staging only. Genuine capability
-- gap: no linkage between cycle-time.ts's cooling-time model and real
-- discrete water-line diameters exists today.
--
-- Found via a full directory reconciliation of memory/plastic modeling/
-- lookup/ against migrations 651-686 — this file was present on disk but
-- never explicitly handed over in the file-by-file sequence.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
