#!/usr/bin/env node
// Generates migration 828: seed mhr_records with the machines in
// memory/Sheetmetal Hydroforming/Machine/*.csv, process_group
// Sheet Metal - Hydroforming, and point the catalog rows (migration 792) at
// their classes.
//
//   machines_hydroform.csv      Hydroform     (38 presses)
//   machines_offline_blank.csv  Offline Blank (18 blanking presses)
//
// The hydroform file carries capability and economics but NO labour or
// overhead rate columns; those rows are seeded with their rates NULL (the
// source states none), never with a rate derived here. Engines skip a machine
// with no rate and say so.
//
// Run: node backend/migrations/scripts/gen_828_seed_hydroforming_mhr_records.js

const path = require('path');
const fs = require('fs');
const { readCsv, sqlStr, buildMachineRows, insertSql } = require('./lib/memory-machine-seed');

const ROOT = path.resolve(__dirname, '..', '..', '..');
const SRC = path.join(ROOT, 'memory', 'Sheetmetal Hydroforming');
const OUT = path.join(__dirname, '..', '828_seed_hydroforming_mhr_records.sql');
const GROUP = 'Sheet Metal - Hydroforming';

const wage = readCsv(path.join(SRC, 'hydroforming_wage_grade_associations.csv')).rows;
const gradeOf = (p) => wage.find((w) => w['Process Name'] === p)?.['Wage Grade Name'] ?? null;

const FILES = [
  { file: 'machines_hydroform.csv', process: 'Hydroform', cls: 'hydroform', ratesAbsentInSource: true,
    envelope: ['Forming Area Length (mm)', 'Forming Area Width (mm)', 'Max Draw Depth (mm)', null] },
  { file: 'machines_offline_blank.csv', process: 'Offline Blank', cls: 'hydroform_offline_blank', ratesAbsentInSource: false,
    envelope: [null, null, null, null] },
];
const onDisk = fs.readdirSync(path.join(SRC, 'Machine')).filter((f) => f.endsWith('.csv'));
const unmapped = onDisk.filter((f) => !FILES.some((x) => x.file === f));
if (unmapped.length) throw new Error(`unmapped machine files: ${unmapped.join(', ')}`);

const specs = FILES.map((f) => ({
  file: path.join(SRC, 'Machine', f.file), rel: `Sheetmetal Hydroforming/Machine/${f.file}`,
  category: f.process, machineClass: f.cls, grade: gradeOf(f.process), envelope: f.envelope,
  ratesAbsentInSource: f.ratesAbsentInSource,
}));
const { columns, rows, report } = buildMachineRows(specs, GROUP);
const catVals = FILES.map((f) => `  (${sqlStr(f.process)}, ${sqlStr(f.cls)})`).join(',\n');

const sql = `-- ============================================================================
-- Migration 828: Seed mhr_records with the Sheet Metal Hydroforming machines
-- ============================================================================
-- Generated by scripts/gen_828_seed_hydroforming_mhr_records.js -- do not
-- hand-edit, re-run the generator and diff instead.
--
-- Source: memory/Sheetmetal Hydroforming/Machine/*.csv (USA reference export):
${report.map((r) => `--   ${r.category.padEnd(16)} ${r.machineClass.padEnd(26)} ${String(r.n).padStart(2)} machine(s)  wage ${r.grade ?? '-'}${r.ratesAbsentInSource ? '  (source has no labour/overhead rates: seeded NULL)' : ''}`).join('\n')}
--
-- Row shape of 806/818/820/824/826 (scripts/lib/memory-machine-seed.js).
-- Independent, idempotent statements.
-- ============================================================================

-- ── 1. Machines.
${insertSql(columns, rows)}

-- ── 2. Catalog rows (migration 792): machine_class, where still NULL.
UPDATE process_taxonomy pt
SET machine_class = v.machine_class
FROM (VALUES
${catVals}
) AS v(process_name, machine_class)
WHERE pt.process_group = '${GROUP}' AND pt.process_name = v.process_name AND pt.machine_class IS NULL;

UPDATE process_calculator_mappings pcm
SET machine_class = v.machine_class, updated_at = now()
FROM (VALUES
${catVals}
) AS v(operation, machine_class)
WHERE pcm.process_group = '${GROUP}' AND pcm.operation = v.operation AND pcm.machine_class IS NULL;

NOTIFY pgrst, 'reload schema';
`;
fs.writeFileSync(OUT, sql, 'utf8');
console.log(`Wrote ${path.relative(ROOT, OUT)}: ${rows.length} machines`);
