// Generator: stages the real Injection Molding "cmToolMachiningRates"
// lookup-table export (memory/plastic modeling/lookup/cmToolMachiningRates.json
// — 18 real mold-manufacturing machining throughput rates: cavity/core
// plate general machining and roughing, EDM electrode burn, chamfering,
// clamp/ejector-box plate machining, coarse texture finishing, coordinate
// measuring, guide-pin/heater-line/standard hole drilling, insert pocket
// machining, parting-line spotting (simple/average/complex), rib CNC
// machining, vent machining — each with real rate + real unit (m2/hr,
// mm3/min, mm/min, S/m2, each)) into im_reference_data category=
// 'lookup_table' — same shape and staging-only discipline as migrations
// 651-657.
//
// key = name, value = rate, unit_type = units (as given by source — mixed
// real units, not normalized), raw = full source record.
//
// Major relevance to the open SPI_MOLD_CLASSES.baseCostUsd citation gap
// (cost-injection-molding-engine.ts): combined with the real hourly rates
// already staged by migration 637 (machiningRateUsdPerHr, edmRateUsdPerHr,
// gunDrillRateUsdPerHr), this table converts real geometric quantities
// (cavity plate area, roughing volume, hole length) into real machining
// TIME, and TIME x real hourly rate = a real, itemized base-mold-plate
// manufacturing cost — the largest missing piece toward replacing the
// uncited flat SPI_MOLD_CLASSES numbers. Still NOT wired into any cost
// calculation here — same "combine once all lookup tables have arrived"
// sequencing as every prior lookup_table migration this batch.
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const RATES_FILE = path.join(__dirname, '../../../memory/plastic modeling/lookup/cmToolMachiningRates.json');
const OUT_SQL = path.join(__dirname, '../658_seed_im_lookup_tool_machining_rates.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(RATES_FILE, 'utf8'));

const rows = data.records.map((r) => ({
  category: 'lookup_table',
  key: r.name,
  value: String(r.rate),
  unit_type: r.units,
  notes: 'Mold-manufacturing machining throughput rate',
  raw: r,
}));

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 658: Seed im_reference_data category = 'lookup_table'
-- (tool machining rates) — schema: migration 636
--
-- Generated by gen_658_seed_im_lookup_tool_machining_rates.js.
-- Row count: ${rows.length} (memory/plastic modeling/lookup/cmToolMachiningRates.json).
--
-- NOT wired into any cost calculation — staging only. See the generator
-- script header for how this relates to the open SPI_MOLD_CLASSES
-- citation gap in cost-injection-molding-engine.ts.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
