// Generator: stages the real Injection Molding "cavityTextures" lookup-table
// export (memory/plastic modeling/lookup/cavityTextures.json — 26 real mold
// cavity surface texture standards: Mold-Tech A/B/C/D pattern families plus
// a "None" baseline, each with a real pattern code, texture depth in mm,
// and SPI surface-finish equivalent rating) into im_reference_data
// category='lookup_table' — same shape and staging-only discipline as
// migration 651's adviceRules.
//
// key = texture_name (unique per record — already encodes pattern + depth),
// value = texture_depth_mm, unit_type = 'Length', raw = full source record.
//
// NOT promoted into any live cost-consuming table here — same deliberate
// staging-only scope as every other lookup_table category row. Promotion
// (e.g. into surface-finish/tooling-cost selection) is a separate, later,
// reviewed decision once a real consumer needs it.
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const TEXTURES_FILE = path.join(__dirname, '../../../memory/plastic modeling/lookup/cavityTextures.json');
const OUT_SQL = path.join(__dirname, '../652_seed_im_lookup_cavity_textures.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(TEXTURES_FILE, 'utf8'));

const rows = data.records.map((r) => ({
  category: 'lookup_table',
  key: r.texture_name,
  value: String(r.texture_depth_mm),
  unit_type: 'Length',
  notes: `${r.standard} cavity texture (pattern ${r.pattern}, SPI equivalent ${r.spi_refinish})`,
  raw: r,
}));

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 652: Seed im_reference_data category = 'lookup_table'
-- (cavity textures) — schema: migration 636
--
-- Generated by gen_652_seed_im_lookup_cavity_textures.js.
-- Row count: ${rows.length} (memory/plastic modeling/lookup/cavityTextures.json).
--
-- NOT promoted into any live cost-consuming table — staging only. See the
-- generator script header for why.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
