// ============================================================================
// Generator: Migration 787 — remaining Multi-Spindle Machining reference data
//
// Source: memory/Multi-Spindle Maching/{lookup,Procesess}/*.csv and
// wage_grade_associations.csv. Lossless landing only, same discipline as
// 784/785/786 — nothing promoted or wired to any calculator.
//
// processes/operations are staged as-is: "Material Stock" and
// "User-Defined Process" are the real content of this source file — per
// the Sheet Metal process taxonomy's own roadmap (roadmap_status: non_mfg),
// these are system markers, not real manufacturing operations. This source
// export was never populated with real multi-spindle turning/drilling/
// parting process rows beyond that scaffolding, so that's what's staged.
// ============================================================================

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '../../../memory/Multi-Spindle Maching');
const OUT_SQL = path.join(__dirname, '../787_stage_multi_spindle_remaining_reference_data.sql');

function parseCsv(text) {
  const lines = text.replace(/^﻿/, '').split(/\r?\n/).filter((l) => l.length > 0);
  const header = splitCsvLine(lines[0]);
  return lines.slice(1).map((line) => {
    const fields = splitCsvLine(line);
    const row = {};
    header.forEach((h, i) => { row[h] = fields[i] ?? ''; });
    return row;
  });
}

function splitCsvLine(line) {
  const out = [];
  let cur = '';
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const c = line[i];
    if (inQuotes) {
      if (c === '"' && line[i + 1] === '"') { cur += '"'; i++; }
      else if (c === '"') { inQuotes = false; }
      else { cur += c; }
    } else {
      if (c === '"') inQuotes = true;
      else if (c === ',') { out.push(cur); cur = ''; }
      else cur += c;
    }
  }
  out.push(cur);
  return out;
}

function sqlStr(v) {
  if (v === undefined || v === null || v === '') return 'NULL';
  return `$str$${v}$str$`;
}
function jsonbLit(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$`;
}

// lookup tables: whole-table blob, one row each
const partingRing = parseCsv(fs.readFileSync(path.join(ROOT, 'lookup/tblPartingRingWidth.csv'), 'utf8'))
  .map((r) => ({ diameterMm: Number(r.diameterMm), ringWidthMm: Number(r.ringWidthMm) }));
const preferredSizes = parseCsv(fs.readFileSync(path.join(ROOT, 'lookup/tblPreferredSizes.csv'), 'utf8'))
  .map((r) => ({ sizeMm: Number(r.sizeMm), unitSystem: r.unitSystem, comment: r.comment }));

const lookupRows = [
  `('lookup_table', 'USA', '2026-Multi-Spindle', ${sqlStr('tblPartingRingWidth')}, NULL, NULL, 'Parting ring width by diameter', ${jsonbLit(partingRing)})`,
  `('lookup_table', 'USA', '2026-Multi-Spindle', ${sqlStr('tblPreferredSizes')}, NULL, NULL, 'Preferred stock sizes for snap-to-size stock selection', ${jsonbLit(preferredSizes)})`,
];

// processes / operations / wage grades: one row per item
const processes = parseCsv(fs.readFileSync(path.join(ROOT, 'Procesess/multi_spindle_processes.csv'), 'utf8'));
const operations = parseCsv(fs.readFileSync(path.join(ROOT, 'Procesess/multi_spindle_operations.csv'), 'utf8'));
const wageGrades = parseCsv(fs.readFileSync(path.join(ROOT, 'wage_grade_associations.csv'), 'utf8'));

const processRows = processes.map((r) => {
  const raw = { processName: r.processName, defaultToolShopName: r.defaultToolShopName || '', defaultMachine: r.defaultMachine || '', notes: r.notes || '' };
  return `('process', 'USA', '2026-Multi-Spindle', ${sqlStr(r.processName)}, ${sqlStr(r.defaultMachine)}, NULL, NULL, ${jsonbLit(raw)})`;
});

const operationRows = operations.map((r) => {
  const raw = { processName: r.processName };
  return `('operation', 'USA', '2026-Multi-Spindle', ${sqlStr(r.processName)}, NULL, NULL, NULL, ${jsonbLit(raw)})`;
});

const wageGradeRows = wageGrades.map((r) => {
  const raw = { process: r.processName, wageGrade: r.wageGradeName || null, hasChildren: r.hasChildren === 'True' };
  return `('wage_grade', 'USA', '2026-Multi-Spindle', ${sqlStr(r.processName)}, ${sqlStr(r.wageGradeName)}, NULL, 'Process -> required labour grade', ${jsonbLit(raw)})`;
});

const allValues = [...lookupRows, ...processRows, ...operationRows, ...wageGradeRows].join(',\n');

const sql = `-- ============================================================================
-- Migration 787: Stage remaining Multi-Spindle Machining reference data (2026-09-19)
--
-- Source: memory/Multi-Spindle Maching/{lookup,Procesess}/*.csv and
-- wage_grade_associations.csv. Generated by gen_787_stage_multi_spindle_remaining.js
-- -- lossless landing only, same discipline as migrations 784/785/786.
--
-- processes/operations are staged as-is: "Material Stock" and
-- "User-Defined Process" are the real content of this source file, and per
-- the Sheet Metal process taxonomy's own roadmap (memory/sheetmetal/process/
-- README.md, roadmap_status: non_mfg) these two names are system markers,
-- not real manufacturing operations -- this source export was never
-- populated with real multi-spindle turning/drilling/parting process rows
-- beyond that scaffolding. Staged honestly as what the source actually
-- contains, not filled in with invented operation names.
--
-- lookup tables use the same one-row-per-table whole-blob shape as migration
-- 739 (main Machining lookup tables); process/operation/wage_grade use the
-- same one-row-per-item shape as migrations 689/690/640.
-- ============================================================================

BEGIN;

INSERT INTO machining_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${allValues}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

COMMIT;

-- Verification (run manually after):
-- SELECT category, count(*) FROM machining_reference_data
--   WHERE source_version = '2026-Multi-Spindle' GROUP BY category;
-- -- Expect: material 105, variable 23, lookup_table 2, process 2, operation 2, wage_grade 2.
-- SELECT jsonb_array_length(raw) FROM machining_reference_data WHERE key = 'tblPreferredSizes';
-- -- Expect 814.
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${OUT_SQL}`);
console.log(`  lookup_table: ${lookupRows.length} (tblPreferredSizes rows: ${preferredSizes.length})`);
console.log(`  process: ${processRows.length}, operation: ${operationRows.length}, wage_grade: ${wageGradeRows.length}`);
