// Generates migration 866: material properties for the Sand Casting raw materials.
// Source: memory/Sand casting/Raw Material/raw_materials.csv. The core columns (cost,
// density, hardness, names) are already in raw_materials (migration 852); every other
// column becomes a property, with its unit taken from the header, the same rules as
// gen_855_promote_memory_raw_material_domains.js. Re-run this script, never hand-edit the SQL.
const fs = require('fs');
const path = require('path');

const MEM = path.join(__dirname, '..', '..', '..', 'memory');
const FILE = path.join(MEM, 'Sand casting', 'Raw Material', 'raw_materials.csv');
const OUT = path.join(__dirname, '..', '866_sand_casting_properties.sql');
const GROUP = 'Sand Casting';
const SOURCE_VERSION = '2026-SandCasting';

// Headers already stored as raw_materials columns (same classification as gen_855).
const CORE = new Set([
  'Name', 'Source Name', 'Description', 'Cut Code', 'Material Type', 'USA Name', 'Unit Cost (USD / kg)',
  'Cost Units', 'Base Cost Per Unit (USD)', 'Density (kg / m^3)', 'Hardness', 'Hardness System',
]);
const VENDOR_RE = /a\s*priori/i;

function parseCsv(text) {
  const rows = [];
  let field = '', row = [], quoted = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (quoted) {
      if (c === '"' && text[i + 1] === '"') { field += '"'; i++; }
      else if (c === '"') quoted = false;
      else field += c;
    } else if (c === '"') quoted = true;
    else if (c === ',') { row.push(field); field = ''; }
    else if (c === '\n') { row.push(field); rows.push(row); row = []; field = ''; }
    else if (c !== '\r') field += c;
  }
  if (field !== '' || row.length) { row.push(field); rows.push(row); }
  return rows;
}

const snake = (s) => s
  .replace(/\(([^()]*)\)\s*$/, '')
  .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
  .replace(/[^A-Za-z0-9]+/g, '_')
  .replace(/^_+|_+$/g, '')
  .toLowerCase();
const unitOf = (header) => {
  const m = /\(([^()]*)\)\s*$/.exec(header);
  return m ? m[1].trim() : null;
};
const sqlStr = (v) => (v == null ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`);
const scrub = (v) => (VENDOR_RE.test(v) ? 'reference export baseline' : v);

const text = fs.readFileSync(FILE, 'utf8').replace(/^﻿/, '');
const [header, ...body] = parseCsv(text);
const col = (h) => header.indexOf(h);
const srcIdx = col('Source Name');
if (srcIdx < 0) throw new Error('Source Name column not found');

const propCols = header.map((h, i) => ({ h, i })).filter(({ h }) => h && !CORE.has(h));
const seen = new Set();
const values = [];
for (const r of body) {
  const name = (r[srcIdx] || '').trim();
  if (!name) continue;
  if (seen.has(name)) throw new Error(`duplicate Source Name in the file: ${name}`);
  seen.add(name);
  for (const { h, i } of propCols) {
    const raw = (r[i] || '').trim();
    if (raw === '') continue;
    const numeric = /^-?\d+(\.\d+)?$/.test(raw.replace(/,/g, ''));
    const key = snake(h);
    const unit = unitOf(h);
    if (numeric) values.push(`  (${sqlStr(name)}, ${sqlStr(key)}, ${raw.replace(/,/g, '')}, NULL, ${sqlStr(unit)})`);
    else values.push(`  (${sqlStr(name)}, ${sqlStr(key)}, NULL, ${sqlStr(scrub(raw))}, ${sqlStr(unit)})`);
  }
}

const sql = `-- 866: Sand Casting material properties (raw_material_properties), generated by
-- backend/migrations/scripts/gen_866_sand_casting_properties.js from
-- memory/Sand casting/Raw Material/raw_materials.csv. Each value attaches to the Sand Casting
-- row whose source name (grade) matches. Idempotent (ON CONFLICT DO NOTHING).
WITH props(source_name, property_key, value_num, value_text, unit) AS (VALUES
${values.join(',\n')}
)
INSERT INTO raw_material_properties (raw_material_id, property_key, value_num, value_text, unit, source_version)
SELECT rm.id, p.property_key, CAST(p.value_num AS NUMERIC), CAST(p.value_text AS TEXT), CAST(p.unit AS TEXT), '${SOURCE_VERSION}'
FROM props p
JOIN raw_materials rm ON rm.grade = p.source_name AND rm.material_group = '${GROUP}'
ON CONFLICT (raw_material_id, property_key) DO NOTHING;
`;

fs.writeFileSync(OUT, sql);
console.log(`materials: ${seen.size}, property values: ${values.length}, written: ${path.basename(OUT)}`);
