// ============================================================================
// Generator: Migration 786 — Multi-Spindle Machining variables
//
// Source: memory/Multi-Spindle Maching/variables.csv (23 real variables —
// stock-allowance/snap-size/scrap-credit/gear-quality-default system
// settings). Same lossless-landing-only pattern as migration 639 (main
// Machining variables) — these are not promoted anywhere; no calculator
// consumes them yet. Checked directly: zero name overlap with the 264
// variables already staged by migration 639, so a distinct source_version
// ('2026-Multi-Spindle') is used purely to keep this batch attributable to
// its own source file, not because of any real key collision risk.
// ============================================================================

const fs = require('fs');
const path = require('path');

const CSV_FILE = path.join(__dirname, '../../../memory/Multi-Spindle Maching/variables.csv');
const OUT_SQL = path.join(__dirname, '../786_seed_multi_spindle_machining_variables.sql');

function parseCsv(text) {
  const lines = text.replace(/^﻿/, '').split(/\r?\n/).filter((l) => l.length > 0);
  const header = splitCsvLine(lines[0]);
  return lines.slice(1).map((line) => {
    const fields = splitCsvLine(line);
    const row = {};
    header.forEach((h, i) => { row[h] = fields[i] ?? ''; });
    return row;
  });
}

function splitCsvLine(line) {
  const out = [];
  let cur = '';
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const c = line[i];
    if (inQuotes) {
      if (c === '"' && line[i + 1] === '"') { cur += '"'; i++; }
      else if (c === '"') { inQuotes = false; }
      else { cur += c; }
    } else {
      if (c === '"') inQuotes = true;
      else if (c === ',') { out.push(cur); cur = ''; }
      else cur += c;
    }
  }
  out.push(cur);
  return out;
}

function sqlStr(v) {
  if (v === undefined || v === null || v === '') return 'NULL';
  return `$str$${v}$str$`;
}
function jsonbLit(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$`;
}

const rows = parseCsv(fs.readFileSync(CSV_FILE, 'utf8'));

const values = rows.map((r) => {
  const key = r['variableName'];
  const value = r['stringValue'];
  const unitType = r['unitTypeName'] || null;
  const notes = r['notes'] || null;
  const raw = { ...r };
  return `('variable', 'USA', '2026-Multi-Spindle', ${sqlStr(key)}, ${sqlStr(value)}, ${sqlStr(unitType)}, ${sqlStr(notes)}, ${jsonbLit(raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 786: Seed Multi-Spindle Machining variables (2026-09-19)
--
-- Source: memory/Multi-Spindle Maching/variables.csv (23 real variables).
-- Generated by gen_786_seed_multi_spindle_machining_variables.js -- lossless
-- landing only, same as migration 639 for the main Machining variables --
-- not promoted or consumed by any calculator yet.
-- ============================================================================

BEGIN;

INSERT INTO machining_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${values}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

COMMIT;

-- Verification (run manually after):
-- SELECT count(*) FROM machining_reference_data WHERE category = 'variable' AND source_version = '2026-Multi-Spindle';
-- -- Expect 23.
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${OUT_SQL} (${rows.length} variables)`);
