// Generator: stages the real Injection Molding "partHandlingTimes"
// lookup-table export (memory/plastic modeling/lookup/partHandlingTimes.json
// — 12 real (box_length_mm, box_width_mm) -> handling_time_s breakpoints)
// into im_reference_data category='lookup_table' — same shape and
// staging-only discipline as migrations 651-666.
//
// key = "<box_length_mm>x<box_width_mm>", value = handling_time_s,
// unit_type = 's', raw = full source record.
//
// Complementary to migration 666's materialHandling (weight_kg ->
// handling_time_s) — that table covers a heavy-but-compact part; this one
// covers a bulky-but-light part (handling constrained by footprint, not
// mass). A real, principled combination is most likely "whichever
// constraint is more limiting" (max of the two lookups), but that
// combination rule is not given by either raw table and is not invented
// here. Real bbox length/width are already computed for every part
// throughout cost-injection-molding-engine.ts/cycle-time.ts (bboxMaxMm /
// longestBboxMm), so — like migration 666 — this has no open blocking
// dependency the way the mold-base-area-keyed tables do. NOT wired into
// any cost calculation here — same "combine once all lookup tables have
// arrived" sequencing as every prior lookup_table migration this batch.
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const HANDLING_FILE = path.join(__dirname, '../../../memory/plastic modeling/lookup/partHandlingTimes.json');
const OUT_SQL = path.join(__dirname, '../667_seed_im_lookup_part_handling_times.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(HANDLING_FILE, 'utf8'));

const rows = data.records.map((r) => {
  const lenMm = r['Box Length (mm)'];
  const widMm = r['Box Width (mm)'];
  const timeS = r['Part Handling Time (s)'];
  return {
    category: 'lookup_table',
    key: `${lenMm}x${widMm}`,
    value: String(timeS),
    unit_type: 's',
    notes: `Part handling time for box footprint <= ${lenMm} x ${widMm} mm`,
    raw: { box_length_mm: lenMm, box_width_mm: widMm, handling_time_s: timeS },
  };
});

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 667: Seed im_reference_data category = 'lookup_table'
-- (part handling times by footprint) — schema: migration 636
--
-- Generated by gen_667_seed_im_lookup_part_handling_times.js.
-- Row count: ${rows.length} (memory/plastic modeling/lookup/partHandlingTimes.json).
--
-- NOT wired into any cost calculation — staging only. See the generator
-- script header — complementary to migration 666's weight-based handling
-- time table.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
