// Generator: stages the real Injection Molding "cmToolMachiningSetups"
// lookup-table export (memory/plastic modeling/lookup/cmToolMachiningSetups.json
// — 18 real mold-manufacturing operations with real setup count + setup
// time in hours) into im_reference_data category='lookup_table' — same
// shape and staging-only discipline as migrations 651-658.
//
// key = name, value = setup_time_hr, unit_type = 'hr', raw = full source
// record (incl. number_of_setups).
//
// Direct companion to migration 658's cmToolMachiningRates (same
// operation names largely: Cavity/Core/Clamp Plate machining, Ejector Box
// Plates/Rails, Guide Pin, Insert Pocket, Parting Line Spotting, Support
// Pillars, Vent Machining) — together they give a complete real cycle-
// time model per mold operation: total_time = setups x setup_time_hr +
// (work_quantity / rate). NOT wired into any cost calculation here — same
// "combine once all lookup tables have arrived" sequencing as every prior
// lookup_table migration this batch.
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const SETUPS_FILE = path.join(__dirname, '../../../memory/plastic modeling/lookup/cmToolMachiningSetups.json');
const OUT_SQL = path.join(__dirname, '../659_seed_im_lookup_tool_machining_setups.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(SETUPS_FILE, 'utf8'));

const rows = data.records.map((r) => ({
  category: 'lookup_table',
  key: r.name,
  value: String(r.setup_time_hr),
  unit_type: 'hr',
  notes: `Number of setups: ${r.number_of_setups}`,
  raw: r,
}));

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 659: Seed im_reference_data category = 'lookup_table'
-- (tool machining setups) — schema: migration 636
--
-- Generated by gen_659_seed_im_lookup_tool_machining_setups.js.
-- Row count: ${rows.length} (memory/plastic modeling/lookup/cmToolMachiningSetups.json).
--
-- NOT wired into any cost calculation — staging only. See the generator
-- script header for how this pairs with migration 658's machining rates.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
