#!/usr/bin/env node
// Generates migration 873: Sand Casting catalog rows, machine_class where still NULL.
// Migration 851 created process_taxonomy/process_taxonomy_operations/process_calculator_mappings
// for Sand Casting AND seeded its real machines (mhr_records), but never linked the two --
// every process_taxonomy row stayed machine_class NULL. This is the missing step, the same
// one migration 845 (Die Casting) and migration 872 (Casting Investment) already did for their
// own domains.
//
// A process is linked only when 851 actually mapped it to a real (non-placeholder) machine
// file -- the exact same file-matching logic as gen_851, copied verbatim so there is no drift
// between what 851 seeded and what this links. A process with no real machine file (851's own
// disclosed gap) is left NULL here too, never guessed.
//
// Run: node backend/migrations/scripts/gen_873_sand_casting_catalog_machine_class.js
const fs = require('fs');
const path = require('path');
const { readCsv } = require('./lib/memory-machine-seed');

const ROOT = path.resolve(__dirname, '..', '..', '..');
const SRC = path.join(ROOT, 'memory', 'Sand casting');
const OUT = path.join(__dirname, '..', '873_sand_casting_catalog_machine_class.sql');
const GROUP = 'Sand Casting';
const SKIP_PROCESS = new Set(['User-Defined Process']);
const NON_MFG = new Set(['No Cost Feature']);
const classOf = (process) => 'sand_casting_' + process.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '');

// Copied from gen_851_seed_sand_casting_catalog_and_machines.js verbatim.
const FILE_ALIAS = {
  'machines_co2_coremaking.csv': 'CO2 Cured',
  'machines_no_bake_coremaking.csv': 'No Bake',
  'machines_shell_coremaking.csv': 'Shell',
};
const PLACEHOLDER_FILES = new Set(['machines_default_2.csv', 'machines_default_3.csv', 'machines_stock_core.csv']);
const normalize = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '');

const processesCsv = readCsv(path.join(SRC, 'Processes', 'processes.csv'));
const processes = processesCsv.rows
  .map((r) => String(r['Process Name']))
  .filter((name) => !SKIP_PROCESS.has(name) && !NON_MFG.has(name));

const machineDir = path.join(SRC, 'Machine');
const machineFiles = fs.readdirSync(machineDir).filter((f) => f.endsWith('.csv')).sort();
const linkedProcesses = new Set();
const unmappedFiles = [];
for (const file of machineFiles) {
  if (PLACEHOLDER_FILES.has(file)) continue;
  const proc = FILE_ALIAS[file] ?? processes.find((p) => normalize(p) === normalize(file.replace(/^machines_/, '').replace(/\.csv$/, '')));
  if (!proc) { unmappedFiles.push(file); continue; }
  linkedProcesses.add(proc);
}
const notLinked = processes.filter((p) => !linkedProcesses.has(p));

const q = (s) => `'${s.replace(/'/g, "''")}'`;
const pairs = [...linkedProcesses].sort().map((p) => `  (${q(p)}, ${q(classOf(p))})`).join(',\n');

const sql = `-- 873: Sand Casting catalog rows, machine_class where still NULL.
-- Generated by scripts/gen_873_sand_casting_catalog_machine_class.js -- do not hand-edit,
-- re-run the generator and diff instead.
--
-- Migration 851 created the Sand Casting catalog and seeded its machines in the same pass,
-- but never linked process_taxonomy/process_calculator_mappings to the machine_class those
-- machines actually got. This closes that gap, the same step migration 845 (Die Casting) and
-- 872 (Casting Investment) already did for their own domains.
--
-- Linked: ${linkedProcesses.size} of ${processes.length} real processes (excluding User-Defined
-- Process and No Cost Feature, same as 851).
-- Not linked, with the reason -- 851's own disclosed gap, no real machine file for these:
--   ${notLinked.join(', ') || 'none'}
-- Unmapped machine files (should be empty; 851 would already have failed on these): ${unmappedFiles.join(', ') || 'none'}
--
-- Idempotent: only rows still NULL are touched.
-- Verify: SELECT process_name, machine_class FROM process_taxonomy
--   WHERE process_group = '${GROUP}' ORDER BY process_name;

UPDATE process_taxonomy pt
SET machine_class = v.machine_class
FROM (VALUES
${pairs}
) AS v(process_name, machine_class)
WHERE pt.process_group = '${GROUP}' AND pt.process_name = v.process_name AND pt.machine_class IS NULL;

UPDATE process_calculator_mappings pcm
SET machine_class = v.machine_class, updated_at = now()
FROM (VALUES
${pairs}
) AS v(operation, machine_class)
WHERE pcm.process_group = '${GROUP}' AND pcm.operation = v.operation AND pcm.machine_class IS NULL;

NOTIFY pgrst, 'reload schema';
`;
fs.writeFileSync(OUT, sql, 'utf8');
console.log(`Wrote ${path.basename(OUT)}: linked ${linkedProcesses.size} of ${processes.length}, not linked: ${notLinked.join(', ') || 'none'}`);
if (unmappedFiles.length) console.log('WARNING unmapped files:', unmappedFiles.join(', '));
