// Generator: stages the real Machining "processes.json" export
// (memory/machining/processes.json — 43 real CNC/manual machining process
// names, each with a real default machine and, where present, a real
// default tool-shop name — e.g. "5 Axis Mill" -> "DMG MORI DMU 105
// monoBLOCK", "Wire EDM" -> "Fanuc 0id") into machining_reference_data
// (migration 638's schema) category='process' — same shape and
// staging-only discipline as this whole reference-data-staging effort
// (sm_reference_data migration 479, im_reference_data migration 636,
// machining_reference_data migration 638).
//
// key = processName, value = defaultMachine, notes = defaultToolShopName
// (when non-empty), raw = full source record.
//
// This is the real machining process taxonomy — mirrors Sheet Metal's own
// process_operations.json taxonomy layer (per this repo's CLAUDE.md) but
// for the Machining domain, which per CLAUDE.md's "Correction (2026-08-29)"
// note already has a real, tested, live-wired costing engine
// (cost-cnc-engine.ts, 43 tests) — this table is the real process-name
// catalog that engine's process selection should eventually be checked
// against, not a replacement for it. NOT wired into any cost calculation
// here — staging only, same discipline as every prior reference-data
// migration.
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const PROC_FILE = path.join(__dirname, '../../../memory/machining/processes.json');
const OUT_SQL = path.join(__dirname, '../689_seed_machining_processes.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(PROC_FILE, 'utf8'));

const rows = data.processes.map((r) => {
  const name = r.processName;
  const machine = r.defaultMachine || null;
  const toolShop = r.defaultToolShopName || null;
  const notesParts = [];
  if (toolShop) notesParts.push(`Tool shop: ${toolShop}`);
  if (r.notes) notesParts.push(r.notes);
  return {
    category: 'process',
    key: name,
    value: machine,
    unit_type: null,
    notes: notesParts.length ? notesParts.join(' — ') : null,
    raw: r,
  };
});

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 689: Seed machining_reference_data category = 'process'
-- (schema: migration 638)
--
-- Generated by gen_689_seed_machining_processes.js.
-- Row count: ${rows.length} (memory/machining/processes.json).
--
-- NOT wired into any cost calculation — staging only. Real machining
-- process-name catalog (mirrors Sheet Metal's process_operations.json
-- taxonomy for the Machining domain).
-- ============================================================================

INSERT INTO machining_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
