#!/usr/bin/env node
// Generates migration 858: the rest of the USA stock prices, from the band-saw and
// the bar-and-tube fabrication material tables, into material_stock_prices.
//
// One source per (material, stock form). Priority: Multi-Spindle (857, already
// loaded) > band saw > bar and tube fab. A lower-priority source only fills a form
// the higher ones do not price; a value it would overwrite is counted and listed,
// never silently replaced. The stock_form check is widened to the new forms.
//
// Run: node backend/migrations/scripts/gen_858_usa_stock_forms_from_bar_and_band_saw.js

const fs = require('fs');
const path = require('path');
const { readCsv, sqlStr, sqlNum } = require('./lib/memory-machine-seed');

const ROOT = path.resolve(__dirname, '..', '..', '..');
const R = path.join(ROOT, 'memory');
const OUT = path.join(__dirname, '..', '858_usa_stock_forms_band_saw_bar_tube.sql');

const MS = 'Multi-Spindle Maching/Materials/materials_table.csv';
const BS = 'Stock Maching/metirials/materials_band_saw.csv';
const BT = 'Bar and tube fab/Raw material/materials.csv';

// [stock_form, the column header in each file]
const FORMS = {
  band_saw: [
    ['hex_bar', 'Hex Bar Unit Cost (USD / kg)'], ['plate', 'Plate Cost Per KG (USD / kg)'],
    ['rectangular_bar', 'Rectangular Bar Unit Cost (USD / kg)'], ['round_bar', 'Round Bar Unit Cost (USD / kg)'],
    ['round_tube', 'Round Tube Unit Cost (USD / kg)'], ['square_bar', 'Square Bar Unit Cost (USD / kg)'],
  ],
  bar_tube: [
    ['angle_bar', 'Angle Bar Unit Cost (USD / kg)'], ['channel_bar', 'Channel Bar Unit Cost (USD / kg)'],
    ['hex_bar', 'Hex Bar Unit Cost (USD / kg)'], ['i_beam', 'I-Beam Unit Cost (USD / kg)'],
    ['rectangular_bar', 'Rectangular Bar Unit Cost (USD / kg)'], ['rectangular_tube', 'Rectangular Tube Unit Cost (USD / kg)'],
    ['round_bar', 'Round Bar Unit Cost (USD / kg)'], ['round_tube', 'Round Tube Unit Cost (USD / kg)'],
    ['sheet', 'Sheet Unit Cost (USD / kg)'], ['square_bar', 'Square Bar Unit Cost (USD / kg)'],
    ['square_tube', 'Square Tube Unit Cost (USD / kg)'], ['t_beam', 'T-Beam Unit Cost (USD / kg)'],
  ],
};

// Forms already priced by migration 857 (Multi-Spindle), which win every conflict.
const taken = new Set();
const msRows = readCsv(path.join(R, MS)).rows;
for (const r of msRows) {
  const ref = String(r['USA Name'] ?? r['Name']).trim();
  for (const [form, col] of [['hex_bar', 'Hex Bar Unit Cost (USD / kg)'], ['rectangular_bar', 'Rectangular Bar Unit Cost (USD / kg)'], ['round_bar', 'Round Bar Unit Cost (USD / kg)'], ['round_tube', 'Round Tube Unit Cost (USD / kg)'], ['square_bar', 'Square Bar Unit Cost (USD / kg)']]) {
    if (typeof r[col] === 'number' && r[col] > 0) taken.add(`${ref}|${form}`);
  }
}

const values = [];
const report = { band_saw: 0, bar_tube: 0, conflicts: [] };
function take(file, label, forms, key) {
  for (const r of readCsv(path.join(R, file)).rows) {
    const ref = String(r[key] ?? r['Name']).trim();
    for (const [form, col] of forms) {
      const price = r[col];
      if (typeof price !== 'number' || price <= 0) continue;
      const k = `${ref}|${form}`;
      if (taken.has(k)) { report.conflicts.push(`${label}: ${ref} ${form}`); continue; }
      taken.add(k);
      report[label]++;
      values.push(`  (${sqlStr(ref)}, ${sqlStr(form)}, 'USA', ${sqlNum(price)}, 'USD', ${sqlStr('memory/' + file)})`);
    }
  }
}
take(BS, 'band_saw', FORMS.band_saw, 'Name');
take(BT, 'bar_tube', FORMS.bar_tube, 'Name');

const ALL_FORMS = ['round_bar', 'hex_bar', 'rectangular_bar', 'square_bar', 'round_tube', 'plate',
  'angle_bar', 'channel_bar', 'i_beam', 't_beam', 'sheet', 'rectangular_tube', 'square_tube'];

const sql = `-- ============================================================================
-- Migration 858: the rest of the USA stock prices, by stock form
-- ============================================================================
-- Generated by scripts/gen_858_usa_stock_forms_from_bar_and_band_saw.js -- do not hand-edit.
--
-- Sources (one per material and form; Multi-Spindle from 857 wins, then band saw,
-- then bar and tube fab):
--   band saw            ${report.band_saw} prices (plate, the forms Multi-Spindle lacks)
--   bar and tube fab    ${report.bar_tube} prices (angle, channel, I-beam, T-beam, sheet, tubes)
--   skipped, already priced by a higher-priority source: ${report.conflicts.length}
--
-- Widens the stock_form check to the new forms. Run after 857 and 833.
-- Idempotent: ON CONFLICT DO NOTHING; the check is dropped and re-added.
-- ============================================================================

DO $$
DECLARE c record;
BEGIN
  FOR c IN SELECT conname FROM pg_constraint
           WHERE conrelid = 'material_stock_prices'::regclass AND contype = 'c'
             AND pg_get_constraintdef(oid) LIKE '%stock_form%'
  LOOP
    EXECUTE format('ALTER TABLE material_stock_prices DROP CONSTRAINT %I', c.conname);
  END LOOP;
END $$;

ALTER TABLE material_stock_prices
  ADD CONSTRAINT material_stock_prices_stock_form_check
  CHECK (stock_form IN (${ALL_FORMS.map((f) => `'${f}'`).join(', ')}));

INSERT INTO material_stock_prices (reference_material, stock_form, location, price_per_kg, currency_code, source)
VALUES
${values.join(',\n')}
ON CONFLICT (reference_material, stock_form, location) DO NOTHING;

DO $$
DECLARE
  unmatched text;
BEGIN
  UPDATE material_stock_prices p
  SET raw_material_name = m.material
  FROM (
    SELECT p2.reference_material, min(r.material) AS material
    FROM (SELECT DISTINCT reference_material FROM material_stock_prices) p2
    JOIN raw_materials r
      ON lower(r.material) IN (lower(p2.reference_material), lower('Generic ' || p2.reference_material))
    GROUP BY p2.reference_material
    HAVING count(DISTINCT lower(r.material)) = 1
  ) m
  WHERE p.reference_material = m.reference_material AND p.raw_material_name IS NULL;

  SELECT string_agg(DISTINCT reference_material, ', ' ORDER BY reference_material) INTO unmatched
  FROM material_stock_prices WHERE raw_material_name IS NULL;
  RAISE NOTICE 'Migration 858: stock prices with no raw_materials match: %', coalesce(unmatched, '(none)');
END $$;

NOTIFY pgrst, 'reload schema';

-- Verify (run after): SELECT location, stock_form, count(*), count(raw_material_name)
--   FROM material_stock_prices GROUP BY 1, 2 ORDER BY 1, 2;
`;
fs.writeFileSync(OUT, sql, 'utf8');
console.log(`Wrote ${path.relative(ROOT, OUT)}: band saw ${report.band_saw}, bar and tube ${report.bar_tube}, skipped ${report.conflicts.length}`);
console.log('conflicts (first 8):', report.conflicts.slice(0, 8).join(' ; '));
