// Generator: stages the real Injection Molding "cmToolAssemblyNumOperators"
// lookup-table export (memory/plastic modeling/lookup/cmToolAssemblyNumOperators.json
// — 5 real (mold_base_area_m2 -> num_operators_required) breakpoints, a
// monotonic step function for mold-assembly labor headcount vs. mold size)
// into im_reference_data category='lookup_table' — same shape and
// staging-only discipline as migrations 651-655.
//
// key = area breakpoint (m^2, as string), value = num_operators_required,
// raw = full source record.
//
// Same open dependency as migration 654's cmMoldBaseDesignHours (also
// keyed by mold base area, there in mm^2 -- this table's m^2 axis is
// consistent with that one's up to ~100 m^2, reinforcing "mold base area"
// as a real, load-bearing concept in the source tool) -- NOT wired into
// any cost calculation. Computing mold base area for a specific part still
// has no real formula/source in this app; the user is providing that
// separately (2026-09-03: "i will give u one by one u keep improving once
// all it came").
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const OPERATORS_FILE = path.join(__dirname, '../../../memory/plastic modeling/lookup/cmToolAssemblyNumOperators.json');
const OUT_SQL = path.join(__dirname, '../656_seed_im_lookup_tool_assembly_num_operators.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(OPERATORS_FILE, 'utf8'));

const rows = data.records.map((r) => ({
  category: 'lookup_table',
  key: `area_m2_${r.mold_base_area_m2}`,
  value: String(r.num_operators_required),
  unit_type: 'count',
  notes: `Tool assembly operators required for mold base area <= ${r.mold_base_area_m2} m^2`,
  raw: r,
}));

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 656: Seed im_reference_data category = 'lookup_table'
-- (tool assembly num operators) — schema: migration 636
--
-- Generated by gen_656_seed_im_lookup_tool_assembly_num_operators.js.
-- Row count: ${rows.length} (memory/plastic modeling/lookup/cmToolAssemblyNumOperators.json).
--
-- NOT wired into any cost calculation — staging only. See the generator
-- script header for the shared open dependency (mold base area
-- methodology) with migration 654.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
