// Generator: stages the real Injection Molding "tblHrsPerSqInchSimple"
// lookup-table export (memory/plastic modeling/lookup/tblHrsPerSqInchSimple.json
// — 10 real (surface_area_in2 -> hrs_per_sq_inch) breakpoints: real
// finishing/polishing hours per in^2 for the "Simple" complexity tier —
// completes the imperial-unit Simple/Average/Complex set alongside
// migrations 676 and 677) into im_reference_data category='lookup_table'
// — same shape and staging-only discipline as migrations 651-677.
//
// key = surface_area_in2 breakpoint (as string — the hours value repeats
// (0.048) across the 3500/5000 in^2 breakpoints, so area is the unique
// key), value = hrs_per_sq_inch, unit_type = 'hr/in^2', raw = full source
// record.
//
// NOT wired into any cost calculation here — same "combine once all
// lookup tables have arrived" sequencing as every prior lookup_table
// migration this batch.
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const RATE_FILE = path.join(__dirname, '../../../memory/plastic modeling/lookup/tblHrsPerSqInchSimple.json');
const OUT_SQL = path.join(__dirname, '../678_seed_im_lookup_hrs_per_sq_inch_simple.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(RATE_FILE, 'utf8'));

const rows = data.records.map((r) => {
  const hrs = r['Hrs Per Sq Inch Simple (hr)'];
  const areaIn2 = r['Surface Area Simple (in^2)'];
  return {
    category: 'lookup_table',
    key: `area_in2_${areaIn2}`,
    value: String(hrs),
    unit_type: 'hr/in^2',
    notes: `Simple finishing rate for surface area <= ${areaIn2} in^2`,
    raw: { hrs_per_sq_inch: hrs, surface_area_in2: areaIn2 },
  };
});

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 678: Seed im_reference_data category = 'lookup_table'
-- (hours per sq inch simple) — schema: migration 636
--
-- Generated by gen_678_seed_im_lookup_hrs_per_sq_inch_simple.js.
-- Row count: ${rows.length} (memory/plastic modeling/lookup/tblHrsPerSqInchSimple.json).
--
-- NOT wired into any cost calculation — staging only. See the generator
-- script header — completes the imperial Simple/Average/Complex set
-- (migrations 676, 677, 678).
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
