#!/usr/bin/env node
// Generates migration 845: promote the Sand Casting raw materials from
// memory/Sand casting/Raw Material/raw_materials.csv into the live raw_materials
// table under material_group 'Sand Casting'.
//
// The lossless landing (every column, verbatim) is already done by the
// manifest-driven staging generator (gen_823, stagedBy 846) into
// machining_reference_data, category 'material'. This file only promotes the
// columns raw_materials has a real home for. Same two-step discipline as 784.
//
// Column mapping, matched to how existing rows are named (the density lookup
// and the material search both read these):
//   material            <- Source Name   ("Generic Aluminum Bronze")
//   material_grade      <- Name          ("Aluminum Bronze")
//   material_specification <- Description
//   material_type       <- Material Type
//   density_kg_m3       <- Density (kg / m^3)
//   density             <- Density / 1000  (g/cm3, the unit the density lookup reads)
//   hardness            <- Hardness, hardness_system <- Hardness System
//   cost, cost_usa      <- Unit Cost (USD / kg), currency USD
//
// A row whose material name already exists in raw_materials is skipped by the
// NOT EXISTS guard (same rule as 784). Those names are listed by the verify
// query in the migration header, never silently replaced.
//
// Run: node backend/migrations/scripts/gen_845_promote_sand_casting_raw_materials.js

const fs = require('fs');
const path = require('path');
const { readCsv, sqlStr, sqlNum } = require('./lib/memory-machine-seed');

const ROOT = path.resolve(__dirname, '..', '..', '..');
const SRC = path.join(ROOT, 'memory', 'Sand casting', 'Raw Material', 'raw_materials.csv');
const OUT = path.join(__dirname, '..', '845_promote_sand_casting_raw_materials.sql');
const GROUP = 'Sand Casting';

const { rows } = readCsv(SRC);
const seen = new Set();
const values = rows.map((r) => {
  const material = r['Source Name'];
  if (!material) throw new Error(`raw material row without a Source Name: ${r['Name']}`);
  if (seen.has(material)) throw new Error(`duplicate Source Name in source: ${material}`);
  seen.add(material);
  const densityKg = r['Density (kg / m^3)'];
  const density = typeof densityKg === 'number' ? Math.round((densityKg / 1000) * 1000) / 1000 : null;
  const cost = typeof r['Unit Cost (USD / kg)'] === 'number' ? r['Unit Cost (USD / kg)'] : null;
  return `  (${sqlStr(material)}, ${sqlStr(r['Name'])}, ${sqlStr(r['Description'])}, ${sqlStr(r['Material Type'])}, ${sqlStr(GROUP)}, ` +
    `${sqlNum(densityKg)}, ${sqlNum(density)}, ${sqlNum(r['Hardness'])}, ${sqlStr(r['Hardness System'])}, ` +
    `${sqlNum(cost)}, ${sqlNum(cost)}, 'USD')`;
});

const sql = `-- ============================================================================
-- Migration 845: Sand Casting raw materials into the live raw_materials table
-- ============================================================================
-- Generated by scripts/gen_845_promote_sand_casting_raw_materials.js -- do not
-- hand-edit, re-run the generator and diff instead.
--
-- Source: memory/Sand casting/Raw Material/raw_materials.csv (${rows.length} materials,
-- USA reference export). Every column is also landed losslessly in
-- machining_reference_data (migration 846, category 'material').
--
-- A material whose name already exists in raw_materials is SKIPPED, never
-- overwritten (NOT EXISTS on material). Run the verify query after to list
-- which names were skipped and decide each one; nothing is replaced silently.
--
-- Idempotent: a second run inserts nothing.
-- ============================================================================

INSERT INTO raw_materials (
  material, material_grade, material_specification, material_type, material_group,
  density_kg_m3, density, hardness, hardness_system, cost, cost_usa, currency
)
SELECT v.material, v.material_grade, v.material_specification, v.material_type, v.material_group,
       v.density_kg_m3, v.density, v.hardness, v.hardness_system, v.cost, v.cost_usa, v.currency
FROM (VALUES
${values.join(',\n')}
) AS v(material, material_grade, material_specification, material_type, material_group,
       density_kg_m3, density, hardness, hardness_system, cost, cost_usa, currency)
WHERE NOT EXISTS (
  SELECT 1 FROM raw_materials rm WHERE rm.material = v.material
);

NOTIFY pgrst, 'reload schema';

-- Verify (run manually after):
--   SELECT count(*) FROM raw_materials WHERE material_group = 'Sand Casting';   -- expect the number of inserted rows
--   Skipped by name collision: names in the source that already existed before this ran.
`;

fs.writeFileSync(OUT, sql, 'utf8');
console.log(`Wrote ${path.relative(ROOT, OUT)}: ${rows.length} raw materials`);
