// Generator: stages the real Injection Molding "foamingAgents" lookup-table
// export (memory/plastic modeling/lookup/foamingAgents.json — 26 real
// chemical blowing agent x compatible-material-type records for
// Structural Foam Molding, each with a real cost per kg and real dosage
// percentage of shot weight) into im_reference_data category='lookup_table'
// — same shape and staging-only discipline as migrations 651-661.
//
// key = "<agent_name>_<material_type>" (composite — agent_name repeats
// across every material it's compatible with, e.g. "Azodicarbonamide" is
// listed for ABS/Acetal/Acrylic/PBT/PET/Polypropylene/Polystyrene/PPS),
// value = cost_cfa_usd_per_kg, unit_type = 'Currency/kg', raw = full
// source record (incl. percent_cfa dosage).
//
// NOT wired into any cost calculation here. Confirmed: no foaming-agent
// cost line item exists anywhere in the Structural Foam Molding costing
// path (cost-compression-molding-engine.ts, the closest real file, has
// none) — same genuine capability gap as colorant cost (migration 653):
// there is no existing hardcode to replace, this is a net-new cost factor
// that would need explicit wiring, not a bug fix. Staged per the user's
// "give lookup tables one by one, combine once they've all arrived"
// sequencing (2026-09-03).
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const AGENTS_FILE = path.join(__dirname, '../../../memory/plastic modeling/lookup/foamingAgents.json');
const OUT_SQL = path.join(__dirname, '../662_seed_im_lookup_foaming_agents.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(AGENTS_FILE, 'utf8'));

const rows = data.records.map((r) => ({
  category: 'lookup_table',
  key: `${r.agent_name}_${r.material_type}`,
  value: String(r.cost_cfa_usd_per_kg),
  unit_type: 'Currency/kg',
  notes: `Chemical foaming agent for ${r.material_type} — dosage ${(r.percent_cfa * 100).toFixed(2)}% of shot weight`,
  raw: r,
}));

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 662: Seed im_reference_data category = 'lookup_table'
-- (foaming agents) — schema: migration 636
--
-- Generated by gen_662_seed_im_lookup_foaming_agents.js.
-- Row count: ${rows.length} (memory/plastic modeling/lookup/foamingAgents.json).
--
-- NOT wired into any cost calculation — staging only. See the generator
-- script header — genuine capability gap (no foaming-agent cost line item
-- exists anywhere today), not a hardcode to replace.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
