// Generator: stages the real Machining "operations_full.json" export
// (memory/machining/operations_full.json — 1174 real machining operation
// records, each a compound "<Process Name>:<Operation Name>//<Feature
// Type>" string, e.g. "5 Axis Mill:Finish Milling//PlanarFace",
// "Wire EDM:Wire Cutting//SimpleHole" — same "<Process>:<Operation>//
// <FeatureType>" taxonomy shape as Sheet Metal's own process_operations.json,
// per this repo's CLAUDE.md) into machining_reference_data (migration
// 638's schema) category='operation' — same shape and staging-only
// discipline as this whole reference-data-staging effort.
//
// key = the full compound processName string (confirmed unique across
// all 1174 real records), value = NULL (source has no separate value
// field for this table — it is a taxonomy list, not a parameter table),
// notes = source notes (blank for every row per the source file's own
// warnings block — preserved as NULL rather than fabricated), raw = full
// source record.
//
// Two real data-quality caveats are carried verbatim from the source
// file's own "warnings" array into this migration's header (not
// silently dropped, not fabricated around): (1) a documented capture
// gap for "3 Axis Bar Feed Lathe with Sub Spindle" between "Plunging//
// Ring" and "Slide Machining//SlideBundle" — some intermediate rows were
// not captured from the source screenshots; (2) every row's Notes field
// is genuinely blank in the source, not a staging omission.
//
// Real machining operation taxonomy — the CNC/manual-machining
// counterpart to migration 689's process catalog. NOT wired into any
// cost calculation here — staging only, same discipline as every prior
// reference-data migration.
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const OPS_FILE = path.join(__dirname, '../../../memory/machining/operations_full.json');
const OUT_SQL = path.join(__dirname, '../690_seed_machining_operations.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(OPS_FILE, 'utf8'));

const rows = data.operations.map((r) => {
  return {
    category: 'operation',
    key: r.processName,
    value: null,
    unit_type: null,
    notes: r.notes || null,
    raw: r,
  };
});

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const warningsBlock = (data.warnings || []).map((w) => `-- - ${w}`).join('\n');

const sql = `-- ============================================================================
-- Migration 690: Seed machining_reference_data category = 'operation'
-- (schema: migration 638)
--
-- Generated by gen_690_seed_machining_operations.js.
-- Row count: ${rows.length} (memory/machining/operations_full.json).
--
-- Source-file warnings, carried verbatim (not silently dropped):
${warningsBlock}
--
-- NOT wired into any cost calculation — staging only. Real machining
-- operation taxonomy (<Process>:<Operation>//<FeatureType>), the
-- CNC/manual-machining counterpart to migration 689's process catalog.
-- ============================================================================

INSERT INTO machining_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
