// Generator: stages the FULL raw JSON of all 127 real Injection Molding
// machines (the same memory/Injection/machine/*.json files migration 633
// staged into mhr_records) into im_reference_data category='machine' —
// the Injection Molding equivalent of sm_reference_data's own 'machine'
// category (migration 479), which powers the HR Rates "Edit MHR Record"
// dialog's read-only "Machine & Process Lookup" panel
// (mhr.service.ts#getReferenceDetail).
//
// Migration 633 never staged this lossless copy — it only wrote the
// columns mhr_records actually needs for costing, not the full per-machine
// JSON. getReferenceDetail() only ever queried sm_reference_data, so every
// Injection Molding machine's lookup panel showed "No machine_library
// reference match found" — confirmed live 2026-09-03. This migration
// supplies the missing data; a companion backend change
// (mhr.service.ts#getReferenceDetail) adds the im_reference_data fallback
// query.
//
// `raw` is the untouched, unflattened original machine object (accounting/
// time/rates/limits/other/yields/machine/bottomUpOverheadRateInputs/
// manufacturerInformation nesting preserved) — the frontend's
// groupMachineLibraryDetail() already recursively flattens this shape for
// display (lib/utils/machineLibraryDetail.ts, same change).
//
// key = "<machine_class>:<machine name>", mirroring sm_reference_data's own
// "<category-prefix>:<name>" convention for this same 'machine' category.
// value = machinePriceUsd (a representative real number, same convention
// as existing 'machine'-category rows using price as their headline value).

const fs = require('fs');
const path = require('path');

const MACHINE_DIR = path.join(__dirname, '../../../memory/Injection/machine');
const OUT_SQL = path.join(__dirname, '../648_stage_im_machine_reference_detail.sql');

const FILES = [
  { file: 'injection_molding_machines.json', machineClass: 'injection_molding', label: 'Injection Molding' },
  { file: 'compression_molding_machines.json', machineClass: 'compression_molding', label: 'Compression Molding' },
  { file: 'structural_foam_molding_machines.json', machineClass: 'structural_foam_molding', label: 'Structural Foam Molding' },
  { file: 'reaction_injection_molding_machines.json', machineClass: 'reaction_injection_molding', label: 'Reaction Injection Molding' },
];

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

// Every real machine's manufacturerInformation.dataSource names the
// original tool ("aPriori Baseline") verbatim — per this project's
// standing rule (never name the licensed third-party reference-data
// source in code, comments, migrations, or DB values), rebranded to
// "eMithran" before staging.
function sanitize(v) {
  if (typeof v === 'string') return v.replace(/aPriori/g, 'eMithran');
  if (Array.isArray(v)) return v.map(sanitize);
  if (v && typeof v === 'object') {
    const out = {};
    for (const [k, val] of Object.entries(v)) out[k] = sanitize(val);
    return out;
  }
  return v;
}

const rows = [];

for (const { file, machineClass, label } of FILES) {
  const data = JSON.parse(fs.readFileSync(path.join(MACHINE_DIR, file), 'utf8'));
  const machines = data.machines || [];
  for (const m of machines) {
    const name = m.name || m.primaryId;
    if (!name) continue;
    rows.push({
      key: `${machineClass}:${name}`,
      value: m.machine?.machinePriceUsd != null ? String(m.machine.machinePriceUsd) : null,
      unit_type: 'Currency',
      notes: `${label} reference spec`,
      raw: sanitize(m),
    });
  }
}

const valuesSql = rows.map((r) => {
  return `('machine', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 648: Stage full raw JSON of 127 real Injection Molding machines
-- into im_reference_data category='machine' (schema: migration 636)
--
-- Generated by gen_648_stage_im_machine_reference_detail.js.
-- Row count: ${rows.length}.
--
-- Powers the HR Rates "Edit MHR Record" dialog's read-only "Machine &
-- Process Lookup" panel for Injection Molding machines — see
-- mhr.service.ts#getReferenceDetail's new im_reference_data fallback.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
