#!/usr/bin/env node
// Generates migration 847: the Casting processes and operations in the Process
// page catalog (process_taxonomy + process_taxonomy_operations +
// process_calculator_mappings), from memory/Casting/Processes. Same rules as
// gen_844 (Die Casting):
//   * Every process in processes.csv; every Process:Operation//Feature string
//     in operations.csv whose first segment is one of those processes.
//   * No casting cost engine exists: roadmap_status 'not_modeled', mapping rows
//     INACTIVE; machine_class is set by migration 848 from the machine files.
//   * No Cost Feature is non_mfg; User-Defined Process (a UI placeholder) is
//     skipped.
// operations.csv also lists operation-level entries that name no process
// ("HoleInsertCoring", "CO2CuredHoleCoring:As Cast//Edge", "Green Sand", ...).
// They cannot be attached to a catalog process without guessing, so they are
// not in the catalog; migration 849 stages every row of the file, and they are
// listed in this migration's header.
//
// Run: node backend/migrations/scripts/gen_847_seed_casting_process_catalog.js

const fs = require('fs');
const path = require('path');
const { readCsv } = require('./lib/memory-machine-seed');

const ROOT = path.resolve(__dirname, '..', '..', '..');
const SRC = path.join(ROOT, 'memory', 'Casting', 'Processes');
const OUT = path.join(__dirname, '..', '847_seed_casting_process_catalog.sql');
const GROUP = 'Casting';
const FIRST_ORDER = 2100;

const SKIP_PROCESS = new Set(['User-Defined Process']);
const NON_MFG = new Set(['No Cost Feature']);

const q = (s) => (s == null || String(s).trim() === '' ? 'NULL' : `$str$${String(s).trim()}$str$`);

function parseCompound(raw) {
  const segments = raw.split(':');
  const levels = segments.slice(1).map((seg) => {
    const i = seg.indexOf('//');
    return i === -1 ? { operation: seg, feature: null } : { operation: seg.slice(0, i), feature: seg.slice(i + 2) };
  });
  const leaf = levels[levels.length - 1] || { operation: null, feature: null };
  return { process: segments[0], category: leaf.operation, feature: leaf.feature };
}

const processRows = [];
const seen = new Set();
const skipped = [];
let order = FIRST_ORDER;
for (const r of readCsv(path.join(SRC, 'processes.csv')).rows) {
  const name = r['Process Name'] == null ? null : String(r['Process Name']);
  if (!name) continue;
  if (SKIP_PROCESS.has(name)) { skipped.push(name); continue; }
  if (seen.has(name)) throw new Error(`processes.csv: duplicate process ${name}`);
  seen.add(name);
  processRows.push({
    name,
    machine: r['Default Machine'],
    shop: r['Default Tool Shop Name'],
    order: order++,
    roadmap: NON_MFG.has(name) ? 'non_mfg' : 'not_modeled',
  });
}

const operationRows = [];
const unattached = [];
const seenRaw = new Set();
for (const r of readCsv(path.join(SRC, 'operations.csv')).rows) {
  const raw = r['Process Name'] == null ? null : String(r['Process Name']);
  if (!raw) continue;
  if (seenRaw.has(raw)) throw new Error(`operations.csv: duplicate ${raw}`);
  seenRaw.add(raw);
  const p = parseCompound(raw);
  if (!seen.has(p.process)) { unattached.push(raw); continue; }
  operationRows.push({ ...p, raw });
}

const perProcess = processRows.map((p) => `--   ${p.name.padEnd(26)} ${String(operationRows.filter((o) => o.process === p.name).length).padStart(3)} operation(s)  default machine ${p.machine ?? '-'}${p.roadmap === 'non_mfg' ? '  (non_mfg)' : ''}`).join('\n');
const wrap = (items) => {
  const lines = []; let cur = '';
  for (const it of items) { if ((cur + it).length > 70 && cur) { lines.push(cur); cur = ''; } cur += (cur ? '; ' : '') + it; }
  if (cur) lines.push(cur);
  return lines.map((l) => `--     ${l}`).join('\n');
};

const sql = `-- ============================================================================
-- Migration 847: Casting processes and operations in the Process catalog
-- ============================================================================
-- Generated by scripts/gen_847_seed_casting_process_catalog.js -- do not
-- hand-edit, re-run the generator and diff instead.
--
-- Source: memory/Casting/Processes/processes.csv (processes, default machine,
-- default tool shop) and operations.csv (Process:Operation//Feature).
-- Process group "${GROUP}": ${processRows.length} processes, ${operationRows.length} operation rows.
${perProcess}
--   skipped: ${skipped.join(', ') || 'none'} (UI placeholder, no data)
--
-- ${unattached.length} operations.csv rows name no process (operation-level entries);
-- not in the catalog, staged with every other row by migration 849:
${wrap(unattached)}
--
-- No casting cost engine exists yet: roadmap_status not_modeled and the mapping
-- rows INACTIVE (shape of 790/824, 844). machine_class is set by migration 848.
-- Run 847, then 848, then 849. One transaction, idempotent.
-- ============================================================================

BEGIN;

INSERT INTO process_taxonomy (process_group, process_name, machine_class, roadmap_status, default_machine_name, default_tool_shop_name, display_order)
VALUES
${processRows.map((r) => `  (${q(GROUP)}, ${q(r.name)}, NULL, '${r.roadmap}', ${q(r.machine)}, ${q(r.shop)}, ${r.order})`).join(',\n')}
ON CONFLICT (process_group, process_name) DO UPDATE
SET default_machine_name = COALESCE(process_taxonomy.default_machine_name, EXCLUDED.default_machine_name),
    default_tool_shop_name = COALESCE(process_taxonomy.default_tool_shop_name, EXCLUDED.default_tool_shop_name);

INSERT INTO process_taxonomy_operations (canonical_process_id, operation_category, feature_type, raw_compound_string)
SELECT pt.id, v.operation_category, v.feature_type, v.raw
FROM process_taxonomy pt
JOIN (VALUES
${operationRows.map((o) => `  (${q(o.process)}, ${q(o.category)}, ${q(o.feature)}, ${q(o.raw)})`).join(',\n')}
) AS v(proc, operation_category, feature_type, raw)
  ON pt.process_group = ${q(GROUP)} AND pt.process_name = v.proc
ON CONFLICT (canonical_process_id, raw_compound_string) DO NOTHING;

INSERT INTO process_calculator_mappings (process_group, process_route, operation, calculator_id, calculator_name, is_active, display_order, machine_class, canonical_process_id)
SELECT ${q(GROUP)}, v.name, v.name, NULL, NULL, false, v.display_order, NULL, pt.id
FROM process_taxonomy pt
JOIN (VALUES
${processRows.map((r) => `  (${q(r.name)}, ${r.order})`).join(',\n')}
) AS v(name, display_order)
  ON pt.process_group = ${q(GROUP)} AND pt.process_name = v.name
WHERE NOT EXISTS (
  SELECT 1 FROM process_calculator_mappings m WHERE m.process_group = ${q(GROUP)} AND m.operation = v.name
)
ON CONFLICT (process_group, process_route, operation) DO NOTHING;

COMMIT;

NOTIFY pgrst, 'reload schema';

-- Verify (expect ${processRows.length} processes, ${operationRows.length} operations):
-- SELECT pt.process_name, count(o.id) AS operations FROM process_taxonomy pt
--   LEFT JOIN process_taxonomy_operations o ON o.canonical_process_id = pt.id
--   WHERE pt.process_group = '${GROUP}' GROUP BY 1 ORDER BY 1;
`;
fs.writeFileSync(OUT, sql, 'utf8');
console.log(`Wrote ${path.relative(ROOT, OUT)}: ${processRows.length} processes, ${operationRows.length} operations, ${unattached.length} unattached, skipped ${skipped.join(', ')}`);
