// Generator: stages the real Injection Molding "adviceRules" lookup-table
// export (memory/plastic modeling/lookup/adviceRules.json — 22 named DFM
// advice/check rules, each just a name + enabled flag, no threshold values
// in this export) into im_reference_data category='lookup_table' — the
// Injection Molding equivalent of Sheet Metal's own advice-rules staging
// (migration 483, sm_reference_data category='lookup_table'), same shape:
// key = rule name, value = 'true'/'false' from `enabled`, raw =
// {adviceRuleName, enabled} (camelCase, normalized from the source file's
// own `advice_rule_name` field to match 483's established raw-JSONB
// convention for this exact category).
//
// NOT promoted into any live DFM-consuming table here — same deliberate
// staging-only scope as migration 483 (see that migration's own header:
// this app's live DFM scoring, dfm-scoring.service.ts, does not read
// dfm_rules_library at all today; promotion is a separate, later, reviewed
// decision once a real consumer needs it).
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const RULES_FILE = path.join(__dirname, '../../../memory/plastic modeling/lookup/adviceRules.json');
const OUT_SQL = path.join(__dirname, '../651_seed_im_lookup_advice_rules.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(RULES_FILE, 'utf8'));

const rows = data.advice_rules.map((r) => ({
  category: 'lookup_table',
  key: r.advice_rule_name,
  value: String(r.enabled),
  unit_type: null,
  notes: 'DFM advice-rule toggle (name + enabled flag only, no threshold in this export)',
  raw: { adviceRuleName: r.advice_rule_name, enabled: r.enabled },
}));

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 651: Seed im_reference_data category = 'lookup_table'
-- (advice rules) — schema: migration 636
--
-- Generated by gen_651_seed_im_lookup_advice_rules.js.
-- Row count: ${rows.length} (memory/plastic modeling/lookup/adviceRules.json).
--
-- NOT promoted into any live DFM-consuming table — staging only. See the
-- generator script header for why, same deliberate scope as migration 483.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
