// Generator: self-sufficient seed of process_taxonomy_operations (the
// 1174-row real "<Station>:<Operation>//<FeatureType>" children from
// memory/machining/operations_full.json), superseding reliance on
// migration 690/691 having previously run.
//
// Migration 691 already carried this exact INSERT (same parsing logic,
// parseCompoundOperationString, copied verbatim from
// gen_691_seed_machining_process_taxonomy_and_mappings.js), but 691 turned
// out to have never actually run against the live DB (confirmed live,
// 2026-09-16: migration 753 -- a from-scratch re-seed of process_taxonomy +
// process_calculator_mappings, the same two tables 691 also targets --
// was necessary before the Process Calculator Mappings page showed any
// Machining rows at all). This migration closes the same gap for
// process_taxonomy_operations specifically, which 753 deliberately left
// out of scope (see 753's own header) since it wasn't what the immediately
// visible page bug needed.
//
// Split into size-bounded parts (same convention as migrations 739-751 for
// the oversized lookup-table staging) because a 1174-row single INSERT is
// likely to hit the same "Query is too large to be run via the SQL
// Editor" limit that forced that split.
//
// Offline, file-in/file-out -- matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const OPS_FILE = path.join(__dirname, '../../../memory/machining/operations_full.json');
const OUT_DIR = path.join(__dirname, '..');
const MIGRATION_BASE_NUM = 754;
const PART_SIZE_LIMIT_BYTES = 200_000;

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}

// Verbatim copy of gen_691's parser -- same real logic, not reimplemented.
function parseCompoundOperationString(raw) {
  const segments = raw.split(':');
  const process = segments[0];
  const levels = segments.slice(1).map((seg) => {
    const slashIdx = seg.indexOf('//');
    return slashIdx === -1
      ? { operation: seg, feature: null }
      : { operation: seg.slice(0, slashIdx), feature: seg.slice(slashIdx + 2) };
  });
  const leaf = levels[levels.length - 1] || { operation: null, feature: null };
  return { process, operationCategory: leaf.operation, featureType: leaf.feature };
}

const opsData = JSON.parse(fs.readFileSync(OPS_FILE, 'utf8'));

const rows = opsData.operations.map((o) => {
  const { process, operationCategory, featureType } = parseCompoundOperationString(o.processName);
  const valueSql = `(${sqlStr(process)}, ${sqlStr(operationCategory)}, ${sqlStr(featureType)}, ${sqlStr(o.processName)})`;
  return { valueSql, size: Buffer.byteLength(valueSql, 'utf8') };
});

console.log('total operation rows parsed:', rows.length);

// Greedy batching in original file order, same pattern as gen_739.
const parts = [];
let current = [];
let currentSize = 0;
for (const r of rows) {
  if (current.length > 0 && currentSize + r.size > PART_SIZE_LIMIT_BYTES) {
    parts.push(current);
    current = [];
    currentSize = 0;
  }
  current.push(r);
  currentSize += r.size;
}
if (current.length > 0) parts.push(current);

const totalParts = parts.length;
const writtenFiles = [];

parts.forEach((partRows, i) => {
  const partNum = i + 1;
  const migrationNum = MIGRATION_BASE_NUM + i;
  const fileName = totalParts === 1
    ? `${migrationNum}_seed_machining_process_taxonomy_operations.sql`
    : `${migrationNum}_seed_machining_process_taxonomy_operations_part${partNum}of${totalParts}.sql`;
  const outPath = path.join(OUT_DIR, fileName);

  const valuesSql = partRows.map((r) => `  ${r.valueSql}`).join(',\n');

  const sql = `-- ============================================================================
-- Migration ${migrationNum}: Seed process_taxonomy_operations (real Machining
-- operation/feature-type children, memory/machining/operations_full.json)
-- -- part ${partNum} of ${totalParts} (${partRows.length} of ${rows.length} total rows)
--
-- Generated by gen_754_seed_machining_process_taxonomy_operations.js.
-- Self-sufficient: does not depend on migration 690/691 having run (both
-- appear never to have executed against the live DB -- see migration 753's
-- own header for how that was confirmed). Depends only on migration 753
-- having already run (needs the real process_taxonomy rows it seeds, to
-- resolve canonical_process_id via the join below).
--
-- Same parseCompoundOperationString logic as migration 691's own generator
-- (copied verbatim, not reimplemented) -- splits each real
-- "<Station>:<Operation>//<FeatureType>" compound string into station name
-- (joined against process_taxonomy.process_name), leaf operation_category,
-- and leaf feature_type, keeping the full original string in
-- raw_compound_string so nothing is lost.
-- ============================================================================

INSERT INTO process_taxonomy_operations (canonical_process_id, operation_category, feature_type, raw_compound_string)
SELECT pt.id, v.operation_category, v.feature_type, v.raw
FROM process_taxonomy pt
JOIN (VALUES
${valuesSql}
) AS v(process_name, operation_category, feature_type, raw)
  ON pt.process_group = 'Machining' AND pt.process_name = v.process_name
ON CONFLICT (canonical_process_id, raw_compound_string) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

  fs.writeFileSync(outPath, sql, 'utf8');
  writtenFiles.push({ fileName, rows: partRows.length, bytes: Buffer.byteLength(sql, 'utf8') });
});

console.log(`Wrote ${rows.length} rows across ${totalParts} parts:`);
for (const f of writtenFiles) {
  console.log(`  ${f.fileName} -- ${f.rows} rows, ${(f.bytes / 1024).toFixed(1)} KB`);
}
