// Generator: stages the real Injection Molding "cmStandardToolingComponents"
// lookup-table export (memory/plastic modeling/lookup/cmStandardToolingComponents.json
// — 10 real standard mold tooling components with real unit costs and
// default quantities: guide pins/bushings, ejector pins, ejector guide pin
// bushings, return pins, hydraulic cylinders, side locks, limit switches,
// air poppets) into im_reference_data category='lookup_table' — same shape
// and staging-only discipline as migrations 651-654.
//
// key = name, value = unit_cost_usd (NULL for the one row with no cost —
// "Electrical Connection Or Switch", explicitly noted as included in
// machine price, not a separate tooling line item), raw = full source
// record (incl. default quantity and notes).
//
// NOT wired into any cost calculation here. Real relevance to an already-
// open finding: cost-injection-molding-engine.ts's SPI_MOLD_CLASSES.
// baseCostUsd values ($50k/$25k/$12k/$5k/$1.5k per class) are uncited flat
// numbers with no component breakdown -- this table gives a real,
// itemized alternative build-up (e.g. Side Lock + Hydraulic Cylinder +
// Limit Switch qty 4 each map directly to undercutCount-driven slide/
// lifter mechanisms, a signal this engine already tracks). Still missing
// before that rebuild is possible: the base mold plate/steel cost itself
// (the largest single component) and the mold-base-area methodology
// (open question from migration 654's cmMoldBaseDesignHours staging,
// pending the user's real formula/source). Staged now per the user's own
// "give lookup tables one by one, wire everything once they've all
// arrived" sequencing (2026-09-03) -- not wired piecemeal.
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const COMPONENTS_FILE = path.join(__dirname, '../../../memory/plastic modeling/lookup/cmStandardToolingComponents.json');
const OUT_SQL = path.join(__dirname, '../655_seed_im_lookup_standard_tooling_components.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(COMPONENTS_FILE, 'utf8'));

const rows = data.records.map((r) => ({
  category: 'lookup_table',
  key: r.name,
  value: r.unit_cost_usd != null ? String(r.unit_cost_usd) : null,
  unit_type: 'Currency',
  notes: r.notes || `Default quantity: ${r.quantity ?? 'calculated in cost model'}`,
  raw: r,
}));

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 655: Seed im_reference_data category = 'lookup_table'
-- (standard tooling components) — schema: migration 636
--
-- Generated by gen_655_seed_im_lookup_standard_tooling_components.js.
-- Row count: ${rows.length} (memory/plastic modeling/lookup/cmStandardToolingComponents.json).
--
-- NOT wired into any cost calculation — staging only. See the generator
-- script header for how this relates to the open SPI_MOLD_CLASSES
-- citation gap and the pending mold-base-area methodology.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
