// Generator: stages the real Injection Molding "tblStandardMoldBaseSizes"
// lookup-table export (memory/plastic modeling/lookup/tblStandardMoldBaseSizes.json
// — 127 real, named standard mold base sizes across both USA (inch) and
// Europe (mm) mold-base systems, each with real Actual Width/Length and
// real Effective Window Width/Length — the usable cavity area within the
// standard plate — plus overhanging clamping plate dimensions for the
// Europe system) into im_reference_data category='lookup_table' — same
// shape and staging-only discipline as migrations 651-682.
//
// key = Mold Base Name (e.g. '18X24', '296X446' — unique per source row;
// a small number of USA names repeat across genuinely different window
// sizes, given a numeric suffix to stay unique), value = Actual Width,
// raw = full source record (Actual Length, Effective Window W/L,
// Mold Base System, overhanging clamping plate dims).
//
// This is the real, authoritative answer to the "how is mold base area
// determined" question this batch of lookup tables has been building
// toward (migrations 654/656/664/670/671/673/674/679): real industry
// practice is NOT a continuously-computed area — it is SELECTING the
// smallest standard mold base whose Effective Window fits the required
// cavity-layout footprint (cavity block + edge borders), then using that
// mold base's own real Actual Width x Length as "mold base area" for the
// design-hours/operator-count/etc. lookups. NOT wired into any cost
// calculation here — same "combine once all lookup tables have arrived"
// sequencing as every prior lookup_table migration this batch.
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const SIZES_FILE = path.join(__dirname, '../../../memory/plastic modeling/lookup/tblStandardMoldBaseSizes.json');
const OUT_SQL = path.join(__dirname, '../683_seed_im_lookup_standard_mold_base_sizes.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(SIZES_FILE, 'utf8'));

const seenKeys = new Map();
const rows = data.records.map((r) => {
  let key = r['Mold Base Name'];
  const dupCount = (seenKeys.get(key) ?? 0) + 1;
  seenKeys.set(key, dupCount);
  if (dupCount > 1) key = `${key}_v${dupCount}`;

  return {
    category: 'lookup_table',
    key,
    value: String(r['Actual Width']),
    unit_type: r['Reference Uom'],
    notes: `${r['Mold Base System']} standard mold base, ${r['Reference Size']} ${r['Reference Uom']} — effective window ${r['Effective Window Width']} x ${r['Effective Window Length']}`,
    raw: r,
  };
});

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 683: Seed im_reference_data category = 'lookup_table'
-- (standard mold base sizes) — schema: migration 636
--
-- Generated by gen_683_seed_im_lookup_standard_mold_base_sizes.js.
-- Row count: ${rows.length} (memory/plastic modeling/lookup/tblStandardMoldBaseSizes.json).
--
-- NOT wired into any cost calculation — staging only. See the generator
-- script header — the real, authoritative answer to the mold-base-area
-- question this batch has been building toward.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
