// Generator: stages the real Injection Molding "cmMoldBaseDesignHours"
// lookup-table export (memory/plastic modeling/lookup/cmMoldBaseDesignHours.json
// — 14 real (mold_base_area_mm2 -> base_design_hrs_hr) breakpoints, a
// monotonic step function used to estimate mold-base engineering design
// labor hours from mold size) into im_reference_data category=
// 'lookup_table' — same shape and staging-only discipline as migrations
// 651/652/653.
//
// key = base_design_hrs_hr (as string, since mold_base_area_mm2 is the
// varying breakpoint and multiple rows could theoretically share an hours
// value — using the area breakpoint as key instead, formatted to avoid
// float-string collisions), value = mold_base_area_mm2 (the breakpoint,
// so a consumer can find "hours for area <= X"), raw = full source record.
//
// NOT wired into the live tooling-cost engine here. Confirmed 2026-09-03:
// a real hourly rate to pair with these hours DOES exist
// (digitalFactory_aPrioriUSA.settings.designRateUsdPerHr = $64.73/hr,
// already staged as im_reference_data category='rate_profile' by migration
// 637) — but computing this table's OTHER axis, the actual mold base area
// for a specific part/mold, has no cited real formula anywhere in this
// app's data today (no "mold base length x width" is tracked per BOM item,
// and no sourced cavity-layout-to-mold-base-area rule exists the way
// estimateRunnerVolumeCm3's cited SPI runner-sizing rule does). Wiring the
// dollar cost requires that decision first — see cost-injection-molding-
// engine.ts's SPI_MOLD_CLASSES section for the related open finding
// (baseCostUsd values there are also uncited).
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const HOURS_FILE = path.join(__dirname, '../../../memory/plastic modeling/lookup/cmMoldBaseDesignHours.json');
const OUT_SQL = path.join(__dirname, '../654_seed_im_lookup_mold_base_design_hours.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(HOURS_FILE, 'utf8'));

const rows = data.records.map((r) => ({
  category: 'lookup_table',
  key: `area_${r.mold_base_area_mm2}`,
  value: String(r.base_design_hrs_hr),
  unit_type: 'hr',
  notes: `Base mold-design engineering hours for mold base area <= ${r.mold_base_area_mm2} mm^2`,
  raw: r,
}));

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 654: Seed im_reference_data category = 'lookup_table'
-- (mold base design hours) — schema: migration 636
--
-- Generated by gen_654_seed_im_lookup_mold_base_design_hours.js.
-- Row count: ${rows.length} (memory/plastic modeling/lookup/cmMoldBaseDesignHours.json).
--
-- NOT wired into any cost calculation — staging only. See the generator
-- script header for the specific open question (mold base area
-- methodology) blocking live wiring.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
