// Generator: stages the real Injection Molding "cmToolTexture" lookup-table
// export (memory/plastic modeling/lookup/cmToolTexture.json — 4 real
// texture-complexity tiers with real cost/time multipliers: None=0,
// Fine-Shallow=0.5, Moderate-Medium=0.9, Coarse-Deep=1.0) into
// im_reference_data category='lookup_table' — same shape and staging-only
// discipline as migrations 651-659.
//
// key = texture tier name, value = multiplier, raw = full source record.
//
// Connects migration 652's cavityTextures (26 real specific texture
// patterns, e.g. Mold-Tech A/B/C/D with real depths + SPI equivalents) to
// migration 658's "Coarse Texture Finishing" rate (15500 S/m^2) — this
// multiplier scales that finishing rate by how aggressive a given
// texture's complexity tier is. NOT wired into any cost calculation
// here — same "combine once all lookup tables have arrived" sequencing
// as every prior lookup_table migration this batch.
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const TEXTURE_FILE = path.join(__dirname, '../../../memory/plastic modeling/lookup/cmToolTexture.json');
const OUT_SQL = path.join(__dirname, '../660_seed_im_lookup_tool_texture_multiplier.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(TEXTURE_FILE, 'utf8'));

const rows = data.records.map((r) => ({
  category: 'lookup_table',
  key: r.texture,
  value: String(r.multiplier),
  unit_type: null,
  notes: 'Texture-finishing cost/time complexity multiplier',
  raw: r,
}));

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 660: Seed im_reference_data category = 'lookup_table'
-- (tool texture multiplier) — schema: migration 636
--
-- Generated by gen_660_seed_im_lookup_tool_texture_multiplier.js.
-- Row count: ${rows.length} (memory/plastic modeling/lookup/cmToolTexture.json).
--
-- NOT wired into any cost calculation — staging only. See the generator
-- script header for how this connects migrations 652 and 658.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
