// Generator: stages the real Injection Molding "plasticizingRateByClampForce"
// lookup-table export (memory/plastic modeling/lookup/plasticizingRateByClampForce.json
// — 24 real (clamp_force_kn -> plasticizing_rate_g_s) breakpoints: real
// screw plasticizing/recovery rate as a function of machine clamp force)
// into im_reference_data category='lookup_table' — same shape and
// staging-only discipline as migrations 651-667.
//
// key = clamp_force_kn breakpoint (as string), value =
// plasticizing_rate_g_s, unit_type = 'g/s', raw = full source record.
//
// Real relevance: the 127 real machine records (migration 633) DO carry a
// real per-machine rates.plasticizingRateGppsGPerS field in their source
// JSON, but migration 633's column list never staged it into mhr_records
// (confirmed absent) — this table is a real fallback/estimation path for
// any machine lacking that field, keyed by clamp force (mhr_records.
// max_tonnage x 9.80665, already staged). Also: cycle-time.ts's
// totalCycleSec (fillSec+packSec+coolSec+ejectSec) has no recovery/
// plasticizing term at all today — a real cycle typically overlaps screw
// recovery with cooling and takes whichever is longer, not a simple
// omission. NOT wired into any cost calculation here — same "combine once
// all lookup tables have arrived" sequencing as every prior lookup_table
// migration this batch.
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const RATE_FILE = path.join(__dirname, '../../../memory/plastic modeling/lookup/plasticizingRateByClampForce.json');
const OUT_SQL = path.join(__dirname, '../668_seed_im_lookup_plasticizing_rate.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(RATE_FILE, 'utf8'));

const rows = data.records.map((r) => {
  const clampKn = r['Clamp Force (kN)'];
  const rateGs = r['Plasticizing Rate (g / s)'];
  return {
    category: 'lookup_table',
    key: `clamp_kn_${clampKn}`,
    value: String(rateGs),
    unit_type: 'g/s',
    notes: `Plasticizing rate for clamp force <= ${clampKn} kN`,
    raw: { clamp_force_kn: clampKn, plasticizing_rate_g_s: rateGs },
  };
});

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 668: Seed im_reference_data category = 'lookup_table'
-- (plasticizing rate by clamp force) — schema: migration 636
--
-- Generated by gen_668_seed_im_lookup_plasticizing_rate.js.
-- Row count: ${rows.length} (memory/plastic modeling/lookup/plasticizingRateByClampForce.json).
--
-- NOT wired into any cost calculation — staging only. See the generator
-- script header — real fallback for machines lacking a real per-machine
-- plasticizing rate, and a currently entirely-missing cycle-time phase.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
