// Generator: stages the real Injection Molding "tblRunnerCalculationCoefficients"
// lookup-table export (memory/plastic modeling/lookup/tblRunnerCalculationCoefficients.json
// — 29 real runner-network branch-topology records, keyed by layout
// description (natural/artificial), cavity orientation + runner
// attachment side, and mold layout (e.g. "4x1", "8x2" — same cavity
// layouts as migration 664), each with up to 10 real per-branch cavity
// counts (branch1-branch10, the tree-structured runner network at
// successive branch levels from the sprue) and 4 real diameter-scaling
// coefficients (diameterCoeffBranch1-4 — the classic balanced-runner
// engineering principle: deeper branches carrying more combined melt flow
// need a proportionally larger diameter, values matching sqrt(2)~1.41,
// 2.0, 2*sqrt(2)~2.83)) into im_reference_data category='lookup_table' —
// same shape and staging-only discipline as migrations 651-679.
//
// key = "<layoutDescription>_<cavOrientationAndRunnerAttachmentSide>_<moldLayoutColumn>"
// (composite — moldLayoutColumn alone repeats across layout/orientation
// variants, e.g. "4x1" appears under both natural and artificial
// layouts), value = cavityNumber (the row's total cavity count, matching
// migration 664's own convention), raw = full source record with every
// real branch count and diameter coefficient preserved losslessly.
//
// This is the real, authoritative replacement for cost-injection-molding-
// engine.ts#estimateRunnerVolumeCm3's current generic
// Math.sqrt(cavityCount) "cavity_layout_factor" approximation (its own
// comment cites this as an "SPI rule of thumb") — migration 664 already
// flagged this gap; this table gives the actual branch-by-branch topology
// needed to compute a real total runner length/volume instead of a
// coarse approximation. NOT wired into any cost calculation here — same
// "combine once all lookup tables have arrived" sequencing as every prior
// lookup_table migration this batch.
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const RUNNER_FILE = path.join(__dirname, '../../../memory/plastic modeling/lookup/tblRunnerCalculationCoefficients.json');
const OUT_SQL = path.join(__dirname, '../680_seed_im_lookup_runner_calculation_coefficients.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(RUNNER_FILE, 'utf8'));

const rows = data.records.map((r) => {
  const key = `${r.layoutDescription}_${r.cavOrientationAndRunnerAttachmentSide}_${r.moldLayoutColumn}`;
  return {
    category: 'lookup_table',
    key,
    value: String(r.cavityNumber),
    unit_type: null,
    notes: `Runner branch topology: ${r.layoutDescription} layout, ${r.cavOrientationAndRunnerAttachmentSide}, ${r.moldLayoutColumn} (${r.cavityNumber} cavities)`,
    raw: r,
  };
});

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 680: Seed im_reference_data category = 'lookup_table'
-- (runner calculation coefficients) — schema: migration 636
--
-- Generated by gen_680_seed_im_lookup_runner_calculation_coefficients.js.
-- Row count: ${rows.length} (memory/plastic modeling/lookup/tblRunnerCalculationCoefficients.json).
--
-- NOT wired into any cost calculation — staging only. See the generator
-- script header — the real, authoritative replacement for
-- estimateRunnerVolumeCm3's Math.sqrt(cavityCount) approximation.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
