// Generator: stages the real "validationDisplayControls" lookup-table
// export (memory/plastic modeling/lookup/validationDisplayControls.json —
// 11 real source-tool UI panel-visibility records: Panel Name + a real
// yes/no Display flag for panels like "Blank Size", "Draw Direction",
// "Machining", "Routing", "Stock Form", "Tolerances", "Uncosted GCDs")
// into im_reference_data category='lookup_table' — same shape and
// staging-only discipline as migrations 651-685.
//
// This is the final lookup table in this batch (user-marked "final
// lookup").
//
// key = Panel Name, value = Display ('yes'/'no'), raw = full source
// record.
//
// Note: unlike every other table in this batch, this is source-tool UI
// chrome configuration (which validation panels that tool's own UI shows),
// not manufacturing/cost reference data — several panel names (Blank Size,
// Build Direction, Ram Direction, Stock Form) are Sheet-Metal/Machining
// concepts, not Injection Molding ones, confirming this table is generic
// across that source tool's domains rather than IM-specific. Staged
// losslessly for completeness per the batch's "stage everything handed
// over" discipline; genuinely NOT relevant to any eMithran cost
// calculation — no wiring implied or planned for this table.
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const CONTROLS_FILE = path.join(__dirname, '../../../memory/plastic modeling/lookup/validationDisplayControls.json');
const OUT_SQL = path.join(__dirname, '../686_seed_im_lookup_validation_display_controls.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(CONTROLS_FILE, 'utf8'));

const rows = data.records.map((r) => {
  const panel = r['Panel Name'];
  const display = r['Display'];
  return {
    category: 'lookup_table',
    key: panel,
    value: display,
    unit_type: 'boolean_flag',
    notes: `Source-tool UI panel visibility: ${panel} — display=${display}`,
    raw: r,
  };
});

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 686: Seed im_reference_data category = 'lookup_table'
-- (validation display controls — FINAL table in this lookup batch)
-- — schema: migration 636
--
-- Generated by gen_686_seed_im_lookup_validation_display_controls.js.
-- Row count: ${rows.length} (memory/plastic modeling/lookup/validationDisplayControls.json).
--
-- NOT wired into any cost calculation — staging only. Source-tool UI
-- chrome config, not manufacturing/cost reference data; no wiring
-- implied or planned for this table. See generator header for detail.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
