// Generator: stages the real Injection Molding "SPIFinishes" lookup-table
// export (memory/plastic modeling/lookup/SPIFinishes.json — the complete
// real SPI mold surface finish standard, As-Machined baseline plus SPI
// A1-D3, each with a real polishing labor hours/m^2 rate) into
// im_reference_data category='lookup_table' — same shape and staging-only
// discipline as migrations 651-668.
//
// key = Standard (e.g. 'SPI B2', 'None' for As-Machined), value =
// hrs per sq meter, unit_type = 'hr/m^2', raw = full source record.
//
// Directly completes migration 652's cavityTextures.spi_refinish field
// (real values like "SPI B2"/"SPI C2"/"SPI C3" reference exactly these
// standards) — this table gives the real polishing TIME rate for each
// grade. Distinct from migration 661's finishingHrsPerSqMeter (keyed by
// part surface area + Simple/Average/Complex complexity) and migration
// 658's "Coarse Texture Finishing" rate (textured, not polished, finish)
// — SPI A/B/C/D grades are the POLISHED (non-textured) surface finish
// spectrum, a separate real cost driver. NOT wired into any cost
// calculation here — same "combine once all lookup tables have arrived"
// sequencing as every prior lookup_table migration this batch.
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const FINISHES_FILE = path.join(__dirname, '../../../memory/plastic modeling/lookup/SPIFinishes.json');
const OUT_SQL = path.join(__dirname, '../669_seed_im_lookup_spi_finishes.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(FINISHES_FILE, 'utf8'));

const rows = data.records.map((r) => {
  const name = r['Finish Name'];
  const standard = r['Standard'];
  const hrsPerSqM = r['Hrs Per Sq Meter (hr / m^2)'];
  return {
    category: 'lookup_table',
    key: standard,
    value: String(hrsPerSqM),
    unit_type: 'hr/m^2',
    notes: name,
    raw: { finish_name: name, standard, hrs_per_sq_meter: hrsPerSqM },
  };
});

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 669: Seed im_reference_data category = 'lookup_table'
-- (SPI surface finishes) — schema: migration 636
--
-- Generated by gen_669_seed_im_lookup_spi_finishes.js.
-- Row count: ${rows.length} (memory/plastic modeling/lookup/SPIFinishes.json).
--
-- NOT wired into any cost calculation — staging only. See the generator
-- script header — completes migration 652's cavityTextures.spi_refinish
-- field with real polishing hour rates.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
