// Generator: stages the real Injection Molding "tblToolCoating" lookup-table
// export (memory/plastic modeling/lookup/tblToolCoating.json — 10 real mold
// tool-coating records, each with a real Coating Cost Factor (USD/kg) and a
// real Tool Life Improvement Factor, from "None" (1.0x, $0) through
// "DuplexVariantic" (14.4x life, $26.60/kg)) into im_reference_data
// category='lookup_table' — same shape and staging-only discipline as
// migrations 651-683.
//
// key = Coating Type, value = Tool Life Improvement Factor (the multiplier
// most directly relevant to the confirmed-wrong SPI_MOLD_CLASSES
// lifeShotRating figures from migration 682 — a coated tool changes real
// achievable shot life), unit_type = 'life_factor', raw = full source
// record (incl. Coating Cost Factor).
//
// No existing consumer in cost-injection-molding-engine.ts models tool
// coating at all today — a genuine capability gap, not a refinement of an
// existing formula. NOT wired into any cost calculation here — same
// "combine once all lookup tables have arrived" sequencing as every prior
// lookup_table migration this batch.
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const COATING_FILE = path.join(__dirname, '../../../memory/plastic modeling/lookup/tblToolCoating.json');
const OUT_SQL = path.join(__dirname, '../684_seed_im_lookup_tool_coating.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(COATING_FILE, 'utf8'));

const rows = data.records.map((r) => {
  const type = r['Coating Type'];
  const lifeFactor = r['Tool Life Improvement Factor'];
  const costFactor = r['Coating Cost Factor (USD / kg)'];
  return {
    category: 'lookup_table',
    key: type,
    value: String(lifeFactor),
    unit_type: 'life_factor',
    notes: `Tool coating: ${type} — life improvement ${lifeFactor}x, cost factor $${costFactor}/kg`,
    raw: r,
  };
});

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 684: Seed im_reference_data category = 'lookup_table'
-- (tool coating) — schema: migration 636
--
-- Generated by gen_684_seed_im_lookup_tool_coating.js.
-- Row count: ${rows.length} (memory/plastic modeling/lookup/tblToolCoating.json).
--
-- NOT wired into any cost calculation — staging only. Genuine capability
-- gap: no tool-coating cost/life modeling exists anywhere in this app today.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
