#!/usr/bin/env node
// Generates migration 826: seed mhr_records with every machine in
// memory/Heat treatment/Machine/*.csv (USA reference export), process_group
// Heat Treatment, and point each Heat Treatment process_taxonomy row
// (migration 792, machine_class NULL) at its class.
//
// Every Heat Treatment machine row names its own process ("Process Name"), so
// the class comes from that column, never from a file-to-process table. Most
// rows are priced services (Unit Weight Cost, Min Batch Cost / Weight,
// Certification Cost) with labour and overhead for handling; the virtual ovens
// and HIP furnaces are rated machines with a work envelope.
//
// Run: node backend/migrations/scripts/gen_826_seed_heat_treatment_mhr_records.js

const fs = require('fs');
const path = require('path');
const { readCsv, sqlStr, buildMachineRows, insertSql } = require('./lib/memory-machine-seed');

const ROOT = path.resolve(__dirname, '..', '..', '..');
const SRC = path.join(ROOT, 'memory', 'Heat treatment');
const OUT = path.join(__dirname, '..', '826_seed_heat_treatment_mhr_records.sql');
const GROUP = 'Heat Treatment';
const classOf = (process) => 'heat_treat_' + process.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '');

const wage = readCsv(path.join(SRC, 'wage_grade_associations.csv')).rows;
const gradeOf = (p) => wage.find((w) => w['Process Name'] === p)?.['Wage Grade Name'] ?? null;
const processes = readCsv(path.join(SRC, 'processes.csv')).rows.map((r) => String(r['Process Name']));

// Envelope columns where a file has one.
const ENVELOPE = {
  'machines_virtual_ovens.csv': ['Internal Length (mm)', 'Internal Width (mm)', 'Internal Height (mm)', null],
  'machines_hip_graphite_furnaces.csv': ['Hot Zone Length (mm)', 'Hot Zone Diameter (mm)', 'Hot Zone Diameter (mm)', null],
};

const files = fs.readdirSync(path.join(SRC, 'Machine')).filter((f) => f.endsWith('.csv')).sort().map((file) => ({
  file: path.join(SRC, 'Machine', file),
  rel: `Heat treatment/Machine/${file}`,
  category: null,
  categoryColumn: 'Process Name',
  classOf,
  gradeOf,
  envelope: ENVELOPE[file] ?? [null, null, null, null],
}));

const { columns, rows, report } = buildMachineRows(files, GROUP);
const seeded = [...new Set(files.flatMap((f) => readCsv(f.file).rows.map((r) => String(r['Process Name']))))].sort();
const unknown = seeded.filter((p) => !processes.includes(p));
if (unknown.length) throw new Error(`machine rows name processes not in processes.csv: ${unknown.join(', ')}`);
const noMachine = processes.filter((p) => !seeded.includes(p));
const catVals = seeded.map((p) => `  (${sqlStr(p)}, ${sqlStr(classOf(p))})`).join(',\n');

const sql = `-- ============================================================================
-- Migration 826: Seed mhr_records with the real Heat Treatment machines
-- ============================================================================
-- Generated by scripts/gen_826_seed_heat_treatment_mhr_records.js -- do not
-- hand-edit, re-run the generator and diff instead.
--
-- Source: memory/Heat treatment/Machine/*.csv (USA reference export). ${rows.length} machines
-- for ${seeded.length} processes; class heat_treat_<process>, each row its own "Process Name":
${report.map((r) => `--   ${path.basename(r.rel).padEnd(40)} ${String(r.n).padStart(2)} row(s)`).join('\n')}
--
-- Processes with no machine file in the reference (not seeded, disclosed):
--   ${noMachine.join(', ') || 'none'}
--
-- Priced-service columns (Unit Weight Cost, Min Batch Cost / Weight,
-- Certification Cost) and process-specific ones are kept verbatim in specs;
-- the heat-treatment engine prices from them. Row shape of 806/818/820/824
-- (scripts/lib/memory-machine-seed.js). Independent, idempotent statements.
-- ============================================================================

-- ── 1. Machines.
${insertSql(columns, rows)}

-- ── 2. Heat Treatment catalog rows (migration 792): machine_class, where still NULL.
UPDATE process_taxonomy pt
SET machine_class = v.machine_class
FROM (VALUES
${catVals}
) AS v(process_name, machine_class)
WHERE pt.process_group = '${GROUP}' AND pt.process_name = v.process_name AND pt.machine_class IS NULL;

UPDATE process_calculator_mappings pcm
SET machine_class = v.machine_class, updated_at = now()
FROM (VALUES
${catVals}
) AS v(operation, machine_class)
WHERE pcm.process_group = '${GROUP}' AND pcm.operation = v.operation AND pcm.machine_class IS NULL;

NOTIFY pgrst, 'reload schema';
`;
fs.writeFileSync(OUT, sql, 'utf8');
console.log(`Wrote ${path.relative(ROOT, OUT)}: ${rows.length} machines, processes ${seeded.join(', ')}`);
console.log(`no machine: ${noMachine.join(', ')}`);
