// ============================================================================
// Generator: Migration 784 — Multi-Spindle Machining materials
//
// Source: memory/Multi-Spindle Maching/Materials/materials_table.csv (105 real
// materials — cut_code, density, hardness, shear strength, per-stock-form
// costs: hex/rectangular/round bar, round tube, square bar).
//
// Two-step discipline, same as migration 590 (Sheet Metal raw materials) and
// 638/639 (Machining variables): Step 1 lands every row losslessly into
// machining_reference_data (category='material'), full original row
// preserved in .raw. Step 2 promotes a subset of columns into the live
// raw_materials table under material_group = 'Machining' (a new, additive
// group value — this domain has never had a materials master list staged
// before; the existing tblGeneralTurning/tblDrilling tables carry per-
// material *cutting physics* keyed by material_cut_code, not a density/cost/
// hardness master row).
//
// Deliberately NOT promoted:
//   - Hex/rectangular/round-tube/square-bar costs, and Round Bar cost beyond
//     the single representative `cost` column — no real consumer exists yet
//     for per-stock-form pricing in the Machining cost engine. Preserved
//     losslessly in .raw; promoting them to dedicated columns is a later,
//     separate decision once something actually reads them.
//   - Milling Speed / Turning Speed — every one of the 105 rows has these as
//     0.00 in the source file (checked directly: not a real value, a
//     genuinely empty column in the source export). Nothing real to
//     promote.
//
// Dedup: NOT EXISTS on exact `material` string match — same mechanical
// precedent as migration 590. Will not catch a differently-named duplicate
// of the same alloy under a different material_group (flagged, not solved
// here, matching 590's own disclosed gap).
// ============================================================================

const fs = require('fs');
const path = require('path');

const CSV_FILE = path.join(__dirname, '../../../memory/Multi-Spindle Maching/Materials/materials_table.csv');
const OUT_SQL = path.join(__dirname, '../784_seed_multi_spindle_machining_materials.sql');

function parseCsv(text) {
  const lines = text.replace(/^﻿/, '').split(/\r?\n/).filter((l) => l.length > 0);
  const header = splitCsvLine(lines[0]);
  return lines.slice(1).map((line) => {
    const fields = splitCsvLine(line);
    const row = {};
    header.forEach((h, i) => { row[h] = fields[i] ?? ''; });
    return row;
  });
}

function splitCsvLine(line) {
  const out = [];
  let cur = '';
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const c = line[i];
    if (inQuotes) {
      if (c === '"' && line[i + 1] === '"') { cur += '"'; i++; }
      else if (c === '"') { inQuotes = false; }
      else { cur += c; }
    } else {
      if (c === '"') inQuotes = true;
      else if (c === ',') { out.push(cur); cur = ''; }
      else cur += c;
    }
  }
  out.push(cur);
  return out;
}

function sqlStr(v) {
  if (v === undefined || v === null || v === '') return 'NULL';
  return `$str$${v}$str$`;
}
function sqlNum(v) {
  if (v === undefined || v === null || v === '') return 'NULL';
  const n = Number(v);
  return Number.isFinite(n) ? String(n) : 'NULL';
}
function jsonbLit(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$`;
}

const rows = parseCsv(fs.readFileSync(CSV_FILE, 'utf8'));

const stagingValues = rows.map((r) => {
  const raw = { ...r };
  const key = r['Name'];
  const cost = r['Round Bar Unit Cost (USD / kg)'] || null;
  return `('material', 'USA', '2026-Multi-Spindle', ${sqlStr(key)}, ${sqlNum(cost)}, 'USD/kg', 'Multi-Spindle Machining materials reference row', ${jsonbLit(raw)})`;
}).join(',\n');

const promotionValues = rows.map((r) => {
  const material = `Generic ${r['Name']}`;
  const grade = r['Name'];
  const type = r['Material Type'];
  const density = r['Density (kg / m^3)'];
  const shear = r['Shear Strength (MPa)'];
  const hardness = r['Hardness'];
  const hardnessSystem = r['Hardness System'] || null;
  const cost = r['Round Bar Unit Cost (USD / kg)'];
  return `(${sqlStr(material)}, ${sqlStr(grade)}, ${sqlStr(type)}, 'Machining', ${sqlNum(density)}, ${density ? (Number(density) / 1000) : 'NULL'}, ${sqlNum(shear)}, ${sqlNum(hardness)}, ${sqlStr(hardnessSystem)}, ${sqlNum(cost)}, ${sqlNum(cost)}, 'USD')`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 784: Seed Multi-Spindle Machining materials (2026-09-19)
--
-- Source: memory/Multi-Spindle Maching/Materials/materials_table.csv (105
-- real materials). Generated by gen_784_seed_multi_spindle_machining_materials.js
-- -- see that script's header for the full two-step rationale, what's
-- deliberately NOT promoted (per-stock-form costs beyond Round Bar; Milling/
-- Turning Speed, which is 0.00/not real for every row in the source), and
-- the known dedup limitation (exact-string match only, same as migration 590).
-- ============================================================================

BEGIN;

-- ── Step 1: lossless landing zone ──────────────────────────────────────────
INSERT INTO machining_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${stagingValues}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

-- ── Step 2: promote to the live table, tagged as a new 'Machining' group ───
INSERT INTO raw_materials (
  material, material_grade, material_type, material_group,
  density_kg_m3, density, shearing_strength, hardness, hardness_system,
  cost, cost_usa, currency
)
SELECT v.material, v.material_grade, v.material_type, v.material_group,
       v.density_kg_m3, v.density, v.shear, v.hardness, v.hardness_system,
       v.cost, v.cost_usa, v.currency
FROM (VALUES
${promotionValues}
) AS v(material, material_grade, material_type, material_group,
       density_kg_m3, density, shear, hardness, hardness_system,
       cost, cost_usa, currency)
WHERE NOT EXISTS (
  SELECT 1 FROM raw_materials rm WHERE rm.material = v.material
);

COMMIT;

-- Verification (run manually after):
-- SELECT count(*) FROM raw_materials WHERE material_group = 'Machining';
-- SELECT count(*) FROM machining_reference_data WHERE category = 'material' AND source_version = '2026-Multi-Spindle';
-- -- Expect 105 for the staging count; fewer for raw_materials if any exact
-- -- 'material' string already exists.
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${OUT_SQL} (${rows.length} materials)`);
