// Generates 838_chemical_milling_machine_specs.sql.
//
// Chemical milling runs on four stations seeded by migration 738 (Etch Cell,
// Mask Cure, DeMask, Scribe) without the columns the chemical-milling engine
// needs. This writes, from memory/Machining/machine/*.csv, onto every
// location's row of that machine (matched by machine_class + machine_name):
//   max_x/y/z_mm  the work envelope (etch tank length/width/depth, cure oven
//                 useable length/width/height, scribe bed length/width/height),
//                 used to fit parts per tank / oven load
//   specs         heated_cure (oven), feed_rate_mm_per_min /
//                 rapid_traverse_rate_mm_per_min / programming_time_hr (scribe)
// specs is merged (existing keys kept unless named here).
//
//   node backend/migrations/scripts/gen_838_chemical_milling_machine_specs.js

const fs = require('fs');
const path = require('path');
const { readDoc, MACHINING_MACHINE_FILE_SCALARS } = require('./lib/memory-csv');
const { sqlStr, sqlNum, sqlJsonb } = require('./lib/memory-machine-seed');

const DIR = path.join(__dirname, '../../../memory/Machining/machine');
const OUT_SQL = path.join(__dirname, '../838_chemical_milling_machine_specs.sql');

const FILES = [
  { file: 'etch_cell_usa.csv', machineClass: 'etch_cell', envelope: ['tank_length_mm', 'tank_width_mm', 'tank_depth_mm'], specs: {} },
  { file: 'mask_cure_usa.csv', machineClass: 'mask_cure', envelope: ['useable_length_mm', 'useable_width_mm', 'useable_height_mm'], specs: { heated_cure: ['limits', 'heated_cure'] } },
  { file: 'scribe_usa.csv', machineClass: 'scribe', envelope: ['bed_length_mm', 'bed_width_mm', 'bed_height_mm'],
    specs: { feed_rate_mm_per_min: ['rates', 'feed_rate_mm_per_min'], rapid_traverse_rate_mm_per_min: ['rates', 'rapid_traverse_rate_mm_per_min'], programming_time_hr: ['time', 'programming_time_hr'] } },
  { file: 'demask_usa.csv', machineClass: 'demask', envelope: null, specs: {} },
];

const rows = [];
for (const { file, machineClass, envelope, specs } of FILES) {
  const { machines } = readDoc(path.join(DIR, file), { list: 'machines', scalars: MACHINING_MACHINE_FILE_SCALARS });
  for (const m of machines) {
    const name = m.name ?? m.primary_id;
    if (!name) throw new Error(`${file}: machine with no name`);
    const env = envelope ? envelope.map((k) => m.limits?.[k] ?? null) : [null, null, null];
    const spec = {};
    for (const [key, [group, field]] of Object.entries(specs)) {
      const v = m[group]?.[field];
      if (v !== undefined && v !== null) spec[key] = v;
    }
    rows.push({ machineClass, name, env, spec });
  }
}

const values = rows.map((r) =>
  `  (${sqlStr(r.machineClass)}, ${sqlStr(r.name)}, ${sqlNum(r.env[0])}::numeric, ${sqlNum(r.env[1])}::numeric, ${sqlNum(r.env[2])}::numeric, ${sqlJsonb(r.spec)})`,
).join(',\n');

const sql = `-- ============================================================================
-- Migration 838: chemical milling machine envelope and specs
-- ============================================================================
-- From memory/Machining/machine (etch_cell_usa, mask_cure_usa, scribe_usa,
-- demask_usa). Every location twin of each machine (matched by machine_class
-- and machine_name) gets the machine's own envelope in max_x/y/z_mm (etch tank,
-- cure oven, scribe bed) and its process specs merged into specs: heated_cure
-- (oven), feed_rate_mm_per_min, rapid_traverse_rate_mm_per_min and
-- programming_time_hr (scribe). The chemical-milling engine fits parts per tank
-- / oven load from the envelope and prices scribing from the feed rate.
-- One statement, idempotent. Needs migrations 738 and 814a.
-- Generated by scripts/gen_838_chemical_milling_machine_specs.js.
-- ============================================================================

UPDATE mhr_records m
SET max_x_mm = coalesce(v.max_x, m.max_x_mm),
    max_y_mm = coalesce(v.max_y, m.max_y_mm),
    max_z_mm = coalesce(v.max_z, m.max_z_mm),
    specs    = coalesce(m.specs, '{}'::jsonb) || v.spec
FROM (VALUES
${values}
) AS v(machine_class, machine_name, max_x, max_y, max_z, spec)
WHERE m.machine_class = v.machine_class AND m.machine_name = v.machine_name;

NOTIFY pgrst, 'reload schema';

-- Verify (every chem-mill machine has an envelope, except DeMask which has none):
-- SELECT machine_class, location, count(*), count(max_x_mm) AS with_envelope,
--        count(*) FILTER (WHERE specs ? 'heated_cure' OR specs ? 'feed_rate_mm_per_min') AS with_specs
-- FROM mhr_records WHERE machine_class IN ('etch_cell', 'mask_cure', 'scribe', 'demask')
-- GROUP BY 1, 2 ORDER BY 1, 2;
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${OUT_SQL} (${rows.length} machines)`);
