// Generator: stages the real Injection Molding "materialHandling"
// lookup-table export (memory/plastic modeling/lookup/materialHandling.json
// — 7 real (weight_kg -> handling_time_s) breakpoints: real operator
// part-handling time as a function of part weight) into im_reference_data
// category='lookup_table' — same shape and staging-only discipline as
// migrations 651-665.
//
// key = weight_kg breakpoint (as string), value = handling_time_s,
// unit_type = 's', raw = full source record.
//
// Distinct from cycle-time.ts's IM_EJECT_SEC = 2.5 (mold-open travel +
// ejector stroke + part-release — a mechanical, machine-driven constant,
// that file's own comment already flags as "Phase 5 will scale with part
// height"). This table is a real, CURRENTLY ENTIRELY MISSING cycle-time
// component instead: operator handling time after ejection, scaling with
// part WEIGHT, not part height — totalCycleSec today
// (fillSec+packSec+coolSec+ejectSec) has no handling-time term at all.
// The weight axis this table needs (massG) is already computed correctly
// per-part (manufacturing-intelligence/page.tsx's material-density fix,
// 2026-09-03) — no open dependency blocking this one, unlike the mold-
// base-area-keyed tables. NOT wired into any cost calculation here — same
// "combine once all lookup tables have arrived" sequencing as every prior
// lookup_table migration this batch.
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const HANDLING_FILE = path.join(__dirname, '../../../memory/plastic modeling/lookup/materialHandling.json');
const OUT_SQL = path.join(__dirname, '../666_seed_im_lookup_material_handling.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(HANDLING_FILE, 'utf8'));

const rows = data.records.map((r) => {
  const weightKg = r['Weight (kg)'];
  const handlingS = r['Handling Time (s)'];
  return {
    category: 'lookup_table',
    key: `weight_kg_${weightKg}`,
    value: String(handlingS),
    unit_type: 's',
    notes: `Operator handling time for part weight <= ${weightKg} kg`,
    raw: { weight_kg: weightKg, handling_time_s: handlingS },
  };
});

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 666: Seed im_reference_data category = 'lookup_table'
-- (material handling time) — schema: migration 636
--
-- Generated by gen_666_seed_im_lookup_material_handling.js.
-- Row count: ${rows.length} (memory/plastic modeling/lookup/materialHandling.json).
--
-- NOT wired into any cost calculation — staging only. See the generator
-- script header — a real, currently entirely-missing cycle-time component
-- (operator handling time), distinct from cycle-time.ts's IM_EJECT_SEC.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
