// Generator: stages the real Injection Molding "tblCorePlateDepthBorder"
// lookup-table export (memory/plastic modeling/lookup/tblCorePlateDepthBorder.json
// — 4 real (max_press_force_kn -> core_plate_depth_border_in) breakpoints:
// real mold core-plate border/margin dimension as a function of machine
// press/clamp force — same real breakpoint values as migration 670's
// cavity plate border, for the core (moving) half of the mold instead of
// the cavity (fixed) half) into im_reference_data category='lookup_table'
// — same shape and staging-only discipline as migrations 651-670.
//
// key = max_press_force_kn breakpoint (as string), value =
// core_plate_depth_border_in, unit_type = 'in', raw = full source record.
//
// Same real, growing relevance to the still-open mold-base-area question
// as migration 670 — NOT wired into any cost calculation here — same
// "combine once all lookup tables have arrived" sequencing as every prior
// lookup_table migration this batch.
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const BORDER_FILE = path.join(__dirname, '../../../memory/plastic modeling/lookup/tblCorePlateDepthBorder.json');
const OUT_SQL = path.join(__dirname, '../671_seed_im_lookup_core_plate_depth_border.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(BORDER_FILE, 'utf8'));

const rows = data.records.map((r) => {
  const borderIn = r['Core Plate Depth Border (in)'];
  const pressKn = r['Max Press Force (kN)'];
  return {
    category: 'lookup_table',
    key: `press_kn_${pressKn}`,
    value: String(borderIn),
    unit_type: 'in',
    notes: `Core plate depth border for max press force <= ${pressKn} kN`,
    raw: { core_plate_depth_border_in: borderIn, max_press_force_kn: pressKn },
  };
});

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 671: Seed im_reference_data category = 'lookup_table'
-- (core plate depth border) — schema: migration 636
--
-- Generated by gen_671_seed_im_lookup_core_plate_depth_border.js.
-- Row count: ${rows.length} (memory/plastic modeling/lookup/tblCorePlateDepthBorder.json).
--
-- NOT wired into any cost calculation — staging only. See the generator
-- script header — real, growing relevance to the still-open mold-base-
-- area question (migrations 654/656/664/670).
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
