#!/usr/bin/env node
// Generates migration 833: material stock prices by stock form and location,
// from memory/Plastic Modeling/machine/India/raw_material_stock_costs.csv
// (90 materials x 6 stock forms, USD per kg, location India).
//
// Stored as given: USD, no exchange rate in the migration (quotes convert at
// the FX snapshot of the day). Each row's raw_materials link is resolved in
// SQL against the live raw_materials names: the reference name itself, or the
// reference name with the raw_materials "Generic " prefix. A name matching
// neither (or matching more than one distinct material) stays unlinked and is
// listed by the migration's NOTICE; it is never guessed.
//
// Run: node backend/migrations/scripts/gen_833_material_stock_prices.js

const path = require('path');
const fs = require('fs');
const { readCsv, sqlStr } = require('./lib/memory-machine-seed');

const ROOT = path.resolve(__dirname, '..', '..', '..');
const REL = 'Plastic Modeling/machine/India/raw_material_stock_costs.csv';
const OUT = path.join(__dirname, '..', '833_material_stock_prices.sql');
const LOCATION = 'India';

// CSV column -> stock_form (the platform blank forms, blank-stock-candidates.ts, plus plate/tube/square).
const FORMS = {
  Hex_Bar_USD_per_kg: 'hex_bar',
  Plate_USD_per_kg: 'plate',
  Rectangular_Bar_USD_per_kg: 'rectangular_bar',
  Round_Bar_USD_per_kg: 'round_bar',
  Round_Tube_USD_per_kg: 'round_tube',
  Square_Bar_USD_per_kg: 'square_bar',
};

const { columns, rows } = readCsv(path.join(ROOT, 'memory', REL));
const unknown = columns.filter((c) => c !== 'Material' && !FORMS[c]);
if (unknown.length) throw new Error(`unmapped columns: ${unknown.join(', ')}`);

const values = [];
for (const r of rows) {
  for (const [col, form] of Object.entries(FORMS)) {
    const v = r[col];
    if (v == null || v === '' || !(Number(v) > 0)) continue;
    values.push(`  (${sqlStr(r.Material)}, ${sqlStr(form)}, ${sqlStr(LOCATION)}, ${Number(v)}, 'USD', ${sqlStr(`memory/${REL}`)})`);
  }
}

const sql = `-- ============================================================================
-- Migration 833: material_stock_prices (price by material x stock form x location)
-- ============================================================================
-- Generated by scripts/gen_833_material_stock_prices.js -- do not hand-edit.
--
-- Source: memory/${REL}: ${rows.length} materials, ${values.length} prices, USD per kg,
-- location ${LOCATION}. Stored in their own currency (no exchange rate here).
-- raw_material_name links each price to its raw_materials row by name (the
-- reference name, or "Generic " + the reference name); unmatched names stay
-- NULL and are listed by the NOTICE below. Machining costing prices the
-- blank from the price of its stock form at the quote location when one is on
-- file (costing/machining/stock-price.ts).
--
-- Independent, idempotent statements.
-- ============================================================================

CREATE TABLE IF NOT EXISTS material_stock_prices (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  reference_material TEXT NOT NULL,
  raw_material_name  TEXT,
  stock_form         TEXT NOT NULL CHECK (stock_form IN ('round_bar', 'hex_bar', 'rectangular_bar', 'square_bar', 'round_tube', 'plate')),
  location           TEXT NOT NULL,
  price_per_kg       NUMERIC NOT NULL CHECK (price_per_kg > 0),
  currency_code      TEXT NOT NULL,
  source             TEXT NOT NULL,
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (reference_material, stock_form, location)
);

CREATE INDEX IF NOT EXISTS material_stock_prices_lookup ON material_stock_prices (raw_material_name, stock_form, location);

ALTER TABLE material_stock_prices ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS material_stock_prices_read ON material_stock_prices;

CREATE POLICY material_stock_prices_read ON material_stock_prices FOR SELECT TO authenticated USING (true);

INSERT INTO material_stock_prices (reference_material, stock_form, location, price_per_kg, currency_code, source)
VALUES
${values.join(',\n')}
ON CONFLICT (reference_material, stock_form, location)
DO UPDATE SET price_per_kg = EXCLUDED.price_per_kg, currency_code = EXCLUDED.currency_code, source = EXCLUDED.source, updated_at = now();

DO $$
DECLARE
  unmatched text;
BEGIN
  UPDATE material_stock_prices p
  SET raw_material_name = m.material
  FROM (
    SELECT p2.reference_material, min(r.material) AS material
    FROM (SELECT DISTINCT reference_material FROM material_stock_prices) p2
    JOIN raw_materials r
      ON lower(r.material) IN (lower(p2.reference_material), lower('Generic ' || p2.reference_material))
    GROUP BY p2.reference_material
    HAVING count(DISTINCT lower(r.material)) = 1
  ) m
  WHERE p.reference_material = m.reference_material;

  SELECT string_agg(DISTINCT reference_material, ', ' ORDER BY reference_material) INTO unmatched
  FROM material_stock_prices WHERE raw_material_name IS NULL;
  RAISE NOTICE 'Migration 833: stock prices with no raw_materials match (not used in costing): %', coalesce(unmatched, '(none)');
END $$;

NOTIFY pgrst, 'reload schema';

-- Verify: SELECT location, stock_form, count(*), count(raw_material_name) FROM material_stock_prices GROUP BY 1, 2 ORDER BY 1, 2;
`;
fs.writeFileSync(OUT, sql, 'utf8');
console.log(`Wrote ${path.relative(ROOT, OUT)}: ${values.length} prices for ${rows.length} materials`);
