// Generator: stages the real Injection Molding "tblGrillInsertTypes"
// lookup-table export (memory/plastic modeling/lookup/tblGrillInsertTypes.json
// — 3 real (grill_area_in2 -> grill_insert_size) breakpoints: real grill/
// vent insert size classification as a function of grill area) into
// im_reference_data category='lookup_table' — same shape and
// staging-only discipline as migrations 651-674.
//
// key = grill_insert_size (smallGrill/mediumGrill/largeGrill), value =
// grill_area_in2 (the breakpoint), unit_type = 'in^2', raw = full source
// record.
//
// NOT wired into any cost calculation here — same "combine once all
// lookup tables have arrived" sequencing as every prior lookup_table
// migration this batch.
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const GRILL_FILE = path.join(__dirname, '../../../memory/plastic modeling/lookup/tblGrillInsertTypes.json');
const OUT_SQL = path.join(__dirname, '../675_seed_im_lookup_grill_insert_types.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(GRILL_FILE, 'utf8'));

const rows = data.records.map((r) => {
  const areaIn2 = r['Grill Area (in^2)'];
  const size = r['Grill Insert Size'];
  return {
    category: 'lookup_table',
    key: size,
    value: String(areaIn2),
    unit_type: 'in^2',
    notes: `Grill insert size breakpoint (area <= ${areaIn2} in^2)`,
    raw: { grill_area_in2: areaIn2, grill_insert_size: size },
  };
});

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 675: Seed im_reference_data category = 'lookup_table'
-- (grill insert types) — schema: migration 636
--
-- Generated by gen_675_seed_im_lookup_grill_insert_types.js.
-- Row count: ${rows.length} (memory/plastic modeling/lookup/tblGrillInsertTypes.json).
--
-- NOT wired into any cost calculation — staging only.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
