// Generator: stages the real Injection Molding "layoutNumCav" lookup-table
// export (memory/plastic modeling/lookup/layoutNumCav.json — 24 real
// cavity layout patterns: length-wise x width-wise cavity counts, the
// resulting total cavity count, a real runner-region-width coefficient,
// and a natural/artificial layout-balance classification) into
// im_reference_data category='lookup_table' — same shape and
// staging-only discipline as migrations 651-663.
//
// key = "<cavities_length_wise>x<cavities_width_wise>" (composite —
// number_of_cavities alone is NOT unique: e.g. 32 cavities appears as
// both a 2x16 layout (coefficient 3) and an 8x4 layout (coefficient 1) —
// the runner coefficient depends on the SPECIFIC split, not just the
// total count), value = coefficient_runner_region_width, raw = full
// source record (incl. number_of_cavities and layout_balance).
//
// Real, currently-approximated relevance to cost-injection-molding-
// engine.ts#estimateRunnerVolumeCm3, which today uses a generic
// Math.sqrt(cavityCount) "cavity_layout_factor" (its own comment cites
// this as an "SPI rule of thumb") — this table shows the real coefficient
// actually varies by the SPECIFIC length x width layout chosen for a
// given cavity count, not count alone. Precise wiring needs
// recommendCavityCount() to also resolve a length x width split (it
// currently returns only a scalar count) — not done here. NOT wired into
// any cost calculation — same "combine once all lookup tables have
// arrived" sequencing as every prior lookup_table migration this batch.
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const LAYOUT_FILE = path.join(__dirname, '../../../memory/plastic modeling/lookup/layoutNumCav.json');
const OUT_SQL = path.join(__dirname, '../664_seed_im_lookup_layout_num_cav.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(LAYOUT_FILE, 'utf8'));

const rows = data.records.map((r) => ({
  category: 'lookup_table',
  key: `${r.cavities_length_wise}x${r.cavities_width_wise}`,
  value: String(r.coefficient_runner_region_width),
  unit_type: null,
  notes: `${r.number_of_cavities} cavities, ${r.layout_balance} balance`,
  raw: r,
}));

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 664: Seed im_reference_data category = 'lookup_table'
-- (cavity layout / runner coefficient) — schema: migration 636
--
-- Generated by gen_664_seed_im_lookup_layout_num_cav.js.
-- Row count: ${rows.length} (memory/plastic modeling/lookup/layoutNumCav.json).
--
-- NOT wired into any cost calculation — staging only. See the generator
-- script header — real refinement to estimateRunnerVolumeCm3's
-- Math.sqrt(cavityCount) approximation, pending a cavity-layout (length x
-- width) resolver this app doesn't have yet.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
