// Generator: stages the real Injection Molding "tblTolerances" lookup-table
// export (memory/plastic modeling/lookup/tblTolerances.json — 3 real
// tolerance-class records: Low +/-0.254mm, Medium +/-0.127mm, High
// +/-0.051mm, each with a real Tolerance Factor multiplier 0.25/0.45/0.80)
// into im_reference_data category='lookup_table' — same shape and
// staging-only discipline as migrations 651-687.
//
// key = Tolerance Name, value = Tolerance Factor, unit_type =
// 'cost_factor', raw = full source record.
//
// Genuine capability gap: no tolerance-class cost multiplier exists
// anywhere in cost-injection-molding-engine.ts or cycle-time.ts today —
// tighter dimensional tolerance drives real added mold-machining/QC cost
// (confirmed no existing consumer via repo grep). No wiring here — same
// "combine once all lookup tables have arrived" sequencing as every prior
// lookup_table migration this batch.
//
// This was one of 2 files in memory/plastic modeling/lookup/ found NOT
// yet staged during a full directory reconciliation pass (the other is
// tblStandardWaterLineSizes.json, migration 687) — both were present in
// the source directory but never explicitly handed over during the
// file-by-file sequence that produced migrations 651-686.
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const TOL_FILE = path.join(__dirname, '../../../memory/plastic modeling/lookup/tblTolerances.json');
const OUT_SQL = path.join(__dirname, '../688_seed_im_lookup_tolerances.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(TOL_FILE, 'utf8'));

const rows = data.records.map((r) => {
  const name = r['Tolerance Name'];
  const factor = r['Tolerance Factor'];
  return {
    category: 'lookup_table',
    key: name,
    value: String(factor),
    unit_type: 'cost_factor',
    notes: `Tolerance class: ${name} — cost factor ${factor}`,
    raw: r,
  };
});

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 688: Seed im_reference_data category = 'lookup_table'
-- (tolerance classes) — schema: migration 636
--
-- Generated by gen_688_seed_im_lookup_tolerances.js.
-- Row count: ${rows.length} (memory/plastic modeling/lookup/tblTolerances.json).
--
-- NOT wired into any cost calculation — staging only. Genuine capability
-- gap: no tolerance-class cost multiplier exists anywhere in this app
-- today (confirmed via repo grep).
--
-- Found via a full directory reconciliation of memory/plastic modeling/
-- lookup/ against migrations 651-686 — this file was present on disk but
-- never explicitly handed over in the file-by-file sequence.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
