// Generator: stages the real Injection Molding "tblEdgeMoldBorderY"
// lookup-table export (memory/plastic modeling/lookup/tblEdgeMoldBorderY.json
// — 4 real (max_press_force_kn -> edge_mold_border_y_mm) breakpoints: real
// mold base edge border margin in the Y direction, as a function of
// machine press force) into im_reference_data category='lookup_table' —
// same shape and staging-only discipline as migrations 651-673.
//
// key = max_press_force_kn breakpoint (as string), value =
// edge_mold_border_y_mm, unit_type = 'mm', raw = full source record.
//
// Y-direction counterpart to migration 673's tblEdgeMoldBorderX — real,
// direct piece of the mold-base-area formula (migrations 654/656/664/
// 670/671/673): mold_base_length_y likely = cavity-layout footprint in Y
// + 2 x this border. NOT wired into any cost calculation — same "combine
// once all lookup tables have arrived" sequencing as every prior
// lookup_table migration this batch.
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const BORDER_FILE = path.join(__dirname, '../../../memory/plastic modeling/lookup/tblEdgeMoldBorderY.json');
const OUT_SQL = path.join(__dirname, '../674_seed_im_lookup_edge_mold_border_y.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(BORDER_FILE, 'utf8'));

const rows = data.records.map((r) => {
  const borderMm = r['Edge Mold Border Y (mm)'];
  const pressKn = r['Max Press Force (kN)'];
  return {
    category: 'lookup_table',
    key: `press_kn_${pressKn}`,
    value: String(borderMm),
    unit_type: 'mm',
    notes: `Edge mold border (Y) for max press force <= ${pressKn} kN`,
    raw: { edge_mold_border_y_mm: borderMm, max_press_force_kn: pressKn },
  };
});

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 674: Seed im_reference_data category = 'lookup_table'
-- (edge mold border Y) — schema: migration 636
--
-- Generated by gen_674_seed_im_lookup_edge_mold_border_y.js.
-- Row count: ${rows.length} (memory/plastic modeling/lookup/tblEdgeMoldBorderY.json).
--
-- NOT wired into any cost calculation — staging only. See the generator
-- script header — direct piece of the still-open mold-base-area formula,
-- Y-direction counterpart to migration 673.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
