// Generator: stages the real Injection Molding "tblMoldBaseDesignHrs"
// lookup-table export (memory/plastic modeling/lookup/tblMoldBaseDesignHrs.json
// — 40 real records keyed by (Num Cav, Mold Base Wid) with 7 real design-
// hour components each: Std Base Design Hrs, Cust Base Design Hrs, Per
// Slide Design Hrs, Per Lifter Design Hrs, Hot Drop Design Hrs, Third
// Plate Design Hrs, Stripper Plate Design Hrs) into im_reference_data
// category='lookup_table' — same shape and staging-only discipline as
// migrations 651-678.
//
// NOT a duplicate of migration 654's cmMoldBaseDesignHours (14 rows, a
// single area->hours breakpoint) — this is a far more detailed, real
// table: same underlying "mold base design hours" concept, broken down
// by BOTH cavity count and mold base width, with per-feature additions
// (a mold with slides/lifters/hot drops/a third plate/a stripper plate
// takes real, additional design time beyond the base). Likely the
// authoritative source migration 654's simpler export summarized.
//
// key = "<num_cav>_<mold_base_wid>" (composite), value = Std Base Design
// Hrs (the primary base-hours figure, matching migration 654's own
// convention), raw = full source record with all 7 real components
// preserved losslessly.
//
// Source field name "Mold Base Wid (hr)" is preserved verbatim even
// though its values (203.2, 355.6, ... mm-scale numbers) look like a
// width dimension, not hours — likely a labeling artifact in the source
// export, not something to silently "fix" here (lossless staging).
//
// NOT wired into any cost calculation here — same "combine once all
// lookup tables have arrived" sequencing as every prior lookup_table
// migration this batch.
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const HOURS_FILE = path.join(__dirname, '../../../memory/plastic modeling/lookup/tblMoldBaseDesignHrs.json');
const OUT_SQL = path.join(__dirname, '../679_seed_im_lookup_mold_base_design_hrs.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(HOURS_FILE, 'utf8'));

const rows = data.records.map((r) => {
  const numCav = r['Num Cav'];
  const wid = r['Mold Base Wid (hr)'];
  const stdHrs = r['Std Base Design Hrs (hr)'];
  return {
    category: 'lookup_table',
    key: `${numCav}_${wid}`,
    value: String(stdHrs),
    unit_type: 'hr',
    notes: `Std base design hours for ${numCav} cavities, mold base width breakpoint ${wid}`,
    raw: r,
  };
});

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 679: Seed im_reference_data category = 'lookup_table'
-- (mold base design hours, detailed) — schema: migration 636
--
-- Generated by gen_679_seed_im_lookup_mold_base_design_hrs.js.
-- Row count: ${rows.length} (memory/plastic modeling/lookup/tblMoldBaseDesignHrs.json).
--
-- NOT wired into any cost calculation — staging only. See the generator
-- script header — NOT a duplicate of migration 654, a far more detailed
-- real table for the same underlying concept.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
