// Generator: stages the real Injection Molding "manufacturabilitySeverity"
// lookup-table export (memory/plastic modeling/lookup/manufacturabilitySeverity.json
// — 96 real DFM severity threshold records: Critical/Major/Minor
// thresholds per rule, differentiated by process (Compression/Injection/
// Reaction Injection/Structural Foam Molding), material type (ABS,
// Acetal, Acrylic, Nylon, PBT, PET, Polycarbonate, Polypropylene,
// Polystyrene, PPS, TPA/TPE/TPO/TPS/TPU/TPV), and — for draft angle
// specifically — real per-texture thresholds matching every one of
// migration 652's 26 cavityTextures patterns by name) into
// im_reference_data category='lookup_table' — same shape and
// staging-only discipline as migrations 651-664.
//
// This is the direct completion of migration 651's adviceRules (which
// only had rule NAMES + an enabled flag, no thresholds) — many of the
// same rule names here (ExternalUndercut, InternalUndercut, HighFlowRatio,
// SharpExternalEdge, SharpInternalEdge, ThickSection, ThinSection,
// ThinWallAroundHole, HighHoleLengthToDiameterRatio,
// HighBlindHoleLengthToDiameterRatio, NonRegrindableMaterial) now get
// real Critical/Major/Minor numeric thresholds. Also directly supersedes
// the generic, non-material-aware "Classification: Draft angle <0.3°" /
// "Back-angle >5°" text added to manufacturing-intelligence/page.tsx's
// undercut/undrafted DFM nodes (2026-09-03) — this table gives the real,
// material- and process-specific thresholds that text was standing in
// for.
//
// key = a composite of every differentiating field (Rule Name, Threshold
// Name, Process Name, Material Type, Custom Field, Custom Value) joined
// with '|', substituting 'ANY' for null so composite keys stay stable and
// unique — several rule/threshold-name pairs repeat across many
// process/material/texture combinations. value = JSON-encoded
// {critical, major, minor} (three numbers, not one) since Threshold
// Type/Units already live in unit_type/raw and a single scalar value
// column can't hold three real severity tiers at once. raw = full source
// record, unchanged.
//
// NOT wired into any cost/DFM calculation here. Real wiring (replacing
// the generic manufacturing-intelligence/page.tsx text, and/or feeding
// dfm-scoring.service.ts — this app's one live DFM authority per
// CLAUDE.md's P0.3 note) is a deliberate follow-up decision, same
// "combine once all lookup tables have arrived" sequencing as every prior
// lookup_table migration this batch.
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const SEVERITY_FILE = path.join(__dirname, '../../../memory/plastic modeling/lookup/manufacturabilitySeverity.json');
const OUT_SQL = path.join(__dirname, '../665_seed_im_lookup_manufacturability_severity.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(SEVERITY_FILE, 'utf8'));

const N = (v) => (v === null || v === undefined ? 'ANY' : String(v));

const seenKeys = new Map();
const rows = data.records.map((r) => {
  let key = [
    r['Rule Name'], r['Threshold Name'], r['Process Name'], r['Material Type'],
    r['Custom Field'], r['Custom Value'],
  ].map(N).join('|');
  const dupCount = (seenKeys.get(key) ?? 0) + 1;
  seenKeys.set(key, dupCount);
  if (dupCount > 1) key = `${key}|dup${dupCount}`;

  return {
    category: 'lookup_table',
    key,
    value: JSON.stringify({ critical: r['Critical'] ?? null, major: r['Major'] ?? null, minor: r['Minor'] ?? null }),
    unit_type: r['Units'] || r['Threshold Type'] || null,
    notes: r['Notes'] || `${r['Rule Name']} severity threshold`,
    raw: r,
  };
});

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 665: Seed im_reference_data category = 'lookup_table'
-- (manufacturability severity thresholds) — schema: migration 636
--
-- Generated by gen_665_seed_im_lookup_manufacturability_severity.js.
-- Row count: ${rows.length} (memory/plastic modeling/lookup/manufacturabilitySeverity.json).
--
-- NOT wired into any cost/DFM calculation — staging only. See the
-- generator script header — this is the real, material/process/texture-
-- specific completion of migration 651's bare adviceRules names, and
-- directly relevant to manufacturing-intelligence/page.tsx's generic
-- undercut/undrafted DFM text and dfm-scoring.service.ts.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
