#!/usr/bin/env node
// Generates migration 857: USA stock prices by stock form for material_stock_prices
// (migration 833 held India only). Source: memory/Multi-Spindle Maching/Materials/
// materials_table.csv, the per-stock-form USD/kg costs (hex, rectangular, round bar,
// round tube, square bar). That file has no plate price, so no plate row is written.
// The raw_materials link uses migration 833's rule: exact name, or "Generic " + name,
// only when that matches exactly one material.
//
// Run: node backend/migrations/scripts/gen_857_usa_material_stock_prices.js

const fs = require('fs');
const path = require('path');
const { readCsv, sqlStr, sqlNum } = require('./lib/memory-machine-seed');

const ROOT = path.resolve(__dirname, '..', '..', '..');
const SRC_REL = 'Multi-Spindle Maching/Materials/materials_table.csv';
const OUT = path.join(__dirname, '..', '857_usa_material_stock_prices.sql');
const FORMS = [
  ['hex_bar', 'Hex Bar Unit Cost (USD / kg)'],
  ['rectangular_bar', 'Rectangular Bar Unit Cost (USD / kg)'],
  ['round_bar', 'Round Bar Unit Cost (USD / kg)'],
  ['round_tube', 'Round Tube Unit Cost (USD / kg)'],
  ['square_bar', 'Square Bar Unit Cost (USD / kg)'],
];

const { rows } = readCsv(path.join(ROOT, 'memory', SRC_REL));
const values = [];
for (const r of rows) {
  const ref = r['USA Name'] ?? r['Name'];
  if (!ref) throw new Error('row without a USA Name');
  for (const [form, col] of FORMS) {
    const price = r[col];
    if (typeof price !== 'number' || price <= 0) continue;
    values.push(`  (${sqlStr(String(ref).trim())}, ${sqlStr(form)}, 'USA', ${sqlNum(price)}, 'USD', ${sqlStr('memory/' + SRC_REL)})`);
  }
}

const sql = `-- ============================================================================
-- Migration 857: USA stock prices by stock form (material_stock_prices)
-- ============================================================================
-- Generated by scripts/gen_857_usa_material_stock_prices.js -- do not hand-edit.
--
-- Source: memory/${SRC_REL}: ${rows.length} materials, ${values.length} USD/kg prices
-- (hex, rectangular, round bar, round tube, square bar). Plate has no USA price in
-- that file, so none is written. Migration 833 holds India; this adds USA beside it.
--
-- Run after 833. Idempotent: ON CONFLICT updates the price in place.
-- ============================================================================

INSERT INTO material_stock_prices (reference_material, stock_form, location, price_per_kg, currency_code, source)
VALUES
${values.join(',\n')}
ON CONFLICT (reference_material, stock_form, location)
DO UPDATE SET price_per_kg = EXCLUDED.price_per_kg, currency_code = EXCLUDED.currency_code, source = EXCLUDED.source, updated_at = now();

DO $$
DECLARE
  unmatched text;
BEGIN
  UPDATE material_stock_prices p
  SET raw_material_name = m.material
  FROM (
    SELECT p2.reference_material, min(r.material) AS material
    FROM (SELECT DISTINCT reference_material FROM material_stock_prices) p2
    JOIN raw_materials r
      ON lower(r.material) IN (lower(p2.reference_material), lower('Generic ' || p2.reference_material))
    GROUP BY p2.reference_material
    HAVING count(DISTINCT lower(r.material)) = 1
  ) m
  WHERE p.reference_material = m.reference_material;

  SELECT string_agg(DISTINCT reference_material, ', ' ORDER BY reference_material) INTO unmatched
  FROM material_stock_prices WHERE location = 'USA' AND raw_material_name IS NULL;
  RAISE NOTICE 'Migration 857: USA stock prices with no raw_materials match (not used in costing): %', coalesce(unmatched, '(none)');
END $$;

NOTIFY pgrst, 'reload schema';

-- Verify (run after): SELECT location, stock_form, count(*), count(raw_material_name)
--   FROM material_stock_prices GROUP BY 1, 2 ORDER BY 1, 2;
`;
fs.writeFileSync(OUT, sql, 'utf8');
console.log(`Wrote ${path.relative(ROOT, OUT)}: ${rows.length} materials, ${values.length} prices`);
