#!/usr/bin/env node
// Generates migration 824: seed mhr_records with every machine in
// memory/Forging/Machine/*.csv (USA reference export), process_group Forging,
// and point each Forging process_taxonomy row (migration 790) at its class.
//
// Each file is one machine category; its processes are the ones in
// forging_processes.csv whose default machine is in that file (the oven furnace
// serves both Preheat and Reheat; the trim and forming press share a model but
// are separate files). Wage grades from forging_wage_grade_associations.csv.
//
// Run: node backend/migrations/scripts/gen_824_seed_forging_mhr_records.js

const fs = require('fs');
const path = require('path');
const { readCsv, sqlStr, buildMachineRows, insertSql } = require('./lib/memory-machine-seed');

const ROOT = path.resolve(__dirname, '..', '..', '..');
const SRC = path.join(ROOT, 'memory', 'Forging');
const OUT = path.join(__dirname, '..', '824_seed_forging_mhr_records.sql');
const GROUP = 'Forging';

// file -> HR Rates category + the envelope columns that bound a part/billet.
const FILES = [
  ['forging_machines_bandSaw.csv', 'Band Saw', ['Max Stock Diameter (mm)', 'Max Stock Width (mm)', 'Max Stock Height (mm)', null]],
  ['forging_machines_conveyorInductionHeat.csv', 'Conveyor Induction Heat', ['Total Coil Length (mm)', 'Maximum Coil Diameter (mm)', null, null]],
  ['forging_machines_hammer.csv', 'Hammer', ['Table Length (mm)', 'Table Width (mm)', null, null]],
  ['forging_machines_materialStock.csv', 'Material Stock', [null, null, null, null]],
  ['forging_machines_mechanicalPress.csv', 'Mechanical Press', ['Press Table Length (mm)', 'Press Table Width (mm)', 'Max Shut Height (mm)', null]],
  ['forging_machines_openDiePress.csv', 'Open Die Press', [null, null, null, null]],
  ['forging_machines_ovenFurnace.csv', 'Oven Furnace', ['Oven Length (mm)', 'Oven Width (mm)', 'Oven Height (mm)', null]],
  ['forging_machines_press.csv', 'Press', [null, null, null, null]],
  ['forging_machines_ringRolling.csv', 'Ring Rolling', ['Max Outside Diameter (mm)', 'Max Outside Diameter (mm)', 'Max Preform Height (mm)', null]],
  ['forging_machines_trim.csv', 'Trim', [null, null, null, null]],
];
const classOf = (category) => 'forging_' + category.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '');

const processes = readCsv(path.join(SRC, 'forging_processes.csv')).rows;
const wage = readCsv(path.join(SRC, 'forging_wage_grade_associations.csv')).rows;
const onDisk = fs.readdirSync(path.join(SRC, 'Machine')).filter((f) => f.endsWith('.csv')).sort();
const unmapped = onDisk.filter((f) => !FILES.some(([x]) => x === f));
if (unmapped.length) throw new Error(`unmapped machine files: ${unmapped.join(', ')}`);

const specs = FILES.map(([file, category, envelope]) => {
  const rel = `Forging/Machine/${file}`;
  const names = new Set(readCsv(path.join(SRC, 'Machine', file)).rows.map((r) => String(r['Name'])));
  // The processes this file serves: those whose default machine is in it; a
  // file whose category is itself a process name serves that process.
  let procs = processes.filter((p) => p['Default Machine'] && names.has(String(p['Default Machine']))).map((p) => String(p['Process Name']));
  if (processes.some((p) => p['Process Name'] === category)) procs = [...new Set([category, ...procs.filter((p) => p === category || !FILES.some(([, c]) => c === p))])];
  const grades = [...new Set(procs.map((p) => wage.find((w) => w['Process Name'] === p)?.['Wage Grade Name']).filter(Boolean))];
  if (grades.length > 1) throw new Error(`${file}: processes ${procs.join('/')} disagree on wage grade`);
  return { file: path.join(SRC, 'Machine', file), rel, category, machineClass: classOf(category), grade: grades[0] ?? null, envelope, processes: procs };
});

const { columns, rows, report } = buildMachineRows(specs, GROUP);
const catVals = specs.flatMap((s) => s.processes.map((p) => `  (${sqlStr(p)}, ${sqlStr(s.machineClass)})`)).join(',\n');

const sql = `-- ============================================================================
-- Migration 824: Seed mhr_records with the real Forging machines
-- ============================================================================
-- Generated by scripts/gen_824_seed_forging_mhr_records.js -- do not
-- hand-edit, re-run the generator and diff instead.
--
-- Source: memory/Forging/Machine/*.csv (USA reference export). ${rows.length} machines:
${report.map((r) => `--   ${r.category.padEnd(24)} ${r.machineClass.padEnd(32)} ${String(r.n).padStart(2)} machine(s)  wage ${r.grade ?? '-'}  processes ${r.processes.join(', ') || '-'}`).join('\n')}
--
-- Row shape of migrations 806/818/820 (scripts/lib/memory-machine-seed.js):
-- location USA, MHR = Direct OH + Indirect OH, process-specific columns in specs.
-- Statements are independent and idempotent; run them one at a time.
-- ============================================================================

-- ── 1. Machines.
${insertSql(columns, rows)}

-- ── 2. Forging catalog rows (migration 790): machine_class, where still NULL.
UPDATE process_taxonomy pt
SET machine_class = v.machine_class
FROM (VALUES
${catVals}
) AS v(process_name, machine_class)
WHERE pt.process_group = '${GROUP}' AND pt.process_name = v.process_name AND pt.machine_class IS NULL;

UPDATE process_calculator_mappings pcm
SET machine_class = v.machine_class, updated_at = now()
FROM (VALUES
${catVals}
) AS v(operation, machine_class)
WHERE pcm.process_group = '${GROUP}' AND pcm.operation = v.operation AND pcm.machine_class IS NULL;

NOTIFY pgrst, 'reload schema';
`;
fs.writeFileSync(OUT, sql, 'utf8');
console.log(`Wrote ${path.relative(ROOT, OUT)}: ${rows.length} machines`);
for (const r of report) console.log(`${r.machineClass}: ${r.n} | processes ${r.processes.join(', ')} | grade ${r.grade}`);
