// Generator: stages the real Injection Molding "tblSlideSizes" lookup-table
// export (memory/plastic modeling/lookup/tblSlideSizes.json — 13 real
// mold side-action slide sizing records: core pin diameter breakpoints
// with real core retainer thickness, wear plate thickness, and slide
// body length) into im_reference_data category='lookup_table' — same
// shape and staging-only discipline as migrations 651-680.
//
// key = core_pin_dia_mm breakpoint (as string), value = slide_body_length_mm,
// unit_type = 'mm', raw = full source record (incl. retainer/wear-plate
// thickness).
//
// Directly relevant to migration 655's "Side Lock"/"Hydraulic Cylinder"
// standard tooling components — undercut-driven slide mechanisms this
// engine already signals via undercutCount (cost-injection-molding-
// engine.ts). NOT wired into any cost calculation here — same "combine
// once all lookup tables have arrived" sequencing as every prior
// lookup_table migration this batch.
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const SLIDE_FILE = path.join(__dirname, '../../../memory/plastic modeling/lookup/tblSlideSizes.json');
const OUT_SQL = path.join(__dirname, '../681_seed_im_lookup_slide_sizes.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(SLIDE_FILE, 'utf8'));

const rows = data.records.map((r) => {
  const pinDia = r['Core Pin Dia (mm)'];
  const bodyLen = r['Slide Body Length (mm)'];
  return {
    category: 'lookup_table',
    key: `core_pin_dia_${pinDia}`,
    value: String(bodyLen),
    unit_type: 'mm',
    notes: `Slide sizing for core pin dia <= ${pinDia} mm`,
    raw: r,
  };
});

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 681: Seed im_reference_data category = 'lookup_table'
-- (slide sizes) — schema: migration 636
--
-- Generated by gen_681_seed_im_lookup_slide_sizes.js.
-- Row count: ${rows.length} (memory/plastic modeling/lookup/tblSlideSizes.json).
--
-- NOT wired into any cost calculation — staging only.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
