// Generator: stages the real Injection Molding "injectionTimeAdjustmentFactors"
// lookup-table export (memory/plastic modeling/lookup/injectionTimeAdjustmentFactors.json
// — 9 real breakpoints across 2 attributes: Cavities Per Mold (3/5/8/999999
// -> 1.0/1.02/1.05/1.1) and Gates Per Cavity (1/2/3/4/999999 ->
// 0.6/0.4/0.3/0.25/0.25)) into im_reference_data category='lookup_table'
// — same shape and staging-only discipline as migrations 651-662.
//
// key = "<attribute>_<number>" (composite — both attributes use
// overlapping number ranges), value = adjustment_factor, raw = full
// source record.
//
// Real, currently-missing refinement to the live fill-time model
// (cycle-time.ts#computeFillTimeSec, t_fill = L_flow / v_front) — that
// function's own comment already documents it as a "Phase 4 proxy" with
// no cavity/gate awareness ("Exact flow-length requires gate position —
// a Phase 5 mold-layout item"). cavityCount is already computed
// elsewhere (cost-injection-molding-engine.ts#recommendCavityCount);
// "gates per cavity" is not currently tracked anywhere in this app.
// NOT wired into the fill-time calculation here — same "combine once all
// lookup tables have arrived" sequencing as every prior lookup_table
// migration this batch.
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const FACTORS_FILE = path.join(__dirname, '../../../memory/plastic modeling/lookup/injectionTimeAdjustmentFactors.json');
const OUT_SQL = path.join(__dirname, '../663_seed_im_lookup_injection_time_adjustment_factors.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(FACTORS_FILE, 'utf8'));

const rows = data.records.map((r) => ({
  category: 'lookup_table',
  key: `${r.attribute}_${r.number}`,
  value: String(r.adjustment_factor),
  unit_type: null,
  notes: `Fill-time adjustment factor for ${r.attribute} <= ${r.number}`,
  raw: r,
}));

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 663: Seed im_reference_data category = 'lookup_table'
-- (injection time adjustment factors) — schema: migration 636
--
-- Generated by gen_663_seed_im_lookup_injection_time_adjustment_factors.js.
-- Row count: ${rows.length} (memory/plastic modeling/lookup/injectionTimeAdjustmentFactors.json).
--
-- NOT wired into any cost calculation — staging only. See the generator
-- script header — real, currently-missing refinement to
-- cycle-time.ts#computeFillTimeSec.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
