// Generates 836_restage_sheet_metal_location_rates.sql.
//
// Migration 594 staged the India / China / Mexico / France machine rate files
// into sm_reference_data (category 'machine', source_version '2026-08') with
// the key `loc.category + ':' + name` - the location object has no category,
// so every key was 'undefined:<name>'. 12 machine names repeat across
// categories in every file (the same press listed as Mechanical / Progressive
// Die, Standard and Tandem Press), so ON CONFLICT DO NOTHING kept one of each
// and dropped the rest: 48 source rows never staged. The mhr_records rates are
// not affected (594's promote step joins by name, and 595-599 corrected them).
//
// This replaces those staged rows with every current memory/ record, keyed
// '<category>:<name>' (unique in every file), raw = the full source row
// (594 kept only direct / indirect / labour). Readers that scan machine rows
// by raw name test physics fields (bend_cycle_time_s, punch_rate_cycles_min,
// abrasive_flow_rate_kg_min, rolling_speed_mm_s) that no location row has.
//
//   node backend/migrations/scripts/gen_836_restage_sheet_metal_location_rates.js

const fs = require('fs');
const path = require('path');
const { readRecords } = require('./lib/memory-csv');

const DIR = path.join(__dirname, '../../../memory/Sheetmetal/machine');
const OUT_SQL = path.join(__dirname, '../836_restage_sheet_metal_location_rates.sql');

// file -> region, the file's document-level columns (not machine fields),
// and its direct-overhead column (the staged value, as in 594).
const FILES = [
  { file: 'india_base.csv', region: 'IND', docColumns: ['country', 'recordCount'], direct: 'directOverheadRate' },
  { file: 'china_location_data_full.csv', region: 'CHN', docColumns: ['country', 'currency', 'confidence'], direct: 'direct_overhead_rate_usd_hr' },
  { file: 'mexico_delta.csv', region: 'MEX', docColumns: ['country', 'note', 'recordCount'], direct: 'directOverheadRate' },
  { file: 'france_delta.csv', region: 'FRA', docColumns: ['country', 'note', 'recordCount'], direct: 'directOverheadRate' },
];

const sqlStr = (v) => (v === null || v === undefined || v === '' ? 'NULL' : `$str$${String(v)}$str$`);
const sqlJsonb = (o) => `$jsonb$${JSON.stringify(o)}$jsonb$::jsonb`;

const blocks = [];
let total = 0;
for (const { file, region, docColumns, direct } of FILES) {
  const records = readRecords(path.join(DIR, file));
  const keys = new Set();
  const rows = records.map((r) => {
    const key = `${r.category}:${r.name}`;
    if (!r.category || !r.name) throw new Error(`${file}: row without category / name`);
    if (keys.has(key)) throw new Error(`${file}: duplicate key ${key}`);
    keys.add(key);
    const raw = { ...r };
    for (const c of docColumns) delete raw[c];
    return `('machine', '${region}', '2026-08', ${sqlStr(key)}, ${sqlStr(r[direct])}, 'USD/hr direct overhead', ${sqlStr(`Sheet metal machine rate reference row (${records[0].country})`)}, ${sqlJsonb(raw)})`;
  });
  total += rows.length;
  blocks.push(`-- ${records[0].country}: ${rows.length} rows (memory/Sheetmetal/machine/${file})
INSERT INTO sm_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw)
VALUES
${rows.join(',\n')}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;`);
}

const sql = `-- ============================================================================
-- Migration 836: re-stage the Sheet Metal location machine rates with real keys
-- ============================================================================
-- Migration 594 staged memory/Sheetmetal/machine india_base / china_location_
-- data_full / mexico_delta / france_delta into sm_reference_data (category
-- machine, source_version 2026-08) under keys 'undefined:<name>' (a generator
-- bug: the key read the category from the location, not the row). 12 machine
-- names repeat across categories in every file, so 594 kept one row per name
-- and dropped 48 source rows. mhr_records rates are not changed here (594 joins
-- by name; 595-599 corrected them).
--
-- This deletes those rows and stages all ${total} current memory/ rows keyed
-- '<category>:<name>', raw = the full source row. The SQL editor runs the file
-- as one transaction: if the insert fails the delete is rolled back.
-- Generated by backend/migrations/scripts/gen_836_restage_sheet_metal_location_rates.js.
-- ============================================================================

DELETE FROM sm_reference_data
WHERE category = 'machine' AND source_version = '2026-08'
  AND source_region IN ('IND', 'CHN', 'MEX', 'FRA')
  AND key LIKE 'undefined:%';

${blocks.join('\n\n')}

-- Verify (expect 342 per region, 0 undefined keys):
-- SELECT source_region, count(*) AS rows, count(*) FILTER (WHERE key LIKE 'undefined:%') AS undefined_keys
-- FROM sm_reference_data
-- WHERE category = 'machine' AND source_version = '2026-08' AND source_region IN ('IND', 'CHN', 'MEX', 'FRA')
-- GROUP BY source_region ORDER BY source_region;
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${OUT_SQL} (${total} rows)`);
