// GENERATED by cad-engine/scripts/build_reference_features.py -- do not hand-edit.
// Canonical manufacturing feature vocabulary, derived from the reference
// operation catalogs (memory/sheetmetal/process/process_operations.csv,
// memory/machining/operations_full__operations.csv,
// memory/Die Casting/Processes/operations.csv). The CAD engine emits
// exactly these feature_type strings (cad-engine/shared/reference_features.json).

export type SheetMetalFeatureType =
  | 'Blank'
  | 'ComplexHole'
  | 'CurvedSurface'
  | 'CurvedWall'
  | 'Edge'
  | 'FinishedPart'
  | 'Form'
  | 'Lance'
  | 'MultiBend'
  | 'MultiStepHole'
  | 'NotSupported'
  | 'PartingLine'
  | 'Perimeter'
  | 'PlanarFace'
  | 'ShearForm'
  | 'SimpleHole'
  | 'StraightBend'
  | 'Void';

export type MachiningFeatureType =
  | 'AxiGroove'
  | 'Blank'
  | 'BuildDirection'
  | 'BulkRemoval'
  | 'CamBundle'
  | 'ComboVoid'
  | 'ComplexHole'
  | 'Core'
  | 'CoreBundle'
  | 'CurvedSurface'
  | 'CurvedWall'
  | 'Cutout'
  | 'Edge'
  | 'End'
  | 'FinishedPart'
  | 'Flat'
  | 'Form'
  | 'Keyway'
  | 'MultiStepHole'
  | 'NotSupported'
  | 'Perimeter'
  | 'PlanarFace'
  | 'PocketV2'
  | 'Polygon'
  | 'Ring'
  | 'RingedHole'
  | 'SimpleHole'
  | 'SlideBundle'
  | 'Slot'
  | 'StockTrim'
  | 'Void'
  | 'Workpiece';

export type DieCastingFeatureType =
  | 'ComboVoid'
  | 'CurvedSurface'
  | 'CurvedWall'
  | 'Edge'
  | 'MultiStepHole'
  | 'NotSupported'
  | 'PlanarFace'
  | 'Ring'
  | 'RingedHole'
  | 'SharpEdge'
  | 'SimpleHole'
  | 'SlideBundle'
  | 'Void';

export type SandCastingFeatureType =
  | 'ComboVoid'
  | 'CurvedSurface'
  | 'CurvedWall'
  | 'Edge'
  | 'MultiStepHole'
  | 'NotSupported'
  | 'PlanarFace'
  | 'Ring'
  | 'RingedHole'
  | 'SharpEdge'
  | 'SimpleHole'
  | 'Void';

export type InvestmentCastingFeatureType =
  | 'ComboVoid'
  | 'CoreBundle'
  | 'CurvedSurface'
  | 'CurvedWall'
  | 'Edge'
  | 'MultiStepHole'
  | 'NotSupported'
  | 'PlanarFace'
  | 'Ring'
  | 'SharpEdge'
  | 'SimpleHole'
  | 'SlideBundle'
  | 'Void';

/** Real operation names the reference catalog pairs with each feature type. */
export const REFERENCE_FEATURE_OPERATIONS: {
  readonly sheet_metal: Readonly<Record<SheetMetalFeatureType, readonly string[]>>;
  readonly machining: Readonly<Record<MachiningFeatureType, readonly string[]>>;
  readonly die_casting: Readonly<Record<DieCastingFeatureType, readonly string[]>>;
  readonly sand_casting: Readonly<Record<SandCastingFeatureType, readonly string[]>>;
  readonly investment_casting: Readonly<Record<InvestmentCastingFeatureType, readonly string[]>>;
} = {
  "sheet_metal": {
    "Blank": [
      "As Supplied",
      "Blanking",
      "Coining",
      "Deslag",
      "Die Station:Addendum Trimming Post-Forming",
      "Die Station:Blanking",
      "Die Station:Blanking Piloting",
      "Die Station:Cam Action Trimming",
      "Die Station:Coining",
      "Die Station:Cutoff",
      "Die Station:Edge Trimming",
      "Die Station:Full Blanking",
      "Die Station:Piloting",
      "Die Station:Piloting Edge Trimming",
      "Die Station:Post Form Trimming",
      "Die Station:Re Piloting",
      "Die Station:Tipping",
      "Die Station:Tipping Back",
      "Die Station:Trimming",
      "Die Station:Trimming Piloting",
      "Fiber Laser Bevel Cutting",
      "Fiber Laser Cutting",
      "Laser Bevel Cutting",
      "Laser Cut:Laser Cutting",
      "Laser Cutting",
      "Nibbling:Nibbling",
      "No Cost Feature",
      "OxyFuel Bevel Cutting",
      "OxyFuel Cutting",
      "Plasma Bevel Cutting",
      "Plasma Cut:Plasma Cutting",
      "Plasma Cutting",
      "Punching:Punching",
      "Router Cutting",
      "Shear",
      "Std Press",
      "Trimming",
      "Waterjet Bevel Cutting",
      "Waterjet Cutting"
    ],
    "ComplexHole": [
      "3D Laser Cutting",
      "As Supplied",
      "Coining",
      "Countersinking:Countersinking",
      "Deslag",
      "Die Station:Cam Action Piercing",
      "Die Station:Coining",
      "Die Station:Extruding",
      "Die Station:Piercing",
      "Die Station:Trimming",
      "Extruding",
      "Fiber Laser Bevel Cutting",
      "Fiber Laser Cutting",
      "Flanging:Flanging",
      "Laser Bevel Cutting",
      "Laser Cut:Laser Cutting",
      "Laser Cutting",
      "Nibbling:Nibbling",
      "No Cost Feature",
      "OxyFuel Bevel Cutting",
      "OxyFuel Cutting",
      "Perforating:Perforating",
      "Piercing",
      "Plasma Bevel Cutting",
      "Plasma Cut:Plasma Cutting",
      "Plasma Cutting",
      "Punching:Punching",
      "Router Cutting",
      "Std Press",
      "Trimming",
      "Waterjet Bevel Cutting",
      "Waterjet Cutting"
    ],
    "CurvedSurface": [
      "As Formed",
      "As Supplied",
      "Die Station:As Formed"
    ],
    "CurvedWall": [
      "As Formed",
      "As Supplied",
      "Die Station:As Formed"
    ],
    "Edge": [
      "Fiber Laser Bevel Cutting",
      "Laser Bevel Cutting",
      "Laser Cutting",
      "Nibbling",
      "No Cost Feature",
      "OxyFuel Bevel Cutting",
      "Plasma Bevel Cutting",
      "Plasma Cutting",
      "Punching",
      "Waterjet Bevel Cutting"
    ],
    "FinishedPart": [
      "Waterjet Cutting"
    ],
    "Form": [
      "3 Roll Bending",
      "4 Roll Bending",
      "Bending",
      "Cam Action Bending",
      "Die Station:Bending",
      "Die Station:Cam Action Bending",
      "Die Station:Deep Drawing",
      "Die Station:DownOverBending",
      "Die Station:Drawing",
      "Die Station:Embossing",
      "Die Station:Forming",
      "Die Station:Gusset Forming",
      "Die Station:Restriking",
      "Die Station:Scoring",
      "Die Station:Setting",
      "Die Station:Side Action Forming",
      "Die Station:Stamping",
      "DownOverBending",
      "Embossing",
      "Forming",
      "Forming:Forming",
      "Lancing:Lancing",
      "No Cost Feature",
      "Restriking",
      "Scoring",
      "Setting",
      "Side Action Forming",
      "Stamping",
      "Std Press"
    ],
    "Lance": [
      "Lancing:Lancing",
      "No Cost Feature",
      "Std Press"
    ],
    "MultiBend": [
      "Bending",
      "Die Station:Embossing",
      "Die Station:Forming",
      "Die Station:Restriking",
      "Embossing",
      "Forming",
      "No Cost Feature",
      "Restriking"
    ],
    "MultiStepHole": [
      "Fiber Laser Cut",
      "Laser Cut",
      "No Cost Feature",
      "OxyFuel Cutting",
      "Plasma Cut",
      "Punching:Punching",
      "Waterjet Cut"
    ],
    "NotSupported": [
      "No Cost Feature"
    ],
    "PartingLine": [
      "Waterjet Cutting"
    ],
    "Perimeter": [
      "Laser Cutting",
      "OxyFuel Cutting",
      "Plasma Cutting",
      "Waterjet Cutting"
    ],
    "PlanarFace": [
      "As Formed",
      "As Supplied",
      "Die Station:As Formed"
    ],
    "ShearForm": [
      "Die Station:Embossing",
      "Die Station:Forming",
      "Die Station:Restriking",
      "Die Station:Stamping",
      "Embossing",
      "Forming",
      "No Cost Feature",
      "Restriking",
      "Stamping"
    ],
    "SimpleHole": [
      "3D Laser Cutting",
      "As Supplied",
      "CounterSinking",
      "Countersinking:Countersinking",
      "Deslag",
      "Die Station:Cam Action Piercing",
      "Die Station:Coining",
      "Die Station:CounterSinking",
      "Die Station:Extruding",
      "Die Station:Piercing",
      "Die Station:Shaving",
      "Die Station:Tapping",
      "Extruding",
      "Fiber Laser Bevel Cutting",
      "Fiber Laser Cutting",
      "Flanging:Flanging",
      "Laser Bevel Cutting",
      "Laser Cut:Laser Cutting",
      "Laser Cutting",
      "Nibbling:Nibbling",
      "No Cost Feature",
      "OxyFuel Bevel Cutting",
      "OxyFuel Cutting",
      "Perforating:Perforating",
      "Piercing",
      "Plasma Bevel Cutting",
      "Plasma Cut:Plasma Cutting",
      "Plasma Cutting",
      "Punching:Punching",
      "Router Cutting",
      "Std Press",
      "Tapping:Tapping",
      "Waterjet Bevel Cutting",
      "Waterjet Cutting"
    ],
    "StraightBend": [
      "2 Roll Bending",
      "3 Roll Bending",
      "4 Roll Bending",
      "Bending",
      "Cam Action Bending",
      "CamOverBending",
      "Die Station:Bending",
      "Die Station:Cam Action Bending",
      "Die Station:CamOverBending",
      "Die Station:DownOverBending",
      "Die Station:Gusset Bending",
      "Die Station:Gusset Forming",
      "Die Station:Idle",
      "Die Station:Restriking",
      "Die Station:Scoring",
      "Die Station:Setting",
      "DownOverBending",
      "No Cost Feature",
      "Scoring",
      "Setting",
      "Std Press"
    ],
    "Void": [
      "Waterjet Cutting"
    ]
  },
  "machining": {
    "AxiGroove": [
      "Cutting",
      "General Mill Roughing",
      "No Cost Feature",
      "Profile Grinding",
      "Setup:External AxiGroove Broaching",
      "Setup:Hobbing",
      "Setup:Internal Gear Broaching",
      "Setup:Shaping",
      "Setup:Shaving",
      "Setup:Spiral BG Face Milling",
      "Setup:Spline Rolling",
      "Setup:Straight BG Face Milling",
      "Surface Finishing",
      "Threaded Wheel Grinding"
    ],
    "Blank": [
      "Automated Deburring",
      "Chamfering",
      "Cleaning",
      "Curing",
      "Final Inspecting",
      "Identing",
      "Line Sealing",
      "Manual Deburring",
      "Peeling Residual Maskant",
      "Profile Milling",
      "Spark Testing"
    ],
    "BuildDirection": [
      "Base Plate Facing Op",
      "Base Plate Removal Wire EDM"
    ],
    "BulkRemoval": [
      "Bulk Milling Op",
      "Bulk Milling:Bulk Milling Op",
      "No Cost Feature"
    ],
    "CamBundle": [
      "Automated Deburring",
      "Cam Machining",
      "Manual Deburring"
    ],
    "ComboVoid": [
      "Automated Deburring",
      "ComboVoid Grinding",
      "ComboVoid Machining",
      "Drilling",
      "Manual Deburring",
      "No Cost Feature"
    ],
    "ComplexHole": [
      "Automated Deburring",
      "Chamfering",
      "General Mill Roughing",
      "Manual Deburring",
      "No Cost Feature",
      "Rough Milling",
      "Rounding",
      "Surface Finishing"
    ],
    "Core": [
      "Finish Milling",
      "Rough Milling"
    ],
    "CoreBundle": [
      "Automated Deburring",
      "Core Machining",
      "Manual Deburring"
    ],
    "CurvedSurface": [
      "As Dovetail Milled",
      "As Edge Treated",
      "As Milled",
      "As Polygon Turned",
      "As Routered",
      "Automated Surface Deburring",
      "Back Finish Turning",
      "Back Rough Turning",
      "Back Semi-Finish Turning",
      "Bulk Milling Surface",
      "Chamfer Milling",
      "Contouring",
      "Dressing Edges",
      "Etch Cell Cycle:Depth Inspecting",
      "Etch Cell Cycle:Drying",
      "Etch Cell Cycle:Pocket Etching",
      "Etch Cell Cycle:Pocket Peeling",
      "Etch Cell Cycle:Rinsing",
      "Filleting",
      "Fine Finish Milling",
      "Finish Turning",
      "General Mill Finishing",
      "Indirect Filleting",
      "Line Sealing",
      "Manual Surface Deburring",
      "Mill Contouring",
      "Multiplunging",
      "No Cost Feature",
      "Plunging",
      "Rough Milling",
      "Rough Turning",
      "Rounding",
      "Scribing",
      "Semi-Finish Turning",
      "Side Milling",
      "Undercut Milling"
    ],
    "CurvedWall": [
      "As Dovetail Milled",
      "As Milled",
      "As Perimeter Cut",
      "As Polygon Turned",
      "As Routered",
      "As Wire EDM Cut",
      "Automated Surface Deburring",
      "Back Finish Turning",
      "Back Rough Turning",
      "Back Semi-Finish Turning",
      "Bulk Milling Surface",
      "Contouring",
      "Cutting",
      "Dressing Edges",
      "Etch Cell Cycle:Depth Inspecting",
      "Etch Cell Cycle:Drying",
      "Etch Cell Cycle:Pocket Etching",
      "Etch Cell Cycle:Pocket Peeling",
      "Etch Cell Cycle:Rinsing",
      "Facing",
      "Filleting",
      "Fine Finish Milling",
      "Finish Turning",
      "General Mill Finishing",
      "ID Finish Plunge Grinding",
      "ID Finish Traverse Grinding",
      "Indirect Filleting",
      "Line Sealing",
      "Manual Surface Deburring",
      "Mill Contouring",
      "Multiplunging",
      "No Cost Feature",
      "OD Finish Plunge Grinding",
      "OD Finish Traverse Grinding",
      "Perimeter Cut",
      "Plunging",
      "Rough Milling",
      "Rough Turning",
      "Rounding",
      "Scribing",
      "Semi-Finish Turning",
      "Side Milling",
      "Thread Milling",
      "Thread Turning",
      "Undercut Milling"
    ],
    "Cutout": [
      "No Cost Feature",
      "Perimeter Milling",
      "Perimeter Routering",
      "Rough Milling",
      "Routering",
      "Sharp Corner Touchup"
    ],
    "Edge": [
      "Automated Edge Deburring",
      "Chamfering",
      "Countersinking",
      "Edge Turning",
      "Manual Edge Deburring",
      "Mill Chamfering",
      "Mill Rounding",
      "No Cost Feature",
      "Rounding"
    ],
    "End": [
      "End Machining",
      "No Cost Feature",
      "Reciprocating Surface Grinder",
      "Rotary Surface Grinder"
    ],
    "FinishedPart": [
      "Profile Milling"
    ],
    "Flat": [
      "Automated Deburring:Automated Deburring",
      "Cylindrical Grinder",
      "Internal Grinder",
      "Manual Deburring:Manual Deburring",
      "No Cost Feature",
      "Reciprocating Surface Grinder",
      "Rotary Surface Grinder",
      "Setup:Rough Milling",
      "Setup:Surface Finishing",
      "Surface Finishing",
      "Wire EDM"
    ],
    "Form": [
      "Dressing Edges",
      "Etch Cell Cycle:Depth Inspecting",
      "Etch Cell Cycle:Drying",
      "Etch Cell Cycle:Pocket Etching",
      "Etch Cell Cycle:Pocket Peeling",
      "Etch Cell Cycle:Rinsing",
      "Line Sealing",
      "Rough Milling",
      "Scribing",
      "Setup:Form Machining",
      "Surface Finishing"
    ],
    "Keyway": [
      "Bathtub Slot Milling",
      "No Cost Feature",
      "Obround Slot Milling",
      "Rough Milling",
      "Setup:Multipass Keyway Broaching",
      "Setup:Single Pass Keyway Broaching",
      "Surface Finishing",
      "Woodruff Slot Milling"
    ],
    "MultiStepHole": [
      "Automated Deburring",
      "Feature Inspection",
      "Finish Grinding",
      "Manual Deburring",
      "Multistep Holemaking",
      "No Cost Feature",
      "Port Cutting",
      "Step Drilling",
      "Wire EDM Cutting"
    ],
    "NotSupported": [
      "No Cost Feature"
    ],
    "Perimeter": [
      "Cutting",
      "Perimeter Milling"
    ],
    "PlanarFace": [
      "As Dovetail Milled",
      "As Milled",
      "As Perimeter Cut",
      "As Polygon Turned",
      "As Rotary Broached",
      "As Routered",
      "As Wire EDM Cut",
      "Automated Surface Deburring",
      "Back Finish Turning",
      "Back Rough Turning",
      "Back Semi-Finish Turning",
      "Bulk Milling Surface",
      "Chamfer Milling",
      "Contouring",
      "Corner Picking",
      "Cutting",
      "Dressing Edges",
      "Etch Cell Cycle:Depth Inspecting",
      "Etch Cell Cycle:Drying",
      "Etch Cell Cycle:Pocket Etching",
      "Etch Cell Cycle:Pocket Peeling",
      "Etch Cell Cycle:Rinsing",
      "Facing",
      "Fine Finish Milling",
      "Finish Plunge Grinding",
      "Finish Traverse Grinding",
      "Finish Turning",
      "General Mill Finishing",
      "Line Sealing",
      "Manual Surface Deburring",
      "Mill Contouring",
      "Mill Facing",
      "Mill Grooving",
      "Multiplunging",
      "No Cost Feature",
      "Perimeter Cut",
      "Plunging",
      "Rough Milling",
      "Rough Turning",
      "Scribing",
      "Semi-Finish Turning",
      "Side Milling",
      "Undercut Milling"
    ],
    "PocketV2": [
      "General Rough Milling",
      "No Cost Feature",
      "Rough Milling"
    ],
    "Polygon": [
      "No Cost Feature",
      "Polygon Turning",
      "Rotary Broaching",
      "Rough Milling"
    ],
    "Ring": [
      "Automated Deburring:Automated Deburring",
      "Back Rough Turning",
      "Cylindrical Grinder",
      "Internal Grinder",
      "Manual Deburring:Manual Deburring",
      "Multiplunging",
      "No Cost Feature",
      "Parting",
      "Plunging",
      "Preturn Drilling",
      "Reciprocating Surface Grinder",
      "Rotary Surface Grinder",
      "Rough Milling",
      "Rough Turning",
      "Setup:Jig Boring",
      "Surface Finishing",
      "Thread Turning"
    ],
    "RingedHole": [
      "Automated Deburring",
      "Deep Bore Machine",
      "Drilling",
      "Feature Inspection",
      "ID Grinding",
      "ID Turning",
      "Manual Deburring",
      "Surface Finishing",
      "Wire EDM Cutting"
    ],
    "SimpleHole": [
      "Automated Deburring",
      "Back Counterboring",
      "Boring",
      "Center Drilling",
      "Chamfer Milling",
      "Chamfering",
      "Counterboring",
      "Countersinking",
      "Cutting",
      "Drilling",
      "Edge Turning",
      "Feature Inspection",
      "Finish Boring",
      "Finish Turning",
      "Groove Milling",
      "Groove Turning",
      "Gun Drilling",
      "Hole Bottom Finishing",
      "ID Finish Plunge Grinding",
      "ID Finish Traverse Grinding",
      "Manual Deburring",
      "Mill Boring",
      "No Cost Feature",
      "Pecking",
      "Perimeter Routering",
      "Port Cutting",
      "Postdrill Rough Turning",
      "Preturn Drilling",
      "Reaming",
      "Rough Boring",
      "Rough Milling",
      "Rough Turning",
      "Round Milling",
      "Rounding",
      "Routering",
      "Semi-Finish Boring",
      "Step Drilling",
      "Surface Finishing",
      "Tapping",
      "Thread Milling",
      "Thread Turning",
      "Trepanning"
    ],
    "SlideBundle": [
      "Automated Deburring",
      "Manual Deburring",
      "Slide Machining"
    ],
    "Slot": [
      "As Perimeter Cut",
      "As Wire EDM Cut",
      "Dovetail Edge Rounding",
      "Finish Dovetail Milling",
      "General Finish Dovetail Milling",
      "General Rough Milling",
      "Groove Milling",
      "No Cost Feature",
      "Rough Milling",
      "Slot Milling",
      "Wire EDM Cutting"
    ],
    "StockTrim": [
      "Parting",
      "Rough Milling",
      "Rough Turning",
      "Setup:Stock Prep",
      "Stock Prep",
      "Stock Trim Turning"
    ],
    "Void": [
      "No Cost Feature",
      "Rough Milling"
    ],
    "Workpiece": [
      "Drum Index",
      "Part Eject",
      "Stock Feed",
      "Tool Positioning",
      "Transfer to Back Work",
      "Transfer to Part Eject"
    ]
  },
  "die_casting": {
    "ComboVoid": [
      "As Cast",
      "Core Refractory Coating",
      "Insert Coring",
      "No Coring",
      "No Cost Feature",
      "No Side Pull",
      "Refractory Coat Air Drying",
      "Refractory Coat Oven Drying",
      "SandCore"
    ],
    "CurvedSurface": [
      "As Cast",
      "No Cost Feature"
    ],
    "CurvedWall": [
      "As Cast",
      "No Cost Feature"
    ],
    "Edge": [
      "As Cast",
      "As Trimmed"
    ],
    "MultiStepHole": [
      "As Cast",
      "Core Refractory Coating",
      "Insert Coring",
      "No Coring",
      "No Cost Feature",
      "No Side Pull",
      "Refractory Coat Air Drying",
      "Refractory Coat Oven Drying",
      "SandCore",
      "Trimming",
      "Unscrewing"
    ],
    "NotSupported": [
      "No Cost Feature"
    ],
    "PlanarFace": [
      "As Cast",
      "No Cost Feature"
    ],
    "Ring": [
      "As Cast",
      "Core Refractory Coating",
      "No Coring",
      "No Cost Feature",
      "No Side Pull",
      "Refractory Coat Air Drying",
      "Refractory Coat Oven Drying",
      "SandCore"
    ],
    "RingedHole": [
      "Core Refractory Coating",
      "Insert Coring",
      "No Coring",
      "No Cost Feature",
      "No Side Pull",
      "Refractory Coat Air Drying",
      "Refractory Coat Oven Drying",
      "SandCore",
      "Unscrewing"
    ],
    "SharpEdge": [
      "As Cast"
    ],
    "SimpleHole": [
      "As Cast",
      "Core Refractory Coating",
      "Insert Coring",
      "No Coring",
      "No Cost Feature",
      "No Side Pull",
      "Refractory Coat Air Drying",
      "Refractory Coat Oven Drying",
      "SandCore",
      "Trimming",
      "Unscrewing"
    ],
    "SlideBundle": [
      "Slides"
    ],
    "Void": [
      "As Cast",
      "Core Refractory Coating",
      "Insert Coring",
      "No Coring",
      "No Cost Feature",
      "No Side Pull",
      "Refractory Coat Air Drying",
      "Refractory Coat Oven Drying",
      "SandCore",
      "Trimming"
    ]
  },
  "sand_casting": {
    "ComboVoid": [
      "CO2 Cured Coring:CO2 Cured",
      "Core Refractory Coating",
      "Hot Box Coring:Hot Box",
      "Isocure Gas Coring:Isocure Gas",
      "Manual Coring:Manual Core",
      "Mold Refractory Coating",
      "No Bake Coring:No Bake",
      "No Cost Feature",
      "Oil Core Coring:Oil Core",
      "Refractory Coat Air Drying",
      "Refractory Coat Oven Drying",
      "Sand Casting",
      "Shell Coring:Shell"
    ],
    "CurvedSurface": [
      "As Cast",
      "As Cored",
      "Mold Refractory Coating",
      "No Cost Feature",
      "Refractory Coat Air Drying",
      "Refractory Coat Oven Drying"
    ],
    "CurvedWall": [
      "As Cast",
      "As Cored",
      "Mold Refractory Coating",
      "No Cost Feature",
      "Refractory Coat Air Drying",
      "Refractory Coat Oven Drying"
    ],
    "Edge": [
      "As Cast",
      "As Cored"
    ],
    "MultiStepHole": [
      "As Cored",
      "CO2 Cured Coring:CO2 Cured",
      "Core Refractory Coating",
      "Hot Box Coring:Hot Box",
      "Isocure Gas Coring:Isocure Gas",
      "Manual Coring:Manual Core",
      "Mold Refractory Coating",
      "No Bake Coring:No Bake",
      "No Cost Feature",
      "Oil Core Coring:Oil Core",
      "Refractory Coat Air Drying",
      "Refractory Coat Oven Drying",
      "Sand Casting",
      "Shell Coring:Shell"
    ],
    "NotSupported": [
      "No Cost Feature"
    ],
    "PlanarFace": [
      "As Cast",
      "As Cored",
      "Mold Refractory Coating",
      "No Cost Feature",
      "Refractory Coat Air Drying",
      "Refractory Coat Oven Drying"
    ],
    "Ring": [
      "As Cored",
      "Mold Refractory Coating",
      "No Cost Feature",
      "Refractory Coat Air Drying",
      "Refractory Coat Oven Drying",
      "Sand Casting"
    ],
    "RingedHole": [
      "CO2 Cured Coring:CO2 Cured",
      "Core Refractory Coating",
      "Hot Box Coring:Hot Box",
      "Isocure Gas Coring:Isocure Gas",
      "Manual Coring:Manual Core",
      "Mold Refractory Coating",
      "No Bake Coring:No Bake",
      "No Cost Feature",
      "Oil Core Coring:Oil Core",
      "Refractory Coat Air Drying",
      "Refractory Coat Oven Drying",
      "Sand Casting",
      "Shell Coring:Shell"
    ],
    "SharpEdge": [
      "Mold Refractory Coating",
      "Refractory Coat Air Drying",
      "Refractory Coat Oven Drying",
      "Sand Casting"
    ],
    "SimpleHole": [
      "As Cored",
      "CO2 Cured Coring:CO2 Cured",
      "Core Refractory Coating",
      "Hot Box Coring:Hot Box",
      "Isocure Gas Coring:Isocure Gas",
      "Manual Coring:Manual Core",
      "Mold Refractory Coating",
      "No Bake Coring:No Bake",
      "No Cost Feature",
      "Oil Core Coring:Oil Core",
      "Refractory Coat Air Drying",
      "Refractory Coat Oven Drying",
      "Sand Casting",
      "Shell Coring:Shell",
      "Stock Core Coring:Stock Core"
    ],
    "Void": [
      "As Cored",
      "CO2 Cured Coring:CO2 Cured",
      "Core Refractory Coating",
      "Hot Box Coring:Hot Box",
      "Isocure Gas Coring:Isocure Gas",
      "Manual Coring:Manual Core",
      "Mold Refractory Coating",
      "No Bake Coring:No Bake",
      "No Cost Feature",
      "Oil Core Coring:Oil Core",
      "Refractory Coat Air Drying",
      "Refractory Coat Oven Drying",
      "Sand Casting",
      "Shell Coring:Shell"
    ]
  },
  "investment_casting": {
    "ComboVoid": [
      "Cast",
      "Ceramic Core Finishing:Core Finish",
      "Ceramic Core Resting:Core Rest",
      "Ceramic Coring:Ceramic Core",
      "Ceramic Leach",
      "Core Fire",
      "Molded",
      "No Cost Feature",
      "Shelled",
      "Soluble Wax Coring:Wax Core",
      "Wax Leach"
    ],
    "CoreBundle": [
      "Cast",
      "Ceramic Core Finishing:Core Finish",
      "Ceramic Core Fire",
      "Ceramic Core Resting:Core Rest",
      "Ceramic Coring:Ceramic Core",
      "Extruded Ceramic Coring:Ceramic Core Extrude",
      "Molded",
      "No Cost Feature",
      "Shelled",
      "Soluble Wax Coring:Soluble Wax Core",
      "Soluble Wax Leach"
    ],
    "CurvedSurface": [
      "As Cast",
      "Ceramic Coring:As Cored",
      "No Cost Feature",
      "Soluble Wax Coring:As Cored"
    ],
    "CurvedWall": [
      "As Cast",
      "Ceramic Coring:As Cored",
      "No Cost Feature",
      "Soluble Wax Coring:As Cored"
    ],
    "Edge": [
      "As Cast",
      "Ceramic Coring:As Cored",
      "Extruded Ceramic Coring:As Cored",
      "No Cost Feature",
      "Soluble Wax Coring:As Cored"
    ],
    "MultiStepHole": [
      "Cast",
      "Ceramic Core Finishing:Core Finish",
      "Ceramic Core Resting:Core Rest",
      "Ceramic Coring:Ceramic Core",
      "Ceramic Leach",
      "Core Fire",
      "Molded",
      "No Cost Feature",
      "Shelled",
      "Soluble Wax Coring:Wax Core",
      "Wax Leach"
    ],
    "NotSupported": [
      "No Cost Feature"
    ],
    "PlanarFace": [
      "As Cast",
      "Ceramic Coring:As Cored",
      "No Cost Feature",
      "Soluble Wax Coring:As Cored"
    ],
    "Ring": [
      "Cast",
      "Ceramic Core Finishing:Core Finish",
      "Ceramic Core Resting:Core Rest",
      "Ceramic Coring:Ceramic Core",
      "Ceramic Leach",
      "Core Fire",
      "Molded",
      "No Cost Feature",
      "Shelled",
      "Soluble Wax Coring:Wax Core",
      "Wax Leach"
    ],
    "SharpEdge": [
      "As Cast",
      "No Cost Feature"
    ],
    "SimpleHole": [
      "Cast",
      "Ceramic Core Finishing:Core Finish",
      "Ceramic Core Resting:Core Rest",
      "Ceramic Coring:Ceramic Core",
      "Ceramic Leach",
      "Core Fire",
      "Extruded Ceramic Coring:Ceramic Core Extrude",
      "Molded",
      "No Cost Feature",
      "Shelled",
      "Soluble Wax Coring:Wax Core",
      "Wax Leach"
    ],
    "SlideBundle": [
      "Cast",
      "Loose Piece",
      "No Cost Feature",
      "Shelled",
      "Slide"
    ],
    "Void": [
      "Cast",
      "Ceramic Core Finishing:Core Finish",
      "Ceramic Core Resting:Core Rest",
      "Ceramic Coring:Ceramic Core",
      "Ceramic Leach",
      "Core Fire",
      "Molded",
      "No Cost Feature",
      "Shelled",
      "Soluble Wax Coring:Wax Core",
      "Wax Leach"
    ]
  }
} as const;

/** True when `operation` is a real catalog pairing for `featureType` in `domain`. */
export function isReferenceOperation(
  domain: 'sheet_metal' | 'machining' | 'die_casting' | 'sand_casting' | 'investment_casting',
  featureType: string,
  operation: string,
): boolean {
  const table = REFERENCE_FEATURE_OPERATIONS[domain] as Record<string, readonly string[]>;
  return (table[featureType] ?? []).includes(operation);
}
